/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Substructures.Ideal
import BanLat.OrderComplete

/-!
# Uniform completeness

This file introduces uniformly complete vector lattices. The definition is
given in terms of completeness of principal ideals for their gauge norms, and
the basic permanence facts relate uniform completeness to σ-order completeness
and Banach lattice completeness.
-/

/-- A vector lattice is **uniformly complete** if it is Archimedean and every
principal ideal generated by a non-zero positive element is complete for its
gauge norm. The omitted zero principal ideal is trivial. -/
class IsUniformlyCompleteVectorLattice (X : Type*) [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] : Prop extends IsVLArchimedean X where
  complete_principal :
    ∀ (e : X) (_he : 0 < e),
      letI : IsVLArchimedean X := toIsVLArchimedean
      letI := OrderIdeal.principalNormedAddCommGroup e
      CompleteSpace ↥(OrderIdeal.principalSubmodule e)

private theorem abs_sub_le_of_gauge_le {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] [IsVLArchimedean X]
    {e x y : X} (he : 0 ≤ e) (hx : x ∈ OrderIdeal.principal e)
    (hy : y ∈ OrderIdeal.principal e) {c : ℝ}
    (hxy : OrderIdeal.gaugeNorm e (x - y) ≤ c) :
    |x - y| ≤ c • e := by
  calc |x - y|
      ≤ OrderIdeal.gaugeNorm e (x - y) • |e| :=
        OrderIdeal.abs_le_gaugeNorm_smul_abs e ((OrderIdeal.principal e).toSubmodule.sub_mem hx hy)
    _ ≤ c • |e| := smul_le_smul_of_nonneg_right hxy (abs_nonneg e)
    _ = c • e := by rw [abs_of_nonneg he]

private theorem norm_coe_le_norm_generator_mul_gauge {X : Type*}
    [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [BanachLattice X] {e : X} (x : ↥(OrderIdeal.principalSubmodule e)) :
    ‖(x : X)‖ ≤ ‖e‖ * OrderIdeal.gaugeNorm e (x : X) := by
  have hnonneg : 0 ≤ OrderIdeal.gaugeNorm e (x : X) :=
    OrderIdeal.gaugeNorm_nonneg e (x : X)
  calc ‖(x : X)‖
      ≤ ‖OrderIdeal.gaugeNorm e (x : X) • |e|‖ := by
        apply norm_le_norm_of_abs_le_abs
        rw [abs_of_nonneg (smul_nonneg hnonneg (abs_nonneg e))]
        exact OrderIdeal.abs_le_gaugeNorm_smul_abs e x.2
    _ = ‖OrderIdeal.gaugeNorm e (x : X)‖ * ‖|e|‖ := norm_smul _ _
    _ = ‖e‖ * OrderIdeal.gaugeNorm e (x : X) := by
        rw [Real.norm_of_nonneg hnonneg, norm_abs_eq_norm, mul_comm]

private theorem norm_principal_eq_gauge {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] [IsVLArchimedean X]
    {e : X} (x : ↥(OrderIdeal.principalSubmodule e)) :
    letI := OrderIdeal.principalNormedAddCommGroup e
    ‖x‖ = OrderIdeal.gaugeNorm e (x : X) := by
  letI := OrderIdeal.principalNormedAddCommGroup e
  rfl

private theorem dist_principal_eq_gauge {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] [IsVLArchimedean X]
    {e : X} (x y : ↥(OrderIdeal.principalSubmodule e)) :
    letI := OrderIdeal.principalNormedAddCommGroup e
    letI : PseudoMetricSpace ↥(OrderIdeal.principalSubmodule e) :=
      @SeminormedAddCommGroup.toPseudoMetricSpace _
        (@NormedAddCommGroup.toSeminormedAddCommGroup _
          (OrderIdeal.principalNormedAddCommGroup e))
    dist x y = OrderIdeal.gaugeNorm e ((x : X) - (y : X)) := by
  letI := OrderIdeal.principalNormedAddCommGroup e
  letI : PseudoMetricSpace ↥(OrderIdeal.principalSubmodule e) :=
    @SeminormedAddCommGroup.toPseudoMetricSpace _
      (@NormedAddCommGroup.toSeminormedAddCommGroup _
        (OrderIdeal.principalNormedAddCommGroup e))
  calc
    dist x y = ‖x - y‖ := @dist_eq_norm _
      (@NormedAddCommGroup.toSeminormedAddCommGroup _
        (OrderIdeal.principalNormedAddCommGroup e)) x y
    _ = OrderIdeal.gaugeNorm e ((x : X) - (y : X)) := norm_principal_eq_gauge (x - y)

private theorem completeSpace_principal_of_banachLattice {X : Type*}
    [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [BanachLattice X] (e : X) (he : 0 < e) :
    @CompleteSpace ↥(OrderIdeal.principalSubmodule e)
      (@PseudoMetricSpace.toUniformSpace _
        (@SeminormedAddCommGroup.toPseudoMetricSpace _
          (@NormedAddCommGroup.toSeminormedAddCommGroup _
            (OrderIdeal.principalNormedAddCommGroup e)))) := by
  letI := OrderIdeal.principalNormedAddCommGroup e
  let Y := ↥(OrderIdeal.principalSubmodule e)
  letI : PseudoMetricSpace Y :=
    @SeminormedAddCommGroup.toPseudoMetricSpace Y
      (@NormedAddCommGroup.toSeminormedAddCommGroup Y
        (OrderIdeal.principalNormedAddCommGroup e))
  refine Metric.complete_of_cauchySeq_tendsto (α := Y) fun u hu => ?_
  have hnorme_pos : 0 < ‖e‖ := norm_pos_iff.mpr (ne_of_gt he)
  have hu_ambient : CauchySeq (fun n => (u n : X)) := by
    rw [Metric.cauchySeq_iff] at hu ⊢
    intro ε hε
    obtain ⟨N, hN⟩ := hu (ε / ‖e‖) (div_pos hε hnorme_pos)
    refine ⟨N, fun n hn m hm => ?_⟩
    have hdist := hN n hn m hm
    have hdist_gauge : OrderIdeal.gaugeNorm e ((u n : X) - (u m : X)) < ε / ‖e‖ := by
      have heq : dist (u n) (u m) =
          OrderIdeal.gaugeNorm e ((u n : X) - (u m : X)) := by
        simpa only using (dist_principal_eq_gauge (u n) (u m))
      rw [heq] at hdist
      exact hdist
    rw [dist_eq_norm]
    have hle : ‖(u n : X) - (u m : X)‖ ≤
        ‖e‖ * OrderIdeal.gaugeNorm e ((u n : X) - (u m : X)) := by
      exact norm_coe_le_norm_generator_mul_gauge (e := e) (u n - u m)
    have hmul : ‖e‖ * OrderIdeal.gaugeNorm e ((u n : X) - (u m : X)) <
        ‖e‖ * (ε / ‖e‖) :=
      mul_lt_mul_of_pos_left hdist_gauge hnorme_pos
    have htarget : ‖e‖ * (ε / ‖e‖) = ε := by
      field_simp [ne_of_gt hnorme_pos]
    exact hle.trans_lt (by rwa [htarget] at hmul)
  obtain ⟨x, hx_tend⟩ := cauchySeq_tendsto_of_complete hu_ambient
  have hx_mem : x ∈ OrderIdeal.principalSubmodule e := by
    rw [Metric.cauchySeq_iff] at hu
    obtain ⟨N, hN⟩ := hu 1 zero_lt_one
    have htail : ∀ᶠ n in Filter.atTop,
        |(u n : X) - (u N : X)| ≤ (1 : ℝ) • e := by
      filter_upwards [Filter.eventually_atTop.mpr ⟨N, fun n hn => hn⟩] with n hn
      have hdist := hN n hn N le_rfl
      exact abs_sub_le_of_gauge_le he.le (u n).2 (u N).2 (le_of_lt (by
        have heq : dist (u n) (u N) =
            OrderIdeal.gaugeNorm e ((u n : X) - (u N : X)) := by
          simpa only using (dist_principal_eq_gauge (u n) (u N))
        rw [heq] at hdist
        exact hdist))
    have hlim :
        |x - (u N : X)| ≤ (1 : ℝ) • e := by
      have hdiff_tend :
          Filter.Tendsto (fun n => (u n : X) - (u N : X)) Filter.atTop
            (nhds (x - (u N : X))) :=
        hx_tend.sub tendsto_const_nhds
      have habs_tend :
          Filter.Tendsto (fun n => |(u n : X) - (u N : X)|) Filter.atTop
            (nhds |x - (u N : X)|) :=
        (NormedVectorLattice.lipschitzWith_abs.continuous.tendsto _).comp hdiff_tend
      exact le_of_tendsto_of_tendsto habs_tend tendsto_const_nhds (by
        filter_upwards [htail] with n hn
        simpa [show x - (u N : X) = x - (u N : X) from rfl] using hn)
    have hdiff_mem : x - (u N : X) ∈ OrderIdeal.principal e :=
      ⟨1, zero_le_one, by simpa [abs_of_nonneg he.le] using hlim⟩
    have hadd_mem :
        (x - (u N : X)) + (u N : X) ∈ OrderIdeal.principalSubmodule e :=
      (OrderIdeal.principal e).toSubmodule.add_mem hdiff_mem (u N).2
    simpa using hadd_mem
  refine ⟨⟨x, hx_mem⟩, ?_⟩
  rw [Metric.tendsto_atTop]
  intro ε hε
  rw [Metric.cauchySeq_iff] at hu
  obtain ⟨N, hN⟩ := hu (ε / 2) (by linarith)
  refine ⟨N, fun n hn => ?_⟩
  have horder : |x - (u n : X)| ≤ (ε / 2) • e := by
    have htail : ∀ᶠ m in Filter.atTop,
        |(u m : X) - (u n : X)| ≤ (ε / 2) • e := by
      filter_upwards [Filter.eventually_atTop.mpr ⟨N, fun m hm => hm⟩] with m hm
      have hdist := hN m hm n hn
      exact abs_sub_le_of_gauge_le he.le (u m).2 (u n).2 (le_of_lt (by
        have heq : dist (u m) (u n) =
            OrderIdeal.gaugeNorm e ((u m : X) - (u n : X)) := by
          simpa only using (dist_principal_eq_gauge (u m) (u n))
        rw [heq] at hdist
        exact hdist))
    have hdiff_tend :
        Filter.Tendsto (fun m => (u m : X) - (u n : X)) Filter.atTop
          (nhds (x - (u n : X))) :=
      hx_tend.sub tendsto_const_nhds
    have habs_tend :
        Filter.Tendsto (fun m => |(u m : X) - (u n : X)|) Filter.atTop
          (nhds |x - (u n : X)|) :=
      (NormedVectorLattice.lipschitzWith_abs.continuous.tendsto _).comp hdiff_tend
    exact le_of_tendsto_of_tendsto habs_tend tendsto_const_nhds htail
  have hgauge : OrderIdeal.gaugeNorm e ((u n : X) - x) ≤ ε / 2 := by
    rw [show (u n : X) - x = -(x - (u n : X)) by abel, OrderIdeal.gaugeNorm_neg]
    exact OrderIdeal.gaugeNorm_le_of_abs_le e (by linarith) (by
      simpa [abs_of_nonneg he.le] using horder)
  have hgauge_lt : OrderIdeal.gaugeNorm e ((u n : X) - x) < ε := by
    linarith
  have heq : dist (u n) ⟨x, hx_mem⟩ =
      OrderIdeal.gaugeNorm e ((u n : X) - x) := by
    simpa only using (dist_principal_eq_gauge (u n) ⟨x, hx_mem⟩)
  rw [heq]
  exact hgauge_lt

private theorem completeSpace_principal_of_sigmaConditionallyCompleteLattice {X : Type*}
    [AddCommGroup X] [SigmaConditionallyCompleteLattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (e : X) (he : 0 < e) :
    letI : IsVLArchimedean X := IsVLArchimedean_of_sigmaConditionallyCompleteLattice
    @CompleteSpace ↥(OrderIdeal.principalSubmodule e)
      (@PseudoMetricSpace.toUniformSpace _
        (@SeminormedAddCommGroup.toPseudoMetricSpace _
          (@NormedAddCommGroup.toSeminormedAddCommGroup _
            (OrderIdeal.principalNormedAddCommGroup e)))) := by
  letI : IsVLArchimedean X := IsVLArchimedean_of_sigmaConditionallyCompleteLattice
  letI := OrderIdeal.principalNormedAddCommGroup e
  let Y := ↥(OrderIdeal.principalSubmodule e)
  letI : PseudoMetricSpace Y :=
    @SeminormedAddCommGroup.toPseudoMetricSpace Y
      (@NormedAddCommGroup.toSeminormedAddCommGroup Y
        (OrderIdeal.principalNormedAddCommGroup e))
  let b : ℕ → ℝ := fun n => (1 / 2 : ℝ) ^ n
  let r : ℕ → ℝ := fun n => 2 * b n
  have hb_pos : ∀ n, 0 < b n := fun n => pow_pos (by norm_num) n
  have hb_nonneg : ∀ n, 0 ≤ b n := fun n => (hb_pos n).le
  have hr_nonneg : ∀ n, 0 ≤ r n := fun n => mul_nonneg (by norm_num) (hb_nonneg n)
  have hr_succ : ∀ n, r n = b n + r (n + 1) := by
    intro n
    dsimp [r, b]
    rw [pow_succ]
    ring
  refine Metric.complete_of_convergent_controlled_sequences (α := Y) b hb_pos fun u hu => ?_
  let v : ℕ → X := fun n => (u n : X) - r n • e
  let w : ℕ → X := fun n => (u n : X) + r n • e
  have hstep_abs : ∀ n, |(u n : X) - (u (n + 1) : X)| ≤ b n • e := by
    intro n
    have hdist := hu n n (n + 1) le_rfl (Nat.le_succ n)
    exact abs_sub_le_of_gauge_le he.le (u n).2 (u (n + 1)).2 (le_of_lt (by
        have heq : dist (u n) (u (n + 1)) =
            OrderIdeal.gaugeNorm e ((u n : X) - (u (n + 1) : X)) := by
          simpa only using (dist_principal_eq_gauge (u n) (u (n + 1)))
        rw [heq] at hdist
        exact hdist))
  have hv_mono : Monotone v := by
    refine monotone_nat_of_le_succ fun n => ?_
    have hdiff : (u n : X) - (u (n + 1) : X) ≤ b n • e :=
      (le_abs_self _).trans (hstep_abs n)
    have hu_le : (u n : X) ≤ b n • e + (u (n + 1) : X) :=
      sub_le_iff_le_add.mp hdiff
    calc v n
        ≤ (b n • e + (u (n + 1) : X)) - r n • e := sub_le_sub_right hu_le _
      _ = v (n + 1) := by
          dsimp [v]
          rw [hr_succ n, add_smul]
          abel
  have hw_anti : Antitone w := by
    refine antitone_nat_of_succ_le fun n => ?_
    have hdiff : (u (n + 1) : X) - (u n : X) ≤ b n • e := by
      calc (u (n + 1) : X) - (u n : X)
          = -((u n : X) - (u (n + 1) : X)) := by abel
        _ ≤ |(u n : X) - (u (n + 1) : X)| := neg_le_abs _
        _ ≤ b n • e := hstep_abs n
    have hu_le : (u (n + 1) : X) ≤ b n • e + (u n : X) :=
      sub_le_iff_le_add.mp hdiff
    calc w (n + 1)
        = (u (n + 1) : X) + r (n + 1) • e := rfl
      _ ≤ (b n • e + (u n : X)) + r (n + 1) • e :=
          add_le_add hu_le le_rfl
      _ = w n := by
          dsimp [w]
          rw [hr_succ n, add_smul]
          abel
  have hv_le_w : ∀ n, v n ≤ w n := by
    intro n
    dsimp [v, w]
    rw [sub_eq_add_neg]
    exact add_le_add (le_refl (u n : X))
      ((neg_nonpos.mpr (smul_nonneg (hr_nonneg n) he.le)).trans
        (smul_nonneg (hr_nonneg n) he.le))
  have hv_bdd : BddAbove (Set.range v) :=
    ⟨w 0, by
      rintro _ ⟨n, rfl⟩
      exact (hv_le_w n).trans (hw_anti (Nat.zero_le n))⟩
  let x := sSup (Set.range v)
  have hv_lub : IsLUB (Set.range v) x :=
    ⟨fun _ hy => SigmaConditionallyCompleteLattice.le_csSup _ _ (Set.countable_range _)
        hv_bdd hy,
      fun _ hy => SigmaConditionallyCompleteLattice.csSup_le _ _ (Set.countable_range _)
        (Set.range_nonempty _) hy⟩
  have hw_upper : ∀ n, w n ∈ upperBounds (Set.range v) := by
    intro n _ hm
    rcases hm with ⟨m, rfl⟩
    by_cases hmn : m ≤ n
    · exact (hv_mono hmn).trans (hv_le_w n)
    · exact (hv_le_w m).trans (hw_anti (le_of_not_ge hmn))
  have hx_le_w : ∀ n, x ≤ w n := fun n => hv_lub.2 (hw_upper n)
  have hdist_order : ∀ n, |(u n : X) - x| ≤ r n • e := by
    intro n
    have hleft : (u n : X) - x ≤ r n • e := by
      rw [sub_le_iff_le_add]
      exact (sub_le_iff_le_add.mp (hv_lub.1 ⟨n, rfl⟩)).trans_eq (add_comm _ _)
    have hright : x - (u n : X) ≤ r n • e := by
      rw [sub_le_iff_le_add]
      exact (hx_le_w n).trans_eq (add_comm _ _)
    rw [abs]
    refine sup_le hleft ?_
    calc -((u n : X) - x)
        = x - (u n : X) := by abel
      _ ≤ r n • e := hright
  have hx_mem : x ∈ OrderIdeal.principalSubmodule e := by
    have hdiff_mem : x - (u 0 : X) ∈ OrderIdeal.principal e := by
      refine ⟨r 0, hr_nonneg 0, ?_⟩
      rw [abs_of_nonneg he.le]
      calc |x - (u 0 : X)|
          = |(u 0 : X) - x| := by
              rw [show x - (u 0 : X) = -((u 0 : X) - x) by abel, abs_neg]
        _ ≤ r 0 • e := hdist_order 0
    have hadd_mem :
        (x - (u 0 : X)) + (u 0 : X) ∈ OrderIdeal.principalSubmodule e :=
      (OrderIdeal.principal e).toSubmodule.add_mem hdiff_mem (u 0).2
    simpa using hadd_mem
  refine ⟨⟨x, hx_mem⟩, ?_⟩
  rw [Metric.tendsto_atTop]
  intro ε hε
  have hr_tend : Filter.Tendsto r Filter.atTop (nhds 0) := by
    simpa [r, b] using ((tendsto_pow_atTop_nhds_zero_of_lt_one
      (by norm_num : 0 ≤ (1 / 2 : ℝ))
      (by norm_num : (1 / 2 : ℝ) < 1)).const_mul 2)
  rw [Metric.tendsto_atTop] at hr_tend
  obtain ⟨N, hN⟩ := hr_tend ε hε
  refine ⟨N, fun n hn => ?_⟩
  have hr_lt : r n < ε := by
    have := hN n hn
    rw [dist_eq_norm, Real.norm_eq_abs, sub_zero, abs_of_nonneg (hr_nonneg n)] at this
    exact this
  have hgauge : OrderIdeal.gaugeNorm e ((u n : X) - x) ≤ r n :=
    OrderIdeal.gaugeNorm_le_of_abs_le e (hr_nonneg n) (by
      simpa [abs_of_nonneg he.le] using hdist_order n)
  have hgauge_lt : OrderIdeal.gaugeNorm e ((u n : X) - x) < ε :=
    hgauge.trans_lt hr_lt
  have heq : dist (u n) ⟨x, hx_mem⟩ =
      OrderIdeal.gaugeNorm e ((u n : X) - x) := by
    simpa only using (dist_principal_eq_gauge (u n) ⟨x, hx_mem⟩)
  rw [heq]
  exact hgauge_lt

/-- Every σ-order complete vector lattice is uniformly complete. -/
theorem isUniformlyCompleteVectorLattice_of_sigmaConditionallyCompleteLattice
    (X : Type*) [AddCommGroup X] [SigmaConditionallyCompleteLattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] :
    IsUniformlyCompleteVectorLattice X := by
  letI : IsVLArchimedean X := IsVLArchimedean_of_sigmaConditionallyCompleteLattice
  exact
    { complete_principal := fun e he =>
        completeSpace_principal_of_sigmaConditionallyCompleteLattice e he }

/-- Every Banach lattice is uniformly complete. -/
theorem isUniformlyCompleteVectorLattice_of_banachLattice
    (X : Type*) [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [BanachLattice X] : IsUniformlyCompleteVectorLattice X := by
  exact
    { complete_principal := fun e he =>
        completeSpace_principal_of_banachLattice e he }
