import BanLat.Substructures.Band.Projection
import BanLat.OrderDense
import BanLat.Pi
import BanLat.Normed
import BanLat.Operators.Hom
import BanLat.Substructures.Band.Decomposition
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# Atoms and atomic vector lattices

An **atom** (or *discrete element*) of a vector lattice `X` is a positive
non-zero element `a` such that the order interval `[0, a]` is one-dimensional:
every `0 ≤ x ≤ a` is a (necessarily non-negative) scalar multiple of `a`. The
vector lattice `X` is **atomic** (or *discrete*) when it equals the band
generated by all of its atoms. In general, every Archimedean vector lattice
admits a decomposition into its **atomic part** — the band generated by all
atoms — and its **continuous part**, the disjoint complement of the atomic
part.
-/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-! ### Atoms -/

/-- A positive non-zero element `a` of a vector lattice is an **atom** (or
*discrete element*) when every `0 ≤ x ≤ a` is a scalar multiple of `a`. -/
def IsVLAtom (a : X) : Prop :=
  0 < a ∧ ∀ x : X, 0 ≤ x → x ≤ a → ∃ c : ℝ, x = c • a

/-- An atom is strictly positive. -/
theorem IsVLAtom.pos {a : X} (h : IsVLAtom a) : 0 < a := h.1

/-- An atom is non-zero. -/
theorem IsVLAtom.ne_zero {a : X} (h : IsVLAtom a) : a ≠ 0 := h.1.ne'

private lemma smul_eq_zero_of_ne_zero_of_pos {a : X} (ha : a ≠ 0) {c : ℝ}
    (h : c • a = 0) : c = 0 := by
  by_contra hc
  apply ha
  have hcalc : c⁻¹ • (c • a) = c⁻¹ • (0 : X) := by rw [h]
  rwa [smul_smul, inv_mul_cancel₀ hc, one_smul, smul_zero] at hcalc

private lemma smul_pos_of_pos {a : X} (ha : 0 < a) {c : ℝ} (hc : 0 < c) :
    0 < c • a := by
  refine lt_of_le_of_ne (smul_nonneg hc.le ha.le) ?_
  intro hca
  exact hc.ne' (smul_eq_zero_of_ne_zero_of_pos ha.ne' hca.symm)

/-- The order interval `[0, a]` of an atom contains no two non-zero disjoint
elements. -/
theorem eq_zero_or_eq_zero_of_isVLDisjoint_of_isVLAtom
    {a : X} (h : IsVLAtom a) {x y : X}
    (hx0 : 0 ≤ x) (hxa : x ≤ a) (hy0 : 0 ≤ y) (hya : y ≤ a)
    (hxy : IsVLDisjoint x y) : x = 0 ∨ y = 0 := by
  obtain ⟨c, hc⟩ := h.2 x hx0 hxa
  obtain ⟨d, hd⟩ := h.2 y hy0 hya
  have ha_nn : 0 ≤ a := h.1.le
  have ha_ne : a ≠ 0 := h.1.ne'
  rcases lt_or_ge c 0 with hc_neg | hc_nn
  · left
    have : c • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hc_neg.le ha_nn
    rw [← hc] at this
    exact le_antisymm this hx0
  rcases lt_or_ge d 0 with hd_neg | hd_nn
  · right
    have : d • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hd_neg.le ha_nn
    rw [← hd] at this
    exact le_antisymm this hy0
  have hxy0 : x ⊓ y = 0 := inf_eq_zero_of_isVLDisjoint hx0 hy0 hxy
  rw [hc, hd, ← inf_smul_nonneg a c d ha_nn] at hxy0
  have hmin0 : (c ⊓ d : ℝ) = 0 := smul_eq_zero_of_ne_zero_of_pos ha_ne hxy0
  rcases le_total c d with hcd | hcd
  · left
    have hcd' : c ⊓ d = c := inf_eq_left.mpr hcd
    rw [hcd'] at hmin0
    rw [hc, hmin0, zero_smul]
  · right
    have hcd' : c ⊓ d = d := inf_eq_right.mpr hcd
    rw [hcd'] at hmin0
    rw [hd, hmin0, zero_smul]

/-- Monotonicity of scalar multiplication of a non-negative element by reals. -/
private lemma smul_le_smul_real_of_nonneg {a : X} (ha_nn : 0 ≤ a) {s t : ℝ}
    (hst : s ≤ t) : s • a ≤ t • a := by
  have hts : 0 ≤ t - s := sub_nonneg.mpr hst
  have hnn : 0 ≤ (t - s) • a := smul_nonneg hts ha_nn
  have heq : t • a = (t - s) • a + s • a := by
    rw [← add_smul]; congr 1; ring
  rw [heq]; exact le_add_of_nonneg_left hnn

/-- Under the no-disjoint-pair hypothesis, every `x ∈ [0,a]` is comparable to
every `t • a` with `t ∈ [0,1]`. -/
private lemma comparable_of_no_disjoint_in_interval
    {a : X} (ha_nn : 0 ≤ a)
    (hyp : ∀ x y : X, 0 ≤ x → x ≤ a → 0 ≤ y → y ≤ a →
      IsVLDisjoint x y → x = 0 ∨ y = 0)
    {x : X} (hx0 : 0 ≤ x) (hxa : x ≤ a) {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    t • a ≤ x ∨ x ≤ t • a := by
  have hta_nn : 0 ≤ t • a := smul_nonneg ht0 ha_nn
  have hta_le : t • a ≤ a := by
    have := smul_le_smul_real_of_nonneg ha_nn ht1
    rwa [one_smul] at this
  set p := (x - t • a)⁺ with hp_def
  set q := (x - t • a)⁻ with hq_def
  have hp_nn : 0 ≤ p := posPart_nonneg _
  have hq_nn : 0 ≤ q := negPart_nonneg _
  have hp_le : p ≤ a := by
    rw [hp_def, posPart_def]
    exact sup_le (le_trans (sub_le_self _ hta_nn) hxa) ha_nn
  have hq_le : q ≤ a := by
    rw [hq_def, negPart_def]
    refine sup_le ?_ ha_nn
    rw [neg_sub]; exact le_trans (sub_le_self _ hx0) hta_le
  have hpq_disj : IsVLDisjoint p q := isVLDisjoint_of_inf_eq_zero
    (posPart_inf_negPart_eq_zero _)
  rcases hyp p q hp_nn hp_le hq_nn hq_le hpq_disj with hp0 | hq0
  · right
    exact sub_nonpos.mp (posPart_eq_zero.mp hp0)
  · left
    exact sub_nonneg.mp (negPart_eq_zero.mp hq0)

/-- Characterisation: a positive element `a` is an atom iff the order interval
`[0, a]` contains no two non-zero disjoint elements. -/
theorem isVLAtom_iff_no_disjoint_in_interval [IsVLArchimedean X]
    {a : X} (ha : 0 < a) :
    IsVLAtom a ↔
      ∀ x y : X, 0 ≤ x → x ≤ a → 0 ≤ y → y ≤ a →
        IsVLDisjoint x y → x = 0 ∨ y = 0 := by
  refine ⟨fun h x y hx0 hxa hy0 hya hxy =>
    eq_zero_or_eq_zero_of_isVLDisjoint_of_isVLAtom h hx0 hxa hy0 hya hxy, fun hyp => ?_⟩
  refine ⟨ha, fun x hx0 hxa => ?_⟩
  -- Set T = {t ∈ [0,1] : t•a ≤ x}; show its sup C satisfies x = C • a.
  set T : Set ℝ := {t | 0 ≤ t ∧ t ≤ 1 ∧ t • a ≤ x} with hT_def
  have hT_ne : T.Nonempty := ⟨0, ⟨le_refl 0, zero_le_one, by rw [zero_smul]; exact hx0⟩⟩
  have hT_bdd : BddAbove T := ⟨1, fun t ht => ht.2.1⟩
  set C := sSup T with hC_def
  have hC_nn : 0 ≤ C := le_csSup hT_bdd ⟨le_refl 0, zero_le_one, by rw [zero_smul]; exact hx0⟩
  have hC_le : C ≤ 1 := csSup_le hT_ne (fun t ht => ht.2.1)
  refine ⟨C, ?_⟩
  -- Step A: x ≤ C • a (from "x ≤ t•a for all t > C")
  have hx_le_Ca : x ≤ C • a := by
    have hbound : ∀ n : ℕ, 0 < n → x - C • a ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      rcases lt_or_ge 1 (C + (n : ℝ)⁻¹) with hgt1 | hle1
      · -- C + 1/n > 1, so x ≤ a ≤ C•a + (1/n)•a
        have h1a : x ≤ (1 : ℝ) • a := by rw [one_smul]; exact hxa
        have hsum : (1 : ℝ) • a ≤ (C + (n : ℝ)⁻¹) • a :=
          smul_le_smul_real_of_nonneg ha.le hgt1.le
        rw [add_smul] at hsum
        exact sub_le_iff_le_add'.mpr (le_trans h1a hsum)
      · have hCε_nn : 0 ≤ C + (n : ℝ)⁻¹ := by positivity
        have hnotin : C + (n : ℝ)⁻¹ ∉ T := fun hin => by
          have := le_csSup hT_bdd hin
          have hpos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_real
          linarith
        have hcomp := comparable_of_no_disjoint_in_interval ha.le hyp hx0 hxa hCε_nn hle1
        rcases hcomp with hle | hge
        · exfalso; exact hnotin ⟨hCε_nn, hle1, hle⟩
        · rw [add_smul] at hge
          exact sub_le_iff_le_add'.mpr hge
    -- Now (x - C•a)⁺ ≤ (1/n)•a for all n ≥ 1, so by Archimedean (x - C•a)⁺ = 0.
    have hposPart_bound : ∀ n : ℕ, n • (x - C • a)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha.le
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (x - C • a)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha.le)
      have hns : n • (x - C • a)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (x - C • a)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  -- Step B: C • a ≤ x (since for any n there's t ∈ T with t > C - 1/n)
  have hCa_le_x : C • a ≤ x := by
    have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      obtain ⟨t, htT, htgt⟩ : ∃ t ∈ T, C - (n : ℝ)⁻¹ < t := by
        by_contra hno
        push Not at hno
        have : C ≤ C - (n : ℝ)⁻¹ := csSup_le hT_ne hno
        have hpos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_real
        linarith
      have htle : t • a ≤ x := htT.2.2
      have hCt_le : C - t ≤ (n : ℝ)⁻¹ := by linarith
      have hsmul_le : (C - t) • a ≤ ((n : ℝ)⁻¹) • a :=
        smul_le_smul_real_of_nonneg ha.le hCt_le
      have hsplit : C • a = (C - t) • a + t • a := by
        rw [← add_smul]; congr 1; ring
      have h1 : C • a - x ≤ (C - t) • a := by
        rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr htle)
      exact le_trans h1 hsmul_le
    have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha.le
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha.le)
      have hns : n • (C • a - x)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (C • a - x)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  exact le_antisymm hx_le_Ca hCa_le_x

/-- A positive scalar multiple of an atom is again an atom. -/
theorem IsVLAtom.smul {a : X} (h : IsVLAtom a) {c : ℝ} (hc : 0 < c) :
    IsVLAtom (c • a) := by
  refine ⟨smul_pos_of_pos h.1 hc, fun x hx0 hxca => ?_⟩
  have hcinv : 0 < c⁻¹ := inv_pos.mpr hc
  have h1 : 0 ≤ c⁻¹ • x := smul_nonneg hcinv.le hx0
  have h2 : c⁻¹ • x ≤ a := by
    have hmono := smul_le_smul_of_nonneg_left hxca hcinv.le
    rwa [smul_smul, inv_mul_cancel₀ hc.ne', one_smul] at hmono
  obtain ⟨d, hd⟩ := h.2 (c⁻¹ • x) h1 h2
  refine ⟨d, ?_⟩
  have hx_eq : x = c • (c⁻¹ • x) := by
    rw [smul_smul, mul_inv_cancel₀ hc.ne', one_smul]
  rw [hx_eq, hd, smul_smul, mul_comm, ← smul_smul]

/-- Any non-negative element bounded by a non-negative scalar multiple of an atom
is a scalar multiple of that atom. -/
private lemma exists_smul_of_le_smul_atom
    {a : X} (ha : IsVLAtom a) {y : X} (hy0 : 0 ≤ y) {k : ℝ} (hk : 0 ≤ k)
    (hyk : y ≤ k • a) : ∃ c : ℝ, y = c • a := by
  rcases eq_or_lt_of_le hk with hk0 | hkpos
  · rw [← hk0, zero_smul] at hyk
    have hy : y = 0 := le_antisymm hyk hy0
    exact ⟨0, by rw [hy, zero_smul]⟩
  · have hka : IsVLAtom (k • a) := IsVLAtom.smul ha hkpos
    obtain ⟨α, hα⟩ := hka.2 y hy0 hyk
    exact ⟨α * k, by rw [hα, smul_smul]⟩

/-- Characterisation: a positive element `a` is an atom iff its principal
ideal is the line spanned by `a`. -/
theorem isVLAtom_iff_principal_eq_span [IsVLArchimedean X] {a : X} :
    IsVLAtom a ↔
      0 < a ∧ ∀ x : X, x ∈ OrderIdeal.principal a → ∃ c : ℝ, x = c • a := by
  refine ⟨fun ha => ⟨ha.1, fun x hx => ?_⟩, fun ⟨hpos, hspan⟩ => ⟨hpos, fun x hx0 hxa => ?_⟩⟩
  · obtain ⟨c, hc_nn, hxc⟩ := OrderIdeal.mem_principal.mp hx
    rw [abs_of_nonneg ha.1.le] at hxc
    obtain ⟨α, hα⟩ := exists_smul_of_le_smul_atom ha
      (posPart_nonneg x) hc_nn (le_trans (posPart_le_abs x) hxc)
    obtain ⟨β, hβ⟩ := exists_smul_of_le_smul_atom ha
      (negPart_nonneg x) hc_nn (le_trans (negPart_le_abs x) hxc)
    refine ⟨α - β, ?_⟩
    calc x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
      _ = α • a - β • a := by rw [hα, hβ]
      _ = (α - β) • a := (sub_smul α β a).symm
  · apply hspan
    rw [OrderIdeal.mem_principal]
    refine ⟨1, zero_le_one, ?_⟩
    rw [one_smul, abs_of_nonneg hx0, abs_of_nonneg hpos.le]
    exact hxa

/-- Any two atoms are either disjoint or scalar multiples of each other. -/
theorem isVLDisjoint_or_smul_of_isVLAtom [IsVLArchimedean X]
    {a b : X} (ha : IsVLAtom a) (hb : IsVLAtom b) :
    IsVLDisjoint a b ∨ ∃ c : ℝ, b = c • a := by
  by_cases hd : IsVLDisjoint a b
  · exact Or.inl hd
  refine Or.inr ?_
  have hab_nn : 0 ≤ a ⊓ b := le_inf ha.1.le hb.1.le
  have hab_ne : a ⊓ b ≠ 0 := fun habz => hd (isVLDisjoint_of_inf_eq_zero habz)
  obtain ⟨α, hα⟩ := ha.2 (a ⊓ b) hab_nn inf_le_left
  obtain ⟨β, hβ⟩ := hb.2 (a ⊓ b) hab_nn inf_le_right
  have heq : α • a = β • b := hα ▸ hβ
  have hβ_ne : β ≠ 0 := fun h0 => hab_ne (by rw [hβ, h0, zero_smul])
  refine ⟨α / β, ?_⟩
  have hcalc : (α / β) • a = β⁻¹ • (α • a) := by
    rw [div_eq_inv_mul, mul_smul]
  rw [hcalc, heq, smul_smul, inv_mul_cancel₀ hβ_ne, one_smul]

/-! ### The principal band of an atom -/

/-- For an atom `a`, a non-negative element below `c • a` is non-negatively
spanned by `a`. -/
private lemma exists_nonneg_smul_of_le_smul_atom {a : X} (ha : IsVLAtom a)
    {y : X} (hy0 : 0 ≤ y) {k : ℝ} (hk : 0 ≤ k) (hyk : y ≤ k • a) :
    ∃ c : ℝ, 0 ≤ c ∧ y = c • a := by
  obtain ⟨c, hc⟩ := exists_smul_of_le_smul_atom ha hy0 hk hyk
  rcases lt_or_ge c 0 with hcneg | hcnn
  · have hca : c • a ≤ 0 := smul_nonpos_of_nonpos_of_nonneg hcneg.le ha.1.le
    rw [← hc] at hca
    have hy : y = 0 := le_antisymm hca hy0
    exact ⟨0, le_refl 0, by rw [hy, zero_smul]⟩
  · exact ⟨c, hcnn, hc⟩

/-- For an atom `a`, a non-negative element in the principal band is a
non-negative multiple of `a`. -/
private lemma exists_nonneg_smul_of_nonneg_in_principalBand [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) {x : X} (hx0 : 0 ≤ x) (hxin : x ∈ Band.generated ({a} : Set X)) :
    ∃ c : ℝ, 0 ≤ c ∧ x = c • a := by
  have ha_pos := h.1
  have ha_nn : 0 ≤ a := ha_pos.le
  have ha_ne : a ≠ 0 := ha_pos.ne'
  rw [Band.mem_generated_singleton_iff_isLUB_inf_nsmul ha_nn hx0] at hxin
  -- Choose c_n ≥ 0 with x ⊓ n•a = c_n • a
  have hcn : ∀ n : ℕ, ∃ c : ℝ, 0 ≤ c ∧ x ⊓ (n • a) = c • a := fun n => by
    have hbound : x ⊓ (n • a) ≤ (n : ℝ) • a := by
      rw [Nat.cast_smul_eq_nsmul]; exact inf_le_right
    exact exists_nonneg_smul_of_le_smul_atom h
      (le_inf hx0 (nsmul_nonneg ha_nn n)) n.cast_nonneg hbound
  choose c hc_nn hc_eq using hcn
  -- Key: if `0 ≤ s ≤ t` (reals), then `s • a ≤ t • a`.
  have smul_mono : ∀ {s t : ℝ}, 0 ≤ s → s ≤ t → s • a ≤ t • a := by
    intro s t hs hst
    have hts : 0 ≤ t - s := sub_nonneg.mpr hst
    have hnn : 0 ≤ (t - s) • a := smul_nonneg hts ha_nn
    have heq : t • a = (t - s) • a + s • a := by
      rw [← add_smul]; congr 1; ring
    rw [heq]; exact le_add_of_nonneg_left hnn
  -- {c n} is bounded above (by Archimedean)
  have c_bound : ∃ M : ℝ, ∀ n, c n ≤ M := by
    by_contra hub
    push Not at hub
    have step : ∀ m : ℕ, m • a ≤ x := by
      intro m
      obtain ⟨n, hn⟩ := hub (m : ℝ)
      have hm_le_cn : (m : ℝ) • a ≤ c n • a := smul_mono m.cast_nonneg hn.le
      have hcn_le_x : c n • a ≤ x := by
        have := (hc_eq n).symm.le.trans (inf_le_left (a := x) (b := n • a)); exact this
      have hmx : (m : ℝ) • a ≤ x := le_trans hm_le_cn hcn_le_x
      rwa [Nat.cast_smul_eq_nsmul] at hmx
    exact ha_ne (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le ha_nn step)
  obtain ⟨M, hM⟩ := c_bound
  set S : Set ℝ := Set.range c
  have hS_ne : S.Nonempty := ⟨c 0, ⟨0, rfl⟩⟩
  have hS_bdd : BddAbove S := ⟨M, fun _ ⟨n, hn⟩ => hn ▸ hM n⟩
  set C := sSup S with hC_def
  have hC_ub : ∀ n, c n ≤ C := fun n => le_csSup hS_bdd ⟨n, rfl⟩
  have hC_nn : 0 ≤ C := le_trans (hc_nn 0) (hC_ub 0)
  refine ⟨C, hC_nn, ?_⟩
  -- Step A: x ≤ C • a
  have hCa_ub_set : ∀ y ∈ Set.range (fun n : ℕ => x ⊓ (n • a)), y ≤ C • a := by
    rintro _ ⟨n, rfl⟩
    change x ⊓ (n • a) ≤ C • a
    rw [hc_eq n]
    exact smul_mono (hc_nn n) (hC_ub n)
  have hx_le_Ca : x ≤ C • a := hxin.2 hCa_ub_set
  -- Step B: C • a ≤ x via Archimedean
  have hCa_diff_nn : 0 ≤ C • a - x := sub_nonneg.mpr hx_le_Ca
  have hCa_diff_bound : ∀ n : ℕ, n • (C • a - x) ≤ a := by
    intro n
    rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
    · subst hn0; rw [zero_nsmul]; exact ha_nn
    have hn_pos_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
    have hε_pos : (0 : ℝ) < (n : ℝ)⁻¹ := inv_pos.mpr hn_pos_real
    obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
      by_contra hno
      push Not at hno
      have hCle : C ≤ C - (n : ℝ)⁻¹ := csSup_le hS_ne hno
      linarith
    have hCcm_lt : C - c m < (n : ℝ)⁻¹ := by linarith
    have hCcm_nn : 0 ≤ C - c m := sub_nonneg.mpr (hC_ub m)
    -- (C - c m) • a ≤ n⁻¹ • a
    have hsmul_le : (C - c m) • a ≤ (n : ℝ)⁻¹ • a := smul_mono hCcm_nn hCcm_lt.le
    -- C • a - x ≤ (C - c m) • a since c m • a ≤ x
    have hcm_le_x : c m • a ≤ x := by
      have hh : x ⊓ (m • a) ≤ x := inf_le_left
      rw [hc_eq m] at hh; exact hh
    have hCa_minus_x_le : C • a - x ≤ (C - c m) • a := by
      have hsplit : C • a = (C - c m) • a + c m • a := by
        rw [← add_smul]; congr 1; ring
      rw [hsplit, add_sub_assoc]
      exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
    -- n • (C • a - x) ≤ n • (n⁻¹ • a) = a
    have hstep : (C • a - x) ≤ (n : ℝ)⁻¹ • a := le_trans hCa_minus_x_le hsmul_le
    have hnsmul : n • (C • a - x) ≤ n • ((n : ℝ)⁻¹ • a) :=
      nsmul_le_nsmul_right hstep n
    have hrew : n • ((n : ℝ)⁻¹ • a) = a := by
      rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_pos_real.ne', one_smul]
    rwa [hrew] at hnsmul
  have hCax : C • a - x = 0 :=
    IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le hCa_diff_nn hCa_diff_bound
  exact (sub_eq_zero.mp hCax).symm

/-- The principal band generated by an atom is the line spanned by that atom. -/
theorem principalBand_eq_smul_of_isVLAtom [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) :
    (Band.generated ({a} : Set X) : Set X) = {x | ∃ c : ℝ, x = c • a} := by
  apply Set.Subset.antisymm
  · -- principalBand a ⊆ ℝ • a
    intro x hx
    have hxp_in : x⁺ ∈ Band.generated ({a} : Set X) :=
      (Band.generated ({a} : Set X)).toOrderIdeal.sup_mem
        hx (Band.generated ({a} : Set X)).toOrderIdeal.toSubmodule.zero_mem
    have hxn_in : x⁻ ∈ Band.generated ({a} : Set X) := by
      have hneg : -x ∈ Band.generated ({a} : Set X) :=
        (Band.generated ({a} : Set X)).toOrderIdeal.toSubmodule.neg_mem hx
      exact (Band.generated ({a} : Set X)).toOrderIdeal.sup_mem hneg
        (Band.generated ({a} : Set X)).toOrderIdeal.toSubmodule.zero_mem
    obtain ⟨α, _, hα⟩ := exists_nonneg_smul_of_nonneg_in_principalBand h
      (posPart_nonneg x) hxp_in
    obtain ⟨β, _, hβ⟩ := exists_nonneg_smul_of_nonneg_in_principalBand h
      (negPart_nonneg x) hxn_in
    refine ⟨α - β, ?_⟩
    calc x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
      _ = α • a - β • a := by rw [hα, hβ]
      _ = (α - β) • a := (sub_smul α β a).symm
  · -- ℝ • a ⊆ principalBand a
    rintro x ⟨c, rfl⟩
    have ha_in : a ∈ Band.generated ({a} : Set X) :=
      Band.subset_generated {a} (Set.mem_singleton a)
    exact (Band.generated ({a} : Set X)).toOrderIdeal.toSubmodule.smul_mem c ha_in

/-- For an atom `a`, scalar comparison is reflected by smul. -/
private lemma smul_le_smul_iff_atom {a : X} (h : IsVLAtom a) {c d : ℝ} :
    c • a ≤ d • a ↔ c ≤ d := by
  refine ⟨fun hcd => ?_, fun hcd => smul_le_smul_real_of_nonneg h.1.le hcd⟩
  by_contra hcd'
  push Not at hcd'
  have h1 : (c - d) • a ≤ 0 := by
    rw [sub_smul]; exact sub_nonpos.mpr hcd
  have h2 : 0 < (c - d) • a := smul_pos_of_pos h.1 (by linarith)
  exact (h2.trans_le h1).false

/-- For an atom `a` and `x ≥ 0`, there exists a non-negative `c` with `c • a ≤ x`
and `(x - c • a) ⊥ a`. -/
private lemma decomp_of_atom_nonneg [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) {x : X} (hx0 : 0 ≤ x) :
    ∃ c : ℝ, 0 ≤ c ∧ c • a ≤ x ∧ IsVLDisjoint (x - c • a) a := by
  have ha_pos := h.1
  have ha_nn : 0 ≤ a := ha_pos.le
  have ha_ne : a ≠ 0 := ha_pos.ne'
  -- Choose c_n ≥ 0 with x ⊓ n•a = c_n • a.
  have hcn : ∀ n : ℕ, ∃ c : ℝ, 0 ≤ c ∧ x ⊓ (n • a) = c • a := fun n => by
    have hbound : x ⊓ (n • a) ≤ (n : ℝ) • a := by
      rw [Nat.cast_smul_eq_nsmul]; exact inf_le_right
    exact exists_nonneg_smul_of_le_smul_atom h
      (le_inf hx0 (nsmul_nonneg ha_nn n)) n.cast_nonneg hbound
  choose c hc_nn hc_eq using hcn
  -- {c n} is bounded above (Archimedean argument).
  have c_bound : ∃ M : ℝ, ∀ n, c n ≤ M := by
    by_contra hub
    push Not at hub
    have step : ∀ m : ℕ, m • a ≤ x := by
      intro m
      obtain ⟨n, hn⟩ := hub (m : ℝ)
      have hm_le_cn : (m : ℝ) • a ≤ c n • a :=
        smul_le_smul_real_of_nonneg ha_nn hn.le
      have hcn_le_x : c n • a ≤ x := by
        have hh : x ⊓ (n • a) ≤ x := inf_le_left
        rw [hc_eq n] at hh; exact hh
      have hmx : (m : ℝ) • a ≤ x := le_trans hm_le_cn hcn_le_x
      rwa [Nat.cast_smul_eq_nsmul] at hmx
    exact ha_ne (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le ha_nn step)
  obtain ⟨M, hM⟩ := c_bound
  set S : Set ℝ := Set.range c with hS_def
  have hS_ne : S.Nonempty := ⟨c 0, ⟨0, rfl⟩⟩
  have hS_bdd : BddAbove S := ⟨M, fun _ ⟨n, hn⟩ => hn ▸ hM n⟩
  set C := sSup S with hC_def
  have hC_ub : ∀ n, c n ≤ C := fun n => le_csSup hS_bdd ⟨n, rfl⟩
  have hC_nn : 0 ≤ C := le_trans (hc_nn 0) (hC_ub 0)
  refine ⟨C, hC_nn, ?_, ?_⟩
  · -- C • a ≤ x via Archimedean approximation.
    have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
      intro n hn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
      obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
        by_contra hno
        push Not at hno
        have hCle : C ≤ C - (n : ℝ)⁻¹ := csSup_le hS_ne hno
        linarith [inv_pos.mpr hn_real]
      have hCm_le : C - c m ≤ (n : ℝ)⁻¹ := by linarith
      have hsmul_le : (C - c m) • a ≤ ((n : ℝ)⁻¹) • a :=
        smul_le_smul_real_of_nonneg ha_nn hCm_le
      have hcm_le_x : c m • a ≤ x := by
        have hh : x ⊓ (m • a) ≤ x := inf_le_left
        rw [hc_eq m] at hh; exact hh
      have hsplit : C • a = (C - c m) • a + c m • a := by
        rw [← add_smul]; congr 1; ring
      have h1 : C • a - x ≤ (C - c m) • a := by
        rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
      exact le_trans h1 hsmul_le
    have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
      intro n
      rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
      · subst hn0; rw [zero_nsmul]; exact ha_nn
      have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
      have hb := hbound n hn_pos
      have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
        rw [posPart_def]; exact sup_le hb (smul_nonneg (inv_nonneg.mpr hn_real.le) ha_nn)
      have hns : n • (C • a - x)⁺ ≤ n • (((n : ℝ)⁻¹) • a) := nsmul_le_nsmul_right hpp n
      have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
        rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
      rwa [hrew] at hns
    have hposPart_zero : (C • a - x)⁺ = 0 :=
      IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound
    exact sub_nonpos.mp (posPart_eq_zero.mp hposPart_zero)
  · -- (x - C • a) ⊥ a
    have hCa_le_x : C • a ≤ x := by
      -- redo same Archimedean step (we already have it from above)
      have hbound : ∀ n : ℕ, 0 < n → C • a - x ≤ ((n : ℝ)⁻¹) • a := by
        intro n hn
        have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn
        obtain ⟨_, ⟨m, rfl⟩, hcm_gt⟩ : ∃ y ∈ S, C - (n : ℝ)⁻¹ < y := by
          by_contra hno; push Not at hno
          linarith [csSup_le hS_ne hno, inv_pos.mpr hn_real]
        have hCm_le : C - c m ≤ (n : ℝ)⁻¹ := by linarith
        have hcm_le_x : c m • a ≤ x := by
          have hh : x ⊓ (m • a) ≤ x := inf_le_left
          rw [hc_eq m] at hh; exact hh
        have hsplit : C • a = (C - c m) • a + c m • a := by
          rw [← add_smul]; congr 1; ring
        have h1 : C • a - x ≤ (C - c m) • a := by
          rw [hsplit, add_sub_assoc]; exact add_le_of_nonpos_right (sub_nonpos.mpr hcm_le_x)
        exact le_trans h1 (smul_le_smul_real_of_nonneg ha_nn hCm_le)
      have hposPart_bound : ∀ n : ℕ, n • (C • a - x)⁺ ≤ a := by
        intro n
        rcases Nat.eq_zero_or_pos n with hn0 | hn_pos
        · subst hn0; rw [zero_nsmul]; exact ha_nn
        have hn_real : (0 : ℝ) < n := Nat.cast_pos.mpr hn_pos
        have hpp : (C • a - x)⁺ ≤ ((n : ℝ)⁻¹) • a := by
          rw [posPart_def]
          exact sup_le (hbound n hn_pos) (smul_nonneg (inv_nonneg.mpr hn_real.le) ha_nn)
        have hns := nsmul_le_nsmul_right hpp n
        have hrew : n • (((n : ℝ)⁻¹) • a) = a := by
          rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul, mul_inv_cancel₀ hn_real.ne', one_smul]
        rwa [hrew] at hns
      exact sub_nonpos.mp (posPart_eq_zero.mp
        (IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (posPart_nonneg _) hposPart_bound))
    have hxCa_nn : 0 ≤ x - C • a := sub_nonneg.mpr hCa_le_x
    -- Show (x - C•a) ⊓ a = 0.
    set y := (x - C • a) ⊓ a with hy_def
    have hy_nn : 0 ≤ y := le_inf hxCa_nn ha_nn
    have hy_le : y ≤ a := inf_le_right
    have hy_le_one : y ≤ (1 : ℝ) • a := by rw [one_smul]; exact hy_le
    obtain ⟨d, hd_nn, hyd⟩ := exists_nonneg_smul_of_le_smul_atom h hy_nn zero_le_one hy_le_one
    have hd_zero : d = 0 := by
      by_contra hd_ne
      have hd_pos : 0 < d := lt_of_le_of_ne hd_nn (Ne.symm hd_ne)
      have hda_le : d • a ≤ x - C • a := by rw [← hyd]; exact inf_le_left
      have hCda_le_x : (C + d) • a ≤ x := by
        have h1 : C • a + d • a ≤ C • a + (x - C • a) := add_le_add_right hda_le (C • a)
        have h2 : C • a + (x - C • a) = x := by abel
        rw [h2] at h1
        rw [add_smul]; exact h1
      -- Pick n ∈ ℕ with C + d < n, then (C + d) • a ≤ n • a, contradicting c_n ≤ C.
      obtain ⟨n, hn⟩ : ∃ n : ℕ, C + d < n := exists_nat_gt (C + d)
      have hCdn : C + d ≤ (n : ℝ) := hn.le
      have hCda_le_na : (C + d) • a ≤ (n : ℝ) • a := smul_le_smul_real_of_nonneg ha_nn hCdn
      have hCda_le_inf : (C + d) • a ≤ x ⊓ (n • a) := by
        rw [Nat.cast_smul_eq_nsmul] at hCda_le_na
        exact le_inf hCda_le_x hCda_le_na
      rw [hc_eq n] at hCda_le_inf
      have hCdn_le_cn : C + d ≤ c n := (smul_le_smul_iff_atom h).mp hCda_le_inf
      linarith [hC_ub n]
    have hy_zero : y = 0 := by rw [hyd, hd_zero, zero_smul]
    have habs_x : |x - C • a| = x - C • a := abs_of_nonneg hxCa_nn
    have habs_a : |a| = a := abs_of_nonneg ha_nn
    change |x - C • a| ⊓ |a| = 0
    rw [habs_x, habs_a]; exact hy_zero

/-- The principal band generated by an atom is a projection band. -/
theorem exists_projectionBand_principalBand_of_isVLAtom [IsVLArchimedean X]
    {a : X} (h : IsVLAtom a) :
    ∃ P : ProjectionBand X, (P : Set X) = (Band.generated ({a} : Set X) : Set X) := by
  have ha_nn : 0 ≤ a := h.1.le
  have hpb_eq := principalBand_eq_smul_of_isVLAtom h
  -- Reformulate via projectionBand_iff_add_disjointComplement.
  have hdec : ∀ x : X, ∃ y z : X,
      y ∈ ((Band.generated ({a} : Set X)).toOrderIdeal : Set X)
      ∧ z ∈ disjointComplement ((Band.generated ({a} : Set X)).toOrderIdeal : Set X)
      ∧ x = y + z := by
    intro x
    obtain ⟨c₁, _, _, hc₁_disj⟩ := decomp_of_atom_nonneg h (posPart_nonneg x)
    obtain ⟨c₂, _, _, hc₂_disj⟩ := decomp_of_atom_nonneg h (negPart_nonneg x)
    refine ⟨(c₁ - c₂) • a, x - (c₁ - c₂) • a, ?_, ?_, by abel⟩
    · -- (c₁ - c₂) • a ∈ principalBand a
      have ha_in : a ∈ Band.generated ({a} : Set X) :=
        Band.subset_generated {a} (Set.mem_singleton a)
      exact (Band.generated ({a} : Set X)).toOrderIdeal.toSubmodule.smul_mem (c₁ - c₂) ha_in
    · -- x - (c₁ - c₂) • a is disjoint from every k • a, hence from principalBand a.
      have hdisj_a : IsVLDisjoint (x - (c₁ - c₂) • a) a := by
        have hsplit : x - (c₁ - c₂) • a = (x⁺ - c₁ • a) - (x⁻ - c₂ • a) := by
          have hps : x = x⁺ - x⁻ := (posPart_sub_negPart x).symm
          conv_lhs => rw [hps]
          rw [sub_smul]; abel
        have hd1 : (x⁺ - c₁ • a) ∈ (({a} : Set X))ᵈ := fun a' ha' => by
          rw [Set.mem_singleton_iff.mp ha']; exact hc₁_disj
        have hd2 : (x⁻ - c₂ • a) ∈ (({a} : Set X))ᵈ := fun a' ha' => by
          rw [Set.mem_singleton_iff.mp ha']; exact hc₂_disj
        have hsubmem : (x⁺ - c₁ • a) - (x⁻ - c₂ • a) ∈ (({a} : Set X))ᵈ :=
          (Band.disjointComplement ({a} : Set X)).toOrderIdeal.toSubmodule.sub_mem hd1 hd2
        rw [hsplit]
        exact hsubmem a (Set.mem_singleton a)
      intro y hy
      have hy_set : y ∈ (Band.generated ({a} : Set X) : Set X) := hy
      rw [hpb_eq] at hy_set
      obtain ⟨k, rfl⟩ := hy_set
      exact hdisj_a.smul_right k
  obtain ⟨P, hP⟩ := (ProjectionBand.projectionBand_iff_add_disjointComplement
    (Band.generated ({a} : Set X)).toOrderIdeal).mpr hdec
  exact ⟨P, hP⟩

/-! ### Atomic and continuous parts -/

variable (X) in
/-- The set of all atoms of `X`. -/
def vlAtoms : Set X := {a | IsVLAtom a}

/-- Membership in `vlAtoms X` is the atom predicate. -/
@[simp]
theorem mem_vlAtoms {a : X} : a ∈ vlAtoms X ↔ IsVLAtom a := Iff.rfl

variable (X) in
/-- The **atomic part** of `X` is the band generated by the set of all atoms. -/
def atomicPart : Band X := Band.generated (vlAtoms X)

variable (X) in
/-- The **continuous part** of `X` is the disjoint complement of the set of
atoms — the band of vectors disjoint from every atom. -/
def continuousPart : Band X := Band.disjointComplement (vlAtoms X)

/-- An element belongs to the continuous part iff it is disjoint from every
atom. -/
theorem mem_continuousPart_iff {x : X} :
    x ∈ continuousPart X ↔ ∀ a : X, IsVLAtom a → IsVLDisjoint x a :=
  ⟨fun h a ha => h a ha, fun h a ha => h a ha⟩

/-- Every atom belongs to the atomic part. -/
theorem isVLAtom.mem_atomicPart {a : X} (h : IsVLAtom a) :
    a ∈ atomicPart X :=
  Band.subset_generated (vlAtoms X) h

/-- In an Archimedean vector lattice, the continuous part is the disjoint
complement of the atomic part. -/
theorem continuousPart_eq_disjointComplement_atomicPart [IsVLArchimedean X] :
    (continuousPart X : Set X) = (atomicPart X : Set X)ᵈ := by
  change ((vlAtoms X)ᵈ : Set X) = ((Band.generated (vlAtoms X) : Set X))ᵈ
  rw [← Band.disjointComplement_disjointComplement_eq_generated,
    disjointComplement_disjointComplement_disjointComplement]

/-- The atomic and continuous parts intersect only at zero. -/
theorem atomicPart_inter_continuousPart_eq_zero [IsVLArchimedean X] {x : X}
    (hx : x ∈ atomicPart X) (hx' : x ∈ continuousPart X) : x = 0 := by
  have hx'' : x ∈ ((atomicPart X : Set X))ᵈ := by
    rw [← continuousPart_eq_disjointComplement_atomicPart]; exact hx'
  have hmem : x ∈ ({0} : Set X) :=
    disjointComplement_inter_eq_zero (atomicPart X : Set X) ⟨hx, hx''⟩
  simpa using hmem

/-! ### Atomic vector lattices -/

/-- A vector lattice is **atomic** (or *discrete*) when it equals the band
generated by all of its atoms. -/
class IsAtomicVectorLattice (X : Type*) [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] : Prop where
  mem_atomicPart : ∀ x : X, x ∈ atomicPart X

/-- In an atomic vector lattice, every element belongs to the atomic part. -/
theorem mem_atomicPart_of_isAtomicVectorLattice [IsAtomicVectorLattice X]
    (x : X) : x ∈ atomicPart X :=
  IsAtomicVectorLattice.mem_atomicPart x

/-- An Archimedean vector lattice is atomic iff the only element disjoint from
every atom is zero. -/
theorem isAtomicVectorLattice_iff_continuousPart_eq_zero
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔ ∀ x : X, x ∈ continuousPart X → x = 0 := by
  refine ⟨fun ⟨h⟩ x hx => atomicPart_inter_continuousPart_eq_zero (h x) hx,
    fun hcont => ⟨fun x => ?_⟩⟩
  change x ∈ (atomicPart X : Set X)
  rw [(Band.eq_disjointComplement_disjointComplement (atomicPart X)).symm]
  intro y hy
  have hy_cont : y ∈ continuousPart X := by
    change y ∈ (continuousPart X : Set X)
    rw [continuousPart_eq_disjointComplement_atomicPart]
    exact hy
  rw [hcont y hy_cont]
  exact isVLDisjoint_comm.mp (isVLDisjoint_zero_left x)

/-- An Archimedean vector lattice is atomic iff every strictly positive
element dominates an atom. -/
theorem isAtomicVectorLattice_iff_forall_pos_dominates_atom
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔
      ∀ x : X, 0 < x → ∃ a : X, IsVLAtom a ∧ a ≤ x := by
  rw [isAtomicVectorLattice_iff_continuousPart_eq_zero]
  refine ⟨fun hcont x hx => ?_, fun hdom x hx => ?_⟩
  · -- Atomic ⟹ pos x dominates an atom.
    by_contra hno
    push Not at hno
    have hxc : x ∈ continuousPart X := by
      intro a ha
      have hax_nn : 0 ≤ x ⊓ a := le_inf hx.le ha.1.le
      obtain ⟨c, hc_nn, hc_eq⟩ := exists_nonneg_smul_of_le_smul_atom ha hax_nn zero_le_one
        (by rw [one_smul]; exact inf_le_right)
      rcases eq_or_lt_of_le hc_nn with hc0 | hc_pos
      · have hxa : x ⊓ a = 0 := by rw [hc_eq, ← hc0, zero_smul]
        exact isVLDisjoint_of_inf_eq_zero hxa
      · exfalso
        refine hno (c • a) (IsVLAtom.smul ha hc_pos) ?_
        rw [← hc_eq]; exact inf_le_left
    exact hx.ne' (hcont x hxc)
  · -- Every pos dominates an atom ⟹ continuousPart trivial.
    by_contra hxne
    have habs_nn : 0 ≤ |x| := abs_nonneg x
    have habs_pos : 0 < |x| :=
      lt_of_le_of_ne habs_nn (fun h => hxne ((abs_eq_zero_iff_zero x).mp h.symm))
    have habs_in : |x| ∈ continuousPart X :=
      (continuousPart X).toOrderIdeal.abs_mem hx
    obtain ⟨a, ha, ha_le⟩ := hdom |x| habs_pos
    have hdisj : IsVLDisjoint (|x|) a := habs_in a ha
    have habsa : |a| = a := abs_of_nonneg ha.1.le
    have habsabsx : |(|x|)| = |x| := abs_of_nonneg habs_nn
    have hinf : (|x|) ⊓ a = 0 := by
      have hh : |(|x|)| ⊓ |a| = 0 := hdisj
      rwa [habsa, habsabsx] at hh
    apply ha.ne_zero
    have hh : a ⊓ |x| = a := inf_eq_left.mpr ha_le
    rw [inf_comm] at hinf
    rw [← hh, hinf]

/-- An Archimedean vector lattice is atomic iff its continuous part is
trivial. -/
theorem isAtomicVectorLattice_iff_continuousPart_trivial
    [IsVLArchimedean X] :
    IsAtomicVectorLattice X ↔ (continuousPart X : Set X) = {0} := by
  rw [isAtomicVectorLattice_iff_continuousPart_eq_zero]
  refine ⟨fun h => ?_, fun h x hx => ?_⟩
  · ext x
    refine ⟨h x, ?_⟩
    rintro rfl
    exact (continuousPart X).toOrderIdeal.toSubmodule.zero_mem
  · have : x ∈ ({0} : Set X) := h ▸ hx
    simpa using this

/-! ### Yudin's theorem: finite-dimensional vector lattices -/

/-- If a positive element `u` is not above any atom, then `[0, u]` admits a
disjoint pair of non-zero elements. -/
private lemma exists_disjoint_pair_of_no_atom_below [IsVLArchimedean X]
    {y : X} (hy_pos : 0 < y)
    (hy_no_atom : ∀ a : X, IsVLAtom a → ¬ a ≤ y) :
    ∃ a b : X, 0 < a ∧ a ≤ y ∧ 0 < b ∧ b ≤ y ∧ IsVLDisjoint a b := by
  have hy_not_atom : ¬ IsVLAtom y := fun h_atom => hy_no_atom y h_atom le_rfl
  rw [isVLAtom_iff_no_disjoint_in_interval hy_pos] at hy_not_atom
  push Not at hy_not_atom
  obtain ⟨a, b, ha_nn, ha_le, hb_nn, hb_le, hdisj, ha_ne, hb_ne⟩ := hy_not_atom
  exact ⟨a, b, lt_of_le_of_ne ha_nn (Ne.symm ha_ne), ha_le,
    lt_of_le_of_ne hb_nn (Ne.symm hb_ne), hb_le, hdisj⟩

/-- In a vector lattice with a positive element `u` not above any atom, there
exists an infinite sequence of pairwise disjoint, positive elements all
bounded by `u`. -/
private lemma exists_disjoint_seq_of_no_atom_below [IsVLArchimedean X]
    {u : X} (hu_pos : 0 < u)
    (hu_no_atom : ∀ a : X, IsVLAtom a → ¬ a ≤ u) :
    ∃ x : ℕ → X, (∀ n, 0 < x n) ∧
      Pairwise (fun i j => IsVLDisjoint (x i) (x j)) := by
  -- Existence of a disjoint split for any positive element ≤ u.
  have split_ex : ∀ s : {y : X // 0 < y ∧ y ≤ u},
      ∃ p : X × {y : X // 0 < y ∧ y ≤ u},
      0 < p.1 ∧ p.1 ≤ s.1 ∧ p.2.1 ≤ s.1 ∧ IsVLDisjoint p.1 p.2.1 := by
    intro s
    obtain ⟨y, hy_pos, hy_le⟩ := s
    have hy_no_atom' : ∀ a : X, IsVLAtom a → ¬ a ≤ y :=
      fun a ha hay => hu_no_atom a ha (hay.trans hy_le)
    obtain ⟨a, b, ha_pos, ha_le, hb_pos, hb_le, hdisj⟩ :=
      exists_disjoint_pair_of_no_atom_below hy_pos hy_no_atom'
    refine ⟨(a, ⟨b, hb_pos, hb_le.trans hy_le⟩), ha_pos, ha_le, hb_le, hdisj⟩
  choose pair pair_pos pair_le1 pair_le2 pair_disj using split_ex
  let s_init : {y : X // 0 < y ∧ y ≤ u} := ⟨u, hu_pos, le_refl u⟩
  let step : {y : X // 0 < y ∧ y ≤ u} → {y : X // 0 < y ∧ y ≤ u} :=
    fun s => (pair s).2
  let states : ℕ → {y : X // 0 < y ∧ y ≤ u} := fun n => step^[n] s_init
  let xs : ℕ → X := fun n => (pair (states n)).1
  -- Properties of states/xs
  have states_succ : ∀ n, states (n + 1) = step (states n) := fun n =>
    Function.iterate_succ_apply' step n s_init
  have h_states_anti : ∀ k l, k ≤ l → (states l).1 ≤ (states k).1 := by
    intro k l hkl
    induction l, hkl using Nat.le_induction with
    | base => exact le_refl _
    | succ m hkm IH =>
      have hstep : (states (m + 1)).1 ≤ (states m).1 := by
        rw [states_succ]; exact pair_le2 (states m)
      exact hstep.trans IH
  have hxs_le : ∀ n, xs n ≤ (states n).1 := fun n => pair_le1 (states n)
  have hxs_pos : ∀ n, 0 < xs n := fun n => pair_pos (states n)
  have h_disj_succ : ∀ n, IsVLDisjoint (xs n) (states (n + 1)).1 := fun n => by
    rw [states_succ]
    exact pair_disj (states n)
  have h_states_nn : ∀ n, 0 ≤ (states n).1 := fun n => (states n).2.1.le
  -- Key: xs i ⊥ xs j for i < j
  have h_lt_disj : ∀ i j, i < j → IsVLDisjoint (xs i) (xs j) := by
    intro i j hij
    have hxs_j_nn : 0 ≤ xs j := (hxs_pos j).le
    have h_le : xs j ≤ (states (i + 1)).1 :=
      (hxs_le j).trans (h_states_anti (i + 1) j hij)
    refine (h_disj_succ i).mono_right ?_
    rw [abs_of_nonneg hxs_j_nn, abs_of_nonneg (h_states_nn (i + 1))]
    exact h_le
  refine ⟨xs, hxs_pos, fun i j hij => ?_⟩
  rcases Nat.lt_or_gt_of_ne hij with hlt | hgt
  · exact h_lt_disj i j hlt
  · exact isVLDisjoint_comm.mp (h_lt_disj j i hgt)

/-- In an atomic Archimedean vector lattice, if no atom can be added disjointly
to a finite disjoint family of atoms, then the whole space coincides with the
linear span of that family. -/
private lemma top_eq_span_of_max_disjoint_atom_family [IsVLArchimedean X]
    [hAtomic : IsAtomicVectorLattice X] {n : ℕ} (a : Fin n → X)
    (ha_atom : ∀ i, IsVLAtom (a i))
    (ha_disj : Pairwise (fun i j : Fin n => IsVLDisjoint (a i) (a j)))
    (ha_max : ∀ b : X, IsVLAtom b → ∃ i, ¬ IsVLDisjoint (a i) b) :
    (⊤ : Submodule ℝ X) = Submodule.span ℝ (Set.range a) := by
  -- Pick a projection band realizing each principal band of `a i`.
  choose P hP using fun i => exists_projectionBand_principalBand_of_isVLAtom (ha_atom i)
  -- The underlying set of `P i` is `ℝ • a i`.
  have hP_smul : ∀ i, ((P i : Set X)) = {x | ∃ c : ℝ, x = c • a i} := fun i => by
    rw [hP i]; exact principalBand_eq_smul_of_isVLAtom (ha_atom i)
  -- For `i ≠ j`, the band `P i` is contained in the disjoint complement of `P j`.
  have hP_sub_disj : ∀ i j : Fin n, i ≠ j → (P i : Set X) ⊆ ((P j : Set X))ᵈ := by
    intro i j hij z hz
    rw [hP_smul i] at hz
    obtain ⟨c, rfl⟩ := hz
    intro y hy
    rw [hP_smul j] at hy
    obtain ⟨d, rfl⟩ := hy
    exact ((ha_disj hij).smul_left c).smul_right d
  -- The band projection onto `P j` of any element of `P i` (with `i ≠ j`) is zero.
  have hπ_cross_zero : ∀ i j : Fin n, i ≠ j → ∀ z, z ∈ (P i : Set X) →
      (P j).bandProjection z = 0 := fun i j hij z hz =>
    (P j).bandProjection_eq_zero_of_mem_dc (hP_sub_disj i j hij hz)
  -- The band projection onto `P i` of any `y` is a scalar multiple of `a i`.
  have hπ_smul : ∀ i (y : X), ∃ c : ℝ, (P i).bandProjection y = c • a i := fun i y => by
    have h : (P i).bandProjection y ∈ {x | ∃ c : ℝ, x = c • a i} := by
      rw [← hP_smul i]; exact (P i).bandProjection_mem y
    exact h
  -- For each `j`, `(P j).bandProjection (y - ∑ i, (P i).bandProjection y) = 0`.
  have hπ_f_zero : ∀ (y : X) (j : Fin n),
      (P j).bandProjection (y - ∑ i, (P i).bandProjection y) = 0 := by
    intro y j
    rw [map_sub, map_sum]
    have h_sum_eq : ∑ i : Fin n, (P j).bandProjection ((P i).bandProjection y)
        = (P j).bandProjection y := by
      rw [Finset.sum_eq_single j]
      · exact LinearMap.congr_fun (P j).bandProjection_sq y
      · intro i _ hij
        exact hπ_cross_zero i j hij _ ((P i).bandProjection_mem y)
      · intro h; exact absurd (Finset.mem_univ j) h
    rw [h_sum_eq, sub_self]
  -- Hence `y - ∑ i, (P i).bandProjection y ∈ (P j : Set X)ᵈ`.
  have hf_compl : ∀ (y : X) (j : Fin n),
      y - ∑ i, (P i).bandProjection y ∈ ((P j : Set X))ᵈ := by
    intro y j
    have h := (P j).id_sub_bandProjection_mem (y - ∑ i, (P i).bandProjection y)
    rw [hπ_f_zero y j, sub_zero] at h
    exact h
  -- `f y` is disjoint from each `a j`.
  have hf_disj_aj : ∀ (y : X) (j : Fin n),
      IsVLDisjoint (y - ∑ i, (P i).bandProjection y) (a j) := by
    intro y j
    have ha_in_Pj : a j ∈ (P j : Set X) := by
      rw [hP_smul j]; exact ⟨1, (one_smul ℝ _).symm⟩
    exact hf_compl y j _ ha_in_Pj
  -- For each y, `y - ∑ i, (P i).bandProjection y = 0`.
  have hf_zero_all : ∀ (y : X), y - ∑ i, (P i).bandProjection y = 0 := by
    intro y
    by_contra hne
    have habs_pos : 0 < |y - ∑ i, (P i).bandProjection y| :=
      lt_of_le_of_ne (abs_nonneg _)
        (fun h => hne ((abs_eq_zero_iff_zero _).mp h.symm))
    obtain ⟨b, hb_atom, hb_le⟩ :=
      (isAtomicVectorLattice_iff_forall_pos_dominates_atom.mp hAtomic)
        (|y - ∑ i, (P i).bandProjection y|) habs_pos
    obtain ⟨i, hi⟩ := ha_max b hb_atom
    apply hi
    have h_disj_y : IsVLDisjoint (a i) (y - ∑ i, (P i).bandProjection y) :=
      isVLDisjoint_comm.mp (hf_disj_aj y i)
    refine h_disj_y.mono_right ?_
    rw [abs_of_nonneg hb_atom.1.le]
    exact hb_le
  -- Hence every y is in the span of `Set.range a`.
  have hX_in_span : ∀ y : X, y ∈ Submodule.span ℝ (Set.range a) := by
    intro y
    have heq : y = ∑ i, (P i).bandProjection y := sub_eq_zero.mp (hf_zero_all y)
    rw [heq]
    refine Submodule.sum_mem _ fun i _ => ?_
    obtain ⟨c, hc⟩ := hπ_smul i y
    rw [hc]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)
  exact le_antisymm (fun y _ => hX_in_span y) le_top

/-- For an atomic Archimedean vector lattice that is not finite-dimensional,
any pairwise disjoint family of atoms admits an extension by an atom disjoint
from all of them. -/
private lemma exists_atom_disjoint_of_disjoint_atom_family [IsVLArchimedean X]
    [IsAtomicVectorLattice X] (h_not_fd : ¬ FiniteDimensional ℝ X)
    {n : ℕ} (a : Fin n → X)
    (ha_atom : ∀ i, IsVLAtom (a i))
    (ha_disj : Pairwise (fun i j : Fin n => IsVLDisjoint (a i) (a j))) :
    ∃ b : X, IsVLAtom b ∧ ∀ i, IsVLDisjoint (a i) b := by
  by_contra hno
  push Not at hno
  have h_top_eq := top_eq_span_of_max_disjoint_atom_family a ha_atom ha_disj hno
  apply h_not_fd
  have hFG : (⊤ : Submodule ℝ X).FG := h_top_eq ▸
    ⟨(Set.finite_range a).toFinset, by rw [Set.Finite.coe_toFinset]⟩
  exact ⟨hFG⟩

/-- If a disjoint family of atoms can always be extended by another atom
disjoint from each of its members, then there is an infinite pairwise disjoint
sequence of atoms. -/
private lemma exists_disjoint_atom_seq_of_extendable
    (step : ∀ n (a : Fin n → X), (∀ i, IsVLAtom (a i)) →
        Pairwise (fun i j : Fin n => IsVLDisjoint (a i) (a j)) →
        ∃ b : X, IsVLAtom b ∧ ∀ i, IsVLDisjoint (a i) b) :
    ∃ a : ℕ → X, (∀ n, IsVLAtom (a n)) ∧
      Pairwise (fun i j => IsVLDisjoint (a i) (a j)) := by
  let State : ℕ → Type _ := fun n =>
    { a : Fin n → X // (∀ i, IsVLAtom (a i)) ∧
      Pairwise (fun i j : Fin n => IsVLDisjoint (a i) (a j)) }
  have init : State 0 :=
    ⟨Fin.elim0, fun i => i.elim0, fun i _ _ => i.elim0⟩
  let stepFn : ∀ n, State n → State (n + 1) := fun n s =>
    ⟨Fin.snoc s.1 (step n s.1 s.2.1 s.2.2).choose,
      by
        intro i
        induction i using Fin.lastCases with
        | last => rw [Fin.snoc_last]
                  exact (step n s.1 s.2.1 s.2.2).choose_spec.1
        | cast i => rw [Fin.snoc_castSucc]; exact s.2.1 i,
      by
        intro i j hij
        induction i using Fin.lastCases with
        | last =>
          induction j using Fin.lastCases with
          | last => exact absurd rfl hij
          | cast j =>
            rw [Fin.snoc_last, Fin.snoc_castSucc]
            exact isVLDisjoint_comm.mp ((step n s.1 s.2.1 s.2.2).choose_spec.2 j)
        | cast i =>
          induction j using Fin.lastCases with
          | last =>
            rw [Fin.snoc_castSucc, Fin.snoc_last]
            exact (step n s.1 s.2.1 s.2.2).choose_spec.2 i
          | cast j =>
            rw [Fin.snoc_castSucc, Fin.snoc_castSucc]
            exact s.2.2 (fun heq => hij (by rw [heq]))⟩
  let states : (n : ℕ) → State n := fun n =>
    Nat.rec (motive := State) init stepFn n
  let xs : ℕ → X := fun n => (states (n + 1)).1 (Fin.last n)
  have hxs_atom : ∀ n, IsVLAtom (xs n) := fun n =>
    (states (n + 1)).2.1 (Fin.last n)
  have h_states_succ_val : ∀ k, (states (k + 1)).1 =
      Fin.snoc (states k).1
        (step k (states k).1 (states k).2.1 (states k).2.2).choose :=
    fun _ => rfl
  have h_xs_eq : ∀ k m (h : m < k), (states k).1 ⟨m, h⟩ = xs m := by
    intro k
    induction k with
    | zero => intro m h; exact absurd h (Nat.not_lt_zero m)
    | succ k IH =>
      intro m h
      rcases lt_or_eq_of_le (Nat.lt_succ_iff.mp h) with h' | h'
      · rw [h_states_succ_val k,
            show (⟨m, h⟩ : Fin (k + 1)) = (⟨m, h'⟩ : Fin k).castSucc from rfl,
            Fin.snoc_castSucc]
        exact IH m h'
      · subst h'; rfl
  have hxs_disj : Pairwise (fun i j => IsVLDisjoint (xs i) (xs j)) := by
    have h_lt_disj : ∀ p q : ℕ, p < q → IsVLDisjoint (xs p) (xs q) := by
      intro p q hpq
      have h_xs_q_eq : xs q =
          (step q (states q).1 (states q).2.1 (states q).2.2).choose := by
        change (states (q + 1)).1 (Fin.last q) = _
        rw [h_states_succ_val q, Fin.snoc_last]
      rw [h_xs_q_eq]
      have h_disj :=
        (step q (states q).1 (states q).2.1 (states q).2.2).choose_spec.2
        ⟨p, hpq⟩
      rw [h_xs_eq q p hpq] at h_disj
      exact h_disj
    intro i j hij
    rcases Nat.lt_or_gt_of_ne hij with hlt | hgt
    · exact h_lt_disj i j hlt
    · exact isVLDisjoint_comm.mp (h_lt_disj j i hgt)
  exact ⟨xs, hxs_atom, hxs_disj⟩

/-- Every infinite-dimensional Archimedean vector lattice contains a sequence of
pairwise disjoint non-zero vectors. -/
theorem exists_disjoint_seq_of_not_finiteDimensional [IsVLArchimedean X]
    (h : ¬ FiniteDimensional ℝ X) :
    ∃ x : ℕ → X, (∀ n, x n ≠ 0) ∧
      Pairwise (fun i j => IsVLDisjoint (x i) (x j)) := by
  by_cases hat : IsAtomicVectorLattice X
  · obtain ⟨xs, hxs_atom, hxs_disj⟩ := exists_disjoint_atom_seq_of_extendable
      (fun n a ha hd => exists_atom_disjoint_of_disjoint_atom_family h a ha hd)
    exact ⟨xs, fun n => (hxs_atom n).ne_zero, hxs_disj⟩
  · -- Non-atomic case: there exists `u > 0` with no atom ≤ u; iterate splits.
    rw [isAtomicVectorLattice_iff_forall_pos_dominates_atom] at hat
    push Not at hat
    obtain ⟨u, hu_pos, hu_no_atom⟩ := hat
    obtain ⟨xs, hxs_pos, hxs_disj⟩ :=
      exists_disjoint_seq_of_no_atom_below hu_pos hu_no_atom
    exact ⟨xs, fun n => (hxs_pos n).ne', hxs_disj⟩

/-- A finite-dimensional Archimedean vector lattice is atomic. -/
private lemma isAtomicVectorLattice_of_finiteDimensional [IsVLArchimedean X]
    [FiniteDimensional ℝ X] : IsAtomicVectorLattice X := by
  by_contra hat
  rw [isAtomicVectorLattice_iff_forall_pos_dominates_atom] at hat
  push Not at hat
  obtain ⟨u, hu_pos, hu_no_atom⟩ := hat
  obtain ⟨xs, hxs_pos, hxs_disj⟩ :=
    exists_disjoint_seq_of_no_atom_below hu_pos hu_no_atom
  let N := Module.finrank ℝ X
  let f : Fin (N + 1) → X := fun i => xs i.val
  have hf_ne : ∀ i, f i ≠ 0 := fun i => (hxs_pos i.val).ne'
  have hf_disj : Pairwise (fun i j : Fin (N + 1) => IsVLDisjoint (f i) (f j)) :=
    fun i j hij => hxs_disj (fun hval => hij (Fin.ext hval))
  have hf_lin : LinearIndependent ℝ f :=
    linearIndependent_of_pairwise_isVLDisjoint hf_ne hf_disj
  have h_le := hf_lin.fintype_card_le_finrank
  simp only [Fintype.card_fin] at h_le
  exact absurd h_le (Nat.not_succ_le_self N)

/-- A finite-dimensional atomic Archimedean vector lattice admits a finite
maximal pairwise disjoint family of atoms. -/
private lemma exists_max_disjoint_atom_family_of_finiteDimensional
    [IsVLArchimedean X] [IsAtomicVectorLattice X] [FiniteDimensional ℝ X] :
    ∃ n : ℕ, ∃ a : Fin n → X, (∀ i, IsVLAtom (a i)) ∧
      Pairwise (fun i j : Fin n => IsVLDisjoint (a i) (a j)) ∧
      ∀ b : X, IsVLAtom b → ∃ i, ¬ IsVLDisjoint (a i) b := by
  by_contra h_no_max
  push Not at h_no_max
  obtain ⟨xs, hxs_atom, hxs_disj⟩ :=
    exists_disjoint_atom_seq_of_extendable h_no_max
  let N := Module.finrank ℝ X
  let f : Fin (N + 1) → X := fun i => xs i.val
  have hf_ne : ∀ i, f i ≠ 0 := fun i => (hxs_atom i.val).ne_zero
  have hf_disj : Pairwise (fun i j : Fin (N + 1) => IsVLDisjoint (f i) (f j)) :=
    fun i j hij => hxs_disj (fun hval => hij (Fin.ext hval))
  have hf_lin : LinearIndependent ℝ f :=
    linearIndependent_of_pairwise_isVLDisjoint hf_ne hf_disj
  have h_le := hf_lin.fintype_card_le_finrank
  simp only [Fintype.card_fin] at h_le
  exact absurd h_le (Nat.not_succ_le_self N)

/-- **Yudin's theorem.** An Archimedean vector lattice is finite-dimensional iff
it is lattice isomorphic to `Fin n → ℝ` for some `n`. Equivalently, the absence
of an infinite disjoint sequence of non-zero vectors characterises
finite-dimensionality. -/
theorem finiteDimensional_iff_latticeIso_pi [IsVLArchimedean X] :
    FiniteDimensional ℝ X ↔
      ∃ n : ℕ, Nonempty (VecLatEquiv X (Fin n → ℝ)) := by
  refine ⟨fun hFD => ?_, ?_⟩
  · -- (⇒): X FD ⟹ exists iso to Fin n → ℝ.
    haveI : IsAtomicVectorLattice X := isAtomicVectorLattice_of_finiteDimensional
    -- Get a finite max disjoint atom family.
    obtain ⟨n, a, ha_atom, ha_disj, ha_max⟩ :=
      exists_max_disjoint_atom_family_of_finiteDimensional (X := X)
    -- top = span(a)
    have h_top_eq := top_eq_span_of_max_disjoint_atom_family a ha_atom ha_disj ha_max
    -- Linear independence of `a`
    have ha_lin : LinearIndependent ℝ a :=
      linearIndependent_of_pairwise_isVLDisjoint
        (fun i => (ha_atom i).ne_zero) ha_disj
    -- Define τ : (Fin n → ℝ) → X by τ c = ∑ cᵢ aᵢ.
    let τ : (Fin n → ℝ) → X := fun c => ∑ i, c i • a i
    -- τ preserves nonneg.
    have hτ_nn : ∀ c, 0 ≤ c → 0 ≤ τ c := fun c hc =>
      Finset.sum_nonneg fun i _ => smul_nonneg (hc i) (ha_atom i).1.le
    -- τ is additive.
    have hτ_add : ∀ c c' : Fin n → ℝ, 0 ≤ c → 0 ≤ c' →
        τ (c + c') = τ c + τ c' := fun c c' _ _ => by
      change ∑ i, (c + c') i • a i = ∑ i, c i • a i + ∑ i, c' i • a i
      simp_rw [Pi.add_apply, add_smul]
      exact Finset.sum_add_distrib
    -- τ is injective on the positive cone.
    have hτ_inj : ∀ c c' : Fin n → ℝ, 0 ≤ c → 0 ≤ c' →
        τ c = τ c' → c = c' := fun c c' _ _ heq => by
      have h_diff : ∑ i, (c i - c' i) • a i = 0 := by
        simp_rw [sub_smul]
        rw [Finset.sum_sub_distrib (f := fun i => c i • a i)
              (g := fun i => c' i • a i)]
        change τ c - τ c' = 0
        rw [heq, sub_self]
      have h_zero : ∀ i, c i - c' i = 0 :=
        Fintype.linearIndependent_iff.mp ha_lin _ h_diff
      funext i
      linarith [h_zero i]
    -- τ is surjective onto the positive cone of X.
    have hτ_surj : ∀ y : X, 0 ≤ y → ∃ c : Fin n → ℝ, 0 ≤ c ∧ τ c = y := fun y hy => by
      have hy_in_span : y ∈ Submodule.span ℝ (Set.range a) := by
        rw [← h_top_eq]; trivial
      rw [Submodule.mem_span_range_iff_exists_fun] at hy_in_span
      obtain ⟨c, hc⟩ := hy_in_span
      -- |y| = ∑ |cᵢ| aᵢ.
      have hy_abs_eq : |y| = ∑ i, |c i| • a i := by
        conv_lhs => rw [← hc]
        rw [abs_sum_of_pairwise_isVLDisjoint ha_disj]
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [abs_of_nonneg (ha_atom i).1.le]
      have habs_y : |y| = y := abs_of_nonneg hy
      have hsum_eq : ∑ i, c i • a i = ∑ i, |c i| • a i := by
        rw [hc, ← habs_y, hy_abs_eq]
      have h_zero_diff : ∀ i, c i - |c i| = 0 := by
        have h_combined : ∑ i, (c i - |c i|) • a i = 0 := by
          rw [show (fun i => (c i - |c i|) • a i) =
                fun i => c i • a i - |c i| • a i from
              funext fun i => sub_smul _ _ _,
              Finset.sum_sub_distrib, hsum_eq, sub_self]
        exact Fintype.linearIndependent_iff.mp ha_lin _ h_combined
      have hc_nn : 0 ≤ c := fun i => by
        have h_eq : c i = |c i| := by linarith [h_zero_diff i]
        rw [h_eq]; exact abs_nonneg _
      exact ⟨c, hc_nn, hc⟩
    -- Apply Positive.extensionEquiv.
    let e : VecLatEquiv (Fin n → ℝ) X :=
      Positive.extensionEquiv hτ_nn hτ_add hτ_inj hτ_surj
    exact ⟨n, ⟨e.symm⟩⟩
  · -- (⇐): iso to Fin n → ℝ ⟹ FD.
    rintro ⟨n, ⟨e⟩⟩
    haveI : FiniteDimensional ℝ (Fin n → ℝ) := inferInstance
    exact e.toLinearEquiv.symm.finiteDimensional

/-! ### Coordinate expansion in discrete vector lattices -/

/-- In a discrete (atomic) Archimedean vector lattice, every positive element is
the supremum of its scalar multiples along a maximal disjoint collection of
atoms: there exist scalars `c a` such that `c a • a ≤ x` for each `a ∈ A` and
`x` is the least upper bound of these multiples. -/
theorem exists_isLUB_smul_of_isAtomic_maximal_disjoint
    [IsAtomicVectorLattice X] [IsVLArchimedean X]
    {A : Set X} (hA : A ⊆ vlAtoms X)
    (hdis : IsDisjointSet A) (hmax : IsMaximalDisjoint A)
    {x : X} (hx : 0 ≤ x) :
    ∃ c : A → ℝ, IsLUB (Set.range fun a : A => c a • (a : X)) x := by
  -- For each atom `a ∈ A`, get a projection band realizing the principal band.
  choose P hP using fun a : A =>
    exists_projectionBand_principalBand_of_isVLAtom (hA a.2)
  have hP_smul : ∀ a : A, ((P a : Set X)) = {y | ∃ c : ℝ, y = c • (a : X)} :=
    fun a => by rw [hP a]; exact principalBand_eq_smul_of_isVLAtom (hA a.2)
  -- For each `a`, `P_a.bandProjection x = c a • a` for some scalar `c a`.
  have h_proj_form : ∀ a : A, ∃ c : ℝ, (P a).bandProjection x = c • (a : X) :=
    fun a => by
      have h : (P a).bandProjection x ∈ {y | ∃ c : ℝ, y = c • (a : X)} := by
        rw [← hP_smul a]; exact (P a).bandProjection_mem x
      exact h
  choose c hc using h_proj_form
  -- For each `a`, `P_a.bandProjection a = a`.
  have h_proj_a : ∀ a : A, (P a).bandProjection (a : X) = (a : X) := fun a => by
    have ha_in : (a : X) ∈ Set.range (P a).bandProjection := by
      rw [(P a).range_bandProjection, hP_smul a]
      exact ⟨1, (one_smul ℝ _).symm⟩
    obtain ⟨y, hy⟩ := ha_in
    rw [← hy]
    exact LinearMap.congr_fun (P a).bandProjection_sq y
  refine ⟨c, ?_, ?_⟩
  · -- `x` is an upper bound: for each `a`, `c a • a ≤ x`.
    rintro _ ⟨a, rfl⟩
    change c a • (a : X) ≤ x
    rw [← hc a]
    exact Positive.le_iff.mp (P a).bandProjection_le_id x hx
  · -- `x` is the least upper bound.
    intro z hz_ub
    have hz_each : ∀ a : A, c a • (a : X) ≤ z := fun a => hz_ub ⟨a, rfl⟩
    by_contra hxz
    -- `x ⊓ z < x`.
    have hxiz_le_x : x ⊓ z ≤ x := inf_le_left
    have hxiz_ne : x ⊓ z ≠ x := fun h => hxz (by rw [← h]; exact inf_le_right)
    have hxiz_diff_pos : 0 < x - x ⊓ z := by
      refine lt_of_le_of_ne (sub_nonneg.mpr hxiz_le_x) ?_
      intro h
      exact hxiz_ne (sub_eq_zero.mp h.symm).symm
    -- Atomicity: an atom `b ≤ x - x ⊓ z`.
    obtain ⟨b, hb_atom, hb_le⟩ :=
      isAtomicVectorLattice_iff_forall_pos_dominates_atom.mp inferInstance _
        hxiz_diff_pos
    -- Maximality: `b` is non-disjoint with some `a' ∈ A`.
    have hA_pos : ∀ a' ∈ A, 0 < a' := fun a' ha' => (hA ha').1
    have h_max_eq_zero :=
      (isMaximalDisjoint_iff_forall_eq_zero hA_pos hdis).mp hmax
    have hb_non_disj : ∃ a' ∈ A, ¬ IsVLDisjoint b a' := by
      by_contra hno
      push Not at hno
      exact hb_atom.ne_zero (h_max_eq_zero b hno)
    obtain ⟨a', ha', hba'⟩ := hb_non_disj
    have ha'_atom : IsVLAtom a' := hA ha'
    -- `b = μ • a'` for some `μ > 0` (since `b` is an atom non-disjoint with `a'`).
    rcases isVLDisjoint_or_smul_of_isVLAtom ha'_atom hb_atom with h_d | ⟨μ, hμ⟩
    · exact hba' (isVLDisjoint_comm.mp h_d)
    have hμ_pos : 0 < μ := by
      by_contra hμ_le
      push Not at hμ_le
      have h1 : μ • a' ≤ 0 :=
        smul_nonpos_of_nonpos_of_nonneg hμ_le ha'_atom.1.le
      rw [← hμ] at h1
      have hpos := IsVLAtom.pos hb_atom
      exact hb_atom.ne_zero (le_antisymm h1 hpos.le)
    -- Index in `A` corresponding to `a'`.
    set ai : A := ⟨a', ha'⟩
    -- `c ai • a' ≤ x ⊓ z` because both `x` and `z` dominate `c ai • a'`.
    have hc_le_x : c ai • a' ≤ x := by
      rw [← hc ai]
      exact Positive.le_iff.mp (P ai).bandProjection_le_id x hx
    have hc_le_z : c ai • a' ≤ z := hz_each ai
    have hc_le_iz : c ai • a' ≤ x ⊓ z := le_inf hc_le_x hc_le_z
    -- `μ • a' ≤ x - x ⊓ z`, so `x ⊓ z + μ • a' ≤ x`.
    have hμa_le : μ • a' ≤ x - x ⊓ z := hμ ▸ hb_le
    have hsum_le : x ⊓ z + μ • a' ≤ x := by
      have h := add_le_add_right hμa_le (x ⊓ z)
      rwa [show x ⊓ z + (x - x ⊓ z) = x from by abel] at h
    -- Apply `(P ai).bandProjection`.
    have h_pos := Positive.zero_le_iff.mp (P ai).bandProjection_nonneg
    have h_mono : Monotone (P ai).bandProjection :=
      Positive.monotone_iff.mpr h_pos
    have hP_sum_le : (P ai).bandProjection (x ⊓ z + μ • a') ≤
        (P ai).bandProjection x := h_mono hsum_le
    -- `(P ai).bandProjection (x ⊓ z + μ • a') = (P ai).bandProjection (x ⊓ z) + μ • a'`.
    have hP_dec : (P ai).bandProjection (x ⊓ z + μ • a') =
        (P ai).bandProjection (x ⊓ z) + μ • a' := by
      rw [map_add, map_smul, h_proj_a ai]
    -- `c ai • a' ≤ (P ai).bandProjection (x ⊓ z)`.
    have hP_iz_ge : c ai • a' ≤ (P ai).bandProjection (x ⊓ z) := by
      have h1 : (P ai).bandProjection (c ai • a') = c ai • a' := by
        rw [map_smul, h_proj_a ai]
      rw [← h1]
      exact h_mono hc_le_iz
    -- `(P ai).bandProjection x = c ai • a'`.
    rw [hP_dec, hc ai] at hP_sum_le
    -- `(P ai).bandProjection (x ⊓ z) + μ • a' ≤ c ai • a'`.
    -- Combined with `c ai • a' ≤ (P ai).bandProjection (x ⊓ z)`:
    have h_main : c ai • a' + μ • a' ≤ c ai • a' := by
      calc c ai • a' + μ • a'
          ≤ (P ai).bandProjection (x ⊓ z) + μ • a' := by gcongr
        _ ≤ c ai • a' := hP_sum_le
    rw [← add_smul] at h_main
    have hsum_le_c : c ai + μ ≤ c ai := (smul_le_smul_iff_atom ha'_atom).mp h_main
    linarith only [hμ_pos, hsum_le_c]

/-! ### Atomic coordinates -/

section AtomicCoordinates

variable {X : Type*} [AddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [VectorLattice X]
  [HasPrincipalProjectionProperty X]

/-- The principal-band projection onto an atom has a unique scalar
coefficient. -/
lemma exists_unique_principalBandProjection_eq_smul
    {a : X} (ha : IsVLAtom a) (x : X) :
    ∃! c : ℝ, Band.principalBandProjection a x = c • a := by
  have hmem : Band.principalBandProjection a x ∈
      Band.generated ({a} : Set X) := by
    have h := (Band.principalProjectionBand a).bandProjection_mem x
    change Band.principalBandProjection a x ∈
      (Band.principalProjectionBand a : Set X) at h
    rw [Band.principalProjectionBand_coe] at h
    exact h
  letI : IsVLArchimedean X := isVLArchimedean_of_hasPrincipalProjectionProperty
  change Band.principalBandProjection a x ∈
    (Band.generated ({a} : Set X) : Set X) at hmem
  rw [principalBand_eq_smul_of_isVLAtom ha] at hmem
  obtain ⟨c, hc⟩ := hmem
  refine ⟨c, hc, ?_⟩
  intro d hd
  apply smul_left_injective ℝ ha.ne_zero
  exact hd.symm.trans hc

/-- The coordinate of `x` along the atom `a`, `Pₐx`. -/
noncomputable def atomCoordinate
    {a : X} (ha : IsVLAtom a) (x : X) : ℝ := by
  exact (exists_unique_principalBandProjection_eq_smul ha x).choose

/-- The principal-band projection onto `a` is `Pₐx a`. -/
lemma principalBandProjection_eq_atomCoordinate_smul
    {a : X} (ha : IsVLAtom a) (x : X) :
    Band.principalBandProjection a x =
      atomCoordinate ha x • a := by
  exact (exists_unique_principalBandProjection_eq_smul ha x).choose_spec.1

/-- The coordinate associated with an atom, as a linear map. -/
noncomputable def atomCoordinateLinearMap
    {a : X} (ha : IsVLAtom a) : X →ₗ[ℝ] ℝ := by
  exact
    { toFun := atomCoordinate ha
      map_add' := by
        intro x y
        apply smul_left_injective ℝ ha.ne_zero
        change atomCoordinate ha (x + y) • a =
          (atomCoordinate ha x + atomCoordinate ha y) • a
        rw [add_smul, ← principalBandProjection_eq_atomCoordinate_smul ha,
          ← principalBandProjection_eq_atomCoordinate_smul ha,
          ← principalBandProjection_eq_atomCoordinate_smul ha, map_add]
      map_smul' := by
        intro c x
        apply smul_left_injective ℝ ha.ne_zero
        change atomCoordinate ha (c • x) • a =
          (c • atomCoordinate ha x) • a
        rw [← principalBandProjection_eq_atomCoordinate_smul ha,
          map_smul, principalBandProjection_eq_atomCoordinate_smul ha]
        exact smul_smul c (atomCoordinate ha x) a }

/-- The bundled coordinate map evaluates to the atomic coordinate. -/
@[simp]
lemma atomCoordinateLinearMap_apply
    {a : X} (ha : IsVLAtom a) (x : X) :
    atomCoordinateLinearMap ha x = atomCoordinate ha x := by
  rfl

end AtomicCoordinates

/-! ### Normalized atoms -/

section NormalizedAtoms

variable {X : Type*} [NormedAddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [NormedVectorLattice X]

variable (X) in
/-- The set of normalized vector lattice atoms of `X`. -/
def normalizedAtoms : Set X :=
  {a ∈ vlAtoms X | ‖a‖ = 1}

/-- Membership in `normalizedAtoms X` means being an atom of norm one. -/
@[simp]
lemma mem_normalizedAtoms {a : X} :
    a ∈ normalizedAtoms X ↔ IsVLAtom a ∧ ‖a‖ = 1 := by
  rfl

/-- The set of normalized atoms in `X` is pairwise disjoint. -/
lemma normalizedAtoms_isDisjointSet :
    IsDisjointSet (normalizedAtoms X) := by
  refine ⟨?_, ?_⟩
  · intro hzero
    rw [mem_normalizedAtoms] at hzero
    exact hzero.1.ne_zero rfl
  · intro a ha b hb hab
    rw [mem_normalizedAtoms] at ha hb
    rcases isVLDisjoint_or_smul_of_isVLAtom ha.1 hb.1 with hdis | ⟨c, hc⟩
    · exact hdis
    · have hc_pos : 0 < c := by
        by_contra hc_nonpos
        push Not at hc_nonpos
        have hle : c • a ≤ 0 :=
          smul_nonpos_of_nonpos_of_nonneg hc_nonpos ha.1.pos.le
        rw [← hc] at hle
        exact hb.1.ne_zero (le_antisymm hle hb.1.pos.le)
      have hc_one : c = 1 := by
        have hnorm := congrArg norm hc
        rw [hb.2, norm_smul, ha.2, Real.norm_of_nonneg hc_pos.le,
          mul_one] at hnorm
        exact hnorm.symm
      exact (hab (hc.trans (by rw [hc_one, one_smul])).symm).elim

/-- In an atomic normed vector lattice, normalized atoms form a maximal
disjoint family. -/
lemma normalizedAtoms_isMaximalDisjoint
    [IsAtomicVectorLattice X] :
    IsMaximalDisjoint (normalizedAtoms X) := by
  apply (isMaximalDisjoint_iff_forall_eq_zero
    (fun a ha => (mem_normalizedAtoms.mp ha).1.pos)
    normalizedAtoms_isDisjointSet).2
  intro x hx
  by_contra hxne
  have habs_ne : |x| ≠ 0 :=
    fun h => hxne ((abs_eq_zero_iff_zero x).mp h)
  have habs_pos : 0 < |x| :=
    lt_of_le_of_ne (abs_nonneg x) (Ne.symm habs_ne)
  obtain ⟨b, hb, hb_le⟩ :=
    isAtomicVectorLattice_iff_forall_pos_dominates_atom.mp
      (inferInstance : IsAtomicVectorLattice X) |x| habs_pos
  have hb_norm_pos : 0 < ‖b‖ := norm_pos_iff.mpr hb.ne_zero
  let a := ‖b‖⁻¹ • b
  have ha_mem : a ∈ normalizedAtoms X := by
    rw [mem_normalizedAtoms]
    refine ⟨IsVLAtom.smul hb (inv_pos.mpr hb_norm_pos), ?_⟩
    rw [show a = ‖b‖⁻¹ • b from rfl, norm_smul, Real.norm_of_nonneg
      (inv_pos.mpr hb_norm_pos).le, inv_mul_cancel₀ hb_norm_pos.ne']
  have hxb : IsVLDisjoint x b := by
    have h := (hx a ha_mem).smul_right ‖b‖
    rw [show a = ‖b‖⁻¹ • b from rfl, smul_smul,
      mul_inv_cancel₀ hb_norm_pos.ne', one_smul] at h
    exact h
  apply hb.ne_zero
  have hinf : |x| ⊓ b = 0 := by
    change |x| ⊓ |b| = 0 at hxb
    rwa [abs_of_nonneg hb.pos.le] at hxb
  exact (inf_eq_right.mpr hb_le).symm.trans hinf

/-- Distinct normalized atoms are separated by distance at least one. -/
lemma one_le_dist_normalizedAtoms
    {a b : normalizedAtoms X} (hab : a ≠ b) :
    1 ≤ dist (a : X) b := by
  have ha := mem_normalizedAtoms.mp a.property
  have hb := mem_normalizedAtoms.mp b.property
  have hab_coe : (a : X) ≠ b := fun h => hab (Subtype.ext h)
  have hdis :=
    normalizedAtoms_isDisjointSet.2 a.property b.property hab_coe
  change |(a : X)| ⊓ |(b : X)| = 0 at hdis
  rw [abs_of_nonneg ha.1.pos.le, abs_of_nonneg hb.1.pos.le] at hdis
  have hnorm := norm_inf_sub_inf_le_norm (a : X) b a
  rw [inf_idem, inf_comm (b : X) a, hdis, sub_zero, ha.2] at hnorm
  simpa [dist_eq_norm] using hnorm

/-- In a separable normed vector lattice, the set of normalized atoms is
countable. -/
lemma countable_normalizedAtoms
    [TopologicalSpace.SeparableSpace X] :
    Countable (normalizedAtoms X) := by
  let balls : normalizedAtoms X → Set X :=
    fun a => Metric.ball (a : X) (1 / 2 : ℝ)
  apply Pairwise.countable_of_isOpen_disjoint (s := balls)
  · intro a b hab
    apply Metric.ball_disjoint_ball
    norm_num [balls]
    exact one_le_dist_normalizedAtoms hab
  · intro a
    exact Metric.isOpen_ball
  · intro a
    exact ⟨a, Metric.mem_ball_self (by norm_num)⟩

end NormalizedAtoms

/-! ### Lattice structure of atomic coordinates -/

section AtomicCoordinateLatticeHom

variable {X : Type*} [AddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [VectorLattice X]
  [HasPrincipalProjectionProperty X]

/-- The coordinate of an atom along itself is one. -/
@[simp]
lemma atomCoordinate_self {a : X} (ha : IsVLAtom a) :
    atomCoordinate ha a = 1 := by
  apply smul_left_injective ℝ ha.ne_zero
  change atomCoordinate ha a • a = (1 : ℝ) • a
  rw [← principalBandProjection_eq_atomCoordinate_smul ha, one_smul]
  apply (Band.principalProjectionBand a).bandProjection_eq_of_mem
  change a ∈ (Band.principalProjectionBand a : Set X)
  rw [Band.principalProjectionBand_coe]
  exact Band.subset_generated {a} (Set.mem_singleton a)

/-- The coordinate along an atom vanishes on every element disjoint from it. -/
lemma atomCoordinate_eq_zero_of_isVLDisjoint
    {a x : X} (ha : IsVLAtom a) (hax : IsVLDisjoint a x) :
    atomCoordinate ha x = 0 := by
  apply smul_left_injective ℝ ha.ne_zero
  change atomCoordinate ha x • a = (0 : ℝ) • a
  rw [← principalBandProjection_eq_atomCoordinate_smul ha, zero_smul]
  apply (Band.principalProjectionBand a).bandProjection_eq_zero_of_mem_dc
  intro y hy
  rw [Band.principalProjectionBand_coe] at hy
  have hsub : (Band.generated ({a} : Set X) : Set X) ⊆
      (Band.disjointComplement ({x} : Set X) : Set X) := by
    apply Band.generated_le
    intro z hz
    rw [Set.mem_singleton_iff] at hz
    subst z
    intro w hw
    rw [Set.mem_singleton_iff] at hw
    subst w
    exact hax
  simpa only [isVLDisjoint_comm] using hsub hy x (Set.mem_singleton x)

/-- The coordinate associated with an atom, as a vector lattice homomorphism. -/
noncomputable def atomCoordinateVecLatHom
    {a : X} (ha : IsVLAtom a) : VecLatHom X ℝ := by
  refine VecLatHom.ofAbs (atomCoordinateLinearMap ha) ?_
  intro x
  apply smul_left_injective ℝ ha.ne_zero
  change atomCoordinate ha |x| • a = |atomCoordinate ha x| • a
  rw [← principalBandProjection_eq_atomCoordinate_smul ha]
  calc
    Band.principalBandProjection a |x| =
        |Band.principalBandProjection a x| := by
      exact (VecLatHom.ofIsVecLatHom _
        (Band.principalProjectionBand a).bandProjection_isVecLatHom).map_abs x
    _ = |atomCoordinate ha x • a| :=
      congrArg abs (principalBandProjection_eq_atomCoordinate_smul ha x)
    _ = |atomCoordinate ha x| • a := by
      rw [abs_smul', abs_of_nonneg ha.pos.le]

end AtomicCoordinateLatticeHom
