/-
Authors: Jesús Illescas-Fiorito
-/

import BanLat.AMSpace.Kakutani
import BanLat.LLexpr

/-!
# Functional calculus in uniformly complete vector lattices

This file develops the **lattice-linear** and **positively homogeneous functional calculus**
associated to every tuple `x₁,...,xₙ` in a uniformly complete vector lattice.

* Lattice-linear functional calculus is defined as the (unique) vector-lattice homomorphism
from `CoordinateLLFunction n` to `X`, such that `coordinate i ↦ x i`. Here, `coordinate i : x ↦ xᵢ`
and `CoordinateLLFunction n` is the sublattice of `C(ℝⁿ, ℝ)` generated by them.

* Positively homogeneous functional calculus is defined as the (unique) vector-lattice homomorphism
from `PosHomFunction n` to `X` such that `coordinate i ↦ x i`. Here, `PosHomFunction n` is the
vector sublattice of `C(ℝⁿ, ℝ)` consisting of positively homogeneous functions.

Apart from both uniqueness results, this file also shows that:
* The positively homogeneous functional calculus agrees with the lattice-linear functional calculus
over `CoordinateLLFunction n`.
* `PosHomFunction n` and `C(ellInfinityUnitSphere n, ℝ)`, where `ellInfinityUnitSphere n` denotes
the unit sphere of `(ℝⁿ, ‖·‖_∞)`, are Banach lattice isometric. To do so, we develop the usual
`restriction`-`radialExtension` procedure between these spaces.
* The set of restrictions to the unit sphere of `CoordinateLLFunction n` is dense
in `C(ellInfinityUnitSphere n, ℝ)`.
* Both functional calculi are preserved by lattice homomorphisms.
-/

universe u v

/-! ### Coordinate lattice-linear functions in `C(ℝⁿ)` -/

/-- Coordinate projections `x ↦ xᵢ` as elements of `C(ℝⁿ, ℝ)`. -/
noncomputable def continuousCoordinate (n : ℕ) (i : Fin n) : C(Fin n → ℝ, ℝ) where
  toFun x := x i
  continuous_toFun := by
    exact continuous_apply i

/-- The vector sublattice of `C(ℝⁿ)` generated by coordinate projections. -/
noncomputable def coordinateLLFunctions (n : ℕ) :
    VectorSublattice C(Fin n → ℝ, ℝ) :=
  VectorSublattice.generated (Set.range (continuousCoordinate n))

/-- A coordinate lattice-linear function on `ℝⁿ`, bundled with a proof
of its membership in `coordinateLLFunctions`. -/
abbrev CoordinateLLFunction (n : ℕ) :=
  ↥(coordinateLLFunctions n).toSubmodule

instance instCoeFunCoordinateLLFunction :
    CoeFun (CoordinateLLFunction n) (fun _ ↦ (Fin n → ℝ) → ℝ) where
  coe f := f.1

namespace CoordinateLLFunction

variable {n : ℕ} {X : Type u} [AddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [VectorLattice X]

/-- The `i`-th coordinate projection, bundled with a proof of its membership
in `coordinateLLFunctions`. -/
noncomputable def coordinate (i : Fin n) : CoordinateLLFunction n :=
  ⟨continuousCoordinate n i,
    VectorSublattice.subset_generated _ ⟨i, rfl⟩⟩

@[simp]
theorem coordinate_apply (i : Fin n) (x : Fin n → ℝ) :
    coordinate i x = x i := by
  rfl

/-- `f ∈ coordinateLLFunctions n` iff it is represented by a lattice-linear
expression. -/
theorem mem_coordinateLLFunctions_iff (f : C(Fin n → ℝ, ℝ)) :
    f ∈ coordinateLLFunctions n ↔
      ∃ e : LLexpr n, LLexpr.eval (continuousCoordinate n) e = f := by
  change f ∈ (VectorSublattice.generated (Set.range (continuousCoordinate n)) :
    Set C(Fin n → ℝ, ℝ)) ↔ _
  rw [LLexpr.generated_range_eq_combinations]
  rfl

/-- Every coordinate lattice-linear function on `ℝⁿ` has a formal
lattice-linear expression representative. -/
theorem exists_expression (f : CoordinateLLFunction n) :
    ∃ e : LLexpr n,
      LLexpr.eval (continuousCoordinate n) e =
        (f : C(Fin n → ℝ, ℝ)) := by
  exact (mem_coordinateLLFunctions_iff f.1).mp f.2

/-- For every coordinate lattice-linear function on `ℝⁿ`, `expressionRepresentative` is
a formal lattice-linear expression representing it. -/
private noncomputable def expressionRepresentative (f : CoordinateLLFunction n) : LLexpr n :=
  Classical.choose (exists_expression f)

/-- Evaluating `expressionRepresentative` at the coordinate functions recovers the
original coordinate lattice-linear function. -/
private theorem eval_expressionRepresentative (f : CoordinateLLFunction n) :
    LLexpr.eval (continuousCoordinate n) (expressionRepresentative f) =
      (f.1 : C(Fin n → ℝ, ℝ)) :=
  Classical.choose_spec (exists_expression f)

/-- Evaluating an expression of coordinate functions on `ℝⁿ` at a point agrees
with evaluating the expression directly at that point. -/
private theorem eval_coordinate_apply (r : Fin n → ℝ) (e : LLexpr n) :
    LLexpr.eval (continuousCoordinate n) e r = LLexpr.eval r e := by
  induction e <;> simp [LLexpr.eval, continuousCoordinate, *]

/-- Expressions defining the same real-valued function on `ℝⁿ` have equal
evaluations in every vector lattice. -/
private theorem eval_eq_of_eval_coordinate_eq (x : Fin n → X) (e₁ e₂ : LLexpr n)
    (h : LLexpr.eval (continuousCoordinate n) e₁ =
      LLexpr.eval (continuousCoordinate n) e₂) :
    LLexpr.eval x e₁ = LLexpr.eval x e₂ := by
  apply LLexpr.eval_eq_of_vanishes_real x e₁ e₂
  intro r
  rw [LLexpr.eval_add, LLexpr.eval_smul]
  rw [← eval_coordinate_apply r e₁, ← eval_coordinate_apply r e₂, h]
  simp

/-- The **lattice-linear functional calculus** associated
to every tuple `x₁,...,xₙ ∈ X` in a vector lattice. -/
noncomputable def functionalCalculus (x : Fin n → X) :
    VecLatHom (CoordinateLLFunction n) X := by
  refine
    { toFun := fun f => LLexpr.eval x (expressionRepresentative f)
      map_add' := fun f g => ?_
      map_smul' := fun c f => ?_
      map_sup' := fun f g => ?_
      map_inf' := fun f g => ?_ }
  · apply eval_eq_of_eval_coordinate_eq x (expressionRepresentative (f + g))
      (.add (expressionRepresentative f) (expressionRepresentative g))
    rw [eval_expressionRepresentative, LLexpr.eval_add, eval_expressionRepresentative,
      eval_expressionRepresentative]
    rfl
  · apply eval_eq_of_eval_coordinate_eq x (expressionRepresentative (c • f))
      (.smul c (expressionRepresentative f))
    rw [eval_expressionRepresentative, LLexpr.eval_smul, eval_expressionRepresentative]
    rfl
  · apply eval_eq_of_eval_coordinate_eq x (expressionRepresentative (f ⊔ g))
      (.sup (expressionRepresentative f) (expressionRepresentative g))
    rw [eval_expressionRepresentative, LLexpr.eval_sup, eval_expressionRepresentative,
      eval_expressionRepresentative]
    rfl
  · apply eval_eq_of_eval_coordinate_eq x (expressionRepresentative (f ⊓ g))
      (.inf (expressionRepresentative f) (expressionRepresentative g))
    rw [eval_expressionRepresentative, LLexpr.eval_inf, eval_expressionRepresentative,
      eval_expressionRepresentative]
    rfl

@[simp]
theorem functionalCalculus_coordinate (x : Fin n → X) (i : Fin n) :
    functionalCalculus x (coordinate i) = x i := by
  change LLexpr.eval x (expressionRepresentative (coordinate i)) = LLexpr.eval x (.var i)
  apply eval_eq_of_eval_coordinate_eq x
  rw [eval_expressionRepresentative]
  ext r
  rfl

/-- The lattice-linear functional calculus evaluates a formal expression by
substituting the tuple `x` for its variables. -/
@[simp]
theorem functionalCalculus_eval (x : Fin n → X) (e : LLexpr n) :
    functionalCalculus x (LLexpr.eval (fun i ↦ coordinate i) e) = LLexpr.eval x e := by
  simpa using LLexpr.map_eval (functionalCalculus x) (fun i ↦ coordinate i) e

/-- The **lattice-linear functional calculus** associated to `x₁,...,xₙ ∈ X` is the
**unique** vector-lattice homomorphism from `CoordinateLLFunction n` to `X` such
that `coordinate i ↦ x i`. -/
theorem eq_functionalCalculus_of_map_coordinate (x : Fin n → X)
    (T : VecLatHom (CoordinateLLFunction n) X)
    (hT : ∀ i, T (coordinate i) = x i) :
    T = functionalCalculus x := by
  apply VecLatHom.instFunLike.coe_injective
  funext f
  have hf : LLexpr.eval (fun i => coordinate i) (expressionRepresentative f) = f := by
    apply Subtype.ext
    rw [LLexpr.coe_eval_vectorSublattice]
    exact eval_expressionRepresentative f
  calc
    T f = T (LLexpr.eval (fun i => coordinate i) (expressionRepresentative f)) :=
      congrArg T hf.symm
    _ = LLexpr.eval (fun i => T (coordinate i)) (expressionRepresentative f) :=
      LLexpr.map_eval T (fun i => coordinate i) (expressionRepresentative f)
    _ = LLexpr.eval x (expressionRepresentative f) := by rw [funext hT]
    _ = functionalCalculus x f := rfl

end CoordinateLLFunction

/-! ### Functoriality of the lattice-linear functional calculus -/

variable {n : ℕ} {X : Type u} {Y : Type v}
  [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X] [VectorLattice X]
  [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]

/-- Lattice-linear functional calculus is preserved by lattice homomorphisms:
`T (functionalCalculus x f) = functionalCalculus (Tx) f`. -/
theorem CoordinateLLFunction.functionalCalculus_map
    (T : VecLatHom X Y) (x : Fin n → X) (f : CoordinateLLFunction n) :
    T (CoordinateLLFunction.functionalCalculus x f) =
      CoordinateLLFunction.functionalCalculus (fun i => T (x i)) f := by
  have hcomp : ∀ i,
      (T.comp (CoordinateLLFunction.functionalCalculus x))
        (CoordinateLLFunction.coordinate i) = T (x i) := by
    intro i
    rw [VecLatHom.comp_apply, CoordinateLLFunction.functionalCalculus_coordinate]
  have heq := CoordinateLLFunction.eq_functionalCalculus_of_map_coordinate
    (fun i => T (x i)) (T.comp (CoordinateLLFunction.functionalCalculus x)) hcomp
  simpa [VecLatHom.comp_apply] using DFunLike.congr_fun heq f

/-! ### Positively homogeneous functions in `ℝⁿ` -/

/-- The vector sublattice of `C(ℝⁿ, ℝ)` of positively homogeneous functions. -/
noncomputable def posHomFunctions (n : ℕ) :
    VectorSublattice C(Fin n → ℝ, ℝ) where
  toSubmodule :=
    { carrier := {f | ∀ c : ℝ, 0 ≤ c → ∀ x, f (c • x) = c • f x}
      zero_mem' := by
        intro c hc x
        simp
      add_mem' := by
        intro f g hf hg c hc x
        simp only [ContinuousMap.add_apply, hf c hc x, hg c hc x, smul_add]
      smul_mem' := by
        intro a f hf c hc x
        simp only [ContinuousMap.smul_apply, hf c hc x, smul_smul, mul_comm]
    }
  sup_mem' := by
    intro f g hf hg c hc x
    simp only [ContinuousMap.sup_apply, hf c hc x, hg c hc x]
    rw [smul_max_of_nonneg hc]

/-- A continuous positively homogeneous real-valued function of `n` variables,
bundled with a proof of membership in `posHomFunctions`. -/
abbrev PosHomFunction (n : ℕ) :=
  ↥(posHomFunctions n).toSubmodule

namespace PosHomFunction

variable {n : ℕ}

instance instCoeFun :
    CoeFun (PosHomFunction n) (fun _ ↦ (Fin n → ℝ) → ℝ) where
  coe f := f.1

/-- Positively homogeneous functions are equal if they agree pointwise. -/
@[ext]
theorem ext {f g : PosHomFunction n} (h : ∀ x, f x = g x) : f = g := by
  apply Subtype.ext
  exact ContinuousMap.ext h

@[simp]
theorem map_smul_of_nonneg (f : PosHomFunction n) (c : ℝ) (hc : 0 ≤ c)
    (x : Fin n → ℝ) :
    f (c • x) = c • f x := by
  exact f.2 c hc x

/-- A positively homogeneous function vanishes at zero. -/
@[simp]
theorem map_zero (f : PosHomFunction n) :
    f 0 = 0 := by
  simpa using
    map_smul_of_nonneg f 0 le_rfl (0 : Fin n → ℝ)

/-- The coordinate functions are positively homogeneous. -/
noncomputable def coordinate (i : Fin n) : PosHomFunction n :=
  ⟨continuousCoordinate n i, by
    intro c hc x
    rfl⟩

@[simp]
theorem coordinate_apply (i : Fin n) (x : Fin n → ℝ) :
    coordinate i x = x i := by
  rfl

/-- Coordinate lattice-linear functions on `ℝⁿ` form a sublattice
of continuous positively homogeneous functions. -/
theorem coordinateLLFunctions_le_posHomFunctions :
    coordinateLLFunctions n ≤ posHomFunctions n := by
  apply VectorSublattice.generated_le
  rintro f ⟨i, rfl⟩
  intro c hc x
  rfl

/-- The inclusion `coordinateLLFunctions n ≤ posHomFunctions n` as a
vector lattice homomorphism. -/
noncomputable def coordinateLLInclusion :
    VecLatHom (CoordinateLLFunction n) (PosHomFunction n) := by
  refine
    { toFun := fun f => ⟨f.1, coordinateLLFunctions_le_posHomFunctions f.2⟩
      map_add' := ?_
      map_smul' := ?_
      map_sup' := ?_
      map_inf' := ?_ }
  all_goals intros; rfl

@[simp]
theorem coordinateLLInclusion_apply (f : CoordinateLLFunction n) (x : Fin n → ℝ) :
    coordinateLLInclusion f x = f x := by
  rfl

/-! ### Restriction of positively homogeneous functions to the unit sphere of `(ℝⁿ,‖·‖_∞)` -/

/-- The unit sphere of `(ℝⁿ,‖·‖_∞)`, an element of which consists of
`⟨point, proof_that_point_lies_on_the_unit_sphere⟩`. -/
def ellInfinityUnitSphere (n : ℕ) : Set (Fin n → ℝ) :=
  Metric.sphere 0 1

/-- The unit sphere of `(ℝⁿ,‖·‖_∞)` is compact. -/
noncomputable instance instCompactSpaceEllInfinityUnitSphere :
    CompactSpace (ellInfinityUnitSphere n) := by
  unfold ellInfinityUnitSphere
  infer_instance

private lemma isGreatest_coord_abs (x : ellInfinityUnitSphere n) :
    IsGreatest (Set.range fun i : Fin n => |(x : Fin n → ℝ) i|) 1 := by
  have hnorm : ‖(x : Fin n → ℝ)‖ = 1 := by
    have hx := x.2
    change dist (x : Fin n → ℝ) 0 = 1 at hx
    rwa [dist_zero_right] at hx
  haveI : Nonempty (Fin n) := by
    have hx_ne : (x : Fin n → ℝ) ≠ 0 := norm_ne_zero_iff.mp (by
      rw [hnorm]
      norm_num)
    obtain ⟨i, hi⟩ := Function.ne_iff.mp hx_ne
    exact ⟨i⟩
  obtain ⟨i, hi⟩ := (IsGreatest.pi_norm (x : Fin n → ℝ)).1
  refine ⟨⟨i, ?_⟩, ?_⟩
  · change |(x : Fin n → ℝ) i| = 1
    simpa [Real.norm_eq_abs] using hi.trans hnorm
  · rintro _ ⟨j, rfl⟩
    change |(x : Fin n → ℝ) j| ≤ 1
    rw [← Real.norm_eq_abs]
    have h := norm_le_pi_norm (x : Fin n → ℝ) j
    rw [hnorm] at h
    exact h

/-- Restriction of continuous positively homogeneous functions on `ℝⁿ` to
the unit sphere of `(ℝⁿ,‖·‖_∞)` as a vector lattice homomorphism. -/
noncomputable def restrict :
    VecLatHom (PosHomFunction n) C(ellInfinityUnitSphere n, ℝ) := by
  refine
    { toFun := fun f =>
        ⟨fun x => f (x : Fin n → ℝ),
          f.1.continuous.comp continuous_subtype_val⟩
      map_add' := ?_
      map_smul' := ?_
      map_sup' := ?_
      map_inf' := ?_ }
  all_goals intros; rfl

/-- Pointwise description of restriction to the unit sphere of `(ℝⁿ,‖·‖_∞)`. -/
@[simp]
theorem restrict_apply (f : PosHomFunction n) (x : ellInfinityUnitSphere n) :
    restrict f x = f (x : Fin n → ℝ) := by
  rfl

/-- The normalization map `ℝⁿ ∖ {0} → {x | ‖x‖_∞ = 1}` given by `x ↦ ‖x‖_∞⁻¹ • x`. -/
private noncomputable def normalize :
    {x : Fin n → ℝ // x ≠ 0} → ellInfinityUnitSphere n := fun x =>
  ⟨‖(x : Fin n → ℝ)‖⁻¹ • x, by
    rw [ellInfinityUnitSphere, Metric.mem_sphere, dist_zero_right, norm_smul, norm_inv,
      Real.norm_eq_abs, abs_norm,
      inv_mul_cancel₀ (norm_ne_zero_iff.mpr x.2)]⟩

/-- Normalization is continuous away from the origin. -/
private theorem continuous_normalize : Continuous (normalize (n := n)) := by
  apply continuous_induced_rng.mpr
  exact (continuous_norm.comp continuous_subtype_val).inv₀
    (fun x => norm_ne_zero_iff.mpr x.2) |>.smul continuous_subtype_val

/-- For every `x ∈ ℝⁿ, x ≠ 0`, `‖x‖_∞ · normalize x = x`. -/
private lemma norm_smul_normalize (x : {x : Fin n → ℝ // x ≠ 0}) :
    ‖(x : Fin n → ℝ)‖ • (normalize x : Fin n → ℝ) = x := by
  change ‖(x : Fin n → ℝ)‖ • (‖(x : Fin n → ℝ)‖⁻¹ • (x : Fin n → ℝ)) =
    (x : Fin n → ℝ)
  rw [smul_smul, mul_inv_cancel₀ (norm_ne_zero_iff.mpr x.2), one_smul]

/-- Normalize a nonzero vector to the unit sphere of `(ℝⁿ,‖·‖_∞)`. -/
private noncomputable def unitNormalize (x : Fin n → ℝ) (hx : x ≠ 0) :
    ellInfinityUnitSphere n := normalize ⟨x, hx⟩

/-- Normalization is invariant under multiplication by a positive scalar. -/
private lemma unitNormalize_smul_of_pos (c : ℝ) (hc : 0 < c)
    (x : Fin n → ℝ) (hx : x ≠ 0) :
    unitNormalize (c • x) (smul_ne_zero hc.ne' hx) = unitNormalize x hx := by
  apply Subtype.ext
  change ‖c • x‖⁻¹ • (c • x) = ‖x‖⁻¹ • x
  rw [norm_smul, Real.norm_of_nonneg hc.le, smul_smul]
  apply congrArg (fun a : ℝ => a • x)
  field_simp

/-- A positively homogeneous function is determined by its values over
the unit sphere of `(ℝⁿ,‖·‖_∞)`. -/
private theorem eq_norm_smul_unit (f : PosHomFunction n) {x : Fin n → ℝ} (hx : x ≠ 0) :
    f x = ‖x‖ • f (unitNormalize x hx) := by
  have h := map_smul_of_nonneg f ‖x‖ (norm_nonneg x) (unitNormalize x hx)
  change f (‖x‖ • (unitNormalize x hx : Fin n → ℝ)) = _ at h
  have hscale : ‖x‖ • (unitNormalize x hx : Fin n → ℝ) = x := by
    simpa only [unitNormalize] using
      norm_smul_normalize (⟨x, hx⟩ : {x : Fin n → ℝ // x ≠ 0})
  rw [hscale] at h
  exact h

/-- The `restriction` map is injective. -/
private theorem restrict_injective : Function.Injective (restrict (n := n)) := by
  intro f g hfg
  apply PosHomFunction.ext
  intro x
  by_cases hx : x = 0
  · subst x
    simp
  · rw [eq_norm_smul_unit f hx, eq_norm_smul_unit g hx]
    congr 1
    exact congrArg (fun q : C(ellInfinityUnitSphere n, ℝ) => q (unitNormalize x hx)) hfg

/-- The `radialExtension` of a continuous function on the unit sphere of `(ℝⁿ,‖·‖_∞)` to `ℝⁿ`,
taking the value `0` at zero. -/
private noncomputable def radialExtension (f : C(ellInfinityUnitSphere n, ℝ))
    (x : Fin n → ℝ) : ℝ :=
  if hx : x = 0 then 0 else
    ‖x‖ • f (unitNormalize x hx)

/-- The radial extension of a continuous function on the unit sphere vanishes at the origin. -/
@[simp]
private theorem radialExtension_zero (f : C(ellInfinityUnitSphere n, ℝ)) :
    radialExtension f 0 = 0 := by
  simp [radialExtension]

/-- Formula for the radial extension of a continuous function on the unit sphere
away from the origin. -/
@[simp]
private theorem radialExtension_of_ne (f : C(ellInfinityUnitSphere n, ℝ))
    {x : Fin n → ℝ} (hx : x ≠ 0) :
    radialExtension f x = ‖x‖ • f (unitNormalize x hx) := by
  rw [radialExtension, dif_neg hx]

/-- A function and its radial extension agree on the unit sphere. -/
@[simp]
private theorem radialExtension_sphere (f : C(ellInfinityUnitSphere n, ℝ))
    (y : ellInfinityUnitSphere n) : radialExtension f (y : Fin n → ℝ) = f y := by
  have hnorm : ‖(y : Fin n → ℝ)‖ = 1 := by
    have hy_mem := y.2
    change dist (y : Fin n → ℝ) 0 = 1 at hy_mem
    rw [dist_zero_right] at hy_mem
    exact hy_mem
  have hy : (y : Fin n → ℝ) ≠ 0 := by
    intro h
    rw [h, norm_zero] at hnorm
    norm_num at hnorm
  rw [radialExtension_of_ne f hy]
  have hunit : unitNormalize (y : Fin n → ℝ) hy = y := by
    apply Subtype.ext
    have hscale :=
      norm_smul_normalize (⟨(y : Fin n → ℝ), hy⟩ : {x : Fin n → ℝ // x ≠ 0})
    rw [hnorm, one_smul] at hscale
    simpa only [unitNormalize] using hscale
  rw [hunit]
  simp only [hnorm, one_smul]

/-- The radial extension of a continuous function on the unit sphere is positively homogeneous. -/
private theorem radialExtension_smul_of_nonneg (f : C(ellInfinityUnitSphere n, ℝ))
    (c : ℝ) (hc : 0 ≤ c) (x : Fin n → ℝ) :
    radialExtension f (c • x) = c • radialExtension f x := by
  rcases hc.eq_or_lt with rfl | hc
  · simp
  by_cases hx : x = 0
  · subst x
    simp
  have hcx : c • x ≠ 0 := smul_ne_zero hc.ne' hx
  rw [radialExtension_of_ne f hcx, radialExtension_of_ne f hx]
  have hnormcx : ‖c • x‖ = c * ‖x‖ := by
    rw [norm_smul, Real.norm_of_nonneg hc.le]
  rw [unitNormalize_smul_of_pos c hc x hx, hnormcx, smul_smul]

/-- Radial extension sends a continuous function on the unit sphere of `(ℝⁿ,‖·‖_∞)` to a
continuous positively homogeneous function on `ℝⁿ`. -/
noncomputable def extend : C(ellInfinityUnitSphere n, ℝ) → PosHomFunction n := by
  intro f
  refine ⟨⟨radialExtension f, ?_⟩, radialExtension_smul_of_nonneg f⟩
  rw [continuous_iff_continuousAt]
  intro x
  by_cases hx : x = 0
  · subst x
    rw [Metric.continuousAt_iff]
    intro ε hε
    refine ⟨ε / (‖f‖ + 1), div_pos hε (by positivity), ?_⟩
    intro y hy
    rw [dist_zero_right] at hy
    rw [radialExtension_zero, dist_zero_right]
    by_cases hy0 : y = 0
    · simpa [hy0] using hε
    · calc
        ‖radialExtension f y‖ = ‖(‖y‖ : ℝ)‖ * ‖f (unitNormalize y hy0)‖ := by
              rw [radialExtension_of_ne f hy0, norm_smul]
        _ = ‖y‖ * ‖f (unitNormalize y hy0)‖ := by
              simp only [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg y)]
        _
            ≤ ‖y‖ * ‖f‖ := mul_le_mul_of_nonneg_left
              (ContinuousMap.norm_coe_le_norm _ _) (norm_nonneg y)
        _ ≤ (ε / (‖f‖ + 1)) * ‖f‖ :=
          mul_le_mul_of_nonneg_right (le_of_lt hy) (norm_nonneg f)
        _ < ε := by
          have hf : 0 ≤ ‖f‖ := norm_nonneg f
          calc
            ε / (‖f‖ + 1) * ‖f‖ < ε / (‖f‖ + 1) * (‖f‖ + 1) := by
              exact mul_lt_mul_of_pos_left (by linarith)
                (div_pos hε (by positivity))
            _ = ε := by field_simp
  · have hcontinuous : ContinuousOn (radialExtension f) ({0}ᶜ : Set (Fin n → ℝ)) := by
      rw [continuousOn_iff_continuous_restrict]
      change Continuous (fun y : {y : Fin n → ℝ // y ≠ 0} => radialExtension f y)
      apply Continuous.congr
        ((continuous_norm.comp continuous_subtype_val).smul
          (f.continuous.comp (continuous_normalize (n := n))))
      intro y
      exact (radialExtension_of_ne f y.2).symm
    exact hcontinuous.continuousAt (isOpen_compl_singleton.mem_nhds hx)

/-- Restricting the radial extension of a continuous function on the unit sphere
recovers the original function on the unit sphere of `(ℝⁿ,‖·‖_∞)`. -/
@[simp]
theorem restrict_extend (f : C(ellInfinityUnitSphere n, ℝ)) :
    restrict (extend f) = f := by
  ext y
  exact radialExtension_sphere f y

/-- Radially extending a restriction recovers the original positively
homogeneous function. -/
@[simp]
theorem extend_restrict (f : PosHomFunction n) :
    extend (restrict f) = f := by
  apply restrict_injective
  rw [restrict_extend]

/-- The vector lattice of continuous positively homogeneous functions on `ℝⁿ` is
isomorphic to the vector lattice of continuous real-valued functions on the
unit sphere of `(ℝⁿ,‖·‖_∞)`. The isomorphism is given by restriction (`restrict`)
and radial extension (`extend`). -/
noncomputable def ellInfinityUnitSphereEquiv :
    VecLatEquiv (PosHomFunction n) C(ellInfinityUnitSphere n, ℝ) := by
  exact
    { toFun := restrict
      invFun := extend
      left_inv := extend_restrict
      right_inv := restrict_extend
      map_add' := (restrict (n := n)).map_add
      map_smul' := (restrict (n := n)).map_smul
      map_sup' := (restrict (n := n)).map_sup'
      map_inf' := (restrict (n := n)).map_inf' }

/-!
### `PosHomFunction n` as a Banach lattice
-/

/-- If `f ∈ PosHomFunction`, `‖f‖ := ‖restrict f‖_∞`. -/
noncomputable instance instNorm : Norm (PosHomFunction n) where
  norm f := ‖restrict f‖

@[simp]
theorem norm_restrict (f : PosHomFunction n) :
    ‖restrict f‖ = ‖f‖ := by
  rfl

/-- `PosHomFunction n` becomes a normed additive commutative group. -/
noncomputable instance instNormedAddCommGroup :
    NormedAddCommGroup (PosHomFunction n) := by
  exact NormedAddCommGroup.induced (PosHomFunction n) C(ellInfinityUnitSphere n, ℝ)
    (restrict (n := n)).toLinearMap.toAddHom restrict_injective

/-- `PosHomFunction n` becomes a normed vector lattice. -/
noncomputable instance instNormedVectorLattice :
    @NormedVectorLattice (PosHomFunction n) (instNormedAddCommGroup (n := n))
      (posHomFunctions n).instLatticeSubtype
      (posHomFunctions n).instIsOrderedAddMonoidSubtype := by
  refine
    { solid := ?_
      norm_smul := ?_ }
  · intro f g hfg
    change ‖restrict f‖ ≤ ‖restrict g‖
    apply HasSolidNorm.solid
    simpa only [VecLatHom.map_abs] using (restrict (n := n)).monotone hfg
  · intro a f
    change ‖restrict (a • f)‖ = ‖a‖ * ‖restrict f‖
    rw [map_smul, norm_smul]

/-- Restriction is an isometry equivalence between
`PosHomFunction n` and `C(ellInfinityUnitSphere n, ℝ)`. -/
noncomputable def ellInfinityUnitSphereIsometry :
    PosHomFunction n ≃ᵢ C(ellInfinityUnitSphere n, ℝ) := by
  exact
    { (ellInfinityUnitSphereEquiv (n := n)).toLinearEquiv.toEquiv with
      isometry_toFun := Isometry.of_dist_eq fun f g => by
        rw [dist_eq_norm, dist_eq_norm]
        change ‖restrict f - restrict g‖ = ‖f - g‖
        rw [← map_sub]
        rfl }

/-- `PosHomFunction n` is a Banach lattice. -/
noncomputable instance instBanachLattice :
    @BanachLattice (PosHomFunction n) (instNormedAddCommGroup (n := n))
      (posHomFunctions n).instLatticeSubtype
      (posHomFunctions n).instIsOrderedAddMonoidSubtype := by
  let e := ellInfinityUnitSphereIsometry (n := n)
  exact { toCompleteSpace := e.completeSpace }

/-- `restriction` is a Banach lattice isometric equivalence between
`PosHomFunction n` and `C(ellInfinityUnitSphere n, ℝ)`. -/
noncomputable def ellInfinityUnitSphereBanachLatEquiv :
    BanachLatEquiv (PosHomFunction n) C(ellInfinityUnitSphere n, ℝ) := by
  exact
    { toLinearIsometryEquiv :=
        { (ellInfinityUnitSphereEquiv (n := n)).toLinearEquiv with
          norm_map' := norm_restrict }
      map_sup' := (restrict (n := n)).map_sup'
      map_inf' := (restrict (n := n)).map_inf' }

/-- Restrictions of coordinate lattice-linear functions interpolate arbitrary prescribed
values at any two points of the unit sphere. -/
private theorem coordinateLLRestriction_twoPointInterpolation {n : ℕ}
    (v : ellInfinityUnitSphere n → ℝ) (y z : ellInfinityUnitSphere n) :
    ∃ f : CoordinateLLFunction n,
      restrict (coordinateLLInclusion f) y = v y ∧
      restrict (coordinateLLInclusion f) z = v z := by
  classical
  have hy_coord := isGreatest_coord_abs y
  have hz_coord := isGreatest_coord_abs z
  obtain ⟨iy, hiy⟩ := hy_coord.1
  obtain ⟨iz, hiz⟩ := hz_coord.1
  let u : CoordinateLLFunction n :=
    |CoordinateLLFunction.coordinate iy| ⊔
      |CoordinateLLFunction.coordinate iz|
  have huy : u (y : Fin n → ℝ) = 1 := by
    change max |(y : Fin n → ℝ) iy| |(y : Fin n → ℝ) iz| = 1
    have hiy' : |(y : Fin n → ℝ) iy| = 1 := hiy
    rw [hiy', max_eq_left (hy_coord.2 ⟨iz, rfl⟩)]
  have huz : u (z : Fin n → ℝ) = 1 := by
    change max |(z : Fin n → ℝ) iy| |(z : Fin n → ℝ) iz| = 1
    have hiz' : |(z : Fin n → ℝ) iz| = 1 := hiz
    rw [hiz', max_eq_right (hz_coord.2 ⟨iy, rfl⟩)]
  by_cases hyz : y = z
  · subst z
    refine ⟨(v y) • u, ?_, ?_⟩
    · simp [restrict_apply, coordinateLLInclusion_apply, huy]
    · simp [restrict_apply, coordinateLLInclusion_apply, huy]
  · have hyz_val : (y : Fin n → ℝ) ≠ (z : Fin n → ℝ) := by
      intro h
      exact hyz (Subtype.ext h)
    obtain ⟨k, hk⟩ : ∃ k, (y : Fin n → ℝ) k ≠ (z : Fin n → ℝ) k := by
      simpa only [Function.ne_iff] using hyz_val
    let q := CoordinateLLFunction.coordinate k
    let c := (v z - v y) / (q z - q y)
    let g : CoordinateLLFunction n := c • (q - (q y) • u) + (v y) • u
    refine ⟨g, ?_, ?_⟩
    · simp only [restrict_apply, coordinateLLInclusion_apply]
      change c * (q y - q y * u y) + v y * u y = v y
      rw [huy]
      ring
    · simp only [restrict_apply, coordinateLLInclusion_apply]
      change c * (q z - q y * u z) + v y * u z = v z
      rw [huz]
      have hden : q z - q y ≠ 0 := sub_ne_zero.mpr hk.symm
      dsimp [c]
      field_simp
      ring

/-- Restrictions of coordinate lattice-linear functions to the unit sphere of
`(ℝⁿ, ‖·‖_∞)` are dense in `C(ellInfinityUnitSphere n, ℝ)`. -/
theorem denseRange_restrict_coordinateLLInclusion :
    DenseRange (fun f : CoordinateLLFunction n => restrict (coordinateLLInclusion f)) := by
  classical
  let A : CoordinateLLFunction n → C(ellInfinityUnitSphere n, ℝ) := fun f =>
    restrict (coordinateLLInclusion f)
  let L : Set C(ellInfinityUnitSphere n, ℝ) := Set.range A
  have hL_nonempty : L.Nonempty := ⟨A 0, 0, rfl⟩
  have hL_inf : ∀ f ∈ L, ∀ g ∈ L, f ⊓ g ∈ L := by
    rintro _ ⟨f, rfl⟩ _ ⟨g, rfl⟩
    exact ⟨f ⊓ g, by simp [A]⟩
  have hL_sup : ∀ f ∈ L, ∀ g ∈ L, f ⊔ g ∈ L := by
    rintro _ ⟨f, rfl⟩ _ ⟨g, rfl⟩
    exact ⟨f ⊔ g, by simp [A]⟩
  have hL_sep : L.SeparatesPointsStrongly := by
    intro v y z
    obtain ⟨f, hy, hz⟩ := coordinateLLRestriction_twoPointInterpolation v y z
    refine ⟨A f, ⟨f, rfl⟩, ?_, ?_⟩
    · simpa [A] using hy
    · simpa [A] using hz
  rw [show (fun f : CoordinateLLFunction n => restrict (coordinateLLInclusion f)) = A from rfl,
    denseRange_iff_closure_range]
  exact ContinuousMap.sublattice_closure_eq_top L hL_nonempty hL_inf hL_sup hL_sep

end PosHomFunction

/-! ### Positively homogeneous functional calculus -/

namespace PosHomFunction

variable {n : ℕ} {X : Type u} [AddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [VectorLattice X]
  [IsUniformlyCompleteVectorLattice X]

/-- The zero vector-lattice homomorphism from `PosHomFunction n` to `X`. -/
private noncomputable def zeroVecLatHom :
    VecLatHom (PosHomFunction n) X := by
  exact
    { toFun := fun _ => 0
      map_add' := by simp
      map_smul' := by simp
      map_sup' := by simp
      map_inf' := by simp }

omit [IsUniformlyCompleteVectorLattice X] in
@[simp]
private theorem zeroVecLatHom_apply (f : PosHomFunction n) :
    zeroVecLatHom f = (0 : X) := by
  rfl

omit [VectorLattice X] [IsUniformlyCompleteVectorLattice X] in
private lemma coordinate_eq_zero_of_sum_abs_eq_zero
    (x : Fin n → X) (h : ∑ i, |x i| = 0) (i : Fin n) :
    x i = 0 := by
  apply (abs_eq_zero_iff_zero (x i)).mp
  exact le_antisymm (by
    rw [← h]
    exact Finset.single_le_sum (fun j _ => abs_nonneg (x j)) (Finset.mem_univ i))
    (abs_nonneg (x i))

/-- The positive-sum branch of the positively homogeneous functional calculus,
bundled with its values on the coordinate functions. -/
private noncomputable def functionalCalculusOfPosData
    (x : Fin n → X) (h : 0 < ∑ i, |x i|) :
    { T : VecLatHom (PosHomFunction n) X // ∀ i, T (coordinate i) = x i } := by
  classical
  let e : X := ∑ i, |x i|
  have he_pos : 0 < e := by simpa [e] using h
  have he_nonneg : 0 ≤ e := he_pos.le
  letI := OrderIdeal.principalNormedAddCommGroup e
  letI : Lattice ↥(OrderIdeal.principal e) := OrderIdeal.instLatticePrincipal e
  letI : IsOrderedAddMonoid ↥(OrderIdeal.principal e) :=
    OrderIdeal.instIsOrderedAddMonoidPrincipal e
  letI : AMSpaceWithUnit ↥(OrderIdeal.principal e) :=
    OrderIdeal.principalAMSpaceWithUnit he_pos.le
      (IsUniformlyCompleteVectorLattice.complete_principal e he_pos)
  let x' : Fin n → ↥(OrderIdeal.principal e) := fun i => ⟨x i, by
    refine ⟨1, zero_le_one, ?_⟩
    rw [one_smul, abs_of_nonneg he_nonneg]
    exact Finset.single_le_sum (fun j _ => abs_nonneg (x j)) (Finset.mem_univ i)⟩
  let pullback : VecLatHom (PosHomFunction n)
      C(AMSpaceWithUnit.LatticeCharacter ↥(OrderIdeal.principal e), ℝ) :=
    { toFun := fun f =>
        ⟨fun φ => f (fun i => φ (x' i)),
          f.1.continuous.comp (continuous_pi fun i =>
            AMSpaceWithUnit.LatticeCharacter.continuous_eval _ (x' i))⟩
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl
      map_sup' := fun _ _ => rfl
      map_inf' := fun _ _ => rfl }
  let K := OrderIdeal.principalKakutaniEquiv he_pos
  let T := (OrderIdeal.principal e).subtype.comp
    (K.symm.toVecLatEquiv.toVecLatHom.comp pullback)
  refine ⟨T, ?_⟩
  intro i
  change ((K.symm (pullback (coordinate i)) : ↥(OrderIdeal.principal e)) : X) = x i
  change ((K.symm (pullback (coordinate i)) : ↥(OrderIdeal.principal e)) : X) =
    (x' i : X)
  apply congrArg Subtype.val
  apply K.toLinearIsometryEquiv.injective
  change K.toLinearIsometryEquiv
      (K.toLinearIsometryEquiv.symm (pullback (coordinate i))) =
    K.toLinearIsometryEquiv (x' i)
  rw [K.toLinearIsometryEquiv.apply_symm_apply]
  ext φ
  rfl

/-- The vector lattice homomorphism defining positively homogeneous functional calculus,
bundled with its values on the coordinate functions. -/
private noncomputable def functionalCalculusData
    (x : Fin n → X) :
    { T : VecLatHom (PosHomFunction n) X // ∀ i, T (coordinate i) = x i } := by
  classical
  by_cases h : ∑ i, |x i| = 0
  · refine ⟨zeroVecLatHom, ?_⟩
    intro i
    rw [zeroVecLatHom_apply, coordinate_eq_zero_of_sum_abs_eq_zero x h i]
  · exact functionalCalculusOfPosData x
      (lt_of_le_of_ne (Finset.sum_nonneg fun i _ => abs_nonneg (x i)) (Ne.symm h))

/-- The **positively homogeneous functional calculus** associated to
a tuple `x₁,...,xₙ ∈ X`. -/
noncomputable def functionalCalculus (x : Fin n → X) :
    VecLatHom (PosHomFunction n) X :=
  (functionalCalculusData x).1

/-- The positively homogeneous functional calculus sends the `i`-th coordinate
function to `x i`. -/
@[simp]
theorem functionalCalculus_coordinate (x : Fin n → X) (i : Fin n) :
    functionalCalculus x (coordinate i) = x i := by
  change (functionalCalculusData x).1 (coordinate i) = x i
  exact (functionalCalculusData x).2 i

/-- On coordinate lattice-linear functions, the positively homogeneous functional
calculus agrees with the lattice-linear functional calculus. -/
@[simp]
theorem functionalCalculus_coordinateLL (x : Fin n → X)
    (f : CoordinateLLFunction n) :
    functionalCalculus x (coordinateLLInclusion f) =
      CoordinateLLFunction.functionalCalculus x f := by
  let T := (functionalCalculus x).comp coordinateLLInclusion
  have hT : ∀ i, T (CoordinateLLFunction.coordinate i) = x i := by
    intro i
    exact functionalCalculus_coordinate x i
  have heq := CoordinateLLFunction.eq_functionalCalculus_of_map_coordinate x T hT
  simpa [T, VecLatHom.comp_apply] using DFunLike.congr_fun heq f

/-- A positively homogeneous function is bounded by its norm on the unit sphere. -/
theorem abs_apply_le_norm (f : PosHomFunction n) (x : ellInfinityUnitSphere n) :
    |f x| ≤ ‖f‖ := by
  simpa [Real.norm_eq_abs] using ContinuousMap.norm_coe_le_norm (restrict f) x

/-- The pointwise absolute value of a positively homogeneous function is bounded
by its norm multiplied by the radial extension of the constant function `1` on
the unit sphere. -/
private theorem abs_le_norm_smul_unit (f : PosHomFunction n) :
    |f| ≤ ‖f‖ • extend 1 := by
  intro r
  by_cases hr : r = 0
  · subst r
    simp
  · have hscale : ‖r‖ • (unitNormalize r hr : Fin n → ℝ) = r := by
      simpa only [unitNormalize] using
        norm_smul_normalize (⟨r, hr⟩ : {x : Fin n → ℝ // x ≠ 0})
    have hf := map_smul_of_nonneg f ‖r‖ (norm_nonneg r) (unitNormalize r hr)
    rw [hscale] at hf
    have hu : radialExtension (1 : C(ellInfinityUnitSphere n, ℝ)) r = ‖r‖ := by
      rw [radialExtension_of_ne 1 hr]
      simp
    change |f r| ≤ ‖f‖ * radialExtension 1 r
    rw [hf, hu, abs_smul, abs_of_nonneg (norm_nonneg r)]
    simp only [smul_eq_mul]
    rw [mul_comm]
    exact mul_le_mul_of_nonneg_right (abs_apply_le_norm f (unitNormalize r hr))
      (norm_nonneg r)

omit [IsUniformlyCompleteVectorLattice X] in
/-- For every vector lattice homomorphism `V` from `PosHomFunction n` into `X`,
the absolute value of `V f` is bounded by `‖f‖` times the image under `V` of
the radial extension of the constant function `1` on the unit sphere. -/
private theorem abs_map_le_norm_smul_unit
    (V : VecLatHom (PosHomFunction n) X) (f : PosHomFunction n) :
    |V f| ≤ ‖f‖ • V (extend 1) := by
  calc
    |V f| = V |f| := (V.map_abs f).symm
    _ ≤ V (‖f‖ • extend 1) := V.monotone (abs_le_norm_smul_unit f)
    _ = ‖f‖ • V (extend 1) := V.map_smul _ _

/-- The positively homogeneous functional calculus associated to `x₁,...,xₙ` is the
**unique** vector-lattice homomorphism from `PosHomFunction n` to `X` whose restriction
to `CoordinateLLFunction n` is `CoordinateLLFunction.functionalCalculus x`. -/
private theorem eq_functionalCalculus_of_eq_coordinateLL (x : Fin n → X)
    (V : VecLatHom (PosHomFunction n) X)
    (hV : ∀ f : CoordinateLLFunction n,
      V (coordinateLLInclusion f) = CoordinateLLFunction.functionalCalculus x f) :
    V = functionalCalculus x := by
  apply DFunLike.ext V (functionalCalculus x)
  intro f
  let W := functionalCalculus x
  let u : PosHomFunction n := extend 1
  let e : X := |V u| + |W u|
  have he : 0 ≤ e := add_nonneg (abs_nonneg _) (abs_nonneg _)
  have hzero : |V f - W f| = 0 :=
    IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (abs_nonneg _) fun k => by
      rcases k with _ | k
      · simpa using he
      · have hk : (0 : ℝ) < ((k + 1 : ℕ) : ℝ)⁻¹ := by positivity
        obtain ⟨g, hg⟩ :=
          (Metric.denseRange_iff.mp denseRange_restrict_coordinateLLInclusion)
            (restrict f) _ hk
        let d : PosHomFunction n := f - coordinateLLInclusion g
        have hdnorm : ‖d‖ < ((k + 1 : ℕ) : ℝ)⁻¹ := by
          simpa [d, dist_eq_norm, ← map_sub] using hg
        have hagree : V (coordinateLLInclusion g) =
            W (coordinateLLInclusion g) := by
          rw [hV, show W (coordinateLLInclusion g) =
            CoordinateLLFunction.functionalCalculus x g by
              exact functionalCalculus_coordinateLL x g]
        have hdiff : V f - W f = V d - W d := by
          simp only [d, map_sub]
          rw [hagree]
          abel
        have hVd : |V d| ≤ ‖d‖ • |V u| :=
          (abs_map_le_norm_smul_unit V d).trans
            (smul_le_smul_of_nonneg_left (le_abs_self _) (norm_nonneg d))
        have hWd : |W d| ≤ ‖d‖ • |W u| :=
          (abs_map_le_norm_smul_unit W d).trans
            (smul_le_smul_of_nonneg_left (le_abs_self _) (norm_nonneg d))
        have hde : |V f - W f| ≤ ((k + 1 : ℕ) : ℝ)⁻¹ • e := by
          rw [hdiff]
          calc
            |V d - W d| = |V d + -(W d)| := by rw [sub_eq_add_neg]
            _ ≤ |V d| + |-(W d)| := abs_add_le _ _
            _ = |V d| + |W d| := by rw [abs_neg]
            _ ≤ ‖d‖ • |V u| + ‖d‖ • |W u| := add_le_add hVd hWd
            _ = ‖d‖ • e := by rw [smul_add]
            _ ≤ ((k + 1 : ℕ) : ℝ)⁻¹ • e :=
              smul_le_smul_of_nonneg_right hdnorm.le he
        calc
          (k + 1) • |V f - W f| ≤
              (k + 1) • (((k + 1 : ℕ) : ℝ)⁻¹ • e) :=
            nsmul_le_nsmul_right hde (k + 1)
          _ = e := by
            rw [← Nat.cast_smul_eq_nsmul ℝ, smul_smul,
              mul_inv_cancel₀ (Nat.cast_ne_zero.mpr (Nat.succ_ne_zero k)), one_smul]
  change V f = W f
  apply sub_eq_zero.mp
  apply le_antisymm
  · rw [← hzero]
    exact le_abs_self _
  · have hneg := neg_le_abs (V f - W f)
    rw [hzero] at hneg
    exact neg_nonpos.mp hneg

/-- The **positively homogeneous functional calculus** associated to `x₁,...,xₙ` is the
**unique** vector-lattice homomorphism from `PosHomFunction n` to `X` such that
`coordinate i ↦ x i`. -/
theorem eq_functionalCalculus_of_map_coordinate (x : Fin n → X)
    (V : VecLatHom (PosHomFunction n) X)
    (hV : ∀ i, V (coordinate i) = x i) :
    V = functionalCalculus x := by
  have hV' : ∀ f : CoordinateLLFunction n,
      V (coordinateLLInclusion f) = CoordinateLLFunction.functionalCalculus x f := by
    let T := V.comp coordinateLLInclusion
    have hT : ∀ i, T (CoordinateLLFunction.coordinate i) = x i := by
      intro i
      exact hV i
    have heq := CoordinateLLFunction.eq_functionalCalculus_of_map_coordinate x T hT
    intro f
    simpa [T, VecLatHom.comp_apply] using DFunLike.congr_fun heq f
  exact eq_functionalCalculus_of_eq_coordinateLL x V hV'

/-- The positively homogeneous functional calculus associated to
the zero tuple is zero. -/
@[simp]
theorem functionalCalculus_zero (f : PosHomFunction n) :
    functionalCalculus (fun _ : Fin n => (0 : X)) f = 0 := by
  have hzero : ∀ i,
      zeroVecLatHom (PosHomFunction.coordinate i) = (fun _ : Fin n => (0 : X)) i := by
    intro i
    rw [zeroVecLatHom_apply]
  have heq := eq_functionalCalculus_of_map_coordinate
    (fun _ : Fin n => (0 : X)) zeroVecLatHom hzero
  rw [← heq]
  exact zeroVecLatHom_apply f

/-- The positively homogeneous functional calculus on `C(K, ℝ)` is
computed pointwise. -/
theorem functionalCalculus_continuousMap_apply
    {K : Type*} [TopologicalSpace K]
    [IsUniformlyCompleteVectorLattice C(K, ℝ)]
    (x : Fin n → C(K, ℝ)) (f : PosHomFunction n) (t : K) :
    functionalCalculus x f t = f (fun i => x i t) := by
  let V : VecLatHom (PosHomFunction n) C(K, ℝ) :=
    { toFun := fun g =>
        ⟨fun s => g (fun i => x i s),
          g.1.continuous.comp (continuous_pi fun i => (x i).continuous)⟩
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl
      map_sup' := fun _ _ => rfl
      map_inf' := fun _ _ => rfl }
  have hV : ∀ i, V (coordinate i) = x i := by
    intro i
    ext s
    rfl
  have heq := eq_functionalCalculus_of_map_coordinate x V hV
  rw [← heq]
  rfl

end PosHomFunction

/-! ### Functoriality of positively homogeneous functional calculus -/

namespace PosHomFunction

variable {n : ℕ} {X : Type u} {Y : Type v}
  [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X] [VectorLattice X]
  [IsUniformlyCompleteVectorLattice X]
  [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]
  [IsUniformlyCompleteVectorLattice Y]

/-- Positively homogeneous functional calculus is preserved by lattice homomorphisms:
`T (functionalCalculus x f) = functionalCalculus (Tx) f`. -/
theorem functionalCalculus_map
    (T : VecLatHom X Y) (x : Fin n → X) (f : PosHomFunction n) :
    T (functionalCalculus x f) =
      functionalCalculus (fun i => T (x i)) f := by
  have hcomp : ∀ i,
      (T.comp (functionalCalculus x)) (coordinate i) = T (x i) := by
    intro i
    rw [VecLatHom.comp_apply, functionalCalculus_coordinate]
  have heq := eq_functionalCalculus_of_map_coordinate
    (X := Y) (fun i => T (x i)) (T.comp (functionalCalculus x)) hcomp
  simpa [VecLatHom.comp_apply] using DFunLike.congr_fun heq f

end PosHomFunction

/-! ### Composition and substitution in positively homogeneous functional calculus -/

namespace PosHomFunction

variable {m n : ℕ}

/-- Composition of a positively homogeneous function with a tuple of positively
homogeneous functions. -/
def comp (f : PosHomFunction m) (g : Fin m → PosHomFunction n) :
    PosHomFunction n := by
  refine ⟨⟨fun x ↦ f (fun i ↦ g i x), ?_⟩, ?_⟩
  · exact f.1.continuous.comp (continuous_pi fun i ↦ (g i).1.continuous)
  · intro c hc x
    change f (fun i ↦ g i (c • x)) = c • f (fun i ↦ g i x)
    have hg : (fun i ↦ g i (c • x)) = c • (fun i ↦ g i x) := by
      funext i
      change g i (c • x) = c • g i x
      exact map_smul_of_nonneg (g i) c hc x
    rw [hg, map_smul_of_nonneg f c hc]

/-- Pointwise evaluation of a composition of positively homogeneous functions. -/
@[simp]
theorem comp_apply (f : PosHomFunction m) (g : Fin m → PosHomFunction n)
    (x : Fin n → ℝ) :
    f.comp g x = f (fun i ↦ g i x) := by
  rfl

variable {X : Type u} [AddCommGroup X] [Lattice X]
  [IsOrderedAddMonoid X] [VectorLattice X]
  [IsUniformlyCompleteVectorLattice X]

/-- Substitution of positively homogeneous functions commutes with their
functional calculus. -/
@[simp]
theorem functionalCalculus_comp (x : Fin n → X)
    (g : Fin m → PosHomFunction n) (f : PosHomFunction m) :
    functionalCalculus (fun i ↦ functionalCalculus x (g i)) f =
      functionalCalculus x (f.comp g) := by
  letI := isUniformlyCompleteVectorLattice_of_banachLattice (PosHomFunction n)
  let V : VecLatHom (PosHomFunction m) (PosHomFunction n) :=
    { toFun := fun h ↦ h.comp g
      map_add' := fun _ _ ↦ rfl
      map_smul' := fun _ _ ↦ rfl
      map_sup' := fun _ _ ↦ rfl
      map_inf' := fun _ _ ↦ rfl }
  have hV : ∀ i, V (coordinate i) = g i := by
    intro i
    ext r
    change (coordinate i).comp g r = g i r
    rw [comp_apply, coordinate_apply]
  have hcalc : functionalCalculus g = V :=
    (eq_functionalCalculus_of_map_coordinate g V hV).symm
  rw [← functionalCalculus_map (functionalCalculus x) g f, hcalc]
  rfl

end PosHomFunction
