/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Dual
import BanLat.Free.FVLv
import BanLat.Substructures.Sublattice
import Mathlib.Algebra.Order.Group.Unbundled.Abs
import Mathlib.Analysis.Normed.Operator.Extend

/-!
# The free Banach lattice generated by a normed space

This file gives the concrete construction of the free Banach lattice generated by a real
normed space. The ambient functions live on the weak-star closed unit ball of the dual.
The free norm formula is first defined as an extended non-negative real value on all
continuous functions, and then as a real-valued norm on the subspace where that extended
value is finite. The free Banach lattice `FBL E` is realized as the free-norm closure of
the concrete free vector lattice generated by the evaluation maps.
-/

open scoped BigOperators

noncomputable section

universe u v

namespace FBL

variable (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The admissible finite families of dual functionals used to compute the free norm. -/
def NormAdmissible {n : ℕ} (φ : Fin n → FVLv.dualUnitBall E) : Prop :=
  ∀ x : E, ‖x‖ ≤ 1 → ∑ i, |(φ i : WeakDual ℝ E) x| ≤ 1

/-- The extended free norm on `C(B_{E*}, ℝ)`.

This value can be infinite for an arbitrary continuous function. The real-valued norm is
therefore defined on the subtype of functions for which this extended value is
finite. -/
noncomputable def freeNormExt (f : C(FVLv.dualUnitBall E, ℝ)) : ENNReal :=
  ⨆ (n : ℕ) (φ : Fin n → FVLv.dualUnitBall E) (_h : NormAdmissible E φ),
    ENNReal.ofReal (∑ i, |f (φ i)|)

/-- The finite-free-norm part of `C(B_{E*}, ℝ)` used in the concrete construction.

This is not the whole continuous function space: the formula defining `freeNormExt` can be
infinite. The subtype records the finiteness needed to attach a genuine real-valued norm.
It also keeps the free-norm structure separate from Mathlib's usual supremum norm on
`C(B_{E*}, ℝ)`. -/
def FunctionSpace : Type u :=
  {f : C(FVLv.dualUnitBall E, ℝ) // freeNormExt E f < ⊤}

namespace FunctionSpace

/-- The underlying continuous function on the weak-star dual unit ball. -/
def toContinuousMap (f : FunctionSpace E) : C(FVLv.dualUnitBall E, ℝ) :=
  f.1

/-- Regard a continuous function on the weak-star dual unit ball as an element of the
ambient function space, provided its extended free norm is finite. -/
def ofContinuousMap (f : C(FVLv.dualUnitBall E, ℝ)) (hf : freeNormExt E f < ⊤) :
    FunctionSpace E :=
  ⟨f, hf⟩

instance instCoeContinuousMap : Coe (FunctionSpace E) C(FVLv.dualUnitBall E, ℝ) where
  coe f := toContinuousMap E f

instance instCoeFun : CoeFun (FunctionSpace E) (fun _ => FVLv.dualUnitBall E → ℝ) where
  coe f := toContinuousMap E f

@[simp]
theorem ofContinuousMap_apply (f : C(FVLv.dualUnitBall E, ℝ))
    (hf : freeNormExt E f < ⊤) (φ : FVLv.dualUnitBall E) :
    ofContinuousMap E f hf φ = f φ :=
  rfl

@[simp]
theorem toContinuousMap_apply (f : FunctionSpace E) (φ : FVLv.dualUnitBall E) :
    toContinuousMap E f φ = f φ :=
  rfl

end FunctionSpace

/-- The finiteness assertion built into `FunctionSpace`. -/
theorem freeNormExt_lt_top (f : FunctionSpace E) :
    freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ)) < ⊤ :=
  f.2

/-- The real-valued free norm on the finite-free-norm function space. -/
noncomputable def freeNorm (f : FunctionSpace E) : ℝ :=
  (freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ))).toReal

instance instNormFunctionSpace : Norm (FunctionSpace E) where
  norm := freeNorm E

private theorem le_freeNormExt {f : C(FVLv.dualUnitBall E, ℝ)} {n : ℕ}
    (φ : Fin n → FVLv.dualUnitBall E) (hφ : NormAdmissible E φ) :
    ENNReal.ofReal (∑ i, |f (φ i)|) ≤ freeNormExt E f := by
  rw [freeNormExt]
  exact le_iSup_of_le n <| le_iSup_of_le φ <| le_iSup_of_le hφ le_rfl

private theorem freeNormExt_le_of_forall {f : C(FVLv.dualUnitBall E, ℝ)} {C : ENNReal}
    (h : ∀ (n : ℕ) (φ : Fin n → FVLv.dualUnitBall E), NormAdmissible E φ →
      ENNReal.ofReal (∑ i, |f (φ i)|) ≤ C) :
    freeNormExt E f ≤ C := by
  rw [freeNormExt]
  exact iSup_le fun n => iSup_le fun φ => iSup_le fun hφ => h n φ hφ

private theorem freeNormExt_zero :
    freeNormExt E (0 : C(FVLv.dualUnitBall E, ℝ)) = 0 := by
  simp [freeNormExt]

private theorem freeNormExt_neg (f : C(FVLv.dualUnitBall E, ℝ)) :
    freeNormExt E (-f) = freeNormExt E f := by
  simp [freeNormExt]

private theorem freeNormExt_smul (c : ℝ) (f : C(FVLv.dualUnitBall E, ℝ)) :
    freeNormExt E (c • f) = ENNReal.ofReal |c| * freeNormExt E f := by
  rw [freeNormExt, freeNormExt]
  rw [ENNReal.mul_iSup]
  congr with n
  rw [ENNReal.mul_iSup]
  congr with φ
  rw [ENNReal.mul_iSup]
  congr with hφ
  simp only [ContinuousMap.coe_smul, Pi.smul_apply, smul_eq_mul, abs_mul]
  rw [← ENNReal.ofReal_mul (abs_nonneg c)]
  congr 1
  rw [Finset.mul_sum]

private theorem freeNormExt_add_le (f g : C(FVLv.dualUnitBall E, ℝ)) :
    freeNormExt E (f + g) ≤ freeNormExt E f + freeNormExt E g := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  have hsum :
      ∑ i, |(f + g) (φ i)| ≤ ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by
    calc
      ∑ i, |(f + g) (φ i)| = ∑ i, |f (φ i) + g (φ i)| := by simp
      _ ≤ ∑ i, (|f (φ i)| + |g (φ i)|) := by
        exact Finset.sum_le_sum fun i _ => abs_add_le (f (φ i)) (g (φ i))
      _ = ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by rw [Finset.sum_add_distrib]
  have hf_nonneg : 0 ≤ ∑ i, |f (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  have hg_nonneg : 0 ≤ ∑ i, |g (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  calc
    ENNReal.ofReal (∑ i, |(f + g) (φ i)|)
        ≤ ENNReal.ofReal (∑ i, |f (φ i)| + ∑ i, |g (φ i)|) :=
      ENNReal.ofReal_le_ofReal hsum
    _ = ENNReal.ofReal (∑ i, |f (φ i)|) + ENNReal.ofReal (∑ i, |g (φ i)|) := by
      rw [ENNReal.ofReal_add hf_nonneg hg_nonneg]
    _ ≤ freeNormExt E f + freeNormExt E g :=
      add_le_add (le_freeNormExt E φ hφ) (le_freeNormExt E φ hφ)

private theorem freeNormExt_mono_abs {f g : C(FVLv.dualUnitBall E, ℝ)}
    (h : ∀ φ : FVLv.dualUnitBall E, |f φ| ≤ |g φ|) :
    freeNormExt E f ≤ freeNormExt E g := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  exact (ENNReal.ofReal_le_ofReal (Finset.sum_le_sum fun i _ => h (φ i))).trans
    (le_freeNormExt E φ hφ)

private theorem freeNormExt_sup_le (f g : C(FVLv.dualUnitBall E, ℝ)) :
    freeNormExt E (f ⊔ g) ≤ freeNormExt E f + freeNormExt E g := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  have hsum :
      ∑ i, |(f ⊔ g) (φ i)| ≤ ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by
    calc
      ∑ i, |(f ⊔ g) (φ i)| = ∑ i, |f (φ i) ⊔ g (φ i)| := by simp
      _ ≤ ∑ i, (|f (φ i)| + |g (φ i)|) := by
        exact Finset.sum_le_sum fun i _ => FVLv.abs_sup_le_add_abs (f (φ i)) (g (φ i))
      _ = ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by rw [Finset.sum_add_distrib]
  have hf_nonneg : 0 ≤ ∑ i, |f (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  have hg_nonneg : 0 ≤ ∑ i, |g (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  calc
    ENNReal.ofReal (∑ i, |(f ⊔ g) (φ i)|)
        ≤ ENNReal.ofReal (∑ i, |f (φ i)| + ∑ i, |g (φ i)|) :=
      ENNReal.ofReal_le_ofReal hsum
    _ = ENNReal.ofReal (∑ i, |f (φ i)|) + ENNReal.ofReal (∑ i, |g (φ i)|) := by
      rw [ENNReal.ofReal_add hf_nonneg hg_nonneg]
    _ ≤ freeNormExt E f + freeNormExt E g :=
      add_le_add (le_freeNormExt E φ hφ) (le_freeNormExt E φ hφ)

private theorem freeNormExt_inf_le (f g : C(FVLv.dualUnitBall E, ℝ)) :
    freeNormExt E (f ⊓ g) ≤ freeNormExt E f + freeNormExt E g := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  have hsum :
      ∑ i, |(f ⊓ g) (φ i)| ≤ ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by
    calc
      ∑ i, |(f ⊓ g) (φ i)| = ∑ i, |f (φ i) ⊓ g (φ i)| := by simp
      _ ≤ ∑ i, (|f (φ i)| + |g (φ i)|) := by
        exact Finset.sum_le_sum fun i _ => FVLv.abs_inf_le_add_abs (f (φ i)) (g (φ i))
      _ = ∑ i, |f (φ i)| + ∑ i, |g (φ i)| := by rw [Finset.sum_add_distrib]
  have hf_nonneg : 0 ≤ ∑ i, |f (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  have hg_nonneg : 0 ≤ ∑ i, |g (φ i)| := Finset.sum_nonneg fun i _ => abs_nonneg _
  calc
    ENNReal.ofReal (∑ i, |(f ⊓ g) (φ i)|)
        ≤ ENNReal.ofReal (∑ i, |f (φ i)| + ∑ i, |g (φ i)|) :=
      ENNReal.ofReal_le_ofReal hsum
    _ = ENNReal.ofReal (∑ i, |f (φ i)|) + ENNReal.ofReal (∑ i, |g (φ i)|) := by
      rw [ENNReal.ofReal_add hf_nonneg hg_nonneg]
    _ ≤ freeNormExt E f + freeNormExt E g :=
      add_le_add (le_freeNormExt E φ hφ) (le_freeNormExt E φ hφ)

private theorem normAdmissible_singleton (φ : FVLv.dualUnitBall E) :
    NormAdmissible E (fun _ : Fin 1 => φ) := by
  intro x hx
  simp only [Fin.sum_univ_one]
  have hφmem : WeakDual.toStrongDual (φ : WeakDual ℝ E) ∈
      Metric.closedBall (0 : StrongDual ℝ E) 1 := φ.2
  rw [Metric.mem_closedBall] at hφmem
  have hφ : ‖WeakDual.toStrongDual (φ : WeakDual ℝ E)‖ ≤ 1 := by
    rwa [dist_eq_norm, sub_zero] at hφmem
  have hle : ‖(WeakDual.toStrongDual (φ : WeakDual ℝ E)) x‖ ≤ 1 := by
    calc
      ‖(WeakDual.toStrongDual (φ : WeakDual ℝ E)) x‖
          ≤ ‖WeakDual.toStrongDual (φ : WeakDual ℝ E)‖ * ‖x‖ :=
        ContinuousLinearMap.le_opNorm _ _
      _ ≤ 1 * 1 := mul_le_mul hφ hx (norm_nonneg _) zero_le_one
      _ = 1 := by norm_num
  simpa [Real.norm_eq_abs, WeakDual.toStrongDual_apply] using hle

private theorem coe_eq_zero_of_freeNorm_eq_zero (f : FunctionSpace E)
    (h : freeNorm E f = 0) :
    (f : C(FVLv.dualUnitBall E, ℝ)) = 0 := by
  have hfin : freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ)) ≠ ⊤ :=
    ne_of_lt (freeNormExt_lt_top E f)
  have hext_zero : freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ)) = 0 := by
    rcases (ENNReal.toReal_eq_zero_iff
        (freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ)))).mp h with h0 | htop
    · exact h0
    · exact (hfin htop).elim
  ext φ
  have hle := le_freeNormExt E (f := (f : C(FVLv.dualUnitBall E, ℝ)))
    (fun _ : Fin 1 => φ) (normAdmissible_singleton E φ)
  have hofReal_zero : ENNReal.ofReal |f φ| = 0 :=
    le_antisymm (by simpa [hext_zero] using hle) bot_le
  have habs_nonpos : |f φ| ≤ 0 := by
    simpa [ENNReal.ofReal_eq_zero] using hofReal_zero
  exact abs_eq_zero.mp (le_antisymm habs_nonpos (abs_nonneg _))

private theorem freeNormExt_dualEval_le (x : E) :
    freeNormExt E (FVLv.dualEval E x) ≤ ENNReal.ofReal ‖x‖ := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  by_cases hx : x = 0
  · subst x
    simp [FVLv.dualEval]
  · have hxpos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    have hscale_norm : ‖‖x‖⁻¹ • x‖ ≤ 1 := by
      rw [norm_smul, Real.norm_of_nonneg (inv_nonneg.mpr hxpos.le),
        inv_mul_cancel₀ hxpos.ne']
    have hadm := hφ (‖x‖⁻¹ • x) hscale_norm
    have hscaled_sum : ∑ i, |(φ i : WeakDual ℝ E) (‖x‖⁻¹ • x)| =
        ‖x‖⁻¹ * ∑ i, |(φ i : WeakDual ℝ E) x| := by
      calc
        ∑ i, |(φ i : WeakDual ℝ E) (‖x‖⁻¹ • x)| =
            ∑ i, ‖x‖⁻¹ * |(φ i : WeakDual ℝ E) x| := by
          simp [map_smul, abs_mul, abs_of_nonneg (inv_nonneg.mpr hxpos.le)]
        _ = ‖x‖⁻¹ * ∑ i, |(φ i : WeakDual ℝ E) x| := by
          rw [Finset.mul_sum]
    have hmul : ‖x‖⁻¹ * ∑ i, |(φ i : WeakDual ℝ E) x| ≤ 1 := by
      rw [← hscaled_sum]
      exact hadm
    have hsum : ∑ i, |(φ i : WeakDual ℝ E) x| ≤ ‖x‖ := by
      calc
        ∑ i, |(φ i : WeakDual ℝ E) x| =
            ‖x‖ * (‖x‖⁻¹ * ∑ i, |(φ i : WeakDual ℝ E) x|) := by
          rw [← mul_assoc, mul_inv_cancel₀ hxpos.ne', one_mul]
        _ ≤ ‖x‖ * 1 := mul_le_mul_of_nonneg_left hmul hxpos.le
        _ = ‖x‖ := by rw [mul_one]
    simpa [FVLv.dualEval_apply] using ENNReal.ofReal_le_ofReal hsum

private def functionSpaceSubmodule : Submodule ℝ C(FVLv.dualUnitBall E, ℝ) where
  carrier := {f | freeNormExt E f < ⊤}
  zero_mem' := by
    simp [freeNormExt_zero]
  add_mem' := by
    intro f g hf hg
    refine lt_of_le_of_lt (freeNormExt_add_le E f g) ?_
    exact lt_top_iff_ne_top.mpr (ENNReal.add_ne_top.mpr ⟨ne_of_lt hf, ne_of_lt hg⟩)
  smul_mem' := by
    intro c f hf
    change freeNormExt E (c • f) < ⊤
    rw [freeNormExt_smul]
    exact lt_top_iff_ne_top.mpr (ENNReal.mul_ne_top ENNReal.ofReal_ne_top (ne_of_lt hf))

@[reducible]
private def functionSpaceAddCommGroup : AddCommGroup (FunctionSpace E) :=
  inferInstanceAs (AddCommGroup ↥(functionSpaceSubmodule E))

@[reducible]
private def functionSpaceModule :
    @Module ℝ (FunctionSpace E) _ (functionSpaceAddCommGroup E).toAddCommMonoid :=
  inferInstanceAs (@Module ℝ ↥(functionSpaceSubmodule E) _ _)

private noncomputable def functionSpaceVectorSublattice :
    VectorSublattice C(FVLv.dualUnitBall E, ℝ) where
  toSubmodule := functionSpaceSubmodule E
  sup_mem' := by
    intro f g hf hg
    refine lt_of_le_of_lt (freeNormExt_sup_le E f g) ?_
    exact lt_top_iff_ne_top.mpr (ENNReal.add_ne_top.mpr ⟨ne_of_lt hf, ne_of_lt hg⟩)

instance instNormedAddCommGroupFunctionSpace : NormedAddCommGroup (FunctionSpace E) := by
  letI : AddCommGroup (FunctionSpace E) := functionSpaceAddCommGroup E
  letI : Module ℝ (FunctionSpace E) := functionSpaceModule E
  exact NormedAddCommGroup.ofCore (𝕜 := ℝ) {
    toCore := {
      norm_nonneg := fun _ => ENNReal.toReal_nonneg
      norm_smul := by
        intro c f
        change freeNorm E (c • f) = ‖c‖ * freeNorm E f
        change (freeNormExt E (c • (f : C(FVLv.dualUnitBall E, ℝ)))).toReal =
          ‖c‖ * (freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ))).toReal
        rw [freeNormExt_smul, ENNReal.toReal_mul, ENNReal.toReal_ofReal (abs_nonneg c),
          Real.norm_eq_abs]
      norm_triangle := by
        intro f g
        change freeNorm E (f + g) ≤ freeNorm E f + freeNorm E g
        have hne : freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ)) +
            freeNormExt E (g : C(FVLv.dualUnitBall E, ℝ)) ≠ ⊤ := by
          rw [ENNReal.add_ne_top]
          exact ⟨ne_of_lt f.2, ne_of_lt g.2⟩
        exact (ENNReal.toReal_mono hne
          (freeNormExt_add_le E (f : C(FVLv.dualUnitBall E, ℝ))
            (g : C(FVLv.dualUnitBall E, ℝ)))).trans ENNReal.toReal_add_le
    }
    norm_eq_zero_iff := by
      intro f
      constructor
      · intro h
        exact Subtype.ext (coe_eq_zero_of_freeNorm_eq_zero E f h)
      · intro h
        subst h
        change (freeNormExt E (0 : C(FVLv.dualUnitBall E, ℝ))).toReal = 0
        rw [freeNormExt_zero, ENNReal.toReal_zero]
  }

instance instAddCommGroupFunctionSpace : AddCommGroup (FunctionSpace E) :=
  NormedAddCommGroup.toAddCommGroup (E := FunctionSpace E)
    (self := instNormedAddCommGroupFunctionSpace E)

instance instNormedSpaceFunctionSpace :
    @NormedSpace ℝ (FunctionSpace E) _
      (instNormedAddCommGroupFunctionSpace E).toSeminormedAddCommGroup := by
  letI : Module ℝ (FunctionSpace E) := functionSpaceModule E
  exact {
    toModule := functionSpaceModule E
    norm_smul_le := by
      intro c f
      change freeNorm E (c • f) ≤ ‖c‖ * freeNorm E f
      change (freeNormExt E (c • (f : C(FVLv.dualUnitBall E, ℝ)))).toReal ≤
        ‖c‖ * (freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ))).toReal
      rw [freeNormExt_smul, ENNReal.toReal_mul, ENNReal.toReal_ofReal (abs_nonneg c),
        Real.norm_eq_abs]
  }

instance instMaxFunctionSpace : Max (FunctionSpace E) := by
  exact inferInstanceAs (Max ↥(functionSpaceVectorSublattice E).toSubmodule)

instance instMinFunctionSpace : Min (FunctionSpace E) := by
  exact inferInstanceAs (Min ↥(functionSpaceVectorSublattice E).toSubmodule)

instance instLEFunctionSpace : LE (FunctionSpace E) := by
  exact inferInstanceAs (LE ↥(functionSpaceVectorSublattice E).toSubmodule)

instance instLatticeFunctionSpace : Lattice (FunctionSpace E) := by
  exact inferInstanceAs (Lattice ↥(functionSpaceVectorSublattice E).toSubmodule)

instance instIsOrderedAddMonoidFunctionSpace :
    @IsOrderedAddMonoid (FunctionSpace E)
      (AddCommGroup.toAddCommMonoid (G := FunctionSpace E)
        (self := instAddCommGroupFunctionSpace E))
      (instLatticeFunctionSpace E).toPartialOrder.toPreorder := by
  exact inferInstanceAs (IsOrderedAddMonoid ↥(functionSpaceVectorSublattice E).toSubmodule)

instance instVectorLatticeFunctionSpace :
    @VectorLattice (FunctionSpace E) (instAddCommGroupFunctionSpace E)
      (instLatticeFunctionSpace E) (instIsOrderedAddMonoidFunctionSpace E) where
  toModule :=
    NormedSpace.toModule (𝕜 := ℝ) (E := FunctionSpace E)
      (self := instNormedSpaceFunctionSpace E)
  smul_le_smul_of_nonneg_left := by
    intro c hc f g hfg
    change ∀ φ : FVLv.dualUnitBall E, (c • (f : C(FVLv.dualUnitBall E, ℝ))) φ ≤
      (c • (g : C(FVLv.dualUnitBall E, ℝ))) φ
    intro φ
    exact smul_le_smul_of_nonneg_left (hfg φ) hc

instance instContinuousConstSMulFunctionSpace : ContinuousConstSMul ℝ (FunctionSpace E) := by
  infer_instance

instance instNormedVectorLatticeFunctionSpace :
    @NormedVectorLattice (FunctionSpace E) (instNormedAddCommGroupFunctionSpace E)
      (instLatticeFunctionSpace E) (instIsOrderedAddMonoidFunctionSpace E) where
  toVectorLattice := instVectorLatticeFunctionSpace E
  solid := by
    intro f g hfg
    change freeNorm E f ≤ freeNorm E g
    apply ENNReal.toReal_mono (ne_of_lt g.2)
    apply freeNormExt_mono_abs
    intro φ
    exact hfg φ
  norm_smul := by
    intro c f
    change freeNorm E (c • f) = ‖c‖ * freeNorm E f
    change (freeNormExt E (c • (f : C(FVLv.dualUnitBall E, ℝ)))).toReal =
      ‖c‖ * (freeNormExt E (f : C(FVLv.dualUnitBall E, ℝ))).toReal
    rw [freeNormExt_smul, ENNReal.toReal_mul, ENNReal.toReal_ofReal (abs_nonneg c),
      Real.norm_eq_abs]

private theorem sum_abs_apply_le_freeNorm (f : FunctionSpace E) {n : ℕ}
    (φ : Fin n → FVLv.dualUnitBall E) (hφ : NormAdmissible E φ) :
    ∑ i, |f (φ i)| ≤ ‖f‖ := by
  change ∑ i, |(f : C(FVLv.dualUnitBall E, ℝ)) (φ i)| ≤ freeNorm E f
  have hle := le_freeNormExt E (f := (f : C(FVLv.dualUnitBall E, ℝ))) φ hφ
  exact (ENNReal.ofReal_le_iff_le_toReal (ne_of_lt (freeNormExt_lt_top E f))).mp hle

private theorem continuousMap_norm_le_freeNorm (f : FunctionSpace E) :
    ‖(f : C(FVLv.dualUnitBall E, ℝ))‖ ≤ ‖f‖ := by
  refine (ContinuousMap.norm_le (f := (f : C(FVLv.dualUnitBall E, ℝ)))
    (C := ‖f‖) (norm_nonneg f)).mpr ?_
  intro φ
  rw [Real.norm_eq_abs]
  simpa [Fin.sum_univ_one] using
    sum_abs_apply_le_freeNorm E f (fun _ : Fin 1 => φ) (normAdmissible_singleton E φ)

private theorem freeNormExt_sub_limit_le_of_cauchySeq {u : ℕ → FunctionSpace E}
    {g : C(FVLv.dualUnitBall E, ℝ)}
    (hg : Filter.Tendsto (fun n => (u n : C(FVLv.dualUnitBall E, ℝ))) Filter.atTop
      (nhds g))
    {N : ℕ} {r : ℝ}
    (hN : ∀ᶠ m in Filter.atTop, ‖u m - u N‖ ≤ r) :
    freeNormExt E (g - (u N : C(FVLv.dualUnitBall E, ℝ))) ≤ ENNReal.ofReal r := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  apply ENNReal.ofReal_le_ofReal
  have hsum_tend :
      Filter.Tendsto
        (fun m => ∑ i, |((u m : C(FVLv.dualUnitBall E, ℝ)) -
          (u N : C(FVLv.dualUnitBall E, ℝ))) (φ i)|) Filter.atTop
        (nhds (∑ i, |(g - (u N : C(FVLv.dualUnitBall E, ℝ))) (φ i)|)) := by
    apply tendsto_finsetSum
    intro i hi
    have hdiff_tend :
        Filter.Tendsto
          (fun m => (u m : C(FVLv.dualUnitBall E, ℝ)) -
            (u N : C(FVLv.dualUnitBall E, ℝ))) Filter.atTop
          (nhds (g - (u N : C(FVLv.dualUnitBall E, ℝ)))) :=
      hg.sub tendsto_const_nhds
    have heval_tend :
        Filter.Tendsto
          (fun m => ((u m : C(FVLv.dualUnitBall E, ℝ)) -
            (u N : C(FVLv.dualUnitBall E, ℝ))) (φ i)) Filter.atTop
          (nhds ((g - (u N : C(FVLv.dualUnitBall E, ℝ))) (φ i))) := by
      simpa using
        ((continuous_eval_const (φ i)).tendsto
          (g - (u N : C(FVLv.dualUnitBall E, ℝ)))).comp hdiff_tend
    exact (continuous_abs.tendsto _).comp heval_tend
  have htail :
      ∀ᶠ m in Filter.atTop,
        ∑ i, |((u m : C(FVLv.dualUnitBall E, ℝ)) -
          (u N : C(FVLv.dualUnitBall E, ℝ))) (φ i)| ≤ r := by
    filter_upwards [hN] with m hm
    exact (sum_abs_apply_le_freeNorm E (u m - u N) φ hφ).trans (by simpa using hm)
  exact le_of_tendsto_of_tendsto hsum_tend tendsto_const_nhds htail

private theorem freeNormExt_sub_limit_le_of_cauchySeq' {u : ℕ → FunctionSpace E}
    {g : C(FVLv.dualUnitBall E, ℝ)}
    (hg : Filter.Tendsto (fun n => (u n : C(FVLv.dualUnitBall E, ℝ))) Filter.atTop
      (nhds g))
    {N : ℕ} {r : ℝ}
    (hN : ∀ᶠ m in Filter.atTop, ‖u N - u m‖ ≤ r) :
    freeNormExt E ((u N : C(FVLv.dualUnitBall E, ℝ)) - g) ≤ ENNReal.ofReal r := by
  apply freeNormExt_le_of_forall
  intro n φ hφ
  apply ENNReal.ofReal_le_ofReal
  have hsum_tend :
      Filter.Tendsto
        (fun m => ∑ i, |((u N : C(FVLv.dualUnitBall E, ℝ)) -
          (u m : C(FVLv.dualUnitBall E, ℝ))) (φ i)|) Filter.atTop
        (nhds (∑ i, |((u N : C(FVLv.dualUnitBall E, ℝ)) - g) (φ i)|)) := by
    apply tendsto_finsetSum
    intro i hi
    have hdiff_tend :
        Filter.Tendsto
          (fun m => (u N : C(FVLv.dualUnitBall E, ℝ)) -
            (u m : C(FVLv.dualUnitBall E, ℝ))) Filter.atTop
          (nhds ((u N : C(FVLv.dualUnitBall E, ℝ)) - g)) :=
      tendsto_const_nhds.sub hg
    have heval_tend :
        Filter.Tendsto
          (fun m => ((u N : C(FVLv.dualUnitBall E, ℝ)) -
            (u m : C(FVLv.dualUnitBall E, ℝ))) (φ i)) Filter.atTop
          (nhds (((u N : C(FVLv.dualUnitBall E, ℝ)) - g) (φ i))) := by
      simpa using
        ((continuous_eval_const (φ i)).tendsto
          ((u N : C(FVLv.dualUnitBall E, ℝ)) - g)).comp hdiff_tend
    exact (continuous_abs.tendsto _).comp heval_tend
  have htail :
      ∀ᶠ m in Filter.atTop,
        ∑ i, |((u N : C(FVLv.dualUnitBall E, ℝ)) -
          (u m : C(FVLv.dualUnitBall E, ℝ))) (φ i)| ≤ r := by
    filter_upwards [hN] with m hm
    exact (sum_abs_apply_le_freeNorm E (u N - u m) φ hφ).trans (by simpa using hm)
  exact le_of_tendsto_of_tendsto hsum_tend tendsto_const_nhds htail

private noncomputable instance instCompleteSpaceFunctionSpace :
    CompleteSpace (FunctionSpace E) := by
  refine Metric.complete_of_cauchySeq_tendsto fun u hu => ?_
  have hu_continuousMap :
      CauchySeq (fun n => (u n : C(FVLv.dualUnitBall E, ℝ))) := by
    rw [Metric.cauchySeq_iff] at hu ⊢
    intro ε hε
    obtain ⟨N, hN⟩ := hu ε hε
    refine ⟨N, fun n hn m hm => ?_⟩
    rw [dist_eq_norm]
    exact (continuousMap_norm_le_freeNorm E (u n - u m)).trans_lt (by
      simpa [dist_eq_norm] using hN n hn m hm)
  obtain ⟨g, hg⟩ := cauchySeq_tendsto_of_complete hu_continuousMap
  have hg_finite : freeNormExt E g < ⊤ := by
    rw [Metric.cauchySeq_iff] at hu
    obtain ⟨N, hN⟩ := hu 1 zero_lt_one
    have htail : ∀ᶠ m in Filter.atTop, ‖u m - u N‖ ≤ (1 : ℝ) := by
      filter_upwards [Filter.eventually_atTop.2 ⟨N, fun m hm => hm⟩] with m hm
      exact (le_of_lt (by simpa [dist_eq_norm] using hN m hm N le_rfl))
    have hdiff :
        freeNormExt E (g - (u N : C(FVLv.dualUnitBall E, ℝ))) ≤ ENNReal.ofReal 1 :=
      freeNormExt_sub_limit_le_of_cauchySeq E hg htail
    have hdiff_lt : freeNormExt E (g - (u N : C(FVLv.dualUnitBall E, ℝ))) < ⊤ :=
      lt_of_le_of_lt hdiff (lt_top_iff_ne_top.mpr ENNReal.ofReal_ne_top)
    have hg_le : freeNormExt E g ≤
        freeNormExt E (g - (u N : C(FVLv.dualUnitBall E, ℝ))) +
          freeNormExt E (u N : C(FVLv.dualUnitBall E, ℝ)) := by
      simpa [sub_add_cancel] using
        freeNormExt_add_le E (g - (u N : C(FVLv.dualUnitBall E, ℝ)))
          (u N : C(FVLv.dualUnitBall E, ℝ))
    exact lt_of_le_of_lt hg_le
      (lt_top_iff_ne_top.mpr
        (ENNReal.add_ne_top.mpr ⟨ne_of_lt hdiff_lt, ne_of_lt (freeNormExt_lt_top E (u N))⟩))
  refine ⟨⟨g, hg_finite⟩, ?_⟩
  rw [Metric.tendsto_atTop]
  intro ε hε
  rw [Metric.cauchySeq_iff] at hu
  obtain ⟨N, hN⟩ := hu (ε / 2) (by linarith)
  refine ⟨N, fun n hn => ?_⟩
  rw [dist_eq_norm]
  have htail : ∀ᶠ m in Filter.atTop, ‖u n - u m‖ ≤ ε / 2 := by
    filter_upwards [Filter.eventually_atTop.2 ⟨N, fun m hm => hm⟩] with m hm
    exact le_of_lt (by simpa [dist_eq_norm] using hN n hn m hm)
  have hdiff : freeNormExt E ((u n : C(FVLv.dualUnitBall E, ℝ)) - g) ≤
      ENNReal.ofReal (ε / 2) :=
    freeNormExt_sub_limit_le_of_cauchySeq' E hg htail
  have hnorm : ‖u n - ⟨g, hg_finite⟩‖ ≤ ε / 2 := by
    change (freeNormExt E (((u n - ⟨g, hg_finite⟩ : FunctionSpace E) :
      C(FVLv.dualUnitBall E, ℝ)))).toReal ≤ ε / 2
    exact ENNReal.toReal_le_of_le_ofReal (by linarith) (by simpa using hdiff)
  linarith

private noncomputable instance instBanachLatticeFunctionSpace :
    BanachLattice (FunctionSpace E) where

/-- The evaluation map `x ↦ x̂` as a function into the ambient free-normed space. -/
def dualEval (x : E) : FunctionSpace E :=
  ⟨FVLv.dualEval E x, by
    exact lt_of_le_of_lt (freeNormExt_dualEval_le E x)
      (lt_top_iff_ne_top.mpr ENNReal.ofReal_ne_top)⟩

@[simp]
theorem dualEval_apply (x : E) (φ : FVLv.dualUnitBall E) :
    dualEval E x φ = (φ : WeakDual ℝ E) x := by
  rfl

/-- The concrete free vector lattice generated by the evaluation maps inside the
free-normed ambient function space. -/
def freeVectorLattice : VectorSublattice (FunctionSpace E) :=
  VectorSublattice.generated (Set.range (dualEval E : E → FunctionSpace E))

/-- The concrete free Banach lattice: the closure, for the free norm, of the free vector
lattice generated by `E`. -/
def closedFreeVectorLattice : VectorSublattice (FunctionSpace E) :=
  (freeVectorLattice E).topologicalClosure

@[simp]
theorem coe_closedFreeVectorLattice :
    (closedFreeVectorLattice E : Set (FunctionSpace E)) =
      closure (freeVectorLattice E : Set (FunctionSpace E)) := by
  rfl

end FBL

/-- The free Banach lattice generated by a real normed space, realized as the free-norm closure of
its concrete free vector lattice in `C(B_{E*}, ℝ)`. -/
abbrev FBL (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E] :
    Type u :=
  ↥(FBL.closedFreeVectorLattice E).toSubmodule

namespace FBL

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E]

instance instCoeFunctionSpace : Coe (FBL E) (FunctionSpace E) where
  coe f := f.1

instance instCoeFun : CoeFun (FBL E) (fun _ => FVLv.dualUnitBall E → ℝ) where
  coe f := (f : FunctionSpace E)

instance instNormFBL : Norm (FBL E) where
  norm f := ‖(f : FunctionSpace E)‖

instance instNormedAddCommGroupFBL : NormedAddCommGroup (FBL E) := by
  exact inferInstanceAs (NormedAddCommGroup ↥(closedFreeVectorLattice E).toSubmodule)

instance instAddCommGroupFBL : AddCommGroup (FBL E) :=
  NormedAddCommGroup.toAddCommGroup (E := FBL E)
    (self := instNormedAddCommGroupFBL (E := E))

instance instNormedSpaceFBL :
    @NormedSpace ℝ (FBL E) _
      (instNormedAddCommGroupFBL (E := E)).toSeminormedAddCommGroup := by
  exact inferInstanceAs (NormedSpace ℝ ↥(closedFreeVectorLattice E).toSubmodule)

instance instMaxFBL : Max (FBL E) := by
  exact inferInstanceAs (Max ↥(closedFreeVectorLattice E).toSubmodule)

instance instMinFBL : Min (FBL E) := by
  exact inferInstanceAs (Min ↥(closedFreeVectorLattice E).toSubmodule)

instance instLEFBL : LE (FBL E) := by
  exact inferInstanceAs (LE ↥(closedFreeVectorLattice E).toSubmodule)

instance instLatticeFBL : Lattice (FBL E) := by
  exact inferInstanceAs (Lattice ↥(closedFreeVectorLattice E).toSubmodule)

instance instIsOrderedAddMonoidFBL :
    @IsOrderedAddMonoid (FBL E)
      (AddCommGroup.toAddCommMonoid (G := FBL E)
        (self := instAddCommGroupFBL (E := E)))
      (instLatticeFBL (E := E)).toPartialOrder.toPreorder := by
  exact inferInstanceAs (IsOrderedAddMonoid ↥(closedFreeVectorLattice E).toSubmodule)

instance instVectorLatticeFBL :
    @VectorLattice (FBL E) (instAddCommGroupFBL (E := E)) (instLatticeFBL (E := E))
      (instIsOrderedAddMonoidFBL (E := E)) where
  toModule :=
    NormedSpace.toModule (𝕜 := ℝ) (E := FBL E) (self := instNormedSpaceFBL (E := E))
  smul_le_smul_of_nonneg_left := by
    intro c hc f g hfg
    change c • (f : FunctionSpace E) ≤ c • (g : FunctionSpace E)
    exact smul_le_smul_of_nonneg_left hfg hc

instance instNormedVectorLatticeFBL :
    @NormedVectorLattice (FBL E) (instNormedAddCommGroupFBL (E := E))
      (instLatticeFBL (E := E)) (instIsOrderedAddMonoidFBL (E := E)) where
  toVectorLattice := instVectorLatticeFBL (E := E)
  solid := by
    intro f g hfg
    change ‖(f : FunctionSpace E)‖ ≤ ‖(g : FunctionSpace E)‖
    exact HasSolidNorm.solid hfg
  norm_smul := by
    intro c f
    change ‖c • (f : FunctionSpace E)‖ = ‖c‖ * ‖(f : FunctionSpace E)‖
    exact norm_smul c (f : FunctionSpace E)

instance instBanachLatticeFBL :
    @BanachLattice (FBL E) (instNormedAddCommGroupFBL (E := E))
      (instLatticeFBL (E := E)) (instIsOrderedAddMonoidFBL (E := E)) := by
  exact VectorSublattice.banachLatticeSubtype (Y := closedFreeVectorLattice E) (by
    rw [coe_closedFreeVectorLattice]
    exact isClosed_closure)

/-- The canonical embedding of `E` into its free Banach lattice. -/
def of (x : E) : FBL E :=
  ⟨dualEval E x, by
    change dualEval E x ∈ (closedFreeVectorLattice E : Set (FunctionSpace E))
    rw [coe_closedFreeVectorLattice]
    exact subset_closure (VectorSublattice.subset_generated _ ⟨x, rfl⟩)⟩

@[simp]
theorem of_apply (x : E) (φ : FVLv.dualUnitBall E) :
    (of x : FBL E) φ = (φ : WeakDual ℝ E) x := by
  rfl

/-- The canonical map `E → FBL E`, bundled as a real-linear map. -/
def ofLinear : E →ₗ[ℝ] FBL E := by
  refine
    { toFun := of
      map_add' := ?_
      map_smul' := ?_ }
  · intro x y
    apply Subtype.ext
    apply Subtype.ext
    ext φ
    exact (φ : WeakDual ℝ E).map_add x y
  · intro r x
    apply Subtype.ext
    apply Subtype.ext
    ext φ
    exact (φ : WeakDual ℝ E).map_smul r x

@[simp]
theorem ofLinear_apply (x : E) : ofLinear x = of x := by
  rfl

/-- The canonical map from `E` to `FBL E` preserves norms. -/
theorem norm_of (x : E) : ‖of x‖ = ‖x‖ := by
  refine le_antisymm ?_ ?_
  · change (freeNormExt E (FVLv.dualEval E x)).toReal ≤ ‖x‖
    simpa using ENNReal.toReal_mono ENNReal.ofReal_ne_top (freeNormExt_dualEval_le E x)
  · obtain ⟨φ, hφnorm, hφx⟩ := exists_dual_vector'' ℝ x
    let ψ : FVLv.dualUnitBall E := ⟨StrongDual.toWeakDual φ, by
      dsimp [FVLv.dualUnitBall]
      simpa [Metric.mem_closedBall, dist_eq_norm] using hφnorm⟩
    have hle :=
      sum_abs_apply_le_freeNorm E (of x : FBL E) (fun _ : Fin 1 => ψ)
        (normAdmissible_singleton E ψ)
    simpa [Fin.sum_univ_one, ψ, hφx, Real.norm_eq_abs] using hle

/-- The canonical map from `E` to `FBL E` is an isometric embedding. -/
def ofLinearIsometry : E →ₗᵢ[ℝ] FBL E := by
  exact
    { toLinearMap := ofLinear
      norm_map' := norm_of }

@[simp]
theorem ofLinearIsometry_apply (x : E) : ofLinearIsometry x = of x := by
  rfl

/-- The canonical map from `E` to `FBL E` is injective. -/
theorem of_injective : Function.Injective (of : E → FBL E) := by
  exact ofLinearIsometry.injective

private def subtypeHom {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (Y : VectorSublattice X) :
    VecLatHom ↥Y.toSubmodule X where
  toFun y := y
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

private theorem eval_coe_submodule {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (Y : VectorSublattice X)
    (y : Fin n → ↥Y.toSubmodule) (e : LLexpr n) :
    ((LLexpr.eval y e : ↥Y.toSubmodule) : X) =
      LLexpr.eval (fun i => (y i : X)) e := by
  simpa using (LLexpr.map_eval (subtypeHom Y) y e)

/-- The copy of the concrete free vector lattice from `FVLv.lean` inside `FBL E`. -/
def ofFVLv : FVLv E →ₗ[ℝ] FBL E := by
  exact (FVLv.lift (ofLinear (E := E))).toLinearMap

@[simp]
theorem ofFVLv_of (x : E) : ofFVLv (FVLv.of x) = of x := by
  change FVLv.lift (ofLinear (E := E)) (FVLv.of x) = of x
  exact FVLv.lift_of (T := ofLinear (E := E)) x

/-- The image of the concrete free vector lattice is dense in `FBL E`. -/
theorem denseRange_ofFVLv : DenseRange (ofFVLv (E := E)) := by
  let hst : (freeVectorLattice E : Set (FunctionSpace E)) ⊆
      (closedFreeVectorLattice E : Set (FunctionSpace E)) := by
    intro f hf
    rw [coe_closedFreeVectorLattice]
    exact subset_closure hf
  let ι : ↥(freeVectorLattice E).toSubmodule → FBL E := Set.inclusion hst
  have hι_dense : DenseRange ι := by
    change DenseRange (Set.inclusion hst)
    exact (denseRange_inclusion_iff hst).2 (by
      rw [coe_closedFreeVectorLattice])
  have hι_range : Set.range ι ⊆ Set.range (ofFVLv (E := E)) := by
    intro z hz
    rcases hz with ⟨y, rfl⟩
    have hy : (y : FunctionSpace E) ∈
        VectorSublattice.generated (Set.range (dualEval E : E → FunctionSpace E)) := by
      simp only [freeVectorLattice] at y
      exact y.2
    change (y : FunctionSpace E) ∈
        (VectorSublattice.generated (Set.range (dualEval E : E → FunctionSpace E)) :
          Set (FunctionSpace E)) at hy
    rw [LLexpr.generated_eq_iUnion_combinations
      (Set.range (dualEval E : E → FunctionSpace E))] at hy
    simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range] at hy
    obtain ⟨n, z, e, hz⟩ := hy
    choose x hx using fun i : Fin n => (z i).2
    refine ⟨LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e, ?_⟩
    apply Subtype.ext
    have hmap :
        ofFVLv (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) =
          LLexpr.eval (fun i : Fin n => of (x i)) e := by
      simpa [ofFVLv] using
        LLexpr.map_eval (FVLv.lift (ofLinear (E := E)))
          (fun i : Fin n => FVLv.of (x i)) e
    calc
      ((ofFVLv (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) : FBL E) : FunctionSpace E)
          = ((LLexpr.eval (fun i : Fin n => of (x i)) e : FBL E) : FunctionSpace E) := by
            rw [hmap]
      _ = LLexpr.eval (fun i : Fin n => dualEval E (x i)) e := by
            simpa using
              (eval_coe_submodule (closedFreeVectorLattice E)
                (fun i : Fin n => of (x i)) e)
      _ = LLexpr.eval (fun i : Fin n => (z i : FunctionSpace E)) e := by
            congr
            funext i
            rw [hx i]
      _ = (y : FunctionSpace E) := by
            simpa using hz
  apply denseRange_iff_closure_range.mpr
  ext z
  constructor
  · intro _; trivial
  · intro _
    have hz : z ∈ closure (Set.range ι) := by
      rw [hι_dense.closure_range]
      trivial
    exact closure_mono hι_range hz

section UniversalProperty

variable {X : Type v} [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [BanachLattice X]

private noncomputable def finiteSup {ι Y : Type*} [Fintype ι] [Nonempty ι]
    [Lattice Y] (y : ι → Y) : Y :=
  Finset.univ.sup' Finset.univ_nonempty y

private noncomputable def linCombEval {n : ℕ} {Y : Type*} [AddCommGroup Y] [Module ℝ Y]
    (a : Fin n → ℝ) (y : Fin n → Y) : Y :=
  Fintype.linearCombination ℝ y a

private theorem finiteSup_subtype_eq {n : ℕ} {Y : Type*} [AddCommGroup Y] [Lattice Y]
    [IsOrderedAddMonoid Y] [VectorLattice Y] (A : LLexpr.SupLinearCombination n)
    [Nonempty {p // p ∈ A.coeffs}] (y : Fin n → Y) :
    finiteSup (fun a : {p // p ∈ A.coeffs} => linCombEval a.1 y) = A.eval y := by
  let emb : {p // p ∈ A.coeffs} ↪ (Fin n → ℝ) :=
    ⟨Subtype.val, fun _ _ h => Subtype.ext h⟩
  have huniv : (Finset.univ : Finset {p // p ∈ A.coeffs}) = A.coeffs.attach := by
    ext a
    simp
  have hsattach : A.coeffs.attach.Nonempty := by
    rcases A.nonempty with ⟨p, hp⟩
    exact ⟨⟨p, hp⟩, by simp⟩
  have hmap : A.coeffs.attach.map emb = A.coeffs := by
    ext a
    simp [emb]
  have hsmap : (A.coeffs.attach.map emb).Nonempty := by
    simpa [hmap] using A.nonempty
  calc
    finiteSup (fun a : {p // p ∈ A.coeffs} => linCombEval a.1 y)
        = A.coeffs.attach.sup' hsattach (fun a => linCombEval a.1 y) := by
          simp [finiteSup, huniv]
    _ = (A.coeffs.attach.map emb).sup' hsmap
          (fun a => linCombEval a y) := by
            exact
              (Finset.sup'_map (s := A.coeffs.attach) (f := emb)
                (g := fun a => linCombEval a y) (hs := hsmap)).symm
    _ = A.eval y := by
          simp [LLexpr.SupLinearCombination.eval, linCombEval, hmap]

private theorem finiteSup_comp_equiv {ι κ Y : Type*} [Fintype ι] [Nonempty ι] [Fintype κ]
    [Nonempty κ] [Lattice Y] (e : ι ≃ κ) (f : κ → Y) :
    finiteSup (fun i : ι => f (e i)) = finiteSup f := by
  refine le_antisymm ?_ ?_
  · unfold finiteSup
    rw [Finset.sup'_le_iff]
    intro i hi
    exact Finset.le_sup' (f := f) (Finset.mem_univ _)
  · unfold finiteSup
    rw [Finset.sup'_le_iff]
    intro j hj
    simpa using
      (Finset.le_sup' (f := fun i : ι => f (e i)) (Finset.mem_univ (e.symm j)))

private theorem supLinearCombination_exists_tuple {n : ℕ} (A : LLexpr.SupLinearCombination n) :
    ∃ m : ℕ, ∃ a : Fin (m + 1) → Fin n → ℝ,
      ∀ {Y : Type*} [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]
        (y : Fin n → Y),
        finiteSup (fun i : Fin (m + 1) => linCombEval (a i) y) = A.eval y := by
  let I : Type := {p // p ∈ A.coeffs}
  let e : I ≃ Fin (Fintype.card I) := Fintype.equivFin I
  have hI : Nonempty I := by
    rcases A.nonempty with ⟨p, hp⟩
    exact ⟨⟨p, hp⟩⟩
  let m := Fintype.card I - 1
  have hm : m + 1 = Fintype.card I := by
    dsimp [m]
    exact Nat.succ_pred_eq_of_pos (Fintype.card_pos_iff.mpr hI)
  let a : Fin (m + 1) → Fin n → ℝ := fun i => ((e.symm (finCongr hm i)).1)
  refine ⟨m, a, ?_⟩
  intro Y _ _ _ _ y
  letI : Nonempty I := hI
  have h₁ :
      finiteSup (fun i : Fin (m + 1) => linCombEval (a i) y) =
        finiteSup (fun i : Fin (Fintype.card I) => linCombEval ((e.symm i).1) y) := by
    simpa [a] using
      (finiteSup_comp_equiv (finCongr hm)
        (fun i : Fin (Fintype.card I) => linCombEval ((e.symm i).1) y))
  have h₂ :
      finiteSup (fun i : Fin (Fintype.card I) => linCombEval ((e.symm i).1) y) =
        finiteSup (fun i : I => linCombEval i.1 y) := by
    exact finiteSup_comp_equiv e.symm (fun i : I => linCombEval i.1 y)
  calc
    finiteSup (fun i : Fin (m + 1) => linCombEval (a i) y)
        = finiteSup (fun i : Fin (Fintype.card I) => linCombEval ((e.symm i).1) y) := h₁
    _ = finiteSup (fun i : I => linCombEval i.1 y) := h₂
    _ = A.eval y := finiteSup_subtype_eq A y

private theorem finiteSup_map_vecLatHom {ι Y Z : Type*} [Fintype ι] [Nonempty ι]
    [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]
    [AddCommGroup Z] [Lattice Z] [IsOrderedAddMonoid Z] [VectorLattice Z]
    (S : VecLatHom Y Z) (y : ι → Y) :
    S (finiteSup y) = finiteSup (fun i => S (y i)) := by
  unfold finiteSup
  change S.toLatticeHom (Finset.univ.sup' Finset.univ_nonempty y) =
    Finset.univ.sup' Finset.univ_nonempty (S.toLatticeHom ∘ y)
  exact map_finset_sup' S.toLatticeHom Finset.univ_nonempty y

/-- The algebraic vector-lattice extension of `T` to the dense copy of `FVLv E`. -/
private noncomputable def liftFVLv (T : E →L[ℝ] X) : VecLatHom (FVLv E) X :=
  FVLv.lift T.toLinearMap

private theorem liftFVLv_of (T : E →L[ℝ] X) (x : E) :
    liftFVLv T (FVLv.of x) = T x := by
  unfold liftFVLv
  exact FVLv.lift_of (T := T.toLinearMap) x

private noncomputable def fvlvLinearCombination {n : ℕ}
    (x : Fin n → E) (a : Fin n → ℝ) : FVLv E :=
  ∑ i, a i • FVLv.of (x i)

private noncomputable def imageLinearCombination {n : ℕ}
    (T : E →L[ℝ] X) (x : Fin n → E) (a : Fin n → ℝ) : X :=
  ∑ i, a i • T (x i)

private noncomputable def dualLinearCombination {n : ℕ}
    (x : Fin n → E) (a : Fin n → ℝ) (φ : FVLv.dualUnitBall E) : ℝ :=
  ∑ i, a i * (φ : WeakDual ℝ E) (x i)

private theorem liftFVLv_linearCombination {n : ℕ} (T : E →L[ℝ] X)
    (x : Fin n → E) (a : Fin n → ℝ) :
    liftFVLv T (fvlvLinearCombination x a) = imageLinearCombination T x a := by
  simp [liftFVLv, fvlvLinearCombination, imageLinearCombination]

private theorem liftFVLv_supSubLinearCombination {m p n : ℕ} (T : E →L[ℝ] X)
    (x : Fin n → E) (a : Fin (m + 1) → Fin n → ℝ)
    (b : Fin (p + 1) → Fin n → ℝ) :
    liftFVLv T
        (finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
          finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j))) =
      finiteSup (fun i : Fin (m + 1) => imageLinearCombination T x (a i)) -
        finiteSup (fun j : Fin (p + 1) => imageLinearCombination T x (b j)) := by
  rw [map_sub, finiteSup_map_vecLatHom, finiteSup_map_vecLatHom]
  simp [liftFVLv_linearCombination]

private theorem ofFVLv_linearCombination_apply {n : ℕ}
    (x : Fin n → E) (a : Fin n → ℝ) (φ : FVLv.dualUnitBall E) :
    (ofFVLv (fvlvLinearCombination x a) : FBL E) φ =
      dualLinearCombination x a φ := by
  let ev : FBL E →ₗ[ℝ] ℝ :=
    { toFun := fun f => f φ
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
  change ev (ofFVLv (fvlvLinearCombination x a)) = dualLinearCombination x a φ
  change
      ev
        (liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap)
        (fvlvLinearCombination x a) : FBL E) =
    dualLinearCombination x a φ
  rw [liftFVLv_linearCombination]
  simp [ev, imageLinearCombination, dualLinearCombination, ofLinearIsometry_apply, of_apply,
    smul_eq_mul]

private def evalAtFBL (φ : FVLv.dualUnitBall E) : VecLatHom (FBL E) ℝ where
  toFun f := f φ
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

private theorem ofFVLv_supSubLinearCombination_apply {m p n : ℕ}
    (x : Fin n → E) (a : Fin (m + 1) → Fin n → ℝ)
    (b : Fin (p + 1) → Fin n → ℝ) (φ : FVLv.dualUnitBall E) :
    (ofFVLv
        (finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
          finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j))) :
        FBL E) φ =
      finiteSup (fun i : Fin (m + 1) => dualLinearCombination x (a i) φ) -
        finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) φ) := by
  let S := evalAtFBL (E := E) φ
  unfold ofFVLv
  change S
      ((FVLv.lift (ofLinear (E := E)))
        (finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
          finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j)))) =
    finiteSup (fun i : Fin (m + 1) => dualLinearCombination x (a i) φ) -
      finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) φ)
  rw [map_sub]
  rw [map_sub]
  rw [finiteSup_map_vecLatHom, finiteSup_map_vecLatHom]
  rw [finiteSup_map_vecLatHom, finiteSup_map_vecLatHom]
  have hA :
      (fun i : Fin (m + 1) =>
        S ((FVLv.lift (ofLinear (E := E))) (fvlvLinearCombination x (a i)))) =
        fun i : Fin (m + 1) => dualLinearCombination x (a i) φ := by
    funext i
    simpa [S, ofFVLv] using ofFVLv_linearCombination_apply (x := x) (a := a i) φ
  have hB :
      (fun j : Fin (p + 1) =>
        S ((FVLv.lift (ofLinear (E := E))) (fvlvLinearCombination x (b j)))) =
        fun j : Fin (p + 1) => dualLinearCombination x (b j) φ := by
    funext j
    simpa [S, ofFVLv] using ofFVLv_linearCombination_apply (x := x) (a := b j) φ
  rw [hA, hB]

private theorem exists_supSubLinearCombination_eval {n : ℕ} (e : LLexpr n) :
    ∃ (m p : ℕ) (a : Fin (m + 1) → Fin n → ℝ) (b : Fin (p + 1) → Fin n → ℝ),
      ∀ {Y : Type*} [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y] [VectorLattice Y]
        (y : Fin n → Y),
        LLexpr.eval y e =
          finiteSup (fun i : Fin (m + 1) => linCombEval (a i) y) -
            finiteSup (fun j : Fin (p + 1) => linCombEval (b j) y) := by
  let N := LLexpr.normalize e
  obtain ⟨m, a, ha⟩ := supLinearCombination_exists_tuple N.pos
  obtain ⟨p, b, hb⟩ := supLinearCombination_exists_tuple N.neg
  refine ⟨m, p, a, b, ?_⟩
  intro Y _ _ _ _ y
  calc
    LLexpr.eval y e = N.eval y := by
      exact (LLexpr.normalize_eval y e).symm
    _ = finiteSup (fun i : Fin (m + 1) => linCombEval (a i) y) -
        finiteSup (fun j : Fin (p + 1) => linCombEval (b j) y) := by
          rw [LLexpr.NormalForm.eval, ← ha y, ← hb y]

private theorem exists_eval_of_eq_FVLv (f : FVLv E) :
    ∃ (n : ℕ) (x : Fin n → E) (e : LLexpr n),
      LLexpr.eval (fun i => FVLv.of (x i)) e = f := by
  classical
  have hf : (f : C(FVLv.dualUnitBall E, ℝ)) ∈
      (VectorSublattice.generated
        (Set.range (FVLv.dualEval E : E → C(FVLv.dualUnitBall E, ℝ))) :
          Set C(FVLv.dualUnitBall E, ℝ)) := f.2
  rw [LLexpr.generated_eq_iUnion_combinations
    (Set.range (FVLv.dualEval E : E → C(FVLv.dualUnitBall E, ℝ)))] at hf
  simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range] at hf
  obtain ⟨n, z, e, hz⟩ := hf
  choose x hx using fun i : Fin n => (z i).2
  refine ⟨n, x, e, ?_⟩
  apply Subtype.ext
  calc
    ((LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e : FVLv E) :
        C(FVLv.dualUnitBall E, ℝ))
        = LLexpr.eval (fun i : Fin n => FVLv.dualEval E (x i)) e := by
          exact eval_coe_submodule (FVLv.concreteSublattice E) (fun i : Fin n => FVLv.of (x i)) e
    _ = LLexpr.eval (fun i : Fin n => (z i : C(FVLv.dualUnitBall E, ℝ))) e := by
          congr
          funext i
          rw [hx i]
    _ = f := hz

private theorem exists_supSubLinearCombination_eq (f : FVLv E) :
    ∃ (n m p : ℕ) (x : Fin n → E) (a : Fin (m + 1) → Fin n → ℝ)
      (b : Fin (p + 1) → Fin n → ℝ),
        f =
          finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
            finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j)) := by
  obtain ⟨n, x, e, he⟩ := exists_eval_of_eq_FVLv (E := E) f
  obtain ⟨m, p, a, b, hab⟩ := exists_supSubLinearCombination_eval e
  refine ⟨n, m, p, x, a, b, ?_⟩
  calc
    f = LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e := by
      symm
      exact he
    _ = finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
          finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j)) := by
            simpa [fvlvLinearCombination, linCombEval] using
              (hab (fun i : Fin n => FVLv.of (x i)))

private theorem ofFVLv_apply (f : FVLv E) (φ : FVLv.dualUnitBall E) :
    (ofFVLv f : FBL E) φ = f φ := by
  obtain ⟨n, x, e, hf⟩ := exists_eval_of_eq_FVLv (E := E) f
  rw [← hf]
  let S : VecLatHom (FVLv E) ℝ :=
    { toFun := fun g => g φ
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl
      map_sup' := fun _ _ => rfl
      map_inf' := fun _ _ => rfl }
  have hmap :
      ofFVLv (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) =
        LLexpr.eval (fun i : Fin n => of (x i)) e := by
    simpa [ofFVLv] using
      LLexpr.map_eval (FVLv.lift (ofLinear (E := E)))
        (fun i : Fin n => FVLv.of (x i)) e
  have hFVLv :
      S (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) =
        LLexpr.eval (fun i : Fin n => (φ : WeakDual ℝ E) (x i)) e := by
    simpa [S, FVLv.of_apply] using
      LLexpr.map_eval S (fun i : Fin n => FVLv.of (x i)) e
  have hFBL :
      evalAtFBL φ (LLexpr.eval (fun i : Fin n => of (x i)) e) =
        LLexpr.eval (fun i : Fin n => (φ : WeakDual ℝ E) (x i)) e := by
    simpa [evalAtFBL, of_apply] using
      LLexpr.map_eval (evalAtFBL φ) (fun i : Fin n => of (x i)) e
  calc
    (ofFVLv (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) : FBL E) φ
        = (LLexpr.eval (fun i : Fin n => of (x i)) e : FBL E) φ := by
            rw [hmap]
    _ = evalAtFBL φ (LLexpr.eval (fun i : Fin n => of (x i)) e) := rfl
    _ = LLexpr.eval (fun i : Fin n => (φ : WeakDual ℝ E) (x i)) e := hFBL
    _ = S (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e) := by
          symm
          exact hFVLv
    _ = (LLexpr.eval (fun i : Fin n => FVLv.of (x i)) e : FVLv E) φ := rfl

private theorem isLUB_strongDual_apply_finiteSup {ι : Type*} [Fintype ι] [Nonempty ι]
    {ψ : StrongDual ℝ X} (hψ : 0 ≤ ψ) (y : ι → X) :
    IsLUB
      {r : ℝ | ∃ ψi : ι → StrongDual ℝ X,
        (∀ i, 0 ≤ ψi i) ∧ (∑ i, ψi i) = ψ ∧ r = ∑ i, ψi i (y i)}
      (ψ (finiteSup y)) := by
  classical
  let S₁ : Set ℝ :=
    {r : ℝ | ∃ ψi : ι → StrongDual ℝ X,
      (∀ i, 0 ≤ ψi i) ∧ (∑ i, ψi i) = ψ ∧ r = ∑ i, ψi i (y i)}
  let S₂ : Set ℝ :=
    {r : ℝ | ∃ φi : ι → OrderDualSpace X,
      (∀ i, 0 ≤ φi i) ∧ (∑ i, φi i) = StrongDual.toOrderDualSpace ψ ∧
        r = ∑ i, φi i (y i)}
  have hS : S₁ = S₂ := by
    ext r
    constructor
    · rintro ⟨ψi, hψi0, hsum, hr⟩
      refine ⟨fun i => StrongDual.toOrderDualSpace (ψi i), ?_, ?_, ?_⟩
      · intro i
        simpa using hψi0 i
      · calc
          ∑ i, StrongDual.toOrderDualSpace (ψi i) =
              StrongDual.toOrderDualSpaceLinear (∑ i, ψi i) := by
                simp [StrongDual.toOrderDualSpaceLinear]
          _ = StrongDual.toOrderDualSpace ψ := by rw [hsum]; rfl
      · simpa [StrongDual.toOrderDualSpace_apply] using hr
    · rintro ⟨φi, hφi0, hsum, hr⟩
      refine ⟨fun i => StrongDual.ofOrderDualSpace (φi i), ?_, ?_, ?_⟩
      · intro i
        change StrongDual.toOrderDualSpace (0 : StrongDual ℝ X) ≤
          StrongDual.toOrderDualSpace (StrongDual.ofOrderDualSpace (φi i))
        simpa using hφi0 i
      · calc
          ∑ i, StrongDual.ofOrderDualSpace (φi i) =
              StrongDual.equivOrderDualSpace.symm (∑ i, φi i) := by
                simp [StrongDual.equivOrderDualSpace]
          _ = ψ := by
                rw [hsum]
                ext x
                rfl
      · simpa [StrongDual.ofOrderDualSpace_apply] using hr
  have hOD : 0 ≤ StrongDual.toOrderDualSpace ψ := by
    simpa using hψ
  have hLUB :
      IsLUB S₂ ((StrongDual.toOrderDualSpace ψ) (finiteSup y)) := by
    simpa [S₂, finiteSup] using
      (OrderBoundedHom.isLUB_apply_finset_sup (s := Finset.univ) (hs := Finset.univ_nonempty)
        (f := StrongDual.toOrderDualSpace ψ) hOD y)
  simpa [S₁, hS, StrongDual.toOrderDualSpace_apply] using hLUB

private theorem strongDual_component_le_of_sum {ι : Type*} [Fintype ι]
    {ψi : ι → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (i : ι) :
    ψi i ≤ ψ := by
  refine (StrongDual.le_iff).2 ?_
  intro z hz
  have hsumz : ∑ j, ψi j z = ψ z := by
    simpa using congrArg (fun F : StrongDual ℝ X => F z) hsum
  exact hsumz ▸ Finset.single_le_sum
    (fun j _ => (StrongDual.nonneg_iff.mp (hψi0 j)) z hz) (Finset.mem_univ i)

private theorem strongDual_norm_le_of_nonneg_le {φ ψ : StrongDual ℝ X}
    (hφ0 : 0 ≤ φ) (hψ0 : 0 ≤ ψ) (hφψ : φ ≤ ψ) :
    ‖φ‖ ≤ ‖ψ‖ := by
  exact HasSolidNorm.solid
    (by simpa [abs_of_nonneg hφ0, abs_of_nonneg hψ0] using hφψ)

private noncomputable def scaledCompWeakDualFamily {ι : Type*}
    (T : E →L[ℝ] X) (ψi : ι → StrongDual ℝ X) : ι → WeakDual ℝ E :=
  fun i => StrongDual.toWeakDual (‖T‖⁻¹ • (ψi i).comp T)

private theorem scaledCompWeakDualFamily_mem_dualUnitBall {ι : Type*} [Fintype ι]
    (T : E →L[ℝ] X) {ψi : ι → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (hψ0 : 0 ≤ ψ)
    (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) (i : ι) :
    scaledCompWeakDualFamily T ψi i ∈ FVLv.dualUnitBall E := by
  have hψi_le : ψi i ≤ ψ := strongDual_component_le_of_sum hψi0 hsum i
  have hψi_norm : ‖ψi i‖ ≤ ‖ψ‖ := strongDual_norm_le_of_nonneg_le (hψi0 i) hψ0 hψi_le
  have hnorm : ‖‖T‖⁻¹ • (ψi i).comp T‖ ≤ 1 := by
    calc
      ‖‖T‖⁻¹ • (ψi i).comp T‖ = ‖T‖⁻¹ * ‖(ψi i).comp T‖ := by
            rw [norm_smul, Real.norm_of_nonneg (inv_nonneg.mpr hT.le)]
      _ ≤ ‖T‖⁻¹ * (‖ψi i‖ * ‖T‖) := by
            gcongr
            exact ContinuousLinearMap.opNorm_comp_le (ψi i) T
      _ ≤ ‖T‖⁻¹ * (‖ψ‖ * ‖T‖) := by
            gcongr
      _ ≤ ‖T‖⁻¹ * (1 * ‖T‖) := by
            gcongr
      _ = 1 := by
            rw [one_mul, inv_mul_cancel₀ hT.ne']
  dsimp [scaledCompWeakDualFamily, FVLv.dualUnitBall]
  simpa [Metric.mem_closedBall, dist_eq_norm] using hnorm

private noncomputable def scaledCompDualFamily {ι : Type*} [Fintype ι]
    (T : E →L[ℝ] X) {ψi : ι → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (hψ0 : 0 ≤ ψ)
    (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) : ι → FVLv.dualUnitBall E :=
  fun i =>
    ⟨scaledCompWeakDualFamily T ψi i,
      scaledCompWeakDualFamily_mem_dualUnitBall T hψi0 hsum hψ0 hψnorm hT i⟩

private theorem scaledCompDualFamily_admissible {n : ℕ}
    (T : E →L[ℝ] X) {ψi : Fin n → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (hψ0 : 0 ≤ ψ)
    (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) :
    NormAdmissible E
      (scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT) := by
  let Φ : Fin n → FVLv.dualUnitBall E :=
    scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT
  intro z hz
  calc
    ∑ i, |((Φ i : FVLv.dualUnitBall E) : WeakDual ℝ E) z|
        = ∑ i, ‖T‖⁻¹ * |ψi i (T z)| := by
            apply Finset.sum_congr rfl
            intro i hi
            change |(‖T‖⁻¹ * ψi i (T z))| = ‖T‖⁻¹ * |ψi i (T z)|
            simp [abs_mul, abs_of_nonneg (inv_nonneg.mpr hT.le)]
    _ = ‖T‖⁻¹ * ∑ i, |ψi i (T z)| := by
          rw [Finset.mul_sum]
    _ ≤ ‖T‖⁻¹ * ∑ i, ψi i (|T z|) := by
          refine mul_le_mul_of_nonneg_left ?_ (inv_nonneg.mpr hT.le)
          exact Finset.sum_le_sum fun i _ => StrongDual.abs_apply_le_apply_abs (hψi0 i) (T z)
    _ = ‖T‖⁻¹ * ψ (|T z|) := by
          congr 1
          simpa using congrArg (fun F : StrongDual ℝ X => F (|T z|)) hsum
    _ ≤ ‖T‖⁻¹ * ‖T‖ := by
          refine mul_le_mul_of_nonneg_left ?_ (inv_nonneg.mpr hT.le)
          have hψabs_nonneg : 0 ≤ ψ (|T z|) := (StrongDual.nonneg_iff.mp hψ0) _ (abs_nonneg _)
          calc
            ψ (|T z|) = ‖ψ (|T z|)‖ := by
              rw [Real.norm_eq_abs, abs_of_nonneg hψabs_nonneg]
            _ ≤ ‖ψ‖ * ‖|T z|‖ := ψ.le_opNorm (|T z|)
            _ = ‖ψ‖ * ‖T z‖ := by rw [norm_abs_eq_norm]
            _ ≤ 1 * ‖T z‖ := by
                  gcongr
            _ ≤ 1 * (‖T‖ * ‖z‖) := by
                  gcongr
                  exact ContinuousLinearMap.le_opNorm T z
            _ ≤ 1 * (‖T‖ * 1) := by
                  gcongr
            _ = ‖T‖ := by ring
    _ = 1 := by
          rw [inv_mul_cancel₀ hT.ne']

private theorem ofFVLv_apply_scaledCompDualFamily_nonneg {n : ℕ}
    (T : E →L[ℝ] X) {f : FVLv E} (hf : 0 ≤ f) {ψi : Fin n → StrongDual ℝ X}
    {ψ : StrongDual ℝ X} (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ)
    (hψ0 : 0 ≤ ψ) (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) (i : Fin n) :
    0 ≤ (ofFVLv f : FBL E)
      (scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT i) := by
  simpa [ofFVLv_apply] using
    (FVLv.le_def.mp hf
      (scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT i))

private theorem sum_ofFVLv_apply_scaledCompDualFamily_le {n : ℕ}
    (T : E →L[ℝ] X) {f : FVLv E} (hf : 0 ≤ f) {ψi : Fin n → StrongDual ℝ X}
    {ψ : StrongDual ℝ X} (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ)
    (hψ0 : 0 ≤ ψ) (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) :
    ∑ i,
        (ofFVLv f : FBL E)
          (scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT i) ≤
      ‖ofFVLv f‖ := by
  let Φ : Fin n → FVLv.dualUnitBall E :=
    scaledCompDualFamily (ι := Fin n) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT
  calc
    ∑ i, (ofFVLv f : FBL E) (Φ i) = ∑ i, |(ofFVLv f : FBL E) (Φ i)| := by
            apply Finset.sum_congr rfl
            intro i hi
            rw [abs_of_nonneg (ofFVLv_apply_scaledCompDualFamily_nonneg
              T hf hψi0 hsum hψ0 hψnorm hT i)]
    _ ≤ ‖ofFVLv f‖ := by
          exact sum_abs_apply_le_freeNorm E (ofFVLv f)
            Φ
            (scaledCompDualFamily_admissible T hψi0 hsum hψ0 hψnorm hT)

private theorem dualLinearCombination_scaledCompDualFamily_eq {ι : Type*} [Fintype ι]
    {κ : Type*} {n : ℕ} (T : E →L[ℝ] X) {ψi : ι → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (hψ0 : 0 ≤ ψ)
    (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) (x : Fin n → E) (c : κ → Fin n → ℝ)
    (i : ι) (k : κ) :
    dualLinearCombination x (c k)
        (scaledCompDualFamily (ι := ι) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT i) =
      ‖T‖⁻¹ * ψi i (imageLinearCombination T x (c k)) := by
  unfold dualLinearCombination imageLinearCombination
  calc
    ∑ j,
        c k j *
          (((scaledCompDualFamily (ι := ι) (ψi := ψi) (ψ := ψ) T hψi0 hsum hψ0 hψnorm hT i :
            FVLv.dualUnitBall E) :
            WeakDual ℝ E) (x j))
        = ∑ j, ‖T‖⁻¹ * (c k j * ψi i (T (x j))) := by
            apply Finset.sum_congr rfl
            intro j hj
            change c k j * (‖T‖⁻¹ * ψi i (T (x j))) = ‖T‖⁻¹ * (c k j * ψi i (T (x j)))
            ring
    _ = ‖T‖⁻¹ * ∑ j, c k j * ψi i (T (x j)) := by
          rw [Finset.mul_sum]
    _ = ‖T‖⁻¹ * ψi i (∑ j, c k j • T (x j)) := by
          congr 1
          rw [map_sum]
          apply Finset.sum_congr rfl
          intro j hj
          rw [map_smul]
          simp [smul_eq_mul]

private theorem dualLinearCombination_le_ofFVLv_add_finiteSup {n m p : ℕ}
    {f : FVLv E} (x : Fin n → E) (a : Fin (m + 1) → Fin n → ℝ)
    (b : Fin (p + 1) → Fin n → ℝ)
    (hf_repr :
      f = finiteSup (fun i : Fin (m + 1) => fvlvLinearCombination x (a i)) -
        finiteSup (fun j : Fin (p + 1) => fvlvLinearCombination x (b j)))
    (φ : FVLv.dualUnitBall E) (i : Fin (m + 1)) :
    dualLinearCombination x (a i) φ ≤
      (ofFVLv f : FBL E) φ +
        finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) φ) := by
  have hf_eval :
      (ofFVLv f : FBL E) φ =
        finiteSup (fun k : Fin (m + 1) => dualLinearCombination x (a k) φ) -
          finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) φ) := by
            simpa [hf_repr] using ofFVLv_supSubLinearCombination_apply
              (x := x) (a := a) (b := b) φ
  have hsup :
      dualLinearCombination x (a i) φ ≤
        finiteSup (fun k : Fin (m + 1) => dualLinearCombination x (a k) φ) := by
          unfold finiteSup
          exact Finset.le_sup' (s := Finset.univ)
            (f := fun k : Fin (m + 1) => dualLinearCombination x (a k) φ)
            (h := Finset.mem_univ i)
  linarith

private theorem finiteSup_dualLinearCombination_scaledCompDualFamily_le {ι : Type*}
    [Fintype ι] {n p : ℕ} (T : E →L[ℝ] X) {ψi : ι → StrongDual ℝ X}
    {ψ : StrongDual ℝ X} (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ)
    (hψ0 : 0 ≤ ψ) (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) (x : Fin n → E)
    (b : Fin (p + 1) → Fin n → ℝ) (i : ι) :
    finiteSup (fun j : Fin (p + 1) =>
      dualLinearCombination x (b j) (scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT i)) ≤
        ‖T‖⁻¹ * ψi i (finiteSup (fun j : Fin (p + 1) => imageLinearCombination T x (b j))) := by
  unfold finiteSup
  apply Finset.sup'_le Finset.univ_nonempty
  intro j hj
  calc
    dualLinearCombination x (b j) (scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT i)
        = ‖T‖⁻¹ * ψi i (imageLinearCombination T x (b j)) := by
            simpa using dualLinearCombination_scaledCompDualFamily_eq
              T hψi0 hsum hψ0 hψnorm hT x b i j
    _ ≤ ‖T‖⁻¹ * ψi i (finiteSup (fun j : Fin (p + 1) => imageLinearCombination T x (b j))) := by
          refine mul_le_mul_of_nonneg_left ?_ (inv_nonneg.mpr hT.le)
          exact StrongDual.apply_le_apply_of_nonneg (hψi0 i)
            (by
              unfold finiteSup
              exact Finset.le_sup' (s := Finset.univ)
                (f := fun j : Fin (p + 1) => imageLinearCombination T x (b j))
                (h := Finset.mem_univ j))

private theorem sum_apply_imageLinearCombination_eq_scaled_sum {ι : Type*} [Fintype ι]
    {n : ℕ} (T : E →L[ℝ] X) {ψi : ι → StrongDual ℝ X} {ψ : StrongDual ℝ X}
    (hψi0 : ∀ i, 0 ≤ ψi i) (hsum : ∑ i, ψi i = ψ) (hψ0 : 0 ≤ ψ)
    (hψnorm : ‖ψ‖ ≤ 1) (hT : 0 < ‖T‖) (x : Fin n → E) (c : ι → Fin n → ℝ) :
    ∑ i, ψi i (imageLinearCombination T x (c i)) =
      ‖T‖ * ∑ i,
        dualLinearCombination x (c i) (scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT i) := by
  calc
    ∑ i, ψi i (imageLinearCombination T x (c i))
        = ∑ i, ‖T‖ * dualLinearCombination x (c i)
            (scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT i) := by
              apply Finset.sum_congr rfl
              intro i hi
              rw [dualLinearCombination_scaledCompDualFamily_eq
                T hψi0 hsum hψ0 hψnorm hT x c i i]
              symm
              calc
                ‖T‖ * (‖T‖⁻¹ * ψi i (imageLinearCombination T x (c i)))
                    = (‖T‖ * ‖T‖⁻¹) * ψi i (imageLinearCombination T x (c i)) := by ring
                _ = ψi i (imageLinearCombination T x (c i)) := by
                      rw [mul_inv_cancel₀ hT.ne', one_mul]
    _ = ‖T‖ * ∑ i,
          dualLinearCombination x (c i) (scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT i) := by
            rw [Finset.mul_sum]

private theorem positive_dual_apply_liftFVLv_nonneg_le (T : E →L[ℝ] X)
    {f : FVLv E} (hf : 0 ≤ f) {ψ : StrongDual ℝ X}
    (hψ0 : 0 ≤ ψ) (hψnorm : ‖ψ‖ ≤ 1) :
    ψ (liftFVLv T f) ≤ ‖T‖ * ‖ofFVLv f‖ := by
  classical
  by_cases hT0 : ‖T‖ = 0
  · have hT : T = 0 := norm_eq_zero.mp hT0
    subst hT
    obtain ⟨n, m, p, x, a, b, hf_repr⟩ := exists_supSubLinearCombination_eq (E := E) f
    rw [hf_repr, liftFVLv_supSubLinearCombination]
    simp [finiteSup, imageLinearCombination]
  · have hT : 0 < ‖T‖ := lt_of_le_of_ne (norm_nonneg T) (by simpa [eq_comm] using hT0)
    obtain ⟨n, m, p, x, a, b, hf_repr⟩ := exists_supSubLinearCombination_eq (E := E) f
    let A : Fin (m + 1) → X := fun i => imageLinearCombination T x (a i)
    let B : Fin (p + 1) → X := fun j => imageLinearCombination T x (b j)
    have hA :
        ψ (finiteSup A) ≤ ‖T‖ * ‖ofFVLv f‖ + ψ (finiteSup B) := by
      refine (isLUB_strongDual_apply_finiteSup (ψ := ψ) hψ0 A).2 ?_
      rintro r ⟨ψi, hψi0, hsum, rfl⟩
      let Φ : Fin (m + 1) → FVLv.dualUnitBall E :=
        scaledCompDualFamily T hψi0 hsum hψ0 hψnorm hT
      calc
        ∑ i, ψi i (A i) = ‖T‖ * ∑ i, dualLinearCombination x (a i) (Φ i) := by
              simpa [A, Φ] using
                sum_apply_imageLinearCombination_eq_scaled_sum
                  T hψi0 hsum hψ0 hψnorm hT x a
        _ ≤ ‖T‖ * ∑ i,
              ((ofFVLv f : FBL E) (Φ i) +
                finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) (Φ i))) := by
                  refine mul_le_mul_of_nonneg_left ?_ (norm_nonneg T)
                  exact Finset.sum_le_sum fun i _ => by
                    simpa [Φ] using dualLinearCombination_le_ofFVLv_add_finiteSup
                      (f := f) x a b hf_repr (Φ i) i
        _ = ‖T‖ * (∑ i, (ofFVLv f : FBL E) (Φ i)) +
              ‖T‖ *
                (∑ i, finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) (Φ i))) := by
                rw [Finset.sum_add_distrib, mul_add, Finset.mul_sum, Finset.mul_sum]
        _ ≤ ‖T‖ * ‖ofFVLv f‖ +
              ‖T‖ *
                (∑ i, finiteSup (fun j : Fin (p + 1) => dualLinearCombination x (b j) (Φ i))) := by
                refine add_le_add ?_ le_rfl
                exact mul_le_mul_of_nonneg_left
                  (by
                    simpa [Φ] using sum_ofFVLv_apply_scaledCompDualFamily_le
                      T hf hψi0 hsum hψ0 hψnorm hT)
                  (norm_nonneg T)
        _ ≤ ‖T‖ * ‖ofFVLv f‖ + ‖T‖ * (∑ i, ‖T‖⁻¹ * ψi i (finiteSup B)) := by
              refine add_le_add le_rfl ?_
              refine mul_le_mul_of_nonneg_left ?_ (norm_nonneg T)
              exact Finset.sum_le_sum fun i _ => by
                simpa [B, Φ] using
                  finiteSup_dualLinearCombination_scaledCompDualFamily_le
                    T hψi0 hsum hψ0 hψnorm hT x b i
        _ = ‖T‖ * ‖ofFVLv f‖ + ψ (finiteSup B) := by
              congr 1
              calc
                ‖T‖ * ∑ i, (‖T‖⁻¹ * ψi i (finiteSup B))
                    = ∑ i, ψi i (finiteSup B) := by
                        rw [Finset.mul_sum]
                        apply Finset.sum_congr rfl
                        intro i hi
                        calc
                          ‖T‖ * (‖T‖⁻¹ * ψi i (finiteSup B))
                              = (‖T‖ * ‖T‖⁻¹) * ψi i (finiteSup B) := by ring
                          _ = ψi i (finiteSup B) := by rw [mul_inv_cancel₀ hT.ne', one_mul]
                _ = ψ (finiteSup B) := by
                      simpa using congrArg (fun F : StrongDual ℝ X => F (finiteSup B)) hsum
    calc
      ψ (liftFVLv T f)
          = ψ (finiteSup A - finiteSup B) := by
              rw [hf_repr, liftFVLv_supSubLinearCombination]
      _ = ψ (finiteSup A) - ψ (finiteSup B) := by rw [map_sub]
      _ ≤ ‖T‖ * ‖ofFVLv f‖ := by
            linarith [hA]

private theorem norm_liftFVLv_le (T : E →L[ℝ] X) (f : FVLv E) :
    ‖liftFVLv T f‖ ≤ ‖T‖ * ‖ofFVLv f‖ := by
  obtain ⟨ψ, hψ0, hψnorm, hψval⟩ :=
    StrongDual.exists_positive_dual_norming (x := |liftFVLv T f|) (abs_nonneg _)
  have hmap :
      (ofFVLv |f| : FBL E) = |ofFVLv f| := by
        change liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) |f| =
          |liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) f|
        exact VecLatHom.map_abs
          (liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap)) f
  calc
    ‖liftFVLv T f‖ = ‖|liftFVLv T f|‖ := by rw [norm_abs_eq_norm]
    _ = ψ (|liftFVLv T f|) := by rw [← hψval]
    _ = ψ (liftFVLv T |f|) := by rw [← VecLatHom.map_abs (liftFVLv T) f]
    _ ≤ ‖T‖ * ‖ofFVLv |f|‖ :=
          positive_dual_apply_liftFVLv_nonneg_le (T := T) (f := |f|) (abs_nonneg f) hψ0 hψnorm
    _ = ‖T‖ * ‖ofFVLv f‖ := by rw [hmap, norm_abs_eq_norm]

private theorem dist_liftFVLv_le (T : E →L[ℝ] X) (f g : FVLv E) :
    dist (liftFVLv T f) (liftFVLv T g) ≤ ‖T‖ * dist (ofFVLv f) (ofFVLv g) := by
  rw [dist_eq_norm, dist_eq_norm, ← map_sub, ← LinearMap.map_sub]
  simpa using norm_liftFVLv_le (T := T) (f - g)

private noncomputable def liftAux (T : E →L[ℝ] X) : FBL E →L[ℝ] X :=
  ((liftFVLv T).toLinearMap).extendOfNorm (ofFVLv (E := E))

private theorem liftAux_ofFVLv (T : E →L[ℝ] X) (f : FVLv E) :
    liftAux T (ofFVLv f) = liftFVLv T f := by
  simpa [liftAux] using
    LinearMap.extendOfNorm_eq (f := (liftFVLv T).toLinearMap) (e := ofFVLv (E := E))
      (h_dense := denseRange_ofFVLv (E := E)) (h_norm := ⟨‖T‖, norm_liftFVLv_le (T := T)⟩) f

/-- The vector lattice homomorphic extension of an operator from `E` to a Banach lattice. -/
def lift (T : E →L[ℝ] X) : VecLatHom (FBL E) X := by
  refine VecLatHom.ofIsVecLatHom (liftAux T) ?_
  refine
    { map_add := fun _ _ => (liftAux T).map_add _ _
      map_smul := fun _ _ => (liftAux T).map_smul _ _
      map_sup' := ?_
      map_inf' := ?_ }
  · intro y z
    let e : FVLv E × FVLv E → FBL E × FBL E := fun p => (ofFVLv p.1, ofFVLv p.2)
    have he : DenseRange e := (denseRange_ofFVLv (E := E)).prodMap (denseRange_ofFVLv (E := E))
    have hg : Continuous fun p : FBL E × FBL E => liftAux T (p.1 ⊔ p.2) :=
      (liftAux T).continuous.comp (continuous_fst.sup continuous_snd)
    have hh : Continuous fun p : FBL E × FBL E => liftAux T p.1 ⊔ liftAux T p.2 :=
      ((liftAux T).continuous.comp continuous_fst).sup
        ((liftAux T).continuous.comp continuous_snd)
    have hEq :
        (fun p : FBL E × FBL E => liftAux T (p.1 ⊔ p.2)) =
          fun p : FBL E × FBL E => liftAux T p.1 ⊔ liftAux T p.2 :=
      he.equalizer hg hh (by
        funext p
        rcases p with ⟨f, g⟩
        have hof_sup : ofFVLv (f ⊔ g) = ofFVLv f ⊔ ofFVLv g := by
          change liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) (f ⊔ g) =
            liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) f ⊔
              liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) g
          exact map_sup _ _ _
        change liftAux T (ofFVLv f ⊔ ofFVLv g) = liftAux T (ofFVLv f) ⊔ liftAux T (ofFVLv g)
        rw [← hof_sup, liftAux_ofFVLv, liftAux_ofFVLv, liftAux_ofFVLv, map_sup])
    exact congrFun hEq (y, z)
  · intro y z
    let e : FVLv E × FVLv E → FBL E × FBL E := fun p => (ofFVLv p.1, ofFVLv p.2)
    have he : DenseRange e := (denseRange_ofFVLv (E := E)).prodMap (denseRange_ofFVLv (E := E))
    have hg : Continuous fun p : FBL E × FBL E => liftAux T (p.1 ⊓ p.2) :=
      (liftAux T).continuous.comp (continuous_fst.inf continuous_snd)
    have hh : Continuous fun p : FBL E × FBL E => liftAux T p.1 ⊓ liftAux T p.2 :=
      ((liftAux T).continuous.comp continuous_fst).inf
        ((liftAux T).continuous.comp continuous_snd)
    have hEq :
        (fun p : FBL E × FBL E => liftAux T (p.1 ⊓ p.2)) =
          fun p : FBL E × FBL E => liftAux T p.1 ⊓ liftAux T p.2 :=
      he.equalizer hg hh (by
        funext p
        rcases p with ⟨f, g⟩
        have hof_inf : ofFVLv (f ⊓ g) = ofFVLv f ⊓ ofFVLv g := by
          change liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) (f ⊓ g) =
            liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) f ⊓
              liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap) g
          exact map_inf _ _ _
        change liftAux T (ofFVLv f ⊓ ofFVLv g) = liftAux T (ofFVLv f) ⊓ liftAux T (ofFVLv g)
        rw [← hof_inf, liftAux_ofFVLv, liftAux_ofFVLv, liftAux_ofFVLv, map_inf])
    exact congrFun hEq (y, z)

/-- The extension from `E` to `X`, bundled as a bounded linear operator. -/
def liftContinuousLinearMap (T : E →L[ℝ] X) : FBL E →L[ℝ] X := by
  exact liftAux T

@[simp]
theorem liftContinuousLinearMap_apply (T : E →L[ℝ] X) (f : FBL E) :
    liftContinuousLinearMap T f = lift T f := by
  rfl

@[simp]
theorem lift_of (T : E →L[ℝ] X) (x : E) : lift T (of x) = T x := by
  rw [← ofFVLv_of]
  change liftAux T (ofFVLv (FVLv.of x)) = T x
  rw [liftAux_ofFVLv]
  exact liftFVLv_of T x

/-- The bounded linear operator attached to the extension preserves the operator norm. -/
theorem norm_lift (T : E →L[ℝ] X) : ‖liftContinuousLinearMap T‖ = ‖T‖ := by
  refine le_antisymm ?_ ?_
  · simpa [liftContinuousLinearMap, liftAux] using
      LinearMap.opNorm_extendOfNorm_le (f := (liftFVLv T).toLinearMap) (e := ofFVLv (E := E))
        (h_dense := denseRange_ofFVLv (E := E)) (C := ‖T‖) (norm_nonneg T)
        (norm_liftFVLv_le (T := T))
  · calc
      ‖T‖ = ‖(liftContinuousLinearMap T).comp
          (ofLinearIsometry (E := E)).toContinuousLinearMap‖ := by
            congr 1
            ext x
            simp [lift_of]
      _ ≤ ‖liftContinuousLinearMap T‖ *
            ‖(ofLinearIsometry (E := E)).toContinuousLinearMap‖ :=
          ContinuousLinearMap.opNorm_comp_le _ _
      _ ≤ ‖liftContinuousLinearMap T‖ * 1 := by
            gcongr
            exact LinearIsometry.norm_toContinuousLinearMap_le (ofLinearIsometry (E := E))
      _ = ‖liftContinuousLinearMap T‖ := by rw [mul_one]

/-- A vector lattice homomorphism out of `FBL E` is uniquely determined by its values on
the canonical copy of `E`. -/
theorem lift_unique (T : E →L[ℝ] X) (S : VecLatHom (FBL E) X)
    (h : ∀ x : E, S (of x) = T x) :
    S = lift T := by
  let ι : VecLatHom (FVLv E) (FBL E) :=
    liftFVLv (T := (ofLinearIsometry (E := E)).toContinuousLinearMap)
  have hcomp : S.comp ι = liftFVLv T := by
    apply FVLv.lift_unique
    intro x
    change S (ι (FVLv.of x)) = T x
    rw [liftFVLv_of]
    exact h x
  have hScont : Continuous S.toLinearMap :=
    Positive.continuous ((Positive.monotone_iff).mp S.monotone)
  have hEq :
      (S : FBL E → X) = liftContinuousLinearMap T :=
    (denseRange_ofFVLv (E := E)).equalizer hScont (liftContinuousLinearMap T).continuous (by
      funext f
      change (S.comp ι) f = liftContinuousLinearMap T (ofFVLv f)
      rw [hcomp, liftContinuousLinearMap_apply]
      change liftFVLv T f = liftAux T (ofFVLv f)
      rw [liftAux_ofFVLv])
  apply DFunLike.ext
  intro y
  exact congrFun hEq y

/-- The universal property of `FBL E`: bounded linear maps from `E` into a Banach lattice
extend uniquely to bounded operators from `FBL E` that are vector lattice homomorphisms.
The extension preserves the operator norm. -/
theorem exists_unique_lift (T : E →L[ℝ] X) :
    ∃! S : FBL E →L[ℝ] X,
      IsVecLatHom (S : FBL E → X) ∧ (∀ x : E, S (of x) = T x) ∧
        ‖S‖ = ‖T‖ := by
  refine ⟨liftContinuousLinearMap T, ?_, ?_⟩
  · exact ⟨(lift T).isVecLatHom, lift_of T, norm_lift T⟩
  · intro S hS
    rcases hS with ⟨hSV, hSo, _hSnorm⟩
    let SV : VecLatHom (FBL E) X := VecLatHom.ofIsVecLatHom (S : FBL E → X) hSV
    have hSVeq : SV = lift T := lift_unique T SV hSo
    ext y
    calc
      S y = SV y := rfl
      _ = lift T y := by rw [hSVeq]
      _ = liftContinuousLinearMap T y := by rw [← liftContinuousLinearMap_apply]

end UniversalProperty

end FBL
