/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Pi
import BanLat.LLexpr
import BanLat.Operators.Hom
import BanLat.Substructures.Sublattice
import Mathlib.LinearAlgebra.LinearIndependent.Defs

/-!
# Free vector lattices

This file constructs the free vector lattice on a type of generators as a concrete
vector sublattice of the real-valued function space on `R^A`.
-/

universe u v

/-- The ambient function space `R^(R^A)` used for the concrete representation of `FVL(A)`. -/
abbrev FVL.FunctionSpace (α : Type u) : Type u :=
  (α → ℝ) → ℝ

namespace FVL

variable {α : Type u}

/-- The coordinate functional `δ a : R^A → R`. -/
def coordinate (a : α) : FunctionSpace α :=
  fun x => x a

/-- The vector sublattice of `R^(R^A)` generated by the coordinate functionals. -/
noncomputable def concreteSublattice (α : Type u) : VectorSublattice (FunctionSpace α) :=
  VectorSublattice.generated (Set.range (coordinate : α → FunctionSpace α))

end FVL

/-- The free vector lattice generated by a type `α`, realized concretely as the sublattice of
`R^(R^A)` generated by the coordinate functionals. -/
abbrev FVL (α : Type u) : Type u :=
  ↥(FVL.concreteSublattice α).toSubmodule

namespace FVL

variable {α : Type u}

noncomputable instance instLattice : Lattice (FVL α) :=
  inferInstanceAs (Lattice ↥(concreteSublattice α).toSubmodule)

instance instIsOrderedAddMonoid : IsOrderedAddMonoid (FVL α) :=
  inferInstanceAs (IsOrderedAddMonoid ↥(concreteSublattice α).toSubmodule)

noncomputable instance instVectorLattice : VectorLattice (FVL α) :=
  inferInstanceAs (VectorLattice ↥(concreteSublattice α).toSubmodule)

instance instIsVLArchimedean : IsVLArchimedean (FVL α) := by
  apply isVLArchimedean_of_eq_zero_of_nonneg_of_forall_nsmul_le
  intro f g hf hfg
  apply Subtype.ext
  funext x
  exact IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (show 0 ≤ f.1 x from hf x)
    fun n => show n • f.1 x ≤ g.1 x from hfg n x

instance instCoeFun : CoeFun (FVL α) (fun _ => (α → ℝ) → ℝ) where
  coe f := f.1

/-- The canonical map from the generating type to its free vector lattice. -/
def of (a : α) : FVL α :=
  ⟨coordinate a, VectorSublattice.subset_generated _ ⟨a, rfl⟩⟩

@[simp]
theorem coe_of (a : α) : ((of a : FVL α) : FunctionSpace α) = coordinate a := rfl

@[simp]
theorem of_apply (a : α) (x : α → ℝ) : (of a : FVL α) x = x a := rfl

private theorem eval_coe_submodule {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (Y : VectorSublattice X)
    (y : Fin n → ↥Y.toSubmodule) (e : LLexpr n) :
    ((LLexpr.eval y e : ↥Y.toSubmodule) : X) =
      LLexpr.eval (fun i => (y i : X)) e := by
  induction e with
  | zero => simp [LLexpr.eval]
  | var i => simp [LLexpr.eval]
  | add e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂]
  | smul r e h => simp [LLexpr.eval, h]
  | sup e₁ e₂ h₁ h₂ =>
      change
        ((LLexpr.eval y e₁ : ↥Y.toSubmodule) : X) ⊔
            ((LLexpr.eval y e₂ : ↥Y.toSubmodule) : X) =
          LLexpr.eval (fun i => (y i : X)) e₁ ⊔
            LLexpr.eval (fun i => (y i : X)) e₂
      rw [h₁, h₂]
  | inf e₁ e₂ h₁ h₂ =>
      change
        ((LLexpr.eval y e₁ : ↥Y.toSubmodule) : X) ⊓
            ((LLexpr.eval y e₂ : ↥Y.toSubmodule) : X) =
          LLexpr.eval (fun i => (y i : X)) e₁ ⊓
            LLexpr.eval (fun i => (y i : X)) e₂
      rw [h₁, h₂]

private theorem eval_apply {ι X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (y : Fin n → ι → X)
    (e : LLexpr n) (t : ι) :
    LLexpr.eval y e t = LLexpr.eval (fun i => y i t) e := by
  induction e with
  | zero => simp [LLexpr.eval]
  | var i => simp [LLexpr.eval]
  | add e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂]
  | smul r e h => simp [LLexpr.eval, h]
  | sup e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂]
  | inf e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂]

private theorem exists_eval_of_eq (f : FVL α) :
    ∃ (n : ℕ) (a : Fin n → α) (e : LLexpr n),
      LLexpr.eval (fun i => of (a i)) e = f := by
  classical
  have hf : (f : FunctionSpace α) ∈
      (VectorSublattice.generated (Set.range (coordinate : α → FunctionSpace α)) :
        Set (FunctionSpace α)) := f.2
  rw [LLexpr.generated_eq_iUnion_combinations
    (Set.range (coordinate : α → FunctionSpace α))] at hf
  simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range] at hf
  obtain ⟨n, z, e, he⟩ := hf
  choose a ha using fun i : Fin n => (z i).2
  refine ⟨n, a, e, ?_⟩
  apply Subtype.ext
  calc
    ((LLexpr.eval (fun i : Fin n => of (a i)) e : FVL α) : FunctionSpace α)
        = LLexpr.eval (fun i : Fin n => coordinate (a i)) e := by
          exact eval_coe_submodule (concreteSublattice α) (fun i : Fin n => of (a i)) e
    _ = LLexpr.eval (fun i : Fin n => (z i : FunctionSpace α)) e := by
          congr
          funext i
          rw [ha i]
    _ = f := he

/-- The canonical map into the concrete free vector lattice is injective. -/
theorem of_injective : Function.Injective (of : α → FVL α) := by
  classical
  intro a b h
  have hcoord : coordinate a = coordinate b := by
    simpa using congrArg (fun f : FVL α => (f : FunctionSpace α)) h
  by_contra hne
  have hab : b ≠ a := fun hba => hne hba.symm
  have hval := congrFun hcoord (fun c => if c = a then (1 : ℝ) else 0)
  simp [coordinate, hab] at hval

/-- The canonical generators linearly generate no non-trivial finite linear relation. -/
theorem linearIndependent_of : LinearIndependent ℝ (of : α → FVL α) := by
  classical
  rw [linearIndependent_iff']
  intro s g hsum i hi
  have hfun := congrArg (fun f : FVL α => (f : FunctionSpace α) (Pi.single i 1)) hsum
  have hfun' : (∑ j ∈ s, g j * coordinate j (Pi.single i 1)) = 0 := by
    simpa [of_apply, coordinate, Finset.sum_apply] using hfun
  have hsum_eval : (∑ j ∈ s, g j * coordinate j (Pi.single i 1)) = g i := by
    rw [Finset.sum_eq_single i]
    · simp [coordinate]
    · intro j _ hji
      simp [coordinate, hji]
    · intro hnot
      exact (hnot hi).elim
  rw [hsum_eval] at hfun'
  exact hfun'

/-- The canonical generators generate `FVL α` as a vector sublattice. -/
theorem generated_range_of :
    VectorSublattice.generated (Set.range (of : α → FVL α)) = ⊤ := by
  apply le_antisymm
  · intro f _
    exact VectorSublattice.mem_top
  · intro f _
    change f ∈ (VectorSublattice.generated (Set.range (of : α → FVL α)) : Set (FVL α))
    obtain ⟨n, a, e, he⟩ := exists_eval_of_eq f
    rw [← he]
    rw [LLexpr.generated_eq_iUnion_combinations (Set.range (of : α → FVL α))]
    simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range]
    refine ⟨n, fun i : Fin n => ⟨of (a i), ⟨a i, rfl⟩⟩, e, ?_⟩
    rfl

/-- The partial converse to Yudin's theorem for distinct coordinate functionals. -/
theorem vanishes_real_of_eval_coordinate_eq_zero {n : ℕ} (e : LLexpr n)
    {a : Fin n → α} (ha : Function.Injective a)
    (h : LLexpr.eval (fun i => coordinate (a i)) e = 0) : LLexpr.Vanishes ℝ e := by
  classical
  intro r
  let x : α → ℝ := fun b => if hmem : ∃ i, a i = b then r hmem.choose else 0
  have hx : (fun i : Fin n => coordinate (a i) x) = r := by
    funext i
    have hchoose : a (Classical.choose (show ∃ j, a j = a i from ⟨i, rfl⟩)) = a i :=
      Classical.choose_spec (show ∃ j, a j = a i from ⟨i, rfl⟩)
    have hi : Classical.choose (show ∃ j, a j = a i from ⟨i, rfl⟩) = i := ha hchoose
    simp [coordinate, x, hi]
  have hzero := congrFun h x
  have hzero' : LLexpr.eval (fun i => coordinate (a i) x) e = 0 := by
    simpa [eval_apply] using hzero
  simpa [hx] using hzero'

/-- A family in a vector lattice is lattice-linearly independent if every finite
subfamily of distinct indices is lattice-linearly independent: every lattice-linear
expression vanishing on that finite subfamily vanishes identically on `ℝ`. -/
def LatticeLinearIndependent {ι X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (x : ι → X) : Prop :=
  ∀ {n : ℕ} (a : Fin n → ι), Function.Injective a →
    ∀ e : LLexpr n, LLexpr.eval (fun i => x (a i)) e = 0 → LLexpr.Vanishes ℝ e

/-- A set is lattice-linearly independent if its subtype family is lattice-linearly
independent. -/
def LatticeLinearIndependentOn {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (s : Set X) : Prop :=
  LatticeLinearIndependent (fun x : s => (x : X))

/-- Distinct coordinate functionals in the concrete model are lattice-linearly independent. -/
theorem coordinate_latticeLinearIndependent {n : ℕ} {a : Fin n → α}
    (ha : Function.Injective a) :
    LatticeLinearIndependent (fun i : Fin n => coordinate (a i)) := by
  intro m b hb e h
  exact vanishes_real_of_eval_coordinate_eq_zero e (ha.comp hb) h

/-- Distinct canonical generators in `FVL α` are lattice-linearly independent. -/
theorem of_finiteLatticeLinearIndependent {n : ℕ} {a : Fin n → α}
    (ha : Function.Injective a) :
    LatticeLinearIndependent (fun i : Fin n => of (a i)) := by
  intro m b hb e h
  apply vanishes_real_of_eval_coordinate_eq_zero e (ha.comp hb)
  have hcoord := congrArg (fun f : FVL α => (f : FunctionSpace α)) h
  simpa [eval_coe_submodule] using hcoord

/-- The canonical family of generators of a free vector lattice is lattice-linearly
independent. -/
theorem of_latticeLinearIndependent : LatticeLinearIndependent (of : α → FVL α) := by
  intro n a ha e h
  exact of_finiteLatticeLinearIndependent ha (fun i => i) Function.injective_id e h

private structure Repr (f : FVL α) where
  n : ℕ
  a : Fin n → α
  e : LLexpr n
  eval_eq : LLexpr.eval (fun i => of (a i)) e = f

private theorem exists_repr (f : FVL α) : Nonempty (Repr f) := by
  obtain ⟨n, a, e, he⟩ := exists_eval_of_eq f
  exact ⟨⟨n, a, e, he⟩⟩

private noncomputable def repr (f : FVL α) : Repr f :=
  Classical.choice (exists_repr f)

private noncomputable def reprOf (a : α) : Repr (of a : FVL α) where
  n := 1
  a := fun _ => a
  e := LLexpr.var 0
  eval_eq := by simp [LLexpr.eval]

private noncomputable def reprAdd {f g : FVL α} (rf : Repr f) (rg : Repr g) :
    Repr (f + g) where
  n := rf.n + rg.n
  a := Fin.append rf.a rg.a
  e :=
    LLexpr.add (LLexpr.reindexExpr (Fin.castAdd rg.n) rf.e)
      (LLexpr.reindexExpr (Fin.natAdd rf.n) rg.e)
  eval_eq := by
    rw [LLexpr.eval_add, LLexpr.eval_reindexExpr, LLexpr.eval_reindexExpr]
    simp [rf.eval_eq, rg.eval_eq]

private noncomputable def reprSmul (r : ℝ) {f : FVL α} (rf : Repr f) :
    Repr (r • f) where
  n := rf.n
  a := rf.a
  e := LLexpr.smul r rf.e
  eval_eq := by
    rw [LLexpr.eval_smul, rf.eval_eq]

private noncomputable def reprSup {f g : FVL α} (rf : Repr f) (rg : Repr g) :
    Repr (f ⊔ g) where
  n := rf.n + rg.n
  a := Fin.append rf.a rg.a
  e :=
    LLexpr.sup (LLexpr.reindexExpr (Fin.castAdd rg.n) rf.e)
      (LLexpr.reindexExpr (Fin.natAdd rf.n) rg.e)
  eval_eq := by
    rw [LLexpr.eval_sup, LLexpr.eval_reindexExpr, LLexpr.eval_reindexExpr]
    simp [rf.eval_eq, rg.eval_eq]

private noncomputable def reprInf {f g : FVL α} (rf : Repr f) (rg : Repr g) :
    Repr (f ⊓ g) where
  n := rf.n + rg.n
  a := Fin.append rf.a rg.a
  e :=
    LLexpr.inf (LLexpr.reindexExpr (Fin.castAdd rg.n) rf.e)
      (LLexpr.reindexExpr (Fin.natAdd rf.n) rg.e)
  eval_eq := by
    rw [LLexpr.eval_inf, LLexpr.eval_reindexExpr, LLexpr.eval_reindexExpr]
    simp [rf.eval_eq, rg.eval_eq]

section Lift

variable {X : Type v} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

private theorem eval_eq_of_coordinate_eval_eq {m n : ℕ} (φ : α → X)
    {a : Fin m → α} {b : Fin n → α} {e : LLexpr m} {d : LLexpr n}
    (h : LLexpr.eval (fun i => coordinate (a i)) e =
      LLexpr.eval (fun i => coordinate (b i)) d) :
    LLexpr.eval (fun i => φ (a i)) e = LLexpr.eval (fun i => φ (b i)) d := by
  classical
  let c : Fin (m + n) → α := Fin.append a b
  let E : LLexpr (m + n) :=
    LLexpr.add (LLexpr.reindexExpr (Fin.castAdd n) e)
      (LLexpr.smul (-1) (LLexpr.reindexExpr (Fin.natAdd m) d))
  obtain ⟨k, c', hc', r, hr⟩ := LLexpr.exists_injective_reindex c
  have hcoord0 : LLexpr.eval (fun i : Fin (m + n) => coordinate (c i)) E = 0 := by
    dsimp [E]
    rw [LLexpr.eval_reindexExpr, LLexpr.eval_reindexExpr]
    simp [c, h]
  have hcoord : LLexpr.eval (fun i => coordinate (c' i)) (LLexpr.reindexExpr r E) = 0 := by
    rw [LLexpr.eval_reindexExpr]
    have hc_coord : (fun i : Fin (m + n) => coordinate (c' (r i))) =
        fun i => coordinate (c i) := by
      funext i
      rw [hr i]
    rw [hc_coord]
    exact hcoord0
  have hvreal := vanishes_real_of_eval_coordinate_eq_zero (LLexpr.reindexExpr r E) hc' hcoord
  have hXzero :=
    (LLexpr.vanishes_of_vanishes_real (LLexpr.reindexExpr r E) hvreal X)
      (fun i => φ (c' i))
  rw [LLexpr.eval_reindexExpr] at hXzero
  have hcφ : (fun i : Fin (m + n) => φ (c' (r i))) = fun i => φ (c i) := by
    funext i
    rw [hr i]
  rw [hcφ] at hXzero
  have hdiff :
      LLexpr.eval (fun i : Fin m => φ (a i)) e -
        LLexpr.eval (fun i : Fin n => φ (b i)) d = 0 := by
    simpa [E, c, LLexpr.eval_reindexExpr, sub_eq_add_neg] using hXzero
  exact sub_eq_zero.mp hdiff

private theorem eval_eq_of_of_eval_eq {m n : ℕ} (φ : α → X)
    {a : Fin m → α} {b : Fin n → α} {e : LLexpr m} {d : LLexpr n}
    (h : LLexpr.eval (fun i => of (a i)) e =
      LLexpr.eval (fun i => of (b i)) d) :
    LLexpr.eval (fun i => φ (a i)) e = LLexpr.eval (fun i => φ (b i)) d := by
  apply eval_eq_of_coordinate_eval_eq φ
  have hcoord := congrArg (fun f : FVL α => (f : FunctionSpace α)) h
  have hleft := eval_coe_submodule (concreteSublattice α) (fun i : Fin m => of (a i)) e
  have hright := eval_coe_submodule (concreteSublattice α) (fun i : Fin n => of (b i)) d
  simpa [hleft, hright] using hcoord

private noncomputable def liftFun (φ : α → X) (f : FVL α) : X :=
  LLexpr.eval (fun i => φ ((repr f).a i)) (repr f).e

private theorem liftFun_eq_eval (φ : α → X) {f : FVL α} (r : Repr f) :
    liftFun φ f = LLexpr.eval (fun i => φ (r.a i)) r.e := by
  exact eval_eq_of_of_eval_eq φ (by rw [(repr f).eval_eq, r.eval_eq])

private theorem liftFun_of (φ : α → X) (a : α) : liftFun φ (of a) = φ a := by
  calc
    liftFun φ (of a) = LLexpr.eval (fun i => φ ((reprOf a).a i)) (reprOf a).e :=
      liftFun_eq_eval φ (reprOf a)
    _ = φ a := by simp [reprOf]

private theorem liftFun_add (φ : α → X) (f g : FVL α) :
    liftFun φ (f + g) = liftFun φ f + liftFun φ g := by
  let rf := repr f
  let rg := repr g
  let rfg := reprAdd rf rg
  calc
    liftFun φ (f + g) = LLexpr.eval (fun i => φ (rfg.a i)) rfg.e :=
      liftFun_eq_eval φ rfg
    _ = LLexpr.eval (fun i => φ (rf.a i)) rf.e +
        LLexpr.eval (fun i => φ (rg.a i)) rg.e := by
          simp [rfg, reprAdd, LLexpr.eval_reindexExpr]
    _ = liftFun φ f + liftFun φ g := by
          rw [← liftFun_eq_eval φ rf, ← liftFun_eq_eval φ rg]

private theorem liftFun_smul (φ : α → X) (r : ℝ) (f : FVL α) :
    liftFun φ (r • f) = r • liftFun φ f := by
  let rf := repr f
  let rrf := reprSmul r rf
  calc
    liftFun φ (r • f) = LLexpr.eval (fun i => φ (rrf.a i)) rrf.e :=
      liftFun_eq_eval φ rrf
    _ = r • LLexpr.eval (fun i => φ (rf.a i)) rf.e := by
          simp [rrf, reprSmul]
    _ = r • liftFun φ f := by
          rw [← liftFun_eq_eval φ rf]

private theorem liftFun_sup (φ : α → X) (f g : FVL α) :
    liftFun φ (f ⊔ g) = liftFun φ f ⊔ liftFun φ g := by
  let rf := repr f
  let rg := repr g
  let rfg := reprSup rf rg
  calc
    liftFun φ (f ⊔ g) = LLexpr.eval (fun i => φ (rfg.a i)) rfg.e :=
      liftFun_eq_eval φ rfg
    _ = LLexpr.eval (fun i => φ (rf.a i)) rf.e ⊔
        LLexpr.eval (fun i => φ (rg.a i)) rg.e := by
          simp [rfg, reprSup, LLexpr.eval_reindexExpr]
    _ = liftFun φ f ⊔ liftFun φ g := by
          rw [← liftFun_eq_eval φ rf, ← liftFun_eq_eval φ rg]

private theorem liftFun_inf (φ : α → X) (f g : FVL α) :
    liftFun φ (f ⊓ g) = liftFun φ f ⊓ liftFun φ g := by
  let rf := repr f
  let rg := repr g
  let rfg := reprInf rf rg
  calc
    liftFun φ (f ⊓ g) = LLexpr.eval (fun i => φ (rfg.a i)) rfg.e :=
      liftFun_eq_eval φ rfg
    _ = LLexpr.eval (fun i => φ (rf.a i)) rf.e ⊓
        LLexpr.eval (fun i => φ (rg.a i)) rg.e := by
          simp [rfg, reprInf, LLexpr.eval_reindexExpr]
    _ = liftFun φ f ⊓ liftFun φ g := by
          rw [← liftFun_eq_eval φ rf, ← liftFun_eq_eval φ rg]

/-- The vector lattice homomorphism out of the concrete free vector lattice induced by a map
from the generators. -/
noncomputable def lift : (α → X) ≃ VecLatHom (FVL α) X := by
  refine
    { toFun := fun φ =>
        { toFun := liftFun φ
          map_add' := liftFun_add φ
          map_smul' := liftFun_smul φ
          map_sup' := liftFun_sup φ
          map_inf' := liftFun_inf φ }
      invFun := fun T a => T (of a)
      left_inv := ?_
      right_inv := ?_ }
  · intro φ
    funext a
    exact liftFun_of φ a
  · intro T
    apply DFunLike.ext
    intro f
    let r := repr f
    calc
      liftFun (fun a => T (of a)) f
          = LLexpr.eval (fun i => T (of (r.a i))) r.e :=
            liftFun_eq_eval (fun a => T (of a)) r
      _ = T (LLexpr.eval (fun i => of (r.a i)) r.e) := by
            exact (LLexpr.map_eval T (fun i => of (r.a i)) r.e).symm
      _ = T f := by rw [r.eval_eq]

@[simp]
theorem lift_of (φ : α → X) (a : α) : lift φ (of a) = φ a := by
  exact congrFun (Equiv.left_inv lift φ) a

@[simp]
theorem lift_comp_of (T : VecLatHom (FVL α) X) : lift ((T : FVL α → X) ∘ of) = T := by
  exact Equiv.right_inv lift T

/-- A vector lattice homomorphism out of `FVL α` is determined by its values on generators. -/
theorem lift_unique (φ : α → X) (T : VecLatHom (FVL α) X)
    (h : ∀ a, T (of a) = φ a) : T = lift φ := by
  calc
    T = lift ((T : FVL α → X) ∘ of) := (lift_comp_of T).symm
    _ = lift φ := congrArg lift (funext h)

@[ext]
theorem hom_ext {S T : VecLatHom (FVL α) X} (h : ∀ a, S (of a) = T (of a)) : S = T := by
  calc
    S = lift ((S : FVL α → X) ∘ of) := (lift_comp_of S).symm
    _ = lift ((T : FVL α → X) ∘ of) := congrArg lift (funext h)
    _ = T := lift_comp_of T

private theorem lift_eval {n : ℕ} (x : α → X) (a : Fin n → α) (e : LLexpr n) :
    lift x (LLexpr.eval (fun i => of (a i)) e) =
      LLexpr.eval (fun i => x (a i)) e := by
  simpa using LLexpr.map_eval (lift x) (fun i : Fin n => of (a i)) e

private theorem coordinate_eval_eq_of_latticeLinearIndependent {m n : ℕ} (x : α → X)
    (hx : LatticeLinearIndependent x) {a : Fin m → α} {b : Fin n → α}
    {e : LLexpr m} {d : LLexpr n}
    (h : LLexpr.eval (fun i => x (a i)) e =
      LLexpr.eval (fun i => x (b i)) d) :
    LLexpr.eval (fun i => coordinate (a i)) e =
      LLexpr.eval (fun i => coordinate (b i)) d := by
  classical
  let c : Fin (m + n) → α := Fin.append a b
  let E : LLexpr (m + n) :=
    LLexpr.add (LLexpr.reindexExpr (Fin.castAdd n) e)
      (LLexpr.smul (-1) (LLexpr.reindexExpr (Fin.natAdd m) d))
  obtain ⟨k, c', hc', r, hr⟩ := LLexpr.exists_injective_reindex c
  have hxzero0 : LLexpr.eval (fun i : Fin (m + n) => x (c i)) E = 0 := by
    dsimp [E]
    rw [LLexpr.eval_reindexExpr, LLexpr.eval_reindexExpr]
    simp [c, h]
  have hxzero : LLexpr.eval (fun i => x (c' i)) (LLexpr.reindexExpr r E) = 0 := by
    rw [LLexpr.eval_reindexExpr]
    have hc_x : (fun i : Fin (m + n) => x (c' (r i))) = fun i => x (c i) := by
      funext i
      rw [hr i]
    rw [hc_x]
    exact hxzero0
  have hvreal : LLexpr.Vanishes ℝ (LLexpr.reindexExpr r E) :=
    hx c' hc' (LLexpr.reindexExpr r E) hxzero
  have hcoordZero :=
    (LLexpr.vanishes_of_vanishes_real (LLexpr.reindexExpr r E) hvreal (FunctionSpace α))
      (fun i => coordinate (c' i))
  rw [LLexpr.eval_reindexExpr] at hcoordZero
  have hc_coord : (fun i : Fin (m + n) => coordinate (c' (r i))) =
      fun i => coordinate (c i) := by
    funext i
    rw [hr i]
  rw [hc_coord] at hcoordZero
  have hdiff :
      LLexpr.eval (fun i : Fin m => coordinate (a i)) e -
        LLexpr.eval (fun i : Fin n => coordinate (b i)) d = 0 := by
    simpa [E, c, LLexpr.eval_reindexExpr, sub_eq_add_neg] using hcoordZero
  exact sub_eq_zero.mp hdiff

/-- A family is lattice-linearly independent iff the canonical vector lattice homomorphism
from the free vector lattice is injective. -/
theorem latticeLinearIndependent_iff_lift_injective (x : α → X) :
    LatticeLinearIndependent x ↔ Function.Injective (lift x) := by
  constructor
  · intro hx f g hfg
    change liftFun x f = liftFun x g at hfg
    let rf := repr f
    let rg := repr g
    have hx_eval :
        LLexpr.eval (fun i => x (rf.a i)) rf.e =
          LLexpr.eval (fun i => x (rg.a i)) rg.e := by
      calc
        LLexpr.eval (fun i => x (rf.a i)) rf.e = liftFun x f :=
          (liftFun_eq_eval x rf).symm
        _ = liftFun x g := hfg
        _ = LLexpr.eval (fun i => x (rg.a i)) rg.e := liftFun_eq_eval x rg
    have hcoord := coordinate_eval_eq_of_latticeLinearIndependent x hx hx_eval
    apply Subtype.ext
    have hfcoord : (f : FunctionSpace α) =
        LLexpr.eval (fun i => coordinate (rf.a i)) rf.e := by
      have hrf := congrArg (fun y : FVL α => (y : FunctionSpace α)) rf.eval_eq
      simpa [eval_coe_submodule] using hrf.symm
    have hgcoord : (g : FunctionSpace α) =
        LLexpr.eval (fun i => coordinate (rg.a i)) rg.e := by
      have hrg := congrArg (fun y : FVL α => (y : FunctionSpace α)) rg.eval_eq
      simpa [eval_coe_submodule] using hrg.symm
    calc
      (f : FunctionSpace α) = LLexpr.eval (fun i => coordinate (rf.a i)) rf.e := hfcoord
      _ = LLexpr.eval (fun i => coordinate (rg.a i)) rg.e := hcoord
      _ = (g : FunctionSpace α) := hgcoord.symm
  · intro hinj n a ha e h
    have hf0 : LLexpr.eval (fun i => of (a i)) e = (0 : FVL α) := by
      apply hinj
      calc
        lift x (LLexpr.eval (fun i => of (a i)) e)
            = LLexpr.eval (fun i => x (a i)) e := lift_eval x a e
        _ = 0 := h
        _ = lift x (0 : FVL α) := by simp
    have hcoord : LLexpr.eval (fun i => coordinate (a i)) e = 0 := by
      have hcoe := congrArg (fun f : FVL α => (f : FunctionSpace α)) hf0
      simpa [eval_coe_submodule] using hcoe
    exact vanishes_real_of_eval_coordinate_eq_zero e ha hcoord

end Lift

section Map

variable {β : Type v}

/-- The vector lattice homomorphism induced by a map of generators. -/
noncomputable def map (f : α → β) : VecLatHom (FVL α) (FVL β) :=
  lift (of ∘ f)

@[simp]
theorem map_of (f : α → β) (a : α) : map f (of a) = of (f a) := by
  exact lift_of (of ∘ f) a

end Map

section Generated

variable {X : Type v} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- The generator `x a`, regarded as an element of the vector sublattice generated by
the family `x`. -/
def generatedOf (x : α → X) (a : α) :
    ↥(VectorSublattice.generated (Set.range x)).toSubmodule :=
  ⟨x a, VectorSublattice.subset_generated _ ⟨a, rfl⟩⟩

@[simp]
theorem generatedOf_coe (x : α → X) (a : α) :
    ((generatedOf x a :
      ↥(VectorSublattice.generated (Set.range x)).toSubmodule) : X) = x a :=
  rfl

/-- The canonical homomorphism from `FVL α` to the vector sublattice generated by a family. -/
noncomputable def toGenerated (x : α → X) :
    VecLatHom (FVL α) ↥(VectorSublattice.generated (Set.range x)).toSubmodule :=
  lift (generatedOf x)

@[simp]
theorem toGenerated_of (x : α → X) (a : α) :
    toGenerated x (of a) = generatedOf x a := by
  simp [toGenerated]

private noncomputable def generatedSubtypeHom (x : α → X) :
    VecLatHom (↥(VectorSublattice.generated (Set.range x)).toSubmodule) X where
  toFun y := y
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

@[simp]
private theorem generatedSubtypeHom_apply (x : α → X)
    (y : ↥(VectorSublattice.generated (Set.range x)).toSubmodule) :
    generatedSubtypeHom x y = (y : X) :=
  rfl

private theorem generatedSubtypeHom_comp_toGenerated (x : α → X) :
    (generatedSubtypeHom x).comp (toGenerated x) = lift x := by
  apply hom_ext
  intro a
  rw [VecLatHom.comp_apply]
  simp

private theorem toGenerated_injective {x : α → X}
    (hx : LatticeLinearIndependent x) :
    Function.Injective (toGenerated x) := by
  intro f g hfg
  have h :
      (generatedSubtypeHom x).comp (toGenerated x) f =
        (generatedSubtypeHom x).comp (toGenerated x) g := by
    simpa [VecLatHom.comp_apply] using congrArg (generatedSubtypeHom x) hfg
  rw [generatedSubtypeHom_comp_toGenerated] at h
  exact (latticeLinearIndependent_iff_lift_injective x).mp hx h

private theorem subtype_val_eval {n : ℕ} (Y : VectorSublattice X)
    (y : Fin n → ↥Y.toSubmodule) (e : LLexpr n) :
    ((LLexpr.eval y e : ↥Y.toSubmodule) : X) =
      LLexpr.eval (fun i => (y i : X)) e := by
  induction e with
  | zero => simp [LLexpr.eval]
  | var i => simp [LLexpr.eval]
  | add e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂]
  | smul r e h => simp [LLexpr.eval, h]
  | sup e₁ e₂ h₁ h₂ =>
      change
        ((LLexpr.eval y e₁ : ↥Y.toSubmodule) : X) ⊔
            ((LLexpr.eval y e₂ : ↥Y.toSubmodule) : X) =
          LLexpr.eval (fun i => (y i : X)) e₁ ⊔
            LLexpr.eval (fun i => (y i : X)) e₂
      rw [h₁, h₂]
  | inf e₁ e₂ h₁ h₂ =>
      change
        ((LLexpr.eval y e₁ : ↥Y.toSubmodule) : X) ⊓
            ((LLexpr.eval y e₂ : ↥Y.toSubmodule) : X) =
          LLexpr.eval (fun i => (y i : X)) e₁ ⊓
            LLexpr.eval (fun i => (y i : X)) e₂
      rw [h₁, h₂]

private theorem toGenerated_surjective (x : α → X) :
    Function.Surjective (toGenerated x) := by
  intro y
  classical
  have hy : (y : X) ∈ (VectorSublattice.generated (Set.range x) : Set X) := y.2
  rw [LLexpr.generated_eq_iUnion_combinations (Set.range x)] at hy
  simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range] at hy
  obtain ⟨n, z, e, he⟩ := hy
  choose a ha using fun i : Fin n => (z i).2
  let f : FVL α := LLexpr.eval (fun i : Fin n => of (a i)) e
  refine ⟨f, ?_⟩
  apply Subtype.ext
  have hmap := LLexpr.map_eval (toGenerated x) (fun i : Fin n => of (a i)) e
  calc
    (toGenerated x f : X)
        = ((LLexpr.eval (fun i : Fin n => toGenerated x (of (a i))) e :
            ↥(VectorSublattice.generated (Set.range x)).toSubmodule) : X) := by
          exact congrArg Subtype.val hmap
    _ = LLexpr.eval (fun i : Fin n => (z i : X)) e := by
          rw [subtype_val_eval]
          congr
          funext i
          simp [ha i]
    _ = y := he

/-- If a family is lattice-linearly independent, the free vector lattice on its index type is
isomorphic to the vector sublattice generated by the family. -/
noncomputable def equivGenerated (x : α → X) (hx : LatticeLinearIndependent x) :
    VecLatEquiv (FVL α) ↥(VectorSublattice.generated (Set.range x)).toSubmodule :=
  { LinearEquiv.ofBijective (toGenerated x).toLinearMap
      ⟨toGenerated_injective hx, toGenerated_surjective x⟩ with
    map_sup' := (toGenerated x).map_sup'
    map_inf' := (toGenerated x).map_inf' }

@[simp]
theorem equivGenerated_apply (x : α → X) (hx : LatticeLinearIndependent x) (f : FVL α) :
    equivGenerated x hx f = toGenerated x f :=
  rfl

theorem equivGenerated_of (x : α → X) (hx : LatticeLinearIndependent x) (a : α) :
    equivGenerated x hx (of a) = generatedOf x a := by
  simp [equivGenerated_apply]

@[simp]
theorem equivGenerated_symm_generatedOf (x : α → X) (hx : LatticeLinearIndependent x)
    (a : α) :
    (equivGenerated x hx).symm (generatedOf x a) = of a := by
  change (equivGenerated x hx).toLinearEquiv.symm (generatedOf x a) = of a
  rw [LinearEquiv.symm_apply_eq]
  change generatedOf x a = equivGenerated x hx (of a)
  simp

section GeneratedLift

variable {Z : Type*} [AddCommGroup Z] [Lattice Z] [IsOrderedAddMonoid Z]
  [VectorLattice Z]

/-- The lifting equivalence for the vector sublattice generated by a lattice-linearly
independent family. -/
noncomputable def liftGenerated (x : α → X) (hx : LatticeLinearIndependent x) :
    (α → Z) ≃
      VecLatHom (↥(VectorSublattice.generated (Set.range x)).toSubmodule) Z where
  toFun φ := (lift φ).comp (equivGenerated x hx).symm.toVecLatHom
  invFun T := fun a => T (generatedOf x a)
  left_inv φ := by
    funext a
    change (lift φ) ((equivGenerated x hx).symm (generatedOf x a)) = φ a
    rw [equivGenerated_symm_generatedOf, lift_of]
  right_inv T := by
    apply DFunLike.ext
    intro y
    obtain ⟨f, rfl⟩ := (equivGenerated x hx).toLinearEquiv.surjective y
    have hsymm :
        (equivGenerated x hx).symm ((equivGenerated x hx) f) = f := by
      change (equivGenerated x hx).toLinearEquiv.symm
          ((equivGenerated x hx).toLinearEquiv f) = f
      exact LinearEquiv.left_inv (equivGenerated x hx).toLinearEquiv f
    have hhom :
        lift (fun a => T (generatedOf x a)) =
          T.comp (equivGenerated x hx).toVecLatHom := by
      apply hom_ext
      intro a
      rw [VecLatHom.comp_apply, lift_of]
      change T (generatedOf x a) = T (equivGenerated x hx (of a))
      simp
    calc
      ((lift (fun a => T (generatedOf x a))).comp
          (equivGenerated x hx).symm.toVecLatHom) ((equivGenerated x hx) f)
          = lift (fun a => T (generatedOf x a)) f := by
            rw [VecLatHom.comp_apply]
            change (lift fun a => T (generatedOf x a))
              ((equivGenerated x hx).symm ((equivGenerated x hx) f)) =
                (lift fun a => T (generatedOf x a)) f
            rw [hsymm]
      _ = T ((equivGenerated x hx) f) := by
            exact congrArg (fun S : VecLatHom (FVL α) Z => S f) hhom

@[simp]
theorem liftGenerated_generatedOf (x : α → X) (hx : LatticeLinearIndependent x)
    (φ : α → Z) (a : α) :
    liftGenerated x hx φ (generatedOf x a) = φ a := by
  change (lift φ) ((equivGenerated x hx).symm (generatedOf x a)) = φ a
  rw [equivGenerated_symm_generatedOf, lift_of]

/-- A vector lattice homomorphism out of the generated sublattice is determined by its values
on the independent generators. -/
theorem liftGenerated_unique (x : α → X) (hx : LatticeLinearIndependent x)
    (φ : α → Z)
    (T : VecLatHom (↥(VectorSublattice.generated (Set.range x)).toSubmodule) Z)
    (h : ∀ a, T (generatedOf x a) = φ a) :
    T = liftGenerated x hx φ := by
  have hsymm : (liftGenerated x hx).symm T = φ := funext h
  calc
    T = liftGenerated x hx ((liftGenerated x hx).symm T) :=
      (Equiv.apply_symm_apply (liftGenerated x hx) T).symm
    _ = liftGenerated x hx φ := by rw [hsymm]

end GeneratedLift

end Generated

end FVL
