/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Free.FVL
import BanLat.Examples.CofK.Basic
import BanLat.Tactic.LLexpr
import Mathlib.Analysis.Normed.Module.WeakDual
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-!
# Free vector lattice over a normed space

This file gives the concrete construction of the free vector lattice over a
real normed space as the vector sublattice of `C(B_{E*}, ℝ)` generated by
evaluation functions.
-/

open scoped BigOperators

universe u v

namespace FVLv

variable (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The closed unit ball of the norm dual, equipped with the weak-star topology. -/
def dualUnitBall : Set (WeakDual ℝ E) :=
  WeakDual.toStrongDual ⁻¹' Metric.closedBall (0 : StrongDual ℝ E) 1

/-- The dual unit ball is compact for the weak-star topology. -/
noncomputable instance instCompactSpaceDualUnitBall : CompactSpace (dualUnitBall E) := by
  exact isCompact_iff_compactSpace.mp
    (WeakDual.isCompact_closedBall (𝕜 := ℝ) (E := E) (0 : StrongDual ℝ E) 1)

/-- The restriction of the evaluation functional `x̂` to the weak-star compact dual unit ball. -/
noncomputable def dualEval (x : E) : C(dualUnitBall E, ℝ) where
  toFun φ := (φ : WeakDual ℝ E) x
  continuous_toFun := by
    exact (WeakDual.eval_continuous x).comp continuous_subtype_val

@[simp]
theorem dualEval_apply (x : E) (φ : dualUnitBall E) :
    dualEval E x φ = (φ : WeakDual ℝ E) x := by
  rfl

/-- The concrete vector sublattice of `C(B_{E*}, ℝ)` generated by the evaluation maps. -/
noncomputable def concreteSublattice : VectorSublattice C(dualUnitBall E, ℝ) :=
  VectorSublattice.generated (Set.range (dualEval E : E → C(dualUnitBall E, ℝ)))

private def subtypeHom {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
    [VectorLattice X] (Y : VectorSublattice X) :
    VecLatHom ↥Y.toSubmodule X where
  toFun y := y
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

private theorem eval_coe_submodule {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (Y : VectorSublattice X)
    (y : Fin n → ↥Y.toSubmodule) (e : LLexpr n) :
    ((LLexpr.eval y e : ↥Y.toSubmodule) : X) =
      LLexpr.eval (fun i => (y i : X)) e := by
  have hsubtype (z : ↥Y.toSubmodule) : subtypeHom Y z = (z : X) := rfl
  simpa only [hsubtype] using (LLexpr.map_eval (subtypeHom Y) y e)

end FVLv

/-- The free vector lattice over a real normed space, realized inside `C(B_{E*}, ℝ)`. -/
abbrev FVLv (E : Type u) [NormedAddCommGroup E] [NormedSpace ℝ E] :
    Type _ :=
  ↥(FVLv.concreteSublattice E).toSubmodule

namespace FVLv

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E]

noncomputable instance instLattice : Lattice (FVLv E) :=
  inferInstanceAs (Lattice ↥(concreteSublattice E).toSubmodule)

instance instIsOrderedAddMonoid : IsOrderedAddMonoid (FVLv E) :=
  inferInstanceAs (IsOrderedAddMonoid ↥(concreteSublattice E).toSubmodule)

noncomputable instance instVectorLattice : VectorLattice (FVLv E) :=
  inferInstanceAs (VectorLattice ↥(concreteSublattice E).toSubmodule)

noncomputable instance instCoeFun : CoeFun (FVLv E) (fun _ => dualUnitBall E → ℝ) where
  coe f := f.1

noncomputable instance instCoeContinuousMap : Coe (FVLv E) C(dualUnitBall E, ℝ) where
  coe f := f.1

@[simp]
theorem add_apply (f g : FVLv E) (φ : dualUnitBall E) :
    (f + g : FVLv E) φ = f φ + g φ := by
  rfl

@[simp]
theorem smul_apply (r : ℝ) (f : FVLv E) (φ : dualUnitBall E) :
    (r • f : FVLv E) φ = r * f φ := by
  rfl

@[simp]
theorem sup_apply (f g : FVLv E) (φ : dualUnitBall E) :
    (f ⊔ g : FVLv E) φ = f φ ⊔ g φ := by
  rfl

@[simp]
theorem inf_apply (f g : FVLv E) (φ : dualUnitBall E) :
    (f ⊓ g : FVLv E) φ = f φ ⊓ g φ := by
  rfl

/-- Order on `FVLv E` is inherited pointwise from `C(B_{E*}, ℝ)`. -/
theorem le_def {f g : FVLv E} : f ≤ g ↔ ∀ φ : dualUnitBall E, f φ ≤ g φ := by
  rfl

/-- The canonical embedding of `E` into its free vector lattice. -/
noncomputable def of (x : E) : FVLv E :=
  ⟨dualEval E x, VectorSublattice.subset_generated _ ⟨x, rfl⟩⟩

@[simp]
theorem coe_of (x : E) :
    ((of x : FVLv E) : C(dualUnitBall E, ℝ)) = dualEval E x := by
  rfl

theorem of_apply (x : E) (φ : dualUnitBall E) :
    (of x : FVLv E) φ = (φ : WeakDual ℝ E) x := by
  rfl

/-- The canonical map `E → FVLv E`, bundled as a real-linear map. -/
noncomputable def ofLinear : E →ₗ[ℝ] FVLv E where
  toFun := of
  map_add' := by
    intro x y
    ext φ
    exact (φ : WeakDual ℝ E).map_add x y
  map_smul' := by
    intro r x
    ext φ
    exact (φ : WeakDual ℝ E).map_smul r x

@[simp]
theorem ofLinear_apply (x : E) : ofLinear x = of x := by
  rfl

@[simp]
theorem of_zero : of (0 : E) = 0 := by
  ext φ
  exact (φ : WeakDual ℝ E).map_zero

@[simp]
theorem of_add (x y : E) : of (x + y) = of x + of y := by
  exact (ofLinear (E := E)).map_add x y

@[simp]
theorem of_smul (r : ℝ) (x : E) : of (r • x) = r • of x := by
  exact (ofLinear (E := E)).map_smul r x

/-- The canonical map into `FVLv E` is injective. -/
theorem of_injective : Function.Injective (of : E → FVLv E) := by
  intro x y hxy
  by_contra hne
  obtain ⟨φ, hφnorm, hφ⟩ := exists_dual_vector'' ℝ (x - y)
  let ψ : dualUnitBall E := ⟨StrongDual.toWeakDual φ, by
    dsimp [dualUnitBall]
    simpa [Metric.mem_closedBall, dist_eq_norm] using hφnorm⟩
  have hval := congrArg (fun f : FVLv E => f ψ) hxy
  have hzero : φ (x - y) = 0 := by
    rw [map_sub, sub_eq_zero]
    simpa [ψ] using hval
  have hnorm_zero : ‖x - y‖ = 0 := by
    simpa [hzero] using hφ.symm
  exact hne (sub_eq_zero.mp (norm_eq_zero.mp hnorm_zero))

/-- The canonical linear map has trivial kernel. -/
theorem ker_ofLinear : LinearMap.ker (ofLinear (E := E)) = ⊥ := by
  exact LinearMap.ker_eq_bot.mpr (of_injective (E := E))

private theorem exists_eval_of_eq (f : FVLv E) :
    ∃ (n : ℕ) (x : Fin n → E) (e : LLexpr n),
      LLexpr.eval (fun i => of (x i)) e = f := by
  classical
  have hf : (f : C(dualUnitBall E, ℝ)) ∈
      (VectorSublattice.generated
        (Set.range (dualEval E : E → C(dualUnitBall E, ℝ))) :
        Set C(dualUnitBall E, ℝ)) := f.2
  rw [LLexpr.generated_eq_iUnion_combinations
    (Set.range (dualEval E : E → C(dualUnitBall E, ℝ)))] at hf
  simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range] at hf
  obtain ⟨n, z, e, he⟩ := hf
  choose x hx using fun i : Fin n => (z i).2
  refine ⟨n, x, e, ?_⟩
  apply Subtype.ext
  calc
    ((LLexpr.eval (fun i : Fin n => of (x i)) e : FVLv E) :
        C(dualUnitBall E, ℝ))
        = LLexpr.eval (fun i : Fin n => dualEval E (x i)) e := by
          exact eval_coe_submodule (concreteSublattice E) (fun i : Fin n => of (x i)) e
    _ = LLexpr.eval (fun i : Fin n => (z i : C(dualUnitBall E, ℝ))) e := by
          congr
          funext i
          rw [hx i]
    _ = f := he

/-- The canonical generators generate `FVLv E` as a vector sublattice. -/
theorem generated_range_of :
    VectorSublattice.generated (Set.range (of : E → FVLv E)) = ⊤ := by
  apply le_antisymm
  · intro f _
    exact VectorSublattice.mem_top
  · intro f _
    change f ∈ (VectorSublattice.generated (Set.range (of : E → FVLv E)) : Set (FVLv E))
    obtain ⟨n, x, e, he⟩ := exists_eval_of_eq (E := E) f
    rw [← he]
    rw [LLexpr.generated_eq_iUnion_combinations (Set.range (of : E → FVLv E))]
    simp only [Set.mem_iUnion, LLexpr.combinations, Set.mem_range]
    refine ⟨n, fun i : Fin n => ⟨of (x i), ⟨x i, rfl⟩⟩, e, ?_⟩
    rfl

private noncomputable def equivTopOfEq {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (Y : VectorSublattice X) (hY : Y = ⊤) :
    VecLatEquiv ↥Y.toSubmodule X :=
  { LinearEquiv.ofBijective (subtypeHom Y).toLinearMap
      ⟨by
        intro a b h
        ext
        exact h,
       by
        intro x
        refine ⟨⟨x, ?_⟩, rfl⟩
        rw [hY]
        exact VectorSublattice.mem_top⟩ with
    map_sup' := fun _ _ => rfl
    map_inf' := fun _ _ => rfl }

private noncomputable def evalHom (φ : dualUnitBall E) : VecLatHom (FVLv E) ℝ where
  toFun f := f φ
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

private theorem eval_apply {n : ℕ} (y : Fin n → FVLv E) (e : LLexpr n)
    (φ : dualUnitBall E) :
    LLexpr.eval y e φ = LLexpr.eval (fun i => y i φ) e := by
  have heval (f : FVLv E) : evalHom φ f = f φ := rfl
  simpa only [heval] using (LLexpr.map_eval (evalHom φ) y e)

private theorem eval_const_smul_of_nonneg {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (c : ℝ) (hc : 0 ≤ c)
    (x : Fin n → X) (e : LLexpr n) :
    LLexpr.eval (fun i => c • x i) e = c • LLexpr.eval x e := by
  induction e with
  | zero => simp [LLexpr.eval]
  | var i => rfl
  | add e₁ e₂ h₁ h₂ => simp [LLexpr.eval, h₁, h₂, smul_add]
  | smul r e h =>
      rw [LLexpr.eval_smul, h, LLexpr.eval_smul, smul_smul, smul_smul, mul_comm]
  | sup e₁ e₂ h₁ h₂ =>
      rw [LLexpr.eval_sup, h₁, h₂, LLexpr.eval_sup, nonneg_smul_sup _ _ c hc]
  | inf e₁ e₂ h₁ h₂ =>
      rw [LLexpr.eval_inf, h₁, h₂, LLexpr.eval_inf, nonneg_smul_inf _ _ c hc]

private theorem exists_strongDual_apply_eq_of_linearIndependent {n : ℕ} {x : Fin n → E}
    (hx : LinearIndependent ℝ x) (r : Fin n → ℝ) :
    ∃ φ : StrongDual ℝ E, ∀ i, φ (x i) = r i := by
  classical
  let p : Submodule ℝ E := Submodule.span ℝ (Set.range x)
  haveI : FiniteDimensional ℝ p :=
    FiniteDimensional.span_of_finite (K := ℝ) (A := Set.range x) (Set.finite_range x)
  let coeff : p →ₗ[ℝ] Fin n → ℝ :=
    (Finsupp.linearEquivFunOnFinite ℝ ℝ (Fin n)).toLinearMap.comp hx.repr
  let f : p →L[ℝ] Fin n → ℝ := LinearMap.toContinuousLinearMap coeff
  obtain ⟨g, hg⟩ := f.exist_extension_of_finiteDimensional_range
  let φ : StrongDual ℝ E := ∑ i : Fin n, r i • (ContinuousLinearMap.proj i).comp g
  refine ⟨φ, ?_⟩
  intro i
  let xi : p := ⟨x i, Submodule.subset_span ⟨i, rfl⟩⟩
  have hcoeff : f xi = Pi.single i (1 : ℝ) := by
    change (Finsupp.linearEquivFunOnFinite ℝ ℝ (Fin n)) (hx.repr xi) = Pi.single i 1
    rw [hx.repr_eq_single i xi rfl]
    exact Finsupp.linearEquivFunOnFinite_single (R := ℝ) (M := ℝ) (α := Fin n) i 1
  have hgxi : g (x i) = Pi.single i (1 : ℝ) := by
    have h := congrArg (fun u : p →L[ℝ] Fin n → ℝ => u xi) hg
    simpa [f, xi, hcoeff] using h.symm
  calc
    φ (x i) =
        ∑ j : Fin n, r j * ((Pi.single i (1 : ℝ) : Fin n → ℝ) j) := by
      simp [φ, hgxi, ContinuousLinearMap.proj_apply]
    _ = r i := by
      rw [Finset.sum_eq_single i]
      · simp
      · intro j _ hji
        have hsingle : ((Pi.single i (1 : ℝ) : Fin n → ℝ) j) = 0 :=
          by
            simpa only using
              (Pi.single_eq_of_ne (M := fun _ : Fin n => ℝ) hji (1 : ℝ))
        simp [hsingle]
      · intro hi
        exact (hi (Finset.mem_univ i)).elim

/-- The image of every linearly independent finite family in `E` is lattice-linearly independent
in `FVLv E`. -/
theorem latticeLinearIndependent_of_linearIndependent {n : ℕ} {x : Fin n → E}
    (hx : LinearIndependent ℝ x) :
    FVL.LatticeLinearIndependent (fun i : Fin n => of (x i)) := by
  intro m a ha e hzero r
  have hxa : LinearIndependent ℝ (fun i : Fin m => x (a i)) := hx.comp a ha
  obtain ⟨φ, hφ⟩ := exists_strongDual_apply_eq_of_linearIndependent hxa r
  let c : ℝ := max ‖φ‖ 1
  have hc_pos : 0 < c := lt_of_lt_of_le zero_lt_one (le_max_right _ _)
  have hc_nonneg : 0 ≤ c := hc_pos.le
  have hφ_norm_le : ‖φ‖ ≤ c := le_max_left _ _
  have hscaled_norm : ‖c⁻¹ • φ‖ ≤ 1 := by
    rw [norm_smul, Real.norm_of_nonneg (inv_nonneg.mpr hc_nonneg)]
    have h := mul_le_mul_of_nonneg_left hφ_norm_le (inv_nonneg.mpr hc_nonneg)
    simpa [inv_mul_cancel₀ hc_pos.ne'] using h
  let ψ : dualUnitBall E := ⟨StrongDual.toWeakDual (c⁻¹ • φ), by
    dsimp [dualUnitBall]
    simpa [Metric.mem_closedBall, dist_eq_norm] using hscaled_norm⟩
  have hunit_eval : LLexpr.eval (fun i : Fin m => c⁻¹ * r i) e = 0 := by
    have happly := congrArg (fun f : FVLv E => f ψ) hzero
    have happly' : LLexpr.eval (fun i : Fin m => (of (x (a i)) : FVLv E) ψ) e = 0 := by
      simpa [eval_apply] using happly
    have hscaled :
        (fun i : Fin m => (c⁻¹ • StrongDual.toWeakDual φ) (x (a i))) =
          fun i : Fin m => c⁻¹ * r i := by
      funext i
      change c⁻¹ * (StrongDual.toWeakDual φ) (x (a i)) = c⁻¹ * r i
      rw [StrongDual.toWeakDual_apply, hφ i]
    simpa [ψ, hscaled] using happly'
  have hscale :
      LLexpr.eval r e = c • LLexpr.eval (fun i : Fin m => c⁻¹ * r i) e := by
    have h :=
      eval_const_smul_of_nonneg (X := ℝ) c hc_nonneg (fun i : Fin m => c⁻¹ * r i) e
    have hfun : (fun i : Fin m => c • (c⁻¹ * r i)) = r := by
      funext i
      change c * (c⁻¹ * r i) = r i
      rw [← mul_assoc, mul_inv_cancel₀ hc_pos.ne', one_mul]
    have hfun' : (fun i : Fin m => c * (c⁻¹ * r i)) = r := by
      funext i
      rw [← mul_assoc, mul_inv_cancel₀ hc_pos.ne', one_mul]
    simpa [hfun, hfun'] using h
  rw [hscale, hunit_eval, smul_zero]

private theorem latticeLinearIndependent_of_basis {ι : Type v} (b : Module.Basis ι ℝ E) :
    FVL.LatticeLinearIndependent (fun i : ι => of (b i)) := by
  intro n a ha e hzero
  have hli : FVL.LatticeLinearIndependent (fun i : Fin n => of ((fun j => b (a j)) i)) :=
    latticeLinearIndependent_of_linearIndependent (x := fun j : Fin n => b (a j))
      (b.linearIndependent.comp a ha)
  exact hli (fun i : Fin n => i) Function.injective_id e hzero

private theorem of_mem_generated_basis {ι : Type v} (b : Module.Basis ι ℝ E) (x : E) :
    of x ∈ VectorSublattice.generated (Set.range fun i : ι => of (b i)) := by
  classical
  let Y : VectorSublattice (FVLv E) :=
    VectorSublattice.generated (Set.range fun i : ι => of (b i))
  have hsum_mem :
      Finsupp.linearCombination ℝ (fun i : ι => of (b i)) (b.repr x) ∈ Y := by
    rw [Finsupp.linearCombination_apply, Finsupp.sum]
    exact Submodule.sum_mem _ fun i _ =>
      Y.toSubmodule.smul_mem _ (VectorSublattice.subset_generated _ ⟨i, rfl⟩)
  have hmap :
      of (Finsupp.linearCombination ℝ b (b.repr x)) =
        Finsupp.linearCombination ℝ (fun i : ι => of (b i)) (b.repr x) := by
    change ofLinear (Finsupp.linearCombination ℝ b (b.repr x)) =
      Finsupp.linearCombination ℝ (fun i : ι => of (b i)) (b.repr x)
    rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply, map_finsuppSum]
    simp [ofLinear_apply]
  rw [← b.linearCombination_repr x]
  rw [hmap]
  exact hsum_mem

private theorem generated_range_of_basis {ι : Type v} (b : Module.Basis ι ℝ E) :
    VectorSublattice.generated (Set.range fun i : ι => of (b i)) = ⊤ := by
  apply le_antisymm
  · intro f _
    exact VectorSublattice.mem_top
  · rw [← generated_range_of (E := E)]
    exact VectorSublattice.generated_le (by
      rintro _ ⟨x, rfl⟩
      exact of_mem_generated_basis b x)

/-- The modulus of a supremum is bounded by the sum of the moduli. -/
theorem abs_sup_le_add_abs {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (x y : X) :
    |x ⊔ y| ≤ |x| + |y| := by
  llarith

/-- The modulus of an infimum is bounded by the sum of the moduli. -/
theorem abs_inf_le_add_abs {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] (x y : X) :
    |x ⊓ y| ≤ |x| + |y| := by
  llarith

private theorem sum_abs_nonneg {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (x : Fin n → X) :
    0 ≤ ∑ i : Fin n, |x i| := by
  exact Finset.sum_nonneg fun i _ => abs_nonneg (x i)

private theorem exists_abs_eval_le_const_sum_abs {X : Type*} [AddCommGroup X] [Lattice X]
    [IsOrderedAddMonoid X] [VectorLattice X] {n : ℕ} (x : Fin n → X) (e : LLexpr n) :
    ∃ c : ℝ, 0 < c ∧ |LLexpr.eval x e| ≤ c • (∑ i : Fin n, |x i|) := by
  induction e with
  | zero =>
      refine ⟨1, zero_lt_one, ?_⟩
      simpa [LLexpr.eval] using sum_abs_nonneg x
  | var i =>
      refine ⟨1, zero_lt_one, ?_⟩
      have hsum : |x i| ≤ ∑ j : Fin n, |x j| := by
        exact Finset.single_le_sum (fun j _ => abs_nonneg (x j)) (Finset.mem_univ i)
      simpa [LLexpr.eval] using hsum
  | add e₁ e₂ h₁ h₂ =>
      obtain ⟨c₁, hc₁, hle₁⟩ := h₁
      obtain ⟨c₂, hc₂, hle₂⟩ := h₂
      refine ⟨c₁ + c₂, add_pos hc₁ hc₂, ?_⟩
      calc
        |LLexpr.eval x (LLexpr.add e₁ e₂)| ≤ |LLexpr.eval x e₁| + |LLexpr.eval x e₂| := by
          rw [LLexpr.eval_add]
          exact abs_add_le _ _
        _ ≤ c₁ • (∑ i : Fin n, |x i|) + c₂ • (∑ i : Fin n, |x i|) :=
          add_le_add hle₁ hle₂
        _ = (c₁ + c₂) • (∑ i : Fin n, |x i|) := by rw [add_smul]
  | smul r e h =>
      obtain ⟨c, hc, hle⟩ := h
      refine ⟨|r| * c + 1,
        add_pos_of_nonneg_of_pos (mul_nonneg (abs_nonneg r) hc.le) zero_lt_one, ?_⟩
      calc
        |LLexpr.eval x (LLexpr.smul r e)| = |r| • |LLexpr.eval x e| := by
          rw [LLexpr.eval_smul, abs_smul']
        _ ≤ |r| • (c • (∑ i : Fin n, |x i|)) :=
          smul_le_smul_of_nonneg_left hle (abs_nonneg r)
        _ = (|r| * c) • (∑ i : Fin n, |x i|) := by rw [smul_smul]
        _ ≤ (|r| * c + 1) • (∑ i : Fin n, |x i|) := by
          exact smul_le_smul_of_nonneg_right (le_add_of_nonneg_right zero_le_one)
            (sum_abs_nonneg x)
  | sup e₁ e₂ h₁ h₂ =>
      obtain ⟨c₁, hc₁, hle₁⟩ := h₁
      obtain ⟨c₂, hc₂, hle₂⟩ := h₂
      refine ⟨c₁ + c₂, add_pos hc₁ hc₂, ?_⟩
      calc
        |LLexpr.eval x (LLexpr.sup e₁ e₂)| ≤ |LLexpr.eval x e₁| + |LLexpr.eval x e₂| := by
          rw [LLexpr.eval_sup]
          exact abs_sup_le_add_abs _ _
        _ ≤ c₁ • (∑ i : Fin n, |x i|) + c₂ • (∑ i : Fin n, |x i|) :=
          add_le_add hle₁ hle₂
        _ = (c₁ + c₂) • (∑ i : Fin n, |x i|) := by rw [add_smul]
  | inf e₁ e₂ h₁ h₂ =>
      obtain ⟨c₁, hc₁, hle₁⟩ := h₁
      obtain ⟨c₂, hc₂, hle₂⟩ := h₂
      refine ⟨c₁ + c₂, add_pos hc₁ hc₂, ?_⟩
      calc
        |LLexpr.eval x (LLexpr.inf e₁ e₂)| ≤ |LLexpr.eval x e₁| + |LLexpr.eval x e₂| := by
          rw [LLexpr.eval_inf]
          exact abs_inf_le_add_abs _ _
        _ ≤ c₁ • (∑ i : Fin n, |x i|) + c₂ • (∑ i : Fin n, |x i|) :=
          add_le_add hle₁ hle₂
        _ = (c₁ + c₂) • (∑ i : Fin n, |x i|) := by rw [add_smul]

/-- The sublattice generated by a linearly independent finite family is a free vector lattice on
that finite set. -/
noncomputable def equivGeneratedOfLinearIndependent {n : ℕ} (x : Fin n → E)
    (hx : LinearIndependent ℝ x) :
    VecLatEquiv (FVL (Fin n))
      ↥(VectorSublattice.generated (Set.range fun i : Fin n => of (x i))).toSubmodule := by
  exact FVL.equivGenerated (fun i : Fin n => of (x i))
    (latticeLinearIndependent_of_linearIndependent hx)

/-- For a Hamel basis of `E`, `FVLv E` is vector-lattice isomorphic to the free vector lattice
on the index set of the basis. -/
noncomputable def equivFVLOfBasis {ι : Type v} (b : Module.Basis ι ℝ E) :
    VecLatEquiv (FVL ι) (FVLv E) := by
  exact
    (FVL.equivGenerated (fun i : ι => of (b i)) (latticeLinearIndependent_of_basis b)).trans
      (equivTopOfEq _ (generated_range_of_basis b))

private theorem equivFVLOfBasis_of {ι : Type*} (b : Module.Basis ι ℝ E) (i : ι) :
    equivFVLOfBasis b (FVL.of i) = of (b i) := by
  change (equivTopOfEq
      (VectorSublattice.generated (Set.range fun i : ι => of (b i)))
      (generated_range_of_basis b))
    (FVL.equivGenerated (fun i : ι => of (b i)) (latticeLinearIndependent_of_basis b)
      (FVL.of i)) = of (b i)
  rw [FVL.equivGenerated_of]
  rfl

private theorem equivFVLOfBasis_symm_of_basis {ι : Type*} (b : Module.Basis ι ℝ E) (i : ι) :
    (equivFVLOfBasis b).symm (of (b i)) = FVL.of i := by
  change (equivFVLOfBasis b).toLinearEquiv.symm (of (b i)) = FVL.of i
  rw [LinearEquiv.symm_apply_eq]
  exact (equivFVLOfBasis_of b i).symm

/-- Every element of `FVLv E` is dominated by a finite positive linear combination of moduli of
canonical generators from the unit ball of `E`. -/
theorem exists_abs_le_finite_sum_abs_of (f : FVLv E) :
    ∃ (n : ℕ) (x : Fin n → E) (c : ℝ), 0 < c ∧ (∀ i, ‖x i‖ ≤ 1) ∧
      |f| ≤ c • (∑ i : Fin n, |of (x i)|) := by
  classical
  obtain ⟨n, x, e, he⟩ := exists_eval_of_eq (E := E) f
  obtain ⟨c, hc, hle⟩ := exists_abs_eval_le_const_sum_abs (fun i : Fin n => of (x i)) e
  let M : ℝ := max (∑ i : Fin n, ‖x i‖) 1
  have hM_pos : 0 < M := lt_of_lt_of_le zero_lt_one (le_max_right _ _)
  have hM_nonneg : 0 ≤ M := hM_pos.le
  let y : Fin n → E := fun i => M⁻¹ • x i
  refine ⟨n, y, c * M, mul_pos hc hM_pos, ?_, ?_⟩
  · intro i
    rw [norm_smul, Real.norm_of_nonneg (inv_nonneg.mpr hM_nonneg)]
    have hxi_sum : ‖x i‖ ≤ ∑ j : Fin n, ‖x j‖ := by
      exact Finset.single_le_sum (fun j _ => norm_nonneg (x j)) (Finset.mem_univ i)
    have hxi_M : ‖x i‖ ≤ M := hxi_sum.trans (le_max_left _ _)
    have h := mul_le_mul_of_nonneg_left hxi_M (inv_nonneg.mpr hM_nonneg)
    simpa [inv_mul_cancel₀ hM_pos.ne'] using h
  · have hsum_eq :
        (∑ i : Fin n, |of (x i)|) = M • (∑ i : Fin n, |of (y i)|) := by
      calc
        (∑ i : Fin n, |of (x i)|) = ∑ i : Fin n, |M • of (y i)| := by
          apply Finset.sum_congr rfl
          intro i _
          congr 1
          change of (x i) = M • of (M⁻¹ • x i)
          rw [← of_smul, smul_smul, mul_inv_cancel₀ hM_pos.ne', one_smul]
        _ = ∑ i : Fin n, M • |of (y i)| := by
          apply Finset.sum_congr rfl
          intro i _
          rw [abs_smul', abs_of_nonneg hM_nonneg]
        _ = M • (∑ i : Fin n, |of (y i)|) := by rw [Finset.smul_sum]
    calc
      |f| = |LLexpr.eval (fun i : Fin n => of (x i)) e| := by rw [he]
      _ ≤ c • (∑ i : Fin n, |of (x i)|) := hle
      _ = (c * M) • (∑ i : Fin n, |of (y i)|) := by rw [hsum_eq, smul_smul]

section Lift

variable {Y : Type v} [AddCommGroup Y] [Lattice Y] [IsOrderedAddMonoid Y]
  [VectorLattice Y]

private noncomputable def liftOfBasis {ι : Type*} (b : Module.Basis ι ℝ E)
    (T : E →ₗ[ℝ] Y) : VecLatHom (FVLv E) Y :=
  (FVL.lift (fun i => T (b i))).comp (equivFVLOfBasis b).symm.toVecLatHom

private theorem liftOfBasis_of {ι : Type*} (b : Module.Basis ι ℝ E)
    (T : E →ₗ[ℝ] Y) (x : E) : liftOfBasis b T (of x) = T x := by
  let L : E →ₗ[ℝ] Y := (liftOfBasis b T).toLinearMap.comp (ofLinear (E := E))
  have hL : L = T := by
    apply b.ext
    intro i
    change liftOfBasis b T (of (b i)) = T (b i)
    rw [liftOfBasis, VecLatHom.comp_apply]
    change (FVL.lift fun i => T (b i)) ((equivFVLOfBasis b).symm (of (b i))) = T (b i)
    rw [equivFVLOfBasis_symm_of_basis, FVL.lift_of]
  exact congrArg (fun L : E →ₗ[ℝ] Y => L x) hL

private theorem hom_ext_of {S T : VecLatHom (FVLv E) Y}
    (h : ∀ x, S (of x) = T (of x)) : S = T := by
  apply DFunLike.ext
  intro f
  obtain ⟨n, x, e, he⟩ := exists_eval_of_eq (E := E) f
  calc
    S f = S (LLexpr.eval (fun i : Fin n => of (x i)) e) := by rw [he]
    _ = LLexpr.eval (fun i : Fin n => S (of (x i))) e := by
      exact LLexpr.map_eval S (fun i : Fin n => of (x i)) e
    _ = LLexpr.eval (fun i : Fin n => T (of (x i))) e := by
      congr
      funext i
      rw [h]
    _ = T (LLexpr.eval (fun i : Fin n => of (x i)) e) := by
      exact (LLexpr.map_eval T (fun i : Fin n => of (x i)) e).symm
    _ = T f := by rw [he]

/-- The universal property of `FVLv E`: linear maps from `E` to a vector lattice `Y` are exactly
vector lattice homomorphisms from `FVLv E` to `Y`. -/
noncomputable def lift : (E →ₗ[ℝ] Y) ≃ VecLatHom (FVLv E) Y := by
  classical
  let b := Module.Free.chooseBasis ℝ E
  refine
    { toFun := liftOfBasis b
      invFun := fun S => S.toLinearMap.comp (ofLinear (E := E))
      left_inv := ?_
      right_inv := ?_ }
  · intro T
    ext x
    exact liftOfBasis_of b T x
  · intro S
    apply hom_ext_of
    intro x
    exact liftOfBasis_of b (S.toLinearMap.comp (ofLinear (E := E))) x

@[simp]
theorem lift_of (T : E →ₗ[ℝ] Y) (x : E) : lift T (of x) = T x := by
  change liftOfBasis (Module.Free.chooseBasis ℝ E) T (of x) = T x
  exact liftOfBasis_of (Module.Free.chooseBasis ℝ E) T x

@[simp]
theorem lift_comp_of (T : VecLatHom (FVLv E) Y) :
    lift (T.toLinearMap.comp (ofLinear (E := E))) = T := by
  simpa [lift] using Equiv.apply_symm_apply (lift (E := E) (Y := Y)) T

/-- A vector lattice homomorphism out of `FVLv E` is uniquely determined by its values on `E`. -/
theorem lift_unique (T : E →ₗ[ℝ] Y) (S : VecLatHom (FVLv E) Y)
    (h : ∀ x, S (of x) = T x) : S = lift T := by
  calc
    S = lift (S.toLinearMap.comp (ofLinear (E := E))) := (lift_comp_of S).symm
    _ = lift T := by
      congr
      ext x
      exact h x

@[ext]
theorem hom_ext {S T : VecLatHom (FVLv E) Y} (h : ∀ x, S (of x) = T (of x)) :
    S = T := by
  exact hom_ext_of h

end Lift

section Map

variable {F : Type v} [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- The vector lattice homomorphism induced by a real-linear map of normed spaces. -/
noncomputable def map (T : E →ₗ[ℝ] F) : VecLatHom (FVLv E) (FVLv F) :=
  lift ((ofLinear (E := F)).comp T)

@[simp]
theorem map_of (T : E →ₗ[ℝ] F) (x : E) : map T (of x) = of (T x) := by
  exact lift_of ((ofLinear (E := F)).comp T) x

end Map

end FVLv
