/-
Authors: Jesús Illescas-Fiorito
-/

import BanLat.AMSpace.Basic
import BanLat.ComplexBanachLattice.Basic

/-!
# Complex AM-spaces

A **complex AM-space** is a complex Banach lattice whose self-adjoint part satisfies the
AM-axiom on disjoint elements, that is, is a real AM-space.

It becomes a **complex AM-space with unit** if its self-adjoint part has a strong order unit
whose gauge norm agrees with the original norm, that is, if its self-adjoint part is a real
AM-space with unit.
-/

open scoped ComplexStarModule

/-- A **complex AM-space** is a complex Banach lattice whose self-adjoint part satisfies the
AM-space norm axiom. -/
class ComplexAMSpace (Z : Type*) [NormedAddCommGroup Z] [NormedSpace ℂ Z]
    [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
    [IsOrderedAddMonoid (selfAdjoint Z)] extends ComplexBanachLattice Z where
  norm_add_eq_max_of_inf_eq_zero {x y : selfAdjoint Z} (hxy : x ⊓ y = 0) :
    ‖x + y‖ = max ‖x‖ ‖y‖

/-- The self-adjoint part of a complex AM-space is a real AM-space. -/
instance ComplexAMSpace.instAMSpaceSelfAdjoint {Z : Type*}
    [NormedAddCommGroup Z] [NormedSpace ℂ Z]
    [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
    [IsOrderedAddMonoid (selfAdjoint Z)] [ComplexAMSpace Z] :
    AMSpace (selfAdjoint Z) where
  norm_add_eq_max_of_inf_eq_zero := ComplexAMSpace.norm_add_eq_max_of_inf_eq_zero

namespace ComplexAMSpace

variable {Z : Type*} [NormedAddCommGroup Z] [NormedSpace ℂ Z]
  [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
  [IsOrderedAddMonoid (selfAdjoint Z)] [ComplexAMSpace Z]

/-- In a complex AM-space, the norm of the supremum of two disjoint self-adjoint elements is the
maximum of their norms. -/
theorem norm_sup_eq_max_of_inf_eq_zero {x y : selfAdjoint Z} (hxy : x ⊓ y = 0) :
    ‖x ⊔ y‖ = max ‖x‖ ‖y‖ :=
  AMSpace.norm_sup_eq_max_of_inf_eq_zero hxy

end ComplexAMSpace

/-- A **complex AM-space with unit** has a distinguished strong order unit in its
self-adjoint part whose gauge norm agrees with the original norm. -/
class ComplexAMSpaceWithUnit (Z : Type*) [NormedAddCommGroup Z] [NormedSpace ℂ Z]
    [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
    [IsOrderedAddMonoid (selfAdjoint Z)] extends ComplexAMSpace Z where
  unit : selfAdjoint Z
  strongOrderUnit_unit : StrongOrderUnit unit
  norm_eq_gaugeNorm : ∀ x : selfAdjoint Z, ‖x‖ = OrderIdeal.gaugeNorm unit x

/-- The self-adjoint part of a complex AM-space with unit is a real AM-space with unit. -/
instance ComplexAMSpaceWithUnit.instAMSpaceWithUnitSelfAdjoint {Z : Type*}
    [NormedAddCommGroup Z] [NormedSpace ℂ Z]
    [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
    [IsOrderedAddMonoid (selfAdjoint Z)] [ComplexAMSpaceWithUnit Z] :
    AMSpaceWithUnit (selfAdjoint Z) where
  unit := ComplexAMSpaceWithUnit.unit
  strongOrderUnit_unit := ComplexAMSpaceWithUnit.strongOrderUnit_unit
  norm_eq_gaugeNorm := ComplexAMSpaceWithUnit.norm_eq_gaugeNorm

namespace ComplexAMSpaceWithUnit

variable {Z : Type*} [NormedAddCommGroup Z] [NormedSpace ℂ Z]
  [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
  [IsOrderedAddMonoid (selfAdjoint Z)] [ComplexAMSpaceWithUnit Z]

/-- The distinguished unit is nonnegative in the self-adjoint part. -/
theorem unit_nonneg : 0 ≤ (ComplexAMSpaceWithUnit.unit : selfAdjoint Z) :=
  AMSpaceWithUnit.unit_nonneg

/-- The distinguished unit is a strong order unit of the self-adjoint part. -/
theorem strongOrderUnit_unit' :
    StrongOrderUnit (ComplexAMSpaceWithUnit.unit : selfAdjoint Z) :=
  ComplexAMSpaceWithUnit.strongOrderUnit_unit

/-- The principal ideal generated by the distinguished unit is
the whole self-adjoint part. -/
theorem principal_unit_eq_top :
    OrderIdeal.principal (ComplexAMSpaceWithUnit.unit : selfAdjoint Z) = ⊤ :=
  AMSpaceWithUnit.principal_unit_eq_top

end ComplexAMSpaceWithUnit
