/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Substructures.Band.PPP
import BanLat.Pi
import BanLat.OrderDense
import BanLat.Operators.Hom

/-!
# Infinite band decompositions

Let `X` be a vector lattice with the Principal Projection Property and let
`Λ ⊆ X₊` be a maximal disjoint family. Two structural results follow:

- every positive element of `X` is the supremum of its principal-band
  projections along `Λ`;
- the map sending an element to its tuple of principal-band projections is a
  vector lattice homomorphic embedding into the product of the principal
  bands, with order-dense range.

Existence of a maximal disjoint family of strictly positive elements is
established in `BanLat.Disjoint`.
-/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-! ### Principal band projections under PPP

Under the Principal Projection Property, every principal band carries a
canonical band projection, denoted `Pₐ`. -/

namespace Band

/-- Under PPP, the principal band generated by `a`, viewed as a (chosen)
projection band. -/
noncomputable def principalProjectionBand [HasPrincipalProjectionProperty X]
    (a : X) : ProjectionBand X :=
  (HasPrincipalProjectionProperty.exists_projectionBand a).choose

/-- The chosen projection band has the same underlying set as the principal
band generated by `a`. -/
theorem principalProjectionBand_coe [HasPrincipalProjectionProperty X]
    (a : X) :
    ((principalProjectionBand a : ProjectionBand X) : Set X)
      = (Band.generated ({a} : Set X) : Set X) :=
  (HasPrincipalProjectionProperty.exists_projectionBand a).choose_spec

/-- The band projection onto the principal band generated by `a`, available
under PPP. -/
noncomputable def principalBandProjection [HasPrincipalProjectionProperty X]
    (a : X) : X →ₗ[ℝ] X :=
  (principalProjectionBand a).bandProjection

end Band

/-! ### Decomposition along a maximal disjoint family -/

/-- Let `X` be a vector lattice with the Principal Projection Property and
let `Λ` be a maximal disjoint family of strictly positive elements of `X`.
For every `x ∈ X₊`, `x` is the supremum of the family of its principal-band
projections `(Pₐ x)_{a ∈ Λ}`. -/
theorem isLUB_principalBandProjection_of_isMaximalDisjoint
    [HasPrincipalProjectionProperty X] {Λ : Set X}
    (hΛ : IsMaximalDisjoint Λ) (hΛ_pos : ∀ a ∈ Λ, 0 < a)
    {x : X} (hx : 0 ≤ x) :
    IsLUB (Set.range fun a : Λ => Band.principalBandProjection (a : X) x) x := by
  haveI : IsVLArchimedean X := isVLArchimedean_of_hasPrincipalProjectionProperty
  refine ⟨?_, ?_⟩
  · rintro _ ⟨a, rfl⟩
    exact Positive.le_iff.mp
      (Band.principalProjectionBand (a : X)).bandProjection_le_id x hx
  · intro y hy
    set r : X := x - x ⊓ y with hr_def
    have hr_eq : r = (x - y)⁺ := sub_inf_eq_posPart x y
    have hr_nn : 0 ≤ r := hr_eq ▸ posPart_nonneg _
    have hyx : ∀ a ∈ Λ,
        (Band.principalProjectionBand a).bandProjection x ≤ y := by
      intro a ha
      exact hy ⟨⟨a, ha⟩, rfl⟩
    have hPar_zero : ∀ a ∈ Λ,
        (Band.principalProjectionBand a).bandProjection r = 0 := by
      intro a ha
      set B := Band.principalProjectionBand a
      have hPx_le_y : B.bandProjection x ≤ y := hyx a ha
      have hPx_le_Py : B.bandProjection x ≤ B.bandProjection y := by
        have hmono :=
          (VecLatHom.ofIsVecLatHom B.bandProjection B.bandProjection_isVecLatHom).monotone
            hPx_le_y
        have happly (z : X) :
            VecLatHom.ofIsVecLatHom B.bandProjection B.bandProjection_isVecLatHom z =
              B.bandProjection z := rfl
        have hmono' : B.bandProjection (B.bandProjection x) ≤ B.bandProjection y := by
          simpa only [happly] using hmono
        rwa [show B.bandProjection (B.bandProjection x) = B.bandProjection x from
          congrArg (fun T : X →ₗ[ℝ] X => T x) B.bandProjection_sq] at hmono'
      have hinf_eq : B.bandProjection x ⊓ B.bandProjection y = B.bandProjection x :=
        inf_eq_left.mpr hPx_le_Py
      have : B.bandProjection r =
          B.bandProjection x - B.bandProjection (x ⊓ y) := by
        rw [hr_def, map_sub]
      have hinf_apply : B.bandProjection (x ⊓ y) =
          B.bandProjection x ⊓ B.bandProjection y :=
        B.bandProjection_isVecLatHom.map_inf' x y
      rw [this, hinf_apply, hinf_eq, sub_self]
    have hr_disj : ∀ a ∈ Λ, IsVLDisjoint r a := by
      intro a ha
      set B := Band.principalProjectionBand a
      have hr_compl : r ∈ disjointComplement (B : Set X) := by
        have := B.id_sub_bandProjection_mem r
        rwa [hPar_zero a ha, sub_zero] at this
      have ha_in : a ∈ (B : Set X) := by
        rw [Band.principalProjectionBand_coe a]
        exact Band.subset_generated _ (Set.mem_singleton a)
      exact hr_compl a ha_in
    have hr_zero : r = 0 :=
      (isMaximalDisjoint_iff_forall_eq_zero hΛ_pos hΛ.1).mp hΛ r hr_disj
    have hxy : x ≤ x ⊓ y := by
      have := hr_zero
      rw [hr_def, sub_eq_zero] at this
      exact this.le
    exact le_trans hxy inf_le_right

/-- The componentwise principal band projection map, packaged as a vector
lattice homomorphism into the dependent product of principal bands. -/
private noncomputable def decompositionMap
    [HasPrincipalProjectionProperty X] (Λ : Set X) :
    VecLatHom X ((a : Λ) → ↥(Band.generated ({(a : X)} : Set X)).toSubmodule) :=
  IsVecLatHom.mk'
    (fun x (a : Λ) =>
      ⟨Band.principalBandProjection (a : X) x,
        by
          change Band.principalBandProjection (a : X) x ∈
            (Band.generated ({(a : X)} : Set X) : Set X)
          rw [← Band.principalProjectionBand_coe (a : X)]
          exact (Band.principalProjectionBand (a : X)).bandProjection_mem x⟩)
    { map_add := by
        intro x y; funext a
        apply Subtype.ext
        exact (Band.principalProjectionBand (a : X)).bandProjection.map_add x y
      map_smul := by
        intro c x; funext a
        apply Subtype.ext
        exact (Band.principalProjectionBand (a : X)).bandProjection.map_smul c x
      map_sup' := by
        intro x y; funext a
        apply Subtype.ext
        exact (Band.principalProjectionBand (a : X)).bandProjection_isVecLatHom.map_sup' x y
      map_inf' := by
        intro x y; funext a
        apply Subtype.ext
        exact (Band.principalProjectionBand (a : X)).bandProjection_isVecLatHom.map_inf' x y }

@[simp] private lemma decompositionMap_apply_coe
    [HasPrincipalProjectionProperty X] (Λ : Set X) (x : X) (a : Λ) :
    ((decompositionMap Λ x a) : X) = Band.principalBandProjection (a : X) x := rfl

/-- For two disjoint elements, the band generated by one lies in the disjoint
complement of the band generated by the other. -/
private lemma generated_singleton_subset_disjointComplement
    [HasPrincipalProjectionProperty X] {a b : X} (hdisj : IsVLDisjoint a b) :
    (Band.generated ({a} : Set X) : Set X) ⊆
      (Band.generated ({b} : Set X) : Set X)ᵈ := by
  haveI : IsVLArchimedean X := isVLArchimedean_of_hasPrincipalProjectionProperty
  -- Rewrite both sides via double/triple disjoint complement.
  rw [← Band.disjointComplement_disjointComplement_eq_generated ({a} : Set X),
      ← Band.disjointComplement_disjointComplement_eq_generated ({b} : Set X),
      disjointComplement_disjointComplement_disjointComplement]
  -- Now goal: {a}ᵈᵈ ⊆ {b}ᵈ. By anti from {a} ⊆ {b}ᵈ (which holds since
  -- a is disjoint from b), we get {b}ᵈᵈ ⊆ {a}ᵈ; then {a}ᵈᵈ ⊆ {b}ᵈᵈᵈ = {b}ᵈ.
  intro x hx c hc
  have hcb : c = b := hc
  -- x ∈ {a}ᵈᵈ means x disjoint from all of {a}ᵈ. Since b ∈ {a}ᵈ
  -- (b is disjoint from a), we get x disjoint from b.
  have hbmem : b ∈ ({a} : Set X)ᵈ := by
    intro a' ha'
    have : a' = a := ha'
    subst this
    exact isVLDisjoint_comm.mp hdisj
  rw [hcb]
  exact hx b hbmem

/-- For elements of a maximal disjoint family, the band projection of one onto
the principal band of another vanishes. -/
private lemma principalBandProjection_of_mem_generated_other
    [HasPrincipalProjectionProperty X] {Λ : Set X}
    (hΛ : IsMaximalDisjoint Λ) {a b : X} (ha : a ∈ Λ) (hb : b ∈ Λ) (hab : a ≠ b)
    {z : X} (hz : z ∈ Band.generated ({a} : Set X)) :
    Band.principalBandProjection b z = 0 := by
  set B := Band.principalProjectionBand b
  have hcoe := Band.principalProjectionBand_coe b
  have hdisj : IsVLDisjoint a b := hΛ.1.2 ha hb hab
  have hz_compl : z ∈ disjointComplement (B : Set X) := by
    rw [hcoe]
    exact generated_singleton_subset_disjointComplement hdisj hz
  exact B.bandProjection_eq_zero_of_mem_dc hz_compl

/-- Let `X` be a vector lattice with the Principal Projection Property and
let `Λ` be a maximal disjoint family of strictly positive elements of `X`.
The map `T : X → ∏_{a ∈ Λ} B_a` defined by `T x = (Pₐ x)_{a ∈ Λ}`, where
`B_a` denotes the principal band generated by `a`, is an injective vector
lattice homomorphism whose range is order dense in the product of the
principal bands. -/
theorem exists_orderDense_lattice_embedding_of_isMaximalDisjoint
    [HasPrincipalProjectionProperty X] {Λ : Set X}
    (hΛ : IsMaximalDisjoint Λ) (hΛ_pos : ∀ a ∈ Λ, 0 < a) :
    ∃ T : VecLatHom X
        ((a : Λ) → ↥(Band.generated ({(a : X)} : Set X)).toSubmodule),
      Function.Injective T ∧ IsOrderDense (Set.range T) := by
  haveI : IsVLArchimedean X := isVLArchimedean_of_hasPrincipalProjectionProperty
  refine ⟨decompositionMap Λ, ?_, ?_⟩
  · -- injectivity
    intro x y hxy
    have hxy' : ∀ a : Λ, Band.principalBandProjection (a : X) x =
        Band.principalBandProjection (a : X) y := by
      intro a
      have h := congrArg (fun f => (f a : X)) hxy
      simpa using h
    -- The positive and negative parts vanish because all their principal-band
    -- projections are zero.
    set z := x - y with hz_def
    have hPz : ∀ a ∈ Λ, Band.principalBandProjection a z = 0 := by
      intro a ha
      have := hxy' ⟨a, ha⟩
      simp only [hz_def, map_sub]
      rw [this, sub_self]
    have hPzp : ∀ a ∈ Λ, Band.principalBandProjection a z⁺ = 0 := by
      intro a ha
      have hvlh := (Band.principalProjectionBand a).bandProjection_isVecLatHom
      have :=
        (VecLatHom.ofIsVecLatHom _ hvlh).map_posPart z
      simp only [VecLatHom.ofIsVecLatHom] at this
      change Band.principalBandProjection a z⁺ =
        (Band.principalBandProjection a z)⁺ at this
      rw [this, hPz a ha, posPart_zero]
    have hPzn : ∀ a ∈ Λ, Band.principalBandProjection a z⁻ = 0 := by
      intro a ha
      have hvlh := (Band.principalProjectionBand a).bandProjection_isVecLatHom
      have :=
        (VecLatHom.ofIsVecLatHom _ hvlh).map_negPart z
      simp only [VecLatHom.ofIsVecLatHom] at this
      change Band.principalBandProjection a z⁻ =
        (Band.principalBandProjection a z)⁻ at this
      rw [this, hPz a ha, negPart_zero]
    have hzp_lub :=
      isLUB_principalBandProjection_of_isMaximalDisjoint hΛ hΛ_pos (posPart_nonneg z)
    have hzn_lub :=
      isLUB_principalBandProjection_of_isMaximalDisjoint hΛ hΛ_pos (negPart_nonneg z)
    have hzp_zero : z⁺ = 0 := by
      apply le_antisymm _ (posPart_nonneg z)
      refine hzp_lub.2 ?_
      rintro _ ⟨a, rfl⟩
      change Band.principalBandProjection (a : X) z⁺ ≤ 0
      rw [hPzp a a.2]
    have hzn_zero : z⁻ = 0 := by
      apply le_antisymm _ (negPart_nonneg z)
      refine hzn_lub.2 ?_
      rintro _ ⟨a, rfl⟩
      change Band.principalBandProjection (a : X) z⁻ ≤ 0
      rw [hPzn a a.2]
    have hz_zero : z = 0 := by
      have := posPart_sub_negPart z
      rw [hzp_zero, hzn_zero, sub_zero] at this
      exact this.symm
    rw [hz_def, sub_eq_zero] at hz_zero
    exact hz_zero
  · -- order density
    intro y hy
    have hy_nn : ∀ a : Λ, (0 : X) ≤ ((y a) : X) := fun a => hy.le a
    have hy_ne : y ≠ 0 := fun h => (lt_irrefl (0 : _) (h ▸ hy))
    have hex : ∃ a : Λ, (y a : X) ≠ 0 := by
      by_contra hall
      push Not at hall
      apply hy_ne
      funext a
      exact Subtype.ext (hall a)
    obtain ⟨a₀, ha₀_ne⟩ := hex
    set w : X := ((y a₀ : X)) with hw_def
    have hw_nn : 0 ≤ w := hy_nn a₀
    have hw_mem : w ∈ Band.generated ({(a₀ : X)} : Set X) := (y a₀).2
    -- Key facts about T w := decompositionMap Λ w.
    -- (i) For each a, P_a w ≥ 0.
    have hPw_nn : ∀ a : Λ, (0 : X) ≤ Band.principalBandProjection (a : X) w := by
      intro a
      exact Positive.zero_le_iff.mp
        (Band.principalProjectionBand (a : X)).bandProjection_nonneg w hw_nn
    -- (ii) For a = a₀, P_{a₀} w = w.
    have hPw_self : Band.principalBandProjection (a₀ : X) w = w := by
      set B := Band.principalProjectionBand (a₀ : X)
      have hwB : w ∈ (B : Set X) := by
        rw [Band.principalProjectionBand_coe]; exact hw_mem
      exact B.bandProjection_eq_of_mem hwB
    -- (iii) For a ≠ a₀, P_{a.val} w = 0.
    have hPw_other : ∀ a : Λ, (a : X) ≠ (a₀ : X) →
        Band.principalBandProjection (a : X) w = 0 := by
      intro a hab
      exact principalBandProjection_of_mem_generated_other hΛ a₀.2 a.2
        (fun h => hab h.symm) hw_mem
    refine ⟨decompositionMap Λ w, ⟨w, rfl⟩, ?_, ?_⟩
    · -- 0 < decompositionMap Λ w
      rw [lt_iff_le_and_ne]
      refine ⟨?_, ?_⟩
      · intro a
        change (0 : X) ≤ ((decompositionMap Λ w a : X))
        exact hPw_nn a
      · intro hzero
        apply ha₀_ne
        have := congrArg (fun f => (f a₀ : X)) hzero.symm
        simpa [decompositionMap_apply_coe, hPw_self] using this
    · -- decompositionMap Λ w ≤ y
      intro a
      change ((decompositionMap Λ w a : X)) ≤ ((y a : X))
      rw [decompositionMap_apply_coe]
      by_cases hab : (a : X) = (a₀ : X)
      · have ha_eq : a = a₀ := Subtype.ext hab
        subst ha_eq
        rw [hPw_self]
      · rw [hPw_other a hab]
        exact hy_nn a
