/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Substructures.Band.DisjointComplement
import BanLat.Substructures.Band.Lattice

/-!
# The band generated by a set

The band generated by a set `s ⊆ X` is the smallest band of `X` containing
`s`, obtained as the infimum of all bands containing `s`.

In an Archimedean vector lattice the double disjoint complement `Aᵈᵈ`
coincides with the band generated by `A`. As consequences we obtain four
equivalent descriptions of the band generated by an order ideal in terms of
suprema, a concrete description of the principal band as the supremum of
the increasing sequence `x ⊓ n • a`, and the characterisation of weak
order units as those non-negative elements that generate the whole space
as a band. As another consequence, every band of a normed vector lattice is
norm closed.
-/

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

namespace Band

/-- The band generated by a set `s`: the smallest band of `X` containing
`s`. -/
def generated (s : Set X) : Band X :=
  sInf {B : Band X | s ⊆ B}

/-- The generating set is contained in the band it generates. -/
theorem subset_generated (s : Set X) : s ⊆ (generated s : Set X) := by
  intro x hx
  rw [SetLike.mem_coe, generated, mem_sInf]
  exact fun B hB => hB hx

/-- The band generated by `s` is contained in every band containing `s`. -/
theorem generated_le {s : Set X} {B : Band X} (h : s ⊆ B) :
    generated s ≤ B :=
  sInf_le h

/-! ### Characterisation of bands via disjoint complements -/

omit [VectorLattice X] in
private lemma posPart_mem_dd {A : Set X}
    {x : X} (hx : x ∈ Aᵈᵈ) : x⁺ ∈ Aᵈᵈ := fun a ha =>
  (hx a ha).mono_left (by
    rw [abs_of_nonneg (posPart_nonneg x)]
    exact sup_le (le_abs_self x) (abs_nonneg x))

omit [VectorLattice X] in
private lemma negPart_mem_dd {A : Set X}
    {x : X} (hx : x ∈ Aᵈᵈ) : x⁻ ∈ Aᵈᵈ := fun a ha =>
  (hx a ha).mono_left (by
    rw [abs_of_nonneg (negPart_nonneg x)]
    exact sup_le (neg_le_abs x) (abs_nonneg x))

omit [VectorLattice X] in
private lemma solid_dd {A : Set X} {x y : X}
    (hx : x ∈ Aᵈᵈ) (h : |y| ≤ |x|) : y ∈ Aᵈᵈ := fun a ha =>
  (hx a ha).mono_left h

private lemma archimedean_disjoint_step [IsVLArchimedean X]
    {v t w : X} (hv_nn : 0 ≤ v) (ht_nn : 0 ≤ t) (hw_nn : 0 ≤ w)
    (ht_le_v : t ≤ v) (hbound : ∀ n : ℕ, v ⊓ (n • t - w) ≤ 0) : t = 0 := by
  letI : DistribLattice X := AddCommGroup.toDistribLattice X
  refine IsVLArchimedean.eq_zero_of_nonneg_of_forall_nsmul_le (y := w) ht_nn
    (fun n => ?_)
  have h_nv_nn : (0 : X) ≤ n • v := nsmul_nonneg hv_nn n
  have h_nt_le_nv : n • t ≤ n • v := nsmul_le_nsmul_right ht_le_v n
  have hkey1 : v ⊓ (n • t - w)⁺ = 0 := by
    refine le_antisymm ?_ (le_inf hv_nn (posPart_nonneg _))
    calc v ⊓ (n • t - w)⁺
        = v ⊓ ((n • t - w) ⊔ 0) := by rw [posPart_def]
      _ = (v ⊓ (n • t - w)) ⊔ (v ⊓ 0) := inf_sup_left v _ _
      _ ≤ 0 := sup_le (hbound n) (by rw [inf_of_le_right hv_nn])
  have hkey2 : (n • t - w)⁺ ⊓ (n • v) = 0 := by
    have hdisj : IsVLDisjoint (n • t - w)⁺ v := by
      change |(n • t - w)⁺| ⊓ |v| = 0
      rw [abs_of_nonneg (posPart_nonneg _), abs_of_nonneg hv_nn, inf_comm]
      exact hkey1
    have hdisj_n : IsVLDisjoint (n • t - w)⁺ ((n : ℝ) • v) :=
      hdisj.smul_right (n : ℝ)
    have hh : |(n • t - w)⁺| ⊓ |(n : ℝ) • v| = 0 := hdisj_n
    rw [abs_of_nonneg (posPart_nonneg _),
        abs_of_nonneg (smul_nonneg (Nat.cast_nonneg n) hv_nn)] at hh
    rw [show (n • v : X) = ((n : ℝ) • v) from (Nat.cast_smul_eq_nsmul ℝ n v).symm]
    exact hh
  have hpos_le_nt : (n • t - w)⁺ ≤ n • t :=
    sup_le (sub_le_self _ hw_nn) (nsmul_nonneg ht_nn n)
  have hpos_le_nv : (n • t - w)⁺ ≤ n • v := hpos_le_nt.trans h_nt_le_nv
  have hpos_zero : (n • t - w)⁺ = 0 := by
    have : (n • t - w)⁺ = (n • t - w)⁺ ⊓ (n • v) :=
      (inf_eq_left.mpr hpos_le_nv).symm
    exact this.trans hkey2
  have h_le : n • t - w ≤ 0 := posPart_eq_zero.mp hpos_zero
  exact sub_nonpos.mp h_le

/-- The hard direction: in an Archimedean vector lattice, a non-negative
element of `Aᵈᵈ` lies in the band generated by `A`. -/
private lemma mem_generated_of_nonneg_of_mem_ddc [IsVLArchimedean X]
    (A : Set X) {x : X} (hx : 0 ≤ x) (hxAdd : x ∈ Aᵈᵈ) :
    x ∈ Band.generated A := by
  set G : Band X := Band.generated A with hG_def
  have hAG : A ⊆ (G : Set X) := subset_generated A
  -- It suffices to show `IsLUB (G ∩ [0, x]) x`, since `G` is a band.
  suffices h : IsLUB ((G.toOrderIdeal : Set X) ∩ Set.Icc 0 x) x by
    refine G.sSup_mem (S := (G.toOrderIdeal : Set X) ∩ Set.Icc 0 x)
      (fun y hy => hy.1)
      ⟨0, G.toOrderIdeal.toSubmodule.zero_mem, le_refl 0, hx⟩ h
  refine ⟨fun b hb => hb.2.2, ?_⟩
  intro u hu
  have hu_nn : 0 ≤ u := hu ⟨G.toOrderIdeal.toSubmodule.zero_mem, le_refl 0, hx⟩
  set v : X := (x - u)⁺ with hv_def
  have hv_nn : 0 ≤ v := posPart_nonneg _
  have hv_le_x : v ≤ x := sup_le (sub_le_self _ hu_nn) hx
  have hv_Add : v ∈ Aᵈᵈ :=
    solid_dd hxAdd (by rw [abs_of_nonneg hv_nn, abs_of_nonneg hx]; exact hv_le_x)
  have hv_Ad : v ∈ Aᵈ := by
    intro a ha
    set t : X := v ⊓ |a| with ht_def
    have ht_nn : 0 ≤ t := le_inf hv_nn (abs_nonneg _)
    have ht_le_v : t ≤ v := inf_le_left
    have ht_le_abs : t ≤ |a| := inf_le_right
    have habs_G : |a| ∈ G := G.abs_mem (hAG ha)
    have ht_G : t ∈ G := G.solid habs_G ht_nn ht_le_abs
    set w : X := x ⊓ u with hw_def
    have hbound : ∀ n : ℕ, v ⊓ (n • t - w) ≤ 0 := by
      intro n
      have hnt_G : n • t ∈ G := G.toSubmodule.nsmul_mem ht_G n
      have hnt_nn : 0 ≤ n • t := nsmul_nonneg ht_nn n
      have hxnt_G : x ⊓ n • t ∈ G :=
        G.solid hnt_G (le_inf hx hnt_nn) inf_le_right
      have hxnt_le_x : x ⊓ n • t ≤ x := inf_le_left
      have hxnt_le_u : x ⊓ n • t ≤ u :=
        hu ⟨hxnt_G, le_inf hx hnt_nn, hxnt_le_x⟩
      have hxnt_le_w : x ⊓ n • t ≤ w := le_inf hxnt_le_x hxnt_le_u
      have hv_eq : v = x - w := by rw [hv_def, hw_def, sub_inf_eq_posPart]
      have h1 : v ⊓ (n • t - w) = x ⊓ n • t - w := by
        rw [hv_eq, ← inf_sub]
      rw [h1]
      exact sub_nonpos.mpr hxnt_le_w
    have hw_nn : 0 ≤ w := le_inf hx hu_nn
    have ht_zero : t = 0 :=
      archimedean_disjoint_step hv_nn ht_nn hw_nn ht_le_v hbound
    change |v| ⊓ |a| = 0
    rw [abs_of_nonneg hv_nn]
    exact ht_zero
  have hv_zero : v = 0 :=
    disjointComplement_inter_eq_zero Aᵈ ⟨hv_Ad, hv_Add⟩
  have hxu : (x - u)⁺ = 0 := hv_zero
  rw [posPart_eq_zero, sub_nonpos] at hxu
  exact hxu

/-- In an Archimedean vector lattice, the double disjoint complement of a set
equals the band it generates. -/
theorem disjointComplement_disjointComplement_eq_generated
    [IsVLArchimedean X] (A : Set X) :
    ((Aᵈ)ᵈ : Set X) = (generated A : Set X) := by
  apply Set.Subset.antisymm
  · intro x hx
    have hxp : x⁺ ∈ Band.generated A :=
      mem_generated_of_nonneg_of_mem_ddc A (posPart_nonneg x) (posPart_mem_dd hx)
    have hxn : x⁻ ∈ Band.generated A :=
      mem_generated_of_nonneg_of_mem_ddc A (negPart_nonneg x) (negPart_mem_dd hx)
    have := (Band.generated A).toSubmodule.sub_mem hxp hxn
    rwa [posPart_sub_negPart] at this
  · exact generated_le (B := Band.disjointComplement Aᵈ)
      (subset_disjointComplement_disjointComplement A)

/-- The band generated by a set together with its disjoint complement is the
whole space. -/
theorem generated_union_disjointComplement_eq_top [IsVLArchimedean X] (A : Set X) :
    generated (A ∪ Aᵈ) = (⊤ : Band X) := by
  apply le_antisymm
  · exact le_top
  · intro x _
    have hx : x ∈ ((A ∪ Aᵈ)ᵈ)ᵈ := by
      rw [disjointComplement_union_disjointComplement_eq_singleton A]
      intro a ha
      rw [Set.mem_singleton_iff.mp ha]
      exact isVLDisjoint_zero_right x
    rwa [disjointComplement_disjointComplement_eq_generated] at hx

/-- In an Archimedean vector lattice, every band equals its double disjoint
complement. -/
theorem eq_disjointComplement_disjointComplement [IsVLArchimedean X]
    (B : Band X) : ((↑B : Set X)ᵈ)ᵈ = ↑B := by
  rw [disjointComplement_disjointComplement_eq_generated]
  exact congrArg _ (le_antisymm (generated_le (fun _ h => h)) (subset_generated _))

/-- In an Archimedean vector lattice, every band is the disjoint complement of
some set. -/
theorem exists_eq_disjointComplement [IsVLArchimedean X] (B : Band X) :
    ∃ A : Set X, Aᵈ = ↑B :=
  ⟨(B : Set X)ᵈ, eq_disjointComplement_disjointComplement B⟩

/-! ### Description of the band generated by an ideal

For an order ideal `J`, the positive part of the band generated by `J`
admits four equivalent descriptions: it consists of those non-negative
elements `x` that are the supremum of an upward-directed net in `J`,
equivalently, the supremum of a non-empty set of non-negative elements
of `J`, equivalently, the supremum of `J ∩ [0, x]`. -/

/-- Backward direction: if `IsLUB D x` for some non-empty `D ⊆ J`, then `x`
belongs to the band generated by `J`. -/
private lemma mem_generated_of_isLUB_subset {J : OrderIdeal X} {x : X}
    {D : Set X} (hne : D.Nonempty) (hDJ : D ⊆ (J : Set X)) (hx : IsLUB D x) :
    x ∈ generated (J : Set X) :=
  (generated (J : Set X)).sSup_mem
    (fun _ hy => subset_generated _ (hDJ hy)) hne hx

/-- Forward direction (Archimedean): if `0 ≤ x` belongs to the band generated
by an order ideal `J`, then `x` is the supremum of `J ∩ [0, x]`. -/
private lemma isLUB_inter_of_mem_generated_orderIdeal [IsVLArchimedean X]
    (J : OrderIdeal X) {x : X} (hx : 0 ≤ x)
    (hxG : x ∈ generated (J : Set X)) :
    IsLUB ((J : Set X) ∩ Set.Icc 0 x) x := by
  have hxAdd : x ∈ ((J : Set X)ᵈ)ᵈ := by
    rw [disjointComplement_disjointComplement_eq_generated]; exact hxG
  refine ⟨fun b hb => hb.2.2, ?_⟩
  intro u hu
  have hu_nn : 0 ≤ u := hu ⟨J.toSubmodule.zero_mem, le_refl 0, hx⟩
  set v : X := (x - u)⁺ with hv_def
  have hv_nn : 0 ≤ v := posPart_nonneg _
  have hv_le_x : v ≤ x := sup_le (sub_le_self _ hu_nn) hx
  have hv_Add : v ∈ ((J : Set X)ᵈ)ᵈ :=
    solid_dd hxAdd (by rw [abs_of_nonneg hv_nn, abs_of_nonneg hx]; exact hv_le_x)
  have hv_Ad : v ∈ ((J : Set X))ᵈ := by
    intro a ha
    set t : X := v ⊓ |a| with ht_def
    have ht_nn : 0 ≤ t := le_inf hv_nn (abs_nonneg _)
    have ht_le_v : t ≤ v := inf_le_left
    have ht_le_abs : t ≤ |a| := inf_le_right
    have habs_J : |a| ∈ J := J.abs_mem ha
    set w : X := x ⊓ u with hw_def
    have hbound : ∀ n : ℕ, v ⊓ (n • t - w) ≤ 0 := by
      intro n
      have hnabs_J : n • |a| ∈ J := J.toSubmodule.nsmul_mem habs_J n
      have hnabs_nn : 0 ≤ n • |a| := nsmul_nonneg (abs_nonneg _) n
      have hnt_le_nabs : n • t ≤ n • |a| := nsmul_le_nsmul_right ht_le_abs n
      have hxnt_le_xnabs : x ⊓ n • t ≤ x ⊓ n • |a| :=
        inf_le_inf_left _ hnt_le_nabs
      have hxnabs_J : x ⊓ n • |a| ∈ J :=
        J.solid hnabs_J (le_inf hx hnabs_nn) inf_le_right
      have hxnabs_le_x : x ⊓ n • |a| ≤ x := inf_le_left
      have hxnabs_le_u : x ⊓ n • |a| ≤ u :=
        hu ⟨hxnabs_J, le_inf hx hnabs_nn, hxnabs_le_x⟩
      have hxnt_le_x : x ⊓ n • t ≤ x := inf_le_left
      have hxnt_le_u : x ⊓ n • t ≤ u := hxnt_le_xnabs.trans hxnabs_le_u
      have hxnt_le_w : x ⊓ n • t ≤ w := le_inf hxnt_le_x hxnt_le_u
      have hv_eq : v = x - w := by rw [hv_def, hw_def, sub_inf_eq_posPart]
      have h1 : v ⊓ (n • t - w) = x ⊓ n • t - w := by
        rw [hv_eq, ← inf_sub]
      rw [h1]
      exact sub_nonpos.mpr hxnt_le_w
    have hw_nn : 0 ≤ w := le_inf hx hu_nn
    have ht_zero : t = 0 :=
      archimedean_disjoint_step hv_nn ht_nn hw_nn ht_le_v hbound
    change |v| ⊓ |a| = 0
    rw [abs_of_nonneg hv_nn]; exact ht_zero
  have hv_zero : v = 0 :=
    disjointComplement_inter_eq_zero (J : Set X)ᵈ ⟨hv_Ad, hv_Add⟩
  have hxu : (x - u)⁺ = 0 := hv_zero
  rw [posPart_eq_zero, sub_nonpos] at hxu
  exact hxu

/-- For an order ideal `J` and a non-negative element `x`, `x` belongs to
the band generated by `J` iff `x` is the supremum of an upward-directed
non-empty set of non-negative elements of `J`. -/
theorem mem_generated_orderIdeal_iff_isLUB_directed [IsVLArchimedean X]
    (J : OrderIdeal X) {x : X} (hx : 0 ≤ x) :
    x ∈ generated (J : Set X) ↔
      ∃ S : Set X, S.Nonempty ∧ S ⊆ (J : Set X) ∧ (∀ y ∈ S, 0 ≤ y)
        ∧ DirectedOn (· ≤ ·) S ∧ IsLUB S x := by
  refine ⟨fun hxG => ?_, ?_⟩
  · refine ⟨(J : Set X) ∩ Set.Icc 0 x,
      ⟨0, J.toSubmodule.zero_mem, le_refl 0, hx⟩,
      fun _ hy => hy.1, fun _ hy => hy.2.1, ?_, ?_⟩
    · rintro a ⟨haJ, ha0, hax⟩ b ⟨hbJ, _, hbx⟩
      exact ⟨a ⊔ b, ⟨J.sup_mem haJ hbJ, le_sup_of_le_left ha0, sup_le hax hbx⟩,
        le_sup_left, le_sup_right⟩
    · exact isLUB_inter_of_mem_generated_orderIdeal J hx hxG
  · rintro ⟨S, hne, hSJ, _, _, hx⟩
    exact mem_generated_of_isLUB_subset hne hSJ hx

/-- For an order ideal `J` and a non-negative element `x`, `x` belongs to
the band generated by `J` iff `x` is the supremum of a non-empty set of
non-negative elements of `J`. -/
theorem mem_generated_orderIdeal_iff_isLUB_nonneg [IsVLArchimedean X]
    (J : OrderIdeal X) {x : X} (hx : 0 ≤ x) :
    x ∈ generated (J : Set X) ↔
      ∃ D : Set X, D.Nonempty ∧ D ⊆ (J : Set X) ∧ (∀ y ∈ D, 0 ≤ y)
        ∧ IsLUB D x := by
  refine ⟨fun hxG => ?_, ?_⟩
  · refine ⟨(J : Set X) ∩ Set.Icc 0 x,
      ⟨0, J.toSubmodule.zero_mem, le_refl 0, hx⟩,
      fun _ hy => hy.1, fun _ hy => hy.2.1, ?_⟩
    exact isLUB_inter_of_mem_generated_orderIdeal J hx hxG
  · rintro ⟨D, hne, hDJ, _, hx⟩
    exact mem_generated_of_isLUB_subset hne hDJ hx

/-- For an order ideal `J` and a non-negative element `x`, `x` belongs to
the band generated by `J` iff `x` is the supremum of `J ∩ [0, x]`. -/
theorem mem_generated_orderIdeal_iff_isLUB_inter [IsVLArchimedean X]
    (J : OrderIdeal X) {x : X} (hx : 0 ≤ x) :
    x ∈ generated (J : Set X) ↔
      IsLUB ((J : Set X) ∩ Set.Icc 0 x) x := by
  refine ⟨isLUB_inter_of_mem_generated_orderIdeal J hx, fun h => ?_⟩
  exact mem_generated_of_isLUB_subset (D := (J : Set X) ∩ Set.Icc 0 x)
    ⟨0, J.toSubmodule.zero_mem, le_refl 0, hx⟩
    (fun _ hy => hy.1) h

/-! ### Description of the principal band

The band generated by a single non-negative element `a` admits a concrete
description: a non-negative `x` belongs to it iff `x` is the supremum of
the increasing sequence `x ⊓ n • a` for `n ∈ ℕ`. -/

/-- Forward direction (Archimedean): if `0 ≤ x` belongs to the band generated
by `{a}` for some `0 ≤ a`, then `x` is the supremum of `x ⊓ n • a`. -/
private lemma isLUB_inf_nsmul_of_mem_generated_singleton [IsVLArchimedean X]
    {a x : X} (ha : 0 ≤ a) (hx : 0 ≤ x)
    (hxG : x ∈ generated ({a} : Set X)) :
    IsLUB (Set.range fun n : ℕ => x ⊓ n • a) x := by
  have hxAdd : x ∈ (({a} : Set X)ᵈ)ᵈ := by
    rw [disjointComplement_disjointComplement_eq_generated]; exact hxG
  refine ⟨?_, ?_⟩
  · rintro _ ⟨_, rfl⟩; exact inf_le_left
  intro u hu
  have h0 : x ⊓ (0 : ℕ) • a = 0 := by
    rw [zero_nsmul]; exact inf_of_le_right hx
  have hu_nn : 0 ≤ u := h0 ▸ hu ⟨0, rfl⟩
  set v : X := (x - u)⁺ with hv_def
  have hv_nn : 0 ≤ v := posPart_nonneg _
  have hv_le_x : v ≤ x := sup_le (sub_le_self _ hu_nn) hx
  have hv_Add : v ∈ (({a} : Set X)ᵈ)ᵈ :=
    solid_dd hxAdd (by rw [abs_of_nonneg hv_nn, abs_of_nonneg hx]; exact hv_le_x)
  have hv_Ad : v ∈ (({a} : Set X))ᵈ := by
    rintro b rfl
    set t : X := v ⊓ |b| with ht_def
    have ht_nn : 0 ≤ t := le_inf hv_nn (abs_nonneg _)
    have ht_le_v : t ≤ v := inf_le_left
    have ht_le_abs : t ≤ |b| := inf_le_right
    have habs_eq : |b| = b := abs_of_nonneg ha
    set w : X := x ⊓ u with hw_def
    have hbound : ∀ n : ℕ, v ⊓ (n • t - w) ≤ 0 := by
      intro n
      have ht_le_b : t ≤ b := habs_eq ▸ ht_le_abs
      have hnt_le_nb : n • t ≤ n • b := nsmul_le_nsmul_right ht_le_b n
      have hxnt_le_xnb : x ⊓ n • t ≤ x ⊓ n • b :=
        inf_le_inf_left _ hnt_le_nb
      have hxnb_le_u : x ⊓ n • b ≤ u := hu ⟨n, rfl⟩
      have hxnt_le_x : x ⊓ n • t ≤ x := inf_le_left
      have hxnt_le_u : x ⊓ n • t ≤ u := hxnt_le_xnb.trans hxnb_le_u
      have hxnt_le_w : x ⊓ n • t ≤ w := le_inf hxnt_le_x hxnt_le_u
      have hv_eq : v = x - w := by rw [hv_def, hw_def, sub_inf_eq_posPart]
      have h1 : v ⊓ (n • t - w) = x ⊓ n • t - w := by
        rw [hv_eq, ← inf_sub]
      rw [h1]
      exact sub_nonpos.mpr hxnt_le_w
    have hw_nn : 0 ≤ w := le_inf hx hu_nn
    have ht_zero : t = 0 :=
      archimedean_disjoint_step hv_nn ht_nn hw_nn ht_le_v hbound
    change |v| ⊓ |b| = 0
    rw [abs_of_nonneg hv_nn]; exact ht_zero
  have hv_zero : v = 0 :=
    disjointComplement_inter_eq_zero ({a} : Set X)ᵈ ⟨hv_Ad, hv_Add⟩
  have hxu : (x - u)⁺ = 0 := hv_zero
  rw [posPart_eq_zero, sub_nonpos] at hxu
  exact hxu

/-- For non-negative `a` and `x`, `x` belongs to the band generated by
`{a}` iff `x` is the supremum of the sequence `x ⊓ n • a`. -/
theorem mem_generated_singleton_iff_isLUB_inf_nsmul [IsVLArchimedean X]
    {a x : X} (ha : 0 ≤ a) (hx : 0 ≤ x) :
    x ∈ generated ({a} : Set X) ↔
      IsLUB (Set.range fun n : ℕ => x ⊓ n • a) x := by
  refine ⟨isLUB_inf_nsmul_of_mem_generated_singleton ha hx, fun h => ?_⟩
  set G : Band X := generated ({a} : Set X) with hG_def
  have ha_G : a ∈ G := subset_generated _ rfl
  refine G.sSup_mem (S := Set.range fun n : ℕ => x ⊓ n • a) ?_
    (Set.range_nonempty _) h
  rintro _ ⟨n, rfl⟩
  have hna_G : n • a ∈ G := G.toSubmodule.nsmul_mem ha_G n
  have hna_nn : 0 ≤ n • a := nsmul_nonneg ha n
  exact G.solid hna_G (le_inf hx hna_nn) inf_le_right

end Band

/-! ### Weak order units -/

/-- In an Archimedean vector lattice, a non-negative element `e` is a weak
order unit iff the band it generates is the whole space. -/
theorem weakOrderUnit_iff_generated_singleton_eq_top [IsVLArchimedean X]
    {e : X} (he : 0 ≤ e) :
    WeakOrderUnit e ↔ Band.generated {e} = ⊤ := by
  constructor
  · rintro ⟨_, hwou⟩
    apply SetLike.coe_set_eq.mp
    rw [← Band.disjointComplement_disjointComplement_eq_generated]
    show ((({e} : Set X)ᵈ)ᵈ : Set X) = (⊤ : Band X)
    ext x
    refine ⟨fun _ => trivial, fun _ y hy => ?_⟩
    have hye : IsVLDisjoint y e := hy e rfl
    rw [hwou y hye]
    exact isVLDisjoint_zero_right x
  · intro htop
    refine ⟨he, fun x hxe => ?_⟩
    have hx_in : x ∈ ((↑(Band.generated ({e} : Set X)) : Set X)) := by
      rw [show Band.generated ({e} : Set X) = ⊤ from htop]; trivial
    rw [← Band.disjointComplement_disjointComplement_eq_generated] at hx_in
    have hxe' : x ∈ ({e} : Set X)ᵈ := fun a ha => by
      rcases ha with rfl; exact hxe
    have hx_self : IsVLDisjoint x x :=
      isVLDisjoint_comm.mp (hx_in x hxe')
    have h : |x| ⊓ |x| = 0 := hx_self
    rw [inf_idem] at h
    exact (abs_eq_zero_iff_zero x).mp h

/-! ### Closedness in normed vector lattices -/

section Normed

variable {X : Type*} [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [NormedVectorLattice X]

namespace Band

variable (B : Band X)

/-- Every band of a normed vector lattice is norm closed: it equals its double
disjoint complement, which is closed. -/
theorem isClosed_coe : IsClosed ((B : Set X)) := by
  rw [← Band.eq_disjointComplement_disjointComplement B]
  exact isClosed_disjointComplement _

/-- The underlying submodule of a band of a normed vector lattice is norm
closed. -/
theorem isClosed_toSubmodule : IsClosed ((B.toSubmodule : Set X)) := isClosed_coe B

end Band

end Normed

section Banach

variable {X : Type*} [NormedAddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [BanachLattice X]

namespace Band

variable (B : Band X)

/-- A band of a Banach lattice, equipped with the inherited normed vector
lattice structure, is itself a Banach lattice. -/
noncomputable instance instBanachLatticeSubtype :
    BanachLattice ↥B.toSubmodule :=
  VectorSublattice.banachLatticeSubtype B.toVectorSublattice B.isClosed_coe

end Band

end Banach
