/-
Authors: Jesús Illescas-Fiorito
-/

import BanLat.AMSpace.Kakutani
import BanLat.Examples.CofK.Complex

/-!
# Kakutani's representation theorem for complex AM-spaces with unit

This file shows that every nontrivial complex AM-space with unit `Z` is complex
Banach lattice isometric to some Banach lattice `C(K, ℂ)`, where `K` may be taken
to be `LatticeCharacter (selfAdjoint Z)`, that is the compact space of lattice
characters of the self-adjoint part of `Z`.

This isometry is obtained using these steps:
* `Z` is complex Banach lattice isometric to `complexification (selfAdjoint Z)`.
* By (the real-valued) Kakutani theorem, `selfAdjoint Z` is Banach lattice isometric
to `C(LatticeCharacter (selfAdjoint Z), ℝ)`.
* Since `complexification (C(K, R))` is complex Banach lattice isometric to `C(K, ℂ)`,
the Banach lattice isometry coming from the real Kakutani theorem is complexified into
a complex Banach lattice isometry `Z → C(LatticeCharacter (selfAdjoint Z), ℝ)`.

Moreover, this complex Banach lattice isometry sends the distinguished unit into
the constant `1` function.
-/

open scoped ComplexStarModule

namespace ComplexAMSpaceWithUnit

variable (Z : Type*) [NormedAddCommGroup Z] [NormedSpace ℂ Z]
  [StarAddMonoid Z] [StarModule ℂ Z] [Lattice (selfAdjoint Z)]
  [IsOrderedAddMonoid (selfAdjoint Z)] [ComplexAMSpaceWithUnit Z]
  [Nontrivial Z]

omit [Lattice (selfAdjoint Z)] [IsOrderedAddMonoid (selfAdjoint Z)]
  [ComplexAMSpaceWithUnit Z] in
/-- If `Z` is nontrivial, `selfAdjoint Z` is nontrivial. -/
private theorem nontrivial_selfAdjoint : Nontrivial (selfAdjoint Z) := by
  rw [← not_subsingleton_iff_nontrivial]
  intro h
  letI : Subsingleton (selfAdjoint Z) := h
  letI : Subsingleton Z := ⟨fun z w ↦ by
    rw [← realPart_add_I_smul_imaginaryPart z,
      ← realPart_add_I_smul_imaginaryPart w,
      Subsingleton.elim (ℜ z) (ℜ w),
      Subsingleton.elim (ℑ z) (ℑ w)]⟩
  exact not_subsingleton_iff_nontrivial.mpr
    (inferInstance : Nontrivial Z) inferInstance

/-- **Complex valued Kakutani theorem:**  every nontrivial complex AM-space
with unit `Z` is complex Banach lattice isometric to the Banach lattice
`C(LatticeCharacter (selfAdjoint Z), ℂ)`. -/
noncomputable def kakutaniEquiv :
    ComplexBanachLatEquiv Z
      C(AMSpaceWithUnit.LatticeCharacter (selfAdjoint Z), ℂ) := by
  letI := nontrivial_selfAdjoint Z
  exact (ComplexBanachLattice.complexificationEquiv Z).symm.trans
    ((Complexification.equivOfBanachLatEquiv
      (AMSpaceWithUnit.kakutaniEquiv (selfAdjoint Z))).trans
        ContinuousMap.complexificationEquiv)

/-- The complex Kakutani equivalence `Z → C(LatticeCharacter (selfAdjoint Z), ℂ)`
is evaluated by: `kakutaniEquiv[z](φ) = φ(Re[z]) + i·φ(Im[z])`. -/
@[simp]
theorem kakutaniEquiv_apply
    (z : Z) (φ : AMSpaceWithUnit.LatticeCharacter (selfAdjoint Z)) :
    kakutaniEquiv Z z φ =
      (φ (ℜ z) : ℂ) + Complex.I * (φ (ℑ z) : ℂ) := by
  rw [kakutaniEquiv, ComplexBanachLatEquiv.trans_apply,
    ComplexBanachLatEquiv.trans_apply,
    ComplexBanachLattice.complexificationEquiv_symm_apply,
    Complexification.equivOfBanachLatEquiv_apply,
    ContinuousMap.complexificationEquiv_apply_apply,
    AMSpaceWithUnit.kakutaniEquiv_apply,
    AMSpaceWithUnit.kakutaniEquiv_apply]

/-- Under the complex Kakutani equivalence, the distinguished unit corresponds
to the constant function `1`. -/
theorem kakutaniEquiv_unit :
    kakutaniEquiv Z
      ((ComplexAMSpaceWithUnit.unit : selfAdjoint Z) : Z) = 1 := by
  ext φ
  rw [kakutaniEquiv_apply]
  simp only [selfAdjoint.realPart_coe, selfAdjoint.imaginaryPart_coe,
    ContinuousMap.one_apply]
  change (φ.toVecLatHom (AMSpaceWithUnit.unit : selfAdjoint Z) : ℂ) +
    Complex.I * (φ.toVecLatHom 0 : ℂ) = 1
  rw [φ.map_unit, map_zero]
  simp

end ComplexAMSpaceWithUnit

namespace OrderIdeal

variable {X : Type*} [AddCommGroup X] [Lattice X] [IsOrderedAddMonoid X]
  [VectorLattice X]

/-- The complexification of the principal ideal generated by a strictly positive element in a
uniformly complete vector lattice is complex-Banach lattice isometric to
`C(LatticeCharacter ↥(principal e), ℂ)`. -/
noncomputable def complexPrincipalKakutaniEquiv
    [IsUniformlyCompleteVectorLattice X] {e : X} (he : 0 < e) :
    letI := principalNormedAddCommGroup e
    letI : Lattice ↥(principal e) := instLatticePrincipal e
    letI : IsOrderedAddMonoid ↥(principal e) := instIsOrderedAddMonoidPrincipal e
    letI : AMSpaceWithUnit ↥(principal e) :=
      principalAMSpaceWithUnit he.le
        (IsUniformlyCompleteVectorLattice.complete_principal e he)
    ComplexBanachLatEquiv (Complexification ↥(principal e))
      C(AMSpaceWithUnit.LatticeCharacter ↥(principal e), ℂ) := by
  letI := principalNormedAddCommGroup e
  letI : Lattice ↥(principal e) := instLatticePrincipal e
  letI : IsOrderedAddMonoid ↥(principal e) := instIsOrderedAddMonoidPrincipal e
  letI : AMSpaceWithUnit ↥(principal e) :=
    principalAMSpaceWithUnit he.le
      (IsUniformlyCompleteVectorLattice.complete_principal e he)
  exact (Complexification.equivOfBanachLatEquiv
    (principalKakutaniEquiv he)).trans ContinuousMap.complexificationEquiv

/-- The complex principal-ideal Kakutani equivalence is evaluated by applying a character
to its real and imaginary coordinates. -/
@[simp]
theorem complexPrincipalKakutaniEquiv_apply_apply
    [IsUniformlyCompleteVectorLattice X] {e : X} (he : 0 < e) :
    letI := principalNormedAddCommGroup e
    letI : Lattice ↥(principal e) := instLatticePrincipal e
    letI : IsOrderedAddMonoid ↥(principal e) := instIsOrderedAddMonoidPrincipal e
    letI : AMSpaceWithUnit ↥(principal e) :=
      principalAMSpaceWithUnit he.le
        (IsUniformlyCompleteVectorLattice.complete_principal e he)
    ∀ (z : Complexification ↥(principal e))
      (φ : AMSpaceWithUnit.LatticeCharacter ↥(principal e)),
      complexPrincipalKakutaniEquiv he z φ =
        (φ z.re : ℂ) + Complex.I * (φ z.im : ℂ) := by
  letI := principalNormedAddCommGroup e
  letI : Lattice ↥(principal e) := instLatticePrincipal e
  letI : IsOrderedAddMonoid ↥(principal e) := instIsOrderedAddMonoidPrincipal e
  letI : AMSpaceWithUnit ↥(principal e) :=
    principalAMSpaceWithUnit he.le
      (IsUniformlyCompleteVectorLattice.complete_principal e he)
  intro z φ
  rw [complexPrincipalKakutaniEquiv, ComplexBanachLatEquiv.trans_apply,
    ContinuousMap.complexificationEquiv_apply_apply,
    Complexification.equivOfBanachLatEquiv_apply, principalKakutaniEquiv,
    AMSpaceWithUnit.kakutaniEquiv_apply,
    AMSpaceWithUnit.kakutaniEquiv_apply]

end OrderIdeal
