/-
Authors: David Muñoz-Lahoz
-/

import BanLat.Examples.MofK.ALspace
import BanLat.Examples.Lp.Basic
import Mathlib.MeasureTheory.Function.SimpleFuncDenseLp
import Mathlib.MeasureTheory.VectorMeasure.Decomposition.RadonNikodym

/-!
# Principal bands in `M(K)`

For a positive regular signed measure `μ`, the band generated by `μ` in `M(K)`
is the set of regular signed measures absolutely continuous with respect to
`μ`.
-/

open MeasureTheory Set

universe u

namespace MofK

variable {K : Type u} [TopologicalSpace K] [T2Space K] [CompactSpace K]
  [MeasurableSpace K] [BorelSpace K]

private def absolutelyContinuousOrderIdeal {μ : MofK K} (hμ : 0 ≤ μ) :
    OrderIdeal (MofK K) where
  toSubmodule :=
    { carrier := {ν | (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)}
      add_mem' := fun hν₁ hν₂ => VectorMeasure.AbsolutelyContinuous.add hν₁ hν₂
      zero_mem' := VectorMeasure.AbsolutelyContinuous.zero _
      smul_mem' := fun _ _ hν => VectorMeasure.AbsolutelyContinuous.smul hν }
  sup_mem' := fun {ν₁ ν₂} hν₁ hν₂ => by
    change ((ν₁ : MeasureTheory.SignedMeasure K) ⊔
        (ν₂ : MeasureTheory.SignedMeasure K)) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)
    rw [MeasureTheory.SignedMeasure.max_def]
    refine VectorMeasure.AbsolutelyContinuous.add hν₂ ?_
    have hsub : (ν₁ : MeasureTheory.SignedMeasure K) -
        (ν₂ : MeasureTheory.SignedMeasure K) ≪ᵥ
          (μ : MeasureTheory.SignedMeasure K) :=
      VectorMeasure.AbsolutelyContinuous.sub hν₁ hν₂
    refine MeasureTheory.SignedMeasure.abs_le_of_absolutelyContinuous hμ hsub ?_
    rw [abs_of_nonneg (MeasureTheory.SignedMeasure.zero_le_posPart _)]
    intro E hE
    rw [MeasureTheory.SignedMeasure.abs_eq_posPart_add_negPart, VectorMeasure.add_apply]
    have h2 : (0 : MeasureTheory.SignedMeasure K) E ≤
        ((ν₁ : MeasureTheory.SignedMeasure K) -
          (ν₂ : MeasureTheory.SignedMeasure K)).negPart E :=
      MeasureTheory.SignedMeasure.zero_le_negPart _ E hE
    rw [VectorMeasure.zero_apply] at h2
    linarith
  solid' := fun {ν₁ ν₂} hν₁ h₀ν₂ hν₂le => by
    change (ν₂ : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)
    change (ν₁ : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K) at hν₁
    have h0ν₁ : (0 : MofK K) ≤ ν₁ := le_trans h₀ν₂ hν₂le
    refine MeasureTheory.SignedMeasure.abs_le_of_absolutelyContinuous hμ hν₁ ?_
    rw [abs_of_nonneg (show (0 : MeasureTheory.SignedMeasure K) ≤ ν₂ from h₀ν₂),
      abs_of_nonneg (show (0 : MeasureTheory.SignedMeasure K) ≤ ν₁ from h0ν₁)]
    exact hν₂le

private theorem isClosed_absolutelyContinuous (μ : MofK K) :
    IsClosed {ν : MofK K |
      (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} := by
  have heq : {ν : MofK K |
      (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} =
      ⋂ (E : Set K) (_ : MeasurableSet E)
        (_ : (μ : MeasureTheory.SignedMeasure K) E = 0),
          {ν : MofK K | (ν : MeasureTheory.SignedMeasure K) E = 0} := by
    ext ν
    simp only [Set.mem_iInter, Set.mem_setOf_eq]
    constructor
    · exact fun h E _ hμE => h hμE
    · intro h
      refine VectorMeasure.AbsolutelyContinuous.mk fun E hE hμE => ?_
      exact h E hE hμE
  rw [heq]
  refine isClosed_iInter fun E => isClosed_iInter fun hE => isClosed_iInter fun _ => ?_
  exact isClosed_singleton.preimage
    ((MeasureTheory.SignedMeasure.continuous_apply hE).comp continuous_subtype_val)

private theorem band_of_isClosed_orderIdeal (J : OrderIdeal (MofK K))
    (hcl : IsClosed (J : Set (MofK K))) :
    ∃ B : Band (MofK K), (B : Set (MofK K)) = (J : Set (MofK K)) := by
  refine ⟨Band.ofPosDirectedSSupMem J ?_, rfl⟩
  intro S hS hpos hdir hne x hx
  haveI : Nonempty ↥S := hne.to_subtype
  haveI : IsDirected ↥S (· ≤ ·) := ⟨fun a b => by
    obtain ⟨c, hc, hac, hbc⟩ := hdir a.val a.2 b.val b.2
    exact ⟨⟨c, hc⟩, hac, hbc⟩⟩
  let u : ↥S → MofK K := fun s => x - s.val
  have hu_anti : Antitone u := fun a b h =>
    sub_le_sub_left (show a.val ≤ b.val from h) x
  have hu_nn : ∀ s, 0 ≤ u s := fun s => sub_nonneg.mpr (hx.1 s.2)
  have hu_glb : IsGLB (Set.range u) 0 := by
    refine ⟨?_, ?_⟩
    · rintro _ ⟨s, rfl⟩
      exact hu_nn s
    · intro w hw
      have hub : ∀ y ∈ S, y ≤ x - w := fun y hy =>
        le_sub_comm.mp (hw ⟨⟨y, hy⟩, rfl⟩)
      have h := hx.2 hub
      rwa [le_sub_iff_add_le, add_comm, add_le_iff_nonpos_left] at h
  have htend := IsOrderContinuousNorm.tendsto_of_antitone_isGLB_zero
    hu_anti hu_nn hu_glb
  have hval_tend : Filter.Tendsto (fun s : ↥S => s.val) Filter.atTop (nhds x) := by
    have h1 : Filter.Tendsto (fun s : ↥S => x - u s) Filter.atTop (nhds (x - 0)) :=
      tendsto_const_nhds.sub htend
    simpa [u, sub_sub_cancel] using h1
  exact hcl.mem_of_tendsto hval_tend (Filter.Eventually.of_forall (fun s => hS s.2))

private theorem generated_subset_absolutelyContinuous {μ : MofK K} (hμ : 0 ≤ μ) :
    (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) ⊆
      {ν : MofK K |
        (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} := by
  let J := absolutelyContinuousOrderIdeal hμ
  have hJ_set : (J : Set (MofK K)) =
      {ν : MofK K |
        (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} := rfl
  have hJ_closed : IsClosed (J : Set (MofK K)) := by
    rw [hJ_set]
    exact isClosed_absolutelyContinuous μ
  obtain ⟨B, hB⟩ := band_of_isClosed_orderIdeal J hJ_closed
  have hB_eq : (B : Set (MofK K)) =
      {ν : MofK K |
        (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} := by
    rw [hB]
    exact hJ_set
  have hμ_in : μ ∈ (B : Set (MofK K)) := by
    rw [hB_eq]
    exact VectorMeasure.AbsolutelyContinuous.refl (μ : MeasureTheory.SignedMeasure K)
  have hsub : (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) ⊆
      (B : Set (MofK K)) :=
    Band.generated_le (Set.singleton_subset_iff.mpr hμ_in)
  exact hB_eq ▸ hsub

omit [TopologicalSpace K] [T2Space K] [CompactSpace K] [BorelSpace K] in
private theorem norm_withDensityᵥ_eq (μ : Measure K) [IsFiniteMeasure μ]
    {f : K → ℝ} (hf : Integrable f μ) :
    ‖μ.withDensityᵥ f‖ = ∫ x, |f x| ∂μ := by
  obtain ⟨g, hgm, hgae⟩ : ∃ g : K → ℝ, Measurable g ∧ f =ᵐ[μ] g :=
    ⟨hf.1.mk f, hf.1.stronglyMeasurable_mk.measurable, hf.1.ae_eq_mk⟩
  have hgi : Integrable g μ := hf.congr hgae
  have heq : μ.withDensityᵥ f = μ.withDensityᵥ g := WithDensityᵥEq.congr_ae hgae
  rw [heq, MeasureTheory.SignedMeasure.norm_def,
    MeasureTheory.SignedMeasure.totalVariation_withDensityᵥ_apply_univ hgm hgi]
  refine integral_congr_ae ?_
  filter_upwards [hgae] with x hx
  rw [hx]

omit [TopologicalSpace K] [T2Space K] [CompactSpace K] [BorelSpace K] in
private theorem continuous_withDensityᵥ_L1 {μ : Measure K} [IsFiniteMeasure μ] :
    Continuous (fun f : Lp ℝ 1 μ =>
      (μ.withDensityᵥ (f : K → ℝ) : MeasureTheory.SignedMeasure K)) := by
  refine Metric.continuous_iff.mpr fun f ε hε => ⟨ε, hε, fun g hg => ?_⟩
  rw [dist_eq_norm] at hg ⊢
  have hgi : Integrable (⇑g : K → ℝ) μ := memLp_one_iff_integrable.mp (Lp.memLp g)
  have hfi : Integrable (⇑f : K → ℝ) μ := memLp_one_iff_integrable.mp (Lp.memLp f)
  have h_sub : (μ.withDensityᵥ (⇑g : K → ℝ) : MeasureTheory.SignedMeasure K) -
      (μ.withDensityᵥ (⇑f : K → ℝ) : MeasureTheory.SignedMeasure K) =
      μ.withDensityᵥ ((⇑g : K → ℝ) - ⇑f) := (withDensityᵥ_sub hgi hfi).symm
  rw [h_sub, norm_withDensityᵥ_eq μ (hgi.sub hfi)]
  have hL1 : ‖g - f‖ = ∫ x, ‖(⇑(g - f) : K → ℝ) x‖ ∂μ :=
    L1.norm_eq_integral_norm (g - f)
  rw [hL1] at hg
  have hcoe : (⇑(g - f) : K → ℝ) =ᵐ[μ] ((⇑g : K → ℝ) - ⇑f) := Lp.coeFn_sub g f
  have heq_int : ∫ x, ‖(⇑(g - f) : K → ℝ) x‖ ∂μ =
      ∫ x, |(⇑g : K → ℝ) x - (⇑f : K → ℝ) x| ∂μ := by
    refine integral_congr_ae ?_
    filter_upwards [hcoe] with x hx
    rw [hx, Real.norm_eq_abs]
    rfl
  rw [heq_int] at hg
  exact hg

private theorem isClosed_signedImage_generated (μ : MofK K) :
    IsClosed ((fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ''
      (Band.generated ({μ} : Set (MofK K)) : Set (MofK K))) := by
  have hM_closed : IsClosed (Set.range fun ν : MofK K =>
      (ν : MeasureTheory.SignedMeasure K)) := by
    have hrange : Set.range (fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) =
        ((MeasureTheory.SignedMeasure.regularSignedMeasureSublattice (K := K)).toSubmodule :
          Set (MeasureTheory.SignedMeasure K)) := by
      ext s
      constructor
      · rintro ⟨ν, rfl⟩
        exact ν.2
      · intro hs
        exact ⟨⟨s, hs⟩, rfl⟩
    rw [hrange]
    exact MeasureTheory.SignedMeasure.isClosed_regularSignedMeasureSublattice
  have hEmb : Topology.IsClosedEmbedding (fun ν : MofK K =>
      (ν : MeasureTheory.SignedMeasure K)) := by
    change Topology.IsClosedEmbedding
      (Subtype.val : MofK K → MeasureTheory.SignedMeasure K)
    have hclosed :
        IsClosed
          ((MeasureTheory.SignedMeasure.regularSignedMeasureSublattice (K := K)).toSubmodule :
            Set (MeasureTheory.SignedMeasure K)) :=
      MeasureTheory.SignedMeasure.isClosed_regularSignedMeasureSublattice
    exact hclosed.isClosedEmbedding_subtypeVal
  exact hEmb.isClosedMap _
    (Band.isClosed_coe (Band.generated ({μ} : Set (MofK K))))

private theorem withDensityᵥ_indicator_mem_generated
    {μ : MofK K} (hμ : 0 ≤ μ) (c : ℝ) {A : Set K} (hA : MeasurableSet A) :
    (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart.withDensityᵥ
      (A.indicator (fun _ : K => c)) ∈
        (fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ''
          (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) := by
  set μm := (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart with hμm_def
  have hμm_reg : μm.Regular := by
    simpa [hμm_def] using
      ((MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).mp μ.2).posPart_regular
  have hint : Integrable (A.indicator (fun _ : K => c)) μm :=
    (integrable_const c).indicator hA
  have h_eq : μm.withDensityᵥ (A.indicator (fun _ : K => c)) =
      c • (μm.restrict A).toSignedMeasure := by
    ext E hE
    rw [withDensityᵥ_apply hint hE, VectorMeasure.smul_apply, smul_eq_mul,
      Measure.toSignedMeasure_apply_measurable hE, setIntegral_indicator hA,
      setIntegral_const, smul_eq_mul, measureReal_restrict_apply hE]
    ring
  let ν : MofK K :=
    ⟨(μm.restrict A).toSignedMeasure,
      (MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).2 <| by
        haveI : (μm.restrict A).Regular :=
          Measure.Regular.restrict_of_measure_ne_top (measure_ne_top _ _)
        have hj := SignedMeasure.jordan_of_toSignedMeasure (μm.restrict A)
        change (μm.restrict A).toSignedMeasure.totalVariation.Regular
        rw [MeasureTheory.SignedMeasure.totalVariation, hj]
        change (μm.restrict A + 0).Regular
        rw [add_zero]
        infer_instance⟩
  have hν_nonneg : (0 : MofK K) ≤ ν := by
    exact Measure.zero_le_toSignedMeasure _
  have hν_le : ν ≤ μ := by
    change (ν : MeasureTheory.SignedMeasure K) ≤ (μ : MeasureTheory.SignedMeasure K)
    intro E hE
    rw [Measure.toSignedMeasure_apply_measurable hE, measureReal_def,
      Measure.restrict_apply hE]
    rw [← MeasureTheory.SignedMeasure.real_apply_posPart_of_nonneg hμ hE]
    exact ENNReal.toReal_mono (measure_ne_top _ _) (measure_mono Set.inter_subset_left)
  have hν_mem : ν ∈ Band.generated ({μ} : Set (MofK K)) := by
    exact (Band.generated ({μ} : Set (MofK K))).solid
      (Band.subset_generated _ rfl) hν_nonneg hν_le
  refine ⟨c • ν, ?_, ?_⟩
  · exact (Band.generated ({μ} : Set (MofK K))).toSubmodule.smul_mem c hν_mem
  · change c • (μm.restrict A).toSignedMeasure =
      μm.withDensityᵥ (A.indicator (fun _ : K => c))
    exact h_eq.symm

private theorem withDensityᵥ_mem_signedImage_generated
    {μ : MofK K} (hμ : 0 ≤ μ) {g : K → ℝ}
    (hg : Integrable g (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart) :
    (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart.withDensityᵥ g ∈
      (fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ''
        (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) := by
  set μm := (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart with hμm_def
  have hclosed : IsClosed {f : Lp ℝ 1 μm |
      μm.withDensityᵥ (⇑f : K → ℝ) ∈
        (fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ''
          (Band.generated ({μ} : Set (MofK K)) : Set (MofK K))} := by
    exact (isClosed_signedImage_generated μ).preimage continuous_withDensityᵥ_L1
  have hP := hg.induction
    (P := fun g => μm.withDensityᵥ g ∈
      (fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ''
        (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)))
    ?_ ?_ hclosed ?_
  · simpa [hμm_def] using hP
  · intro c A hA _
    simpa [hμm_def] using
      withDensityᵥ_indicator_mem_generated hμ c hA
  · intro g₁ g₂ _ hg₁ hg₂ hP₁ hP₂
    rw [withDensityᵥ_add hg₁ hg₂]
    rcases hP₁ with ⟨ν₁, hν₁B, hν₁eq⟩
    rcases hP₂ with ⟨ν₂, hν₂B, hν₂eq⟩
    refine ⟨ν₁ + ν₂,
      (Band.generated ({μ} : Set (MofK K))).toSubmodule.add_mem hν₁B hν₂B, ?_⟩
    change ((fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ν₁) +
        ((fun ν : MofK K => (ν : MeasureTheory.SignedMeasure K)) ν₂) =
      μm.withDensityᵥ g₁ + μm.withDensityᵥ g₂
    rw [hν₁eq, hν₂eq]
  · intro g₁ g₂ hae _ hP₁
    rwa [← WithDensityᵥEq.congr_ae hae]

private theorem absolutelyContinuous_subset_generated {μ : MofK K} (hμ : 0 ≤ μ) :
    {ν : MofK K |
      (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} ⊆
        (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) := by
  intro ν hν
  set μm := (μ : MeasureTheory.SignedMeasure K).toJordanDecomposition.posPart with hμm_def
  have hν_μm : (ν : MeasureTheory.SignedMeasure K) ≪ᵥ μm.toENNRealVectorMeasure := by
    simpa [hμm_def] using
      (MeasureTheory.SignedMeasure.absolutelyContinuous_iff_posPart_of_nonneg hμ).mp hν
  have hrn : μm.withDensityᵥ ((ν : MeasureTheory.SignedMeasure K).rnDeriv μm) =
      (ν : MeasureTheory.SignedMeasure K) :=
    MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq
      (ν : MeasureTheory.SignedMeasure K) μm hν_μm
  have hmem_signed :
      (ν : MeasureTheory.SignedMeasure K) ∈
        (fun η : MofK K => (η : MeasureTheory.SignedMeasure K)) ''
          (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) := by
    rw [← hrn]
    exact withDensityᵥ_mem_signedImage_generated hμ
      (MeasureTheory.SignedMeasure.integrable_rnDeriv
        (ν : MeasureTheory.SignedMeasure K) μm)
  rcases hmem_signed with ⟨η, hηB, hην⟩
  have : η = ν := Subtype.ext hην
  simpa [this] using hηB

/-- In `M(K)`, the band generated by a non-negative regular signed measure is
the set of regular signed measures absolutely continuous with respect to it. -/
theorem band_generated_singleton_eq_absolutelyContinuous {μ : MofK K} (hμ : 0 ≤ μ) :
    (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) =
      {ν : MofK K |
        (ν : MeasureTheory.SignedMeasure K) ≪ᵥ (μ : MeasureTheory.SignedMeasure K)} := by
  exact Set.Subset.antisymm (generated_subset_absolutelyContinuous hμ)
    (absolutelyContinuous_subset_generated hμ)

/-- Replacing a generator by its modulus does not change the generated principal band. -/
private theorem band_generated_singleton_eq_abs (μ : MofK K) :
    Band.generated ({μ} : Set (MofK K)) =
      Band.generated ({|μ|} : Set (MofK K)) := by
  apply le_antisymm
  · refine Band.generated_le ?_
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    apply (Band.generated ({|μ|} : Set (MofK K))).mem_of_abs_mem
    exact Band.subset_generated ({|μ|} : Set (MofK K)) rfl
  · refine Band.generated_le ?_
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    apply (Band.generated ({μ} : Set (MofK K))).abs_mem
    exact Band.subset_generated ({μ} : Set (MofK K)) rfl

/-- Membership in the principal band generated by `μ` gives absolute continuity
with respect to the positive generator `|μ|`. -/
private theorem absolutelyContinuous_abs_of_mem_bandGenerated (μ : MofK K)
    {ν : MofK K} (hν : ν ∈ (Band.generated ({μ} : Set (MofK K)) : Set (MofK K))) :
    (ν : MeasureTheory.SignedMeasure K) ≪ᵥ
      ((|μ| : MofK K) : MeasureTheory.SignedMeasure K) := by
  have hν' : ν ∈ (Band.generated ({|μ|} : Set (MofK K)) : Set (MofK K)) := by
    rwa [band_generated_singleton_eq_abs μ] at hν
  have hset := band_generated_singleton_eq_absolutelyContinuous
    (μ := |μ|) (show (0 : MofK K) ≤ |μ| from abs_nonneg μ)
  rwa [hset] at hν'

/-- Membership in the principal band generated by `μ` gives absolute continuity
of total variations with respect to `|μ|`. -/
private theorem totalVariation_absolutelyContinuous_of_mem_bandGenerated (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    (v.val : MeasureTheory.SignedMeasure K).totalVariation ≪
      (|μ| : MofK K).val.toJordanDecomposition.posPart := by
  exact (MeasureTheory.SignedMeasure.totalVariation_absolutelyContinuous_iff_of_nonneg
    (show (0 : MeasureTheory.SignedMeasure K) ≤
      ((|μ| : MofK K) : MeasureTheory.SignedMeasure K) from abs_nonneg μ)).mp
        (absolutelyContinuous_abs_of_mem_bandGenerated μ v.property)

/-- The positive Jordan part of `|μ|` is the total variation of `μ`. -/
private theorem posPart_abs_eq_totalVariation (μ : MofK K) :
    (|μ| : MofK K).val.toJordanDecomposition.posPart =
      (μ : MeasureTheory.SignedMeasure K).totalVariation := by
  change (|(μ : MeasureTheory.SignedMeasure K)|).toJordanDecomposition.posPart =
    (μ : MeasureTheory.SignedMeasure K).totalVariation
  set s : MeasureTheory.SignedMeasure K := (μ : MeasureTheory.SignedMeasure K)
  let j : MeasureTheory.JordanDecomposition K :=
    { posPart := s.totalVariation
      negPart := 0
      mutuallySingular := Measure.MutuallySingular.zero_right }
  have habs : |s| = j.toSignedMeasure := by
    rw [MeasureTheory.SignedMeasure.abs_eq_posPart_add_negPart]
    change s.toJordanDecomposition.posPart.toSignedMeasure +
        s.toJordanDecomposition.negPart.toSignedMeasure =
      (s.toJordanDecomposition.posPart + s.toJordanDecomposition.negPart).toSignedMeasure -
        (0 : Measure K).toSignedMeasure
    rw [Measure.toSignedMeasure_zero, sub_zero, ← Measure.toSignedMeasure_add]
  have hJ : |s|.toJordanDecomposition = j :=
    MeasureTheory.SignedMeasure.toJordanDecomposition_eq habs
  change |s|.toJordanDecomposition.posPart = s.totalVariation
  rw [hJ]

/-- Elements of the principal band have integrable Radon-Nikodym derivatives
with respect to the total variation of the generator. -/
private theorem integrable_rnDeriv_of_mem_bandGenerated (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    Integrable ((v.val : MeasureTheory.SignedMeasure K).rnDeriv
      (μ : MeasureTheory.SignedMeasure K).totalVariation)
        (μ : MeasureTheory.SignedMeasure K).totalVariation := by
  exact MeasureTheory.SignedMeasure.integrable_rnDeriv
    (v.val : MeasureTheory.SignedMeasure K)
    (μ : MeasureTheory.SignedMeasure K).totalVariation

/-- Density-weighted signed measures by `L¹(|μ|)` functions are regular. -/
private theorem withDensityᵥ_regular_of_integrable (μ : MofK K) {f : K → ℝ}
    (hf : Integrable f (μ : MeasureTheory.SignedMeasure K).totalVariation) :
    MeasureTheory.SignedMeasure.IsRegular
      (((μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ f :
        MeasureTheory.SignedMeasure K)) := by
  have hf' : Integrable f ((|μ| : MofK K).val.toJordanDecomposition.posPart) := by
    rwa [posPart_abs_eq_totalVariation μ]
  have hmem := withDensityᵥ_mem_signedImage_generated
    (μ := |μ|) (show (0 : MofK K) ≤ |μ| from abs_nonneg μ) hf'
  rw [posPart_abs_eq_totalVariation μ] at hmem
  rcases hmem with ⟨η, _, hη⟩
  have hηreg : (η : MeasureTheory.SignedMeasure K).IsRegular :=
    (MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).mp η.2
  rwa [← hη]

/-- Density-weighted signed measures by integrable functions lie in the
principal band generated by `μ`. -/
private theorem withDensityᵥ_mem_bandGenerated (μ : MofK K) {f : K → ℝ}
    (hf : Integrable f (μ : MeasureTheory.SignedMeasure K).totalVariation) :
    (⟨((μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ f :
        MeasureTheory.SignedMeasure K),
      (MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).mpr
        (withDensityᵥ_regular_of_integrable μ hf)⟩ : MofK K) ∈
        (Band.generated ({μ} : Set (MofK K)) : Set (MofK K)) := by
  have hf' : Integrable f ((|μ| : MofK K).val.toJordanDecomposition.posPart) := by
    rwa [posPart_abs_eq_totalVariation μ]
  have hmem := withDensityᵥ_mem_signedImage_generated
    (μ := |μ|) (show (0 : MofK K) ≤ |μ| from abs_nonneg μ) hf'
  rw [posPart_abs_eq_totalVariation μ] at hmem
  rcases hmem with ⟨η, hηmem, hη⟩
  have hηeq : η =
      (⟨((μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ f :
          MeasureTheory.SignedMeasure K),
        (MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).mpr
          (withDensityᵥ_regular_of_integrable μ hf)⟩ : MofK K) :=
    Subtype.ext hη
  rw [← hηeq, band_generated_singleton_eq_abs μ]
  exact hηmem

/-- Forward Radon-Nikodym map from the principal band generated by `μ` to
`L¹(|μ|)`. -/
private noncomputable def bandGeneratedToLp (μ : MofK K) :
    ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule →
      Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation := by
  intro v
  exact MemLp.toLp
    ((v.val : MeasureTheory.SignedMeasure K).rnDeriv
      (μ : MeasureTheory.SignedMeasure K).totalVariation)
    (memLp_one_iff_integrable.mpr (integrable_rnDeriv_of_mem_bandGenerated μ v))

/-- The forward map is represented by the Radon-Nikodym derivative. -/
private theorem bandGeneratedToLp_ae_eq_rnDeriv (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    (bandGeneratedToLp μ v : K → ℝ) =ᵐ[(μ : MeasureTheory.SignedMeasure K).totalVariation]
      (v.val : MeasureTheory.SignedMeasure K).rnDeriv
        (μ : MeasureTheory.SignedMeasure K).totalVariation := by
  exact MemLp.coeFn_toLp
    (memLp_one_iff_integrable.mpr (integrable_rnDeriv_of_mem_bandGenerated μ v))

/-- Inverse density map from `L¹(|μ|)` to the principal band generated by `μ`. -/
private noncomputable def lpToBandGenerated (μ : MofK K) :
    Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation →
      ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule := by
  intro f
  exact
    ⟨(⟨((μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ (f : K → ℝ) :
          MeasureTheory.SignedMeasure K),
        (MeasureTheory.SignedMeasure.mem_regularSignedMeasureSublattice_iff).mpr
          (withDensityᵥ_regular_of_integrable μ
            (memLp_one_iff_integrable.mp (Lp.memLp f)))⟩ : MofK K),
      withDensityᵥ_mem_bandGenerated μ (memLp_one_iff_integrable.mp (Lp.memLp f))⟩

/-- The inverse map is represented by density with respect to total variation. -/
private theorem lpToBandGenerated_val_eq_withDensityᵥ (μ : MofK K)
    (f : Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation) :
    ((lpToBandGenerated μ f).val : MeasureTheory.SignedMeasure K) =
      (μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ (f : K → ℝ) := by
  rfl

private theorem absolutelyContinuous_totalVariationVector_of_mem_bandGenerated (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    (v.val : MeasureTheory.SignedMeasure K) ≪ᵥ
      (μ : MeasureTheory.SignedMeasure K).totalVariation.toENNRealVectorMeasure := by
  rw [MeasureTheory.SignedMeasure.absolutelyContinuous_ennreal_iff,
    VectorMeasure.ennrealToMeasure_toENNRealVectorMeasure]
  rw [← posPart_abs_eq_totalVariation μ]
  exact totalVariation_absolutelyContinuous_of_mem_bandGenerated μ v

private theorem bandGeneratedToLp_leftInv (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    lpToBandGenerated μ (bandGeneratedToLp μ v) = v := by
  apply Subtype.ext
  apply Subtype.ext
  change ((lpToBandGenerated μ (bandGeneratedToLp μ v)).val :
      MeasureTheory.SignedMeasure K) = (v.val : MeasureTheory.SignedMeasure K)
  rw [lpToBandGenerated_val_eq_withDensityᵥ]
  exact (WithDensityᵥEq.congr_ae (bandGeneratedToLp_ae_eq_rnDeriv μ v)).trans
    (MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq
      (v.val : MeasureTheory.SignedMeasure K)
      (μ : MeasureTheory.SignedMeasure K).totalVariation
      (absolutelyContinuous_totalVariationVector_of_mem_bandGenerated μ v))

private theorem rnDeriv_withDensityᵥ_ae_eq (μ : MofK K)
    (f : Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation) :
    MeasureTheory.SignedMeasure.rnDeriv
      ((μ : MeasureTheory.SignedMeasure K).totalVariation.withDensityᵥ (f : K → ℝ) :
        MeasureTheory.SignedMeasure K)
      (μ : MeasureTheory.SignedMeasure K).totalVariation
        =ᵐ[(μ : MeasureTheory.SignedMeasure K).totalVariation] ⇑f := by
  have hfi : Integrable (⇑f) (μ : MeasureTheory.SignedMeasure K).totalVariation :=
    memLp_one_iff_integrable.mp (Lp.memLp f)
  exact (Integrable.withDensityᵥ_eq_iff (MeasureTheory.SignedMeasure.integrable_rnDeriv _ _)
    hfi).mp
      (MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq _ _
        (Measure.withDensityᵥ_absolutelyContinuous _ f))

private theorem bandGeneratedToLp_rightInv (μ : MofK K)
    (f : Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation) :
    bandGeneratedToLp μ (lpToBandGenerated μ f) = f := by
  change MemLp.toLp _ _ = f
  exact (MemLp.toLp_congr _ _ (rnDeriv_withDensityᵥ_ae_eq μ f)).trans
    (Lp.toLp_coeFn f (Lp.memLp f))

private theorem bandGeneratedToLp_norm (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    ‖bandGeneratedToLp μ v‖ = ‖v‖ := by
  set μtv := (μ : MeasureTheory.SignedMeasure K).totalVariation
  have hfi := integrable_rnDeriv_of_mem_bandGenerated μ v
  change ‖MemLp.toLp ((v.val : MeasureTheory.SignedMeasure K).rnDeriv μtv)
      (memLp_one_iff_integrable.mpr hfi)‖ = ‖(v.val : MeasureTheory.SignedMeasure K)‖
  rw [L1.norm_eq_integral_norm]
  calc
    ∫ x, ‖(MemLp.toLp ((v.val : MeasureTheory.SignedMeasure K).rnDeriv μtv)
          (memLp_one_iff_integrable.mpr hfi) : K → ℝ) x‖ ∂μtv
        = ∫ x, |(v.val : MeasureTheory.SignedMeasure K).rnDeriv μtv x| ∂μtv := by
          refine integral_congr_ae ?_
          filter_upwards [MemLp.coeFn_toLp (memLp_one_iff_integrable.mpr hfi)] with x hx
          rw [hx, Real.norm_eq_abs]
    _ = ‖μtv.withDensityᵥ ((v.val : MeasureTheory.SignedMeasure K).rnDeriv μtv)‖ :=
        (norm_withDensityᵥ_eq μtv hfi).symm
    _ = ‖(v.val : MeasureTheory.SignedMeasure K)‖ := by
        rw [MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq
          (v.val : MeasureTheory.SignedMeasure K) μtv
          (absolutelyContinuous_totalVariationVector_of_mem_bandGenerated μ v)]

private theorem bandGeneratedToLp_map_add (μ : MofK K)
    (v w : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    bandGeneratedToLp μ (v + w) = bandGeneratedToLp μ v + bandGeneratedToLp μ w := by
  change MemLp.toLp _ _ = MemLp.toLp _ _ + MemLp.toLp _ _
  rw [← MemLp.toLp_add]
  exact MemLp.toLp_congr _ _ (MeasureTheory.SignedMeasure.rnDeriv_add
    (v.val : MeasureTheory.SignedMeasure K) (w.val : MeasureTheory.SignedMeasure K)
    (μ : MeasureTheory.SignedMeasure K).totalVariation)

private theorem bandGeneratedToLp_map_smul (μ : MofK K) (c : ℝ)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    bandGeneratedToLp μ (c • v) = c • bandGeneratedToLp μ v := by
  change MemLp.toLp _ _ = c • MemLp.toLp _ _
  rw [← MemLp.toLp_const_smul]
  exact MemLp.toLp_congr _ _ (MeasureTheory.SignedMeasure.rnDeriv_smul
    (v.val : MeasureTheory.SignedMeasure K) (μ : MeasureTheory.SignedMeasure K).totalVariation c)

private theorem bandGeneratedToLp_map_neg (μ : MofK K)
    (v : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    bandGeneratedToLp μ (-v) = -bandGeneratedToLp μ v := by
  simpa using bandGeneratedToLp_map_smul μ (-1) v

private theorem monotone_bandGeneratedToLp (μ : MofK K)
    {v w : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule} (h : v ≤ w) :
    bandGeneratedToLp μ v ≤ bandGeneratedToLp μ w := by
  set μtv := (μ : MeasureTheory.SignedMeasure K).totalVariation
  have hvi := integrable_rnDeriv_of_mem_bandGenerated μ v
  have hwi := integrable_rnDeriv_of_mem_bandGenerated μ w
  have h_ae :
      (v.val : MeasureTheory.SignedMeasure K).rnDeriv μtv ≤ᵐ[μtv]
        (w.val : MeasureTheory.SignedMeasure K).rnDeriv μtv := by
    refine ae_le_of_forall_setIntegral_le hvi hwi fun E hE _ => ?_
    rw [← withDensityᵥ_apply hvi hE, ← withDensityᵥ_apply hwi hE,
      MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq
        (v.val : MeasureTheory.SignedMeasure K) μtv
        (absolutelyContinuous_totalVariationVector_of_mem_bandGenerated μ v),
      MeasureTheory.SignedMeasure.withDensityᵥ_rnDeriv_eq
        (w.val : MeasureTheory.SignedMeasure K) μtv
        (absolutelyContinuous_totalVariationVector_of_mem_bandGenerated μ w)]
    exact h E hE
  change (bandGeneratedToLp μ v : K →ₘ[μtv] ℝ) ≤ bandGeneratedToLp μ w
  rw [← AEEqFun.coeFn_le]
  filter_upwards [bandGeneratedToLp_ae_eq_rnDeriv μ v,
    bandGeneratedToLp_ae_eq_rnDeriv μ w, h_ae] with x hvx hwx hle
  exact hvx ▸ hwx ▸ hle

private theorem monotone_lpToBandGenerated (μ : MofK K)
    {f g : Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation} (h : f ≤ g) :
    lpToBandGenerated μ f ≤ lpToBandGenerated μ g := by
  intro E hE
  rw [lpToBandGenerated_val_eq_withDensityᵥ, lpToBandGenerated_val_eq_withDensityᵥ]
  have hfi : Integrable (⇑f) (μ : MeasureTheory.SignedMeasure K).totalVariation :=
    memLp_one_iff_integrable.mp (Lp.memLp f)
  have hgi : Integrable (⇑g) (μ : MeasureTheory.SignedMeasure K).totalVariation :=
    memLp_one_iff_integrable.mp (Lp.memLp g)
  rw [withDensityᵥ_apply hfi hE, withDensityᵥ_apply hgi hE]
  have h_ae : (⇑f : K → ℝ) ≤ᵐ[(μ : MeasureTheory.SignedMeasure K).totalVariation] ⇑g :=
    AEEqFun.coeFn_le.mpr h
  exact setIntegral_mono_ae hfi.integrableOn hgi.integrableOn h_ae

private theorem bandGeneratedToLp_map_sup (μ : MofK K)
    (v w : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    bandGeneratedToLp μ (v ⊔ w) = bandGeneratedToLp μ v ⊔ bandGeneratedToLp μ w := by
  apply le_antisymm
  · have hv : v ≤ lpToBandGenerated μ (bandGeneratedToLp μ v ⊔ bandGeneratedToLp μ w) := by
      calc v = lpToBandGenerated μ (bandGeneratedToLp μ v) :=
            (bandGeneratedToLp_leftInv μ v).symm
        _ ≤ _ := monotone_lpToBandGenerated μ le_sup_left
    have hw : w ≤ lpToBandGenerated μ (bandGeneratedToLp μ v ⊔ bandGeneratedToLp μ w) := by
      calc w = lpToBandGenerated μ (bandGeneratedToLp μ w) :=
            (bandGeneratedToLp_leftInv μ w).symm
        _ ≤ _ := monotone_lpToBandGenerated μ le_sup_right
    calc bandGeneratedToLp μ (v ⊔ w)
        ≤ bandGeneratedToLp μ (lpToBandGenerated μ
          (bandGeneratedToLp μ v ⊔ bandGeneratedToLp μ w)) :=
          monotone_bandGeneratedToLp μ (sup_le hv hw)
      _ = _ := bandGeneratedToLp_rightInv μ _
  · exact sup_le (monotone_bandGeneratedToLp μ le_sup_left)
      (monotone_bandGeneratedToLp μ le_sup_right)

private theorem bandGeneratedToLp_map_inf (μ : MofK K)
    (v w : ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule) :
    bandGeneratedToLp μ (v ⊓ w) = bandGeneratedToLp μ v ⊓ bandGeneratedToLp μ w := by
  have lhs : bandGeneratedToLp μ (v ⊓ w) =
      bandGeneratedToLp μ v + bandGeneratedToLp μ w -
        (bandGeneratedToLp μ v ⊔ bandGeneratedToLp μ w) := by
    conv_lhs => rw [eq_sub_of_add_eq (inf_add_sup v w), sub_eq_add_neg]
    rw [bandGeneratedToLp_map_add, bandGeneratedToLp_map_neg,
      bandGeneratedToLp_map_add, bandGeneratedToLp_map_sup, sub_eq_add_neg]
  rw [lhs, ← eq_sub_of_add_eq (inf_add_sup _ _)]

/-- The Radon-Nikodym correspondence as a Banach-lattice equivalence. -/
private noncomputable def bandGeneratedBanachLatEquivL1 (μ : MofK K) :
    BanachLatEquiv ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule
      (Lp ℝ 1 (μ : MeasureTheory.SignedMeasure K).totalVariation) := by
  exact
    { toLinearIsometryEquiv :=
        { toLinearEquiv :=
            { toFun := bandGeneratedToLp μ
              invFun := lpToBandGenerated μ
              map_add' := bandGeneratedToLp_map_add μ
              map_smul' := bandGeneratedToLp_map_smul μ
              left_inv := bandGeneratedToLp_leftInv μ
              right_inv := bandGeneratedToLp_rightInv μ }
          norm_map' := bandGeneratedToLp_norm μ }
      map_sup' := bandGeneratedToLp_map_sup μ
      map_inf' := bandGeneratedToLp_map_inf μ }

/-- Every principal band in `M(K)` is Banach-lattice isometric to some `L¹`
space. -/
theorem exists_principalBand_banachLatEquivL1 (μ : MofK K) :
    ∃ (Ω : Type u) (_ : MeasurableSpace Ω) (ν : Measure Ω) (_ : IsFiniteMeasure ν),
      Nonempty (BanachLatEquiv ↥(Band.generated ({μ} : Set (MofK K))).toSubmodule
        (Lp ℝ 1 ν)) := by
  exact ⟨K, inferInstance, (μ : MeasureTheory.SignedMeasure K).totalVariation,
    inferInstance, ⟨bandGeneratedBanachLatEquivL1 μ⟩⟩

end MofK
